### ISSUE TITLE
`Open Image and Segmentations` all required?

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1001]
Hi,

I tried `Open Image and Segmentations` and it seems that all inputs are required. I like to use this to simlpy open an image in MoBIE.
Would it work to accept empty fields for segmentation and table and simply display the image data?

**Comment by tischi** [comment]
In MoBIE-beta there should be now:

`View Current Image...`

to view the currently open one.

Does that work for you?

**Comment by martinschorb** [comment]
Not in that specific case (trying to open an old BDV-HDF5 in Fiji where the importer fails - XT for the AO4Life). I rather thought of just providing a path to an image file and leave the rest empty.

**Comment by tischi** [comment]
@martinschorb this should work now in MoBIE-beta in a sense that in fact none of the fields in `Open Image and Segmentation` is required :-)

@akhan I think you used this for Dario's project right? Could you check whether this still works for you as expected?
