### ISSUE TITLE
org.embl.mobie.lib.table.LazyAnnotatedSegmentTableModel cannot be transformed yet.

### ISSUE THREAD

**Issue by imagejan** [mobie/mobie-viewer-fiji#1008]
When trying to view a merged grid view (`get_merged_grid_source_transform`) consisting of many transformed segmentation displays (`get_segmentation_display`), I ran into the `RuntimeException` here:

https://github.com/mobie/mobie-viewer-fiji/blob/ccdc760157616a5a226054ec6c1584139478f9bc/src/main/java/org/embl/mobie/lib/table/LazyAnnotatedSegmentTableModel.java#L119-L123

See also: https://github.com/fmi-faim/faim-hcs/issues/16.

What needs to be done to make an interactive table of multiple (grid-transformed) label images functional?

**Comment by tischi** [comment]
It seems I just did not get around yet implementing this :-)
I will have a look, please ping me again if I don't get back to you within one or two weeks.

**Comment by tischi** [comment]
At least this is a super informative error message :-)

**Comment by tischi** [comment]
@imagejan 
To be honest I am not sure this is even needed, in the `develop` branch I sort of commented out this exception.
If you are motivated you could try opening your project from the develop branch and see what happens.

**Comment by imagejan** [comment]
I was running from MoBIE-beta when I was trying this yesterday 😄, so I believe I didn't actually see the `RuntimeException` but rather the print statement:

https://github.com/mobie/mobie-viewer-fiji/blob/7b893bcebb728294b3e88be4eed90251df5e2ead/src/main/java/org/embl/mobie/lib/table/LazyAnnotatedSegmentTableModel.java#L119-L124

Nevertheless, clicking on a segment in the table doesn't have any effect on the positioning of the view...

Maybe I'm still doing something else wrong... I'll try providing a minimal example to reproduce this.

**Comment by imagejan** [comment]
As far as I can see, the table with all the segments gets automatically created when I add the merged grid view (via the Python API). Should I provide table data with the objects? I anyways planned to populate a table with some `regionprops` measurements, I just don't know yet how to achieve that 🙂 

But if we can make the auto-generated table be position-aware for the (grid-transformed) objects, that would be great. If you give me some pointers and explanations (e.g. the logic how the table is set up in the first place), I can try digging into it myself.

**Comment by tischi** [comment]
> As far as I can see, the table with all the segments gets automatically created when I add the merged grid view (via the Python API). Should I provide table data with the objects? I anyways planned to populate a table with some regionprops measurements, I just don't know yet how to achieve that 

@constantinpape can you give some pointers how to do this?

> But if we can make the auto-generated table be position-aware for the (grid-transformed) objects, that would be great. If you give me some pointers and explanations (e.g. the logic how the table is set up in the first place), I can try digging into it myself.

I think we should have a zoom. I will write you a mail.

**Comment by constantinpape** [comment]
> As far as I can see, the table with all the segments gets automatically created when I add the merged grid view (via the Python API). Should I provide table data with the objects? I anyways planned to populate a table with some `regionprops` measurements, I just don't know yet how to achieve that slightly_smiling_face

This is pretty easy if you use the `add_segmentation` functionality: just pass the table you have created as `add_default_table`: https://github.com/mobie/mobie-utils-python/blob/master/mobie/segmentation.py#L24.
`add_default_table` can either be a boolean, which means it will automatically compute the table (`True`) or not (`False`) or it can be a string (path to the table stored as tsv or csv) or a pandas DataFrame (for in memory representation of the table).

Note that the table MUST contain the columns `label_id`, `anchor_x` and `anchor_y`, and MAY contain arbitrary other columns.

**Comment by constantinpape** [comment]
> Can I also hand over a `pd.DataFrame` to `add_source_to_dataset`, or can you advise how I should specify the table data in this case?

In this case you can't pass the table directly; instead `add_source_to_dataset` accepts the `table_folder` argument (https://github.com/mobie/mobie-utils-python/blob/master/mobie/metadata/source_metadata.py#L235), which should point to the directory with the tables for that source (which must be underneath the dataset folder). So you can just write the table yourself (e.g. with pandas), and then pass the correct table folder. Here's a short snippet to show the idea:
```python
my_table = compute_seg_table(...)   # compute the segment table and return it as pandas dataframe

dataset_folder = "./data/my-dataset"  # the current dataset
table_folder = os.path.join(dataset_folder, "tables", "my-seg")  # the folder where the tables for this segmentation are stored
os.makedirs(table_folder, exist_ok=True)  # make sure the table folder is there

# save the table as 'default.tsv' (this is the table that will be loaded by default for this segmentation)
my_table.to_csv(os.path.join(table_folder, "default.tsv"), sep="\t", index=False) 

mobie.metadata.add_source_to_dataset(dataset_folder, "segmentation", ..., table_folder=table_folder)
```

**Comment by imagejan** [comment]
Thanks for all comments.

I'm closing this as invalid, since the original issue was me trying to add a segmentation source without accompanying table data.
