### ISSUE TITLE
extract subvolume

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#101]
Hi,

now that the segmentation army is working, they have requested some way of extracting chunks of raw data.

They would give the position (of a bookmark) and would like the 3x3x3 (scale 0) chunks surrounding it as an ImageJ volume, so they can filter it and move on with segmentation.

Maybe the BDV-playground screenshot feature that captures raw data would work...

**Comment by tischi** [comment]
@martinschorb 
If you need this functionality in ImageJ such that people can immediately draw in Fiji you could also write a Jython script.

**Comment by constantinpape** [comment]
Closing in favor of #243
