### ISSUE TITLE
Creating a colour for channels from Index.xml files

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1019]
@NicoKiaru 

Do you have some code to create channel colours and contrast limits from opening those Index.xml files?

Or are those maybe already contained in the `SpimData` that you create?

**Comment by NicoKiaru** [comment]
I'm using bioformats properties for the colours:

https://github.com/BIOP/bigdataviewer-image-loaders/blob/3d57189d6193d701ac401c3618503a92372187f9/src/main/java/ch/epfl/biop/bdv/img/opener/ChannelProperties.java#L173

For contrast limits, I think I just put 0 to 256 everywhere.

All of these properties (colour, min max) are stored in spimdata `Displaysettings` entities when you serialise the SpimData object to xml.

**Comment by tischi** [comment]
Thanks! 

I am using now the static methods in your ChannelProperties class to compute the colour from the wavelength.

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/2157566/232732375-2d2b6fbe-9c5b-47c2-8c21-47414b8fe4f6.png">

Contrastlimits I still need to fix....


Works nice :-)
