### ISSUE TITLE
Show progress for taking screenshots

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#1023]
The `Take Screenshot` functionality seems to not work for grid views: after clicking ok in the menu nothing happens (see the video below).
I have tested this for the newest MoBIE-beta and the default view from the Covid-IF project.
Note that it works for views without a grid transform (I have tested it for the default platybrowser view, where everything works fine).

(Sidenote: I am not sure if this ever worked for grid-views or if it worked at some point and then stopped working.)

https://user-images.githubusercontent.com/4263537/233024630-b15a8d47-bf91-480d-bcdc-68d113896469.mp4

**Comment by tischi** [comment]
For me it works, you just have to wait quite long.
Try waiting one minute.

**Comment by tischi** [comment]
If you do it at lower resolution, it is much faster (good for testing that it works at all).

**Comment by constantinpape** [comment]
Ok, that makes it much faster indeed. I think it would be good to display some message to the user about this.

**Comment by tischi** [comment]
I took the liberty to change the issue title.

**Comment by tischi** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/2157566/233116040-ea7c0deb-2520-411f-87af-fda538883750.png">

**Comment by constantinpape** [comment]
Ok, for now I think this is a good solution!

**Comment by tischi** [comment]
fixed the progress logging:

```
Screenshot: Fetching data from 3 sources.
plate_nuclei: 20%
plate_nuclei: 40%
plate_nuclei: 60%
plate_nuclei: 80%
plate_nuclei: 100%
plate_serumIgG: 20%
plate_serumIgG: 40%
plate_serumIgG: 60%
plate_serumIgG: 80%
plate_serumIgG: 100%
wells: 20%
wells: 40%
wells: 60%
wells: 80%
wells: 100%
Screenshot: Fetched data in 2232 ms.
```
