### ISSUE TITLE
Volume viewing of images

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1033]
Hi @martinschorb @constantinpape ,

There are some strange things going on with the volume rendering of images.

See here for details: https://imagesc.zulipchat.com/#narrow/stream/327238-Fiji/topic/3D.20viewer.20error.3A.20Transform3D1

I don't have the time right now (or don't think this is of such a high priority) to fully dive into this, it seems that a quick fix is to change the initial rendering from Surface to Volume. 

#### Volume rendering

<img width="512" alt="image" src="https://user-images.githubusercontent.com/2157566/236393721-184132d9-da6f-40e5-ba8d-0b65c55e0143.png">

#### Surface rendering

One can then change this in the Volume Viewer:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/2157566/236393827-4bd4189a-d0fe-4954-90cc-cae3a80823f3.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/2157566/236393880-4dd4be7e-e378-4a68-a81c-ec8b3c89d312.png">

-------

If this is acceptable I would change the behaviour to default to volume rendering for images. 

What do you think?

**Comment by martinschorb** [comment]
Fine with me. Does it come with a performance penalty to use volume?

**Comment by tischi** [comment]
nope
