### ISSUE TITLE
`Ctrl`-clicking to highlight selected labels also in table

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1036]
Hi,

would it be possible to enable the functionality to only display selected labels by `Ctrl`-clicking not only in the viewer window, but also in the table?

**Comment by tischi** [comment]
Hi,

I had a look into the code and it looks as if Ctrl+Click on a table row should select the row and focus on the selected object while only a Click should only focus it. 

I also tried this and indeed this seems to work. In that case I do not understand your request; could you please elaborate?

### Regions selected by Ctrl+Click in the table

<img width="833" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/debfc0d9-935f-4083-9baa-6b79e47d1d30">

**Comment by martinschorb** [comment]
I am not 100% what I meant with "only" 9 months ago.
I assume it is very related to 
https://github.com/mobie/mobie-viewer-fiji/issues/1092

in a sense that currently, when multiple objects are selected the appearance affects the region display color overlay only not the source display and order.

In your example, when selecting the first and last well with `Ctrl` that would still show all sources in between but only highlight the outlines of the two selected ones.

Let's continue in the new issue to see how we can dynamically arrange the sources such that they get grouped together upon selecton in the table.
