### ISSUE TITLE
Persist 'Show labels as boundaries' per source display

### ISSUE THREAD

**Issue by imagejan** [mobie/mobie-viewer-fiji#1042]
When having multiple segmentation displays, the state of `Show labels as boundaries` is currently persisted/remembered globally for the `Configure Segment Rendering` dialog, instead of remembering the state for each source display.

To reproduce (e.g. with segmentation source displays 'nuclei' and 'cyto'):
* Click the <kbd>S</kbd> button for 'nuclei'.
* Select `Show labels as boundaries`.
* Verify that the 'nuclei' are shown as outlines, the 'cyto' segments are still rendered as filled objects.
* Click the <kbd>S</kbd> button for 'cyto'.

=> The checkbox `Show labels as boundaries` is selected, not reflecting the current state of the display. Clicking OK without changing anything in the dialog will now change the display to render boundaries.

**Comment by tischi** [comment]
Turns out to be some SciJava issue, where `persist` seems to overwrite changing values.

This was my code:

```
				final MutableModuleItem< Boolean > showAsBoundaryItem = getInfo().getMutableInput( "showAsBoundary", Boolean.class );
				final boolean showAsBoundaries = boundarySource.showAsBoundaries();
				showAsBoundaryItem.setValue( this, showAsBoundaries );
```

But even though this did the right thing, the UI did not accept it until I set `persist = false` in the corresponding item.
