### ISSUE TITLE
3D Viewer crashes

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1043]
Hi,

in the current Beta the 3D Viewer crashes (Linux, `/g/emcf/software/Fiji/Fiji.app_MoBIEBeta`).

- start Fiji
- open published Project (sponge)
- display cell segmentation 
- click `V` to show it in 3D

```
~/.ImageJ_3D_Viewer.props (No such file or directory)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f175f5281d8, pid=17456, tid=0x00007f170f137640
#
# JRE version: Java(TM) SE Runtime Environment (8.0_172-b11) (build 1.8.0_172-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.172-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libawt_xawt.so+0x421d8]  ReadRegionsInList+0x3b8
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /g/emcf/software/Fiji/Fiji.app_MoBIEBeta/hs_err_pid17456.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

```

**Comment by tischi** [comment]
@martinschorb I mentioned this here: https://forum.image.sc/t/plugin-maintainers-can-you-test-fiji-2-11-0/78852/29, hoping to get some support.

Mark: if you want to reproduce this you would need a [Fiji with the MoBIE-beta update site](https://github.com/mobie/mobie-viewer-fiji/blob/develop/MOBIE-BETA.md#mobie-beta)

**Comment by NicoKiaru** [comment]
Isn't `8.0_172-b11` a very old jdk ? It's from 2018. Can you try with a more recent Java 8 ? Like the one shipped by Fiji (8.0_322) ?

**Comment by martinschorb** [comment]
OK, seems to be a JDK issue. The current one (330 btw.) seems to work. 
Is there a way to have the Fiji updater take care of the JDK as well or does one have to do a full reinstall every year or so to make sure these kind of problems do not occur?

**Comment by hinerm** [comment]
> Is there a way to have the Fiji updater take care of the JDK as well

The updater can't manage the JDK version, but you can [change the JDK](https://imagej.net/learn/faq#how-do-i-launch-imagej-with-a-different-version-of-java) of an existing Fiji installation. Basically if there is a `Fiji.app/java/[platform]` directory, it will use what's in there. If the `java` directory doesn't exist it will fall back to your systemwide-installed JDK, specified by the `JAVA_HOME` environment variable.

**Comment by ctrueden** [comment]
For the upcoming Fiji update, we will at least try to upgrade the version of the JDK to 1.8.0_330 or newer, in the hopes of new installations avoiding this problem. Making the Updater support automatically upgrading the JDK would be more work, very doable IMHO, but unfortunately no one on the LOCI team has time to work on it any time soon.
