### ISSUE TITLE
Manual transform broken for images with TimePointTransformation

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1053]
Hi,

manually transforming sources no longer works.

- open any 2 sources
- press `t` to start transforming
- move one source
- press `t` to fix the transform
- **the moving source jumps back to its original position**

This happens in both MoBIE release and Beta. Tested on Linux and Windows.

**Comment by martinschorb** [comment]
Even though the behaviour seems identical to aborting the transform (pushing `Esc`), the info "fixed manual transform" is shown but not applied.
![Screenshot from 2023-07-25 09-39-40](https://github.com/mobie/mobie-viewer-fiji/assets/35071867/8cc987e4-fc06-4dfe-8df1-646bcefb4d29)

**Comment by martinschorb** [comment]
specific view with that issue:

- `/g/schwab/Beckwith_MSB/MoBIE/parallel_CLEM`
- `clem-registered`  in CLEM menu

**Comment by martinschorb** [comment]
It looks like combining `timepoint` transforms with other types of transforms creates some more trouble:

when having more than 2 `affine` transforms additionally to the `timepoint` the transformed source is no longer shown at all inside the viewer even though the frame in the top left corner and the controls indicate that it is present. I also checked that the `sourceDisplays`are valid.

@tischi Should we look at this together at some point?

**Comment by tischi** [comment]
@martinschorb could you please test this again with the lasted MoBIE release?

**Comment by martinschorb** [comment]
works now!
