### ISSUE TITLE
Annotations: add goto button

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#106]
While annotating cell types the only way to save the results is `save_columns`. But then if you want to continue annotating the same table, you open it again, it takes you to the beginning of the table, and you have to click `next` hundreds of times to get to the moment where you stopped the last time. 
Not to implement any logging here, would it be possible to add `start from` or `go to` option, that you could just type the cell id in and start from there?

**Comment by tischi** [comment]
> `go to`

fantastic idea. I will implement it.

**Comment by tischi** [comment]
Should it be segment index or table row index? They don't need to be the same...
Probably the former, right?

**Comment by vzinche** [comment]
For me segment id would be more intuitive

**Comment by tischi** [comment]
Ok, looks like below now. I moved the annotation buttons down, because it would screw up the UI when adding a new category. Ok?

![image](https://user-images.githubusercontent.com/2157566/84895166-39416900-b0a2-11ea-8599-7c40e204f685.png)

**Comment by vzinche** [comment]
Would it maybe be better to rename 'select segment with label' to  'select segment with label id'?
Because I feel like the labels are the categories we assign

**Comment by vzinche** [comment]
Also, I visually liked it more when all the 'select' buttons were below the categories, but if it really screws everything up I guess we can also make it the way you suggested

**Comment by tischi** [comment]
ok! done!
latest version is on "/cba/exchange/mobie".
please test! 
if it works fine I will push it to the Fiji update site.

![image](https://user-images.githubusercontent.com/2157566/84901241-78c08300-b0ab-11ea-9f90-d8f55fbdb293.png)

**Comment by vzinche** [comment]
![Screenshot from 2020-06-17 16-25-04](https://user-images.githubusercontent.com/32451366/84910450-2edd9a00-b0b7-11ea-8df6-6bbcfea9b5d2.png)

**Comment by tischi** [comment]
ok, can you please try again? you only need to replace the mobie-0.5.0.jar

**Comment by vzinche** [comment]
Seems to work nicely, thanks!

**Comment by vzinche** [comment]
Could you please tell me once you push the updates version to the updates site, so I would send an email to the annotating people?

**Comment by tischi** [comment]
I pushed it to the Update site.
Let me know whether it works for you.

**Comment by vzinche** [comment]
Works, perfect, thanks!

**Comment by vzinche** [comment]
Reopening this to discuss the `goto` behavior

**Comment by vzinche** [comment]
I thought when you go to some label_id, you expect that the annotation continues from there. E.g., if I go to the label_id 40, when I click on `select next` I expect label_id 41, not label_id 0

But I am not sure if it is a desired behavior for any kind of annotations. What do you think about it?

**Comment by tischi** [comment]
> E.g., if I go to the label_id 40, when I click on select next I expect label_id 41, not label_id 0

For sure! That's what it should do! Let me check!

**Comment by tischi** [comment]
I think it was a bug. 
Please update the **imagej-utils jar** from the cba server.

**Comment by vzinche** [comment]
By update you mean
`/g/cba/exchange/mobie/install.sh /PATH/TO/MY/Fiji.app`?
If yes, then it still doesn't work for me

**Comment by tischi** [comment]
Yes, sorry, please try again now.

**Comment by vzinche** [comment]
Seems to work!
