### ISSUE TITLE
Tables wrongly assigned

### ISSUE THREAD

**Issue by giocard** [mobie/mobie-viewer-fiji#1060]
When opening multiple images with the command **Open Multiple Images and Labels**, the tables are assigned to the list of labels `LabelsList `rather than to the list of tables `TablesList`
https://github.com/mobie/mobie-viewer-fiji/blob/7c30ad4b470c5f6c776c26a14d9f9e35a9f69b70/src/main/java/org/embl/mobie/command/open/OpenMultipleImagesAndLabelsCommand.java#L91-L92

**Comment by tischi** [comment]
Thanks a lot for finding this bug @giocard !

Do you need this fix to be urgently shipped with Fiji?

I will probably make a release this week, otherwise if you need it sooner and you would use this update site, I could ship it today: https://github.com/mobie/mobie-viewer-fiji/blob/main/MOBIE-BETA.md#mobie-beta

**Comment by giocard** [comment]
Hi @tischi , I am not in a hurry, take your time. I am just exploring all the possible ways to access to the project viewer and evaluating the best way to integrate it in our workflow at the facility. Expect some questions on the forum once I complete my analysis :)

**Comment by tischi** [comment]
@giocard I think currently there are essentially three entry points:

1. You create a real MoBIE project, using [our python library](https://github.com/mobie/mobie-utils-python)
2. You have data with a decent machine readable file and folder naming scheme
3. You have a table that specifies that paths to the images

One advantage of (1) is that you can specify fancy views on the data and manage your project on github, however, you are buying into the MoBIE way of storing data. Here are [many examples](https://github.com/orgs/mobie/repositories?type=all), everything that ends with `-project`.

Just today I found out that if you open a project via a table and then right-click into BDV and choose: `Save current view > File System > ... `; you can actually later load this view again, which is pretty cool (not sure whether this is understandable for non MoBIE experts... :-)

Personally, also seeing how things evolve here at EMBL, I would probably advise the approach where you have one table that holds the data together, like the CellProfiler table that I showed in the tutorial. The good thing here is that then you could then use the same table to do statistics, e.g. in R, write results back into the table and then visualise the data on top of the images again in MoBIE, using the `Color by column` option (we also have a scatterplot by the way).

Let me know if you need a zoom.

**Comment by tischi** [comment]
Fixed in develop.
