### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#107]
The readme is not quite up-to-date, for example it still refers to MMB instead of MoBIE.
More importantly, I think the installation instructions are not up-to-date:
https://github.com/mobie/mobie-viewer-fiji#installation

Is this true, @tischi?

**Comment by tischi** [comment]
yes, completely out of date. I will update...

**Comment by tischi** [comment]
Updated. Could still be improved at some point when I have a bit more time; so I leave the issue open...
