### ISSUE TITLE
3D hcs-plate is displayed in 2D mode

### ISSUE THREAD

**Issue by tibuch** [mobie/mobie-viewer-fiji#1070]
Hi,

I am testing the new `Open HCS Dataset...` function and noticed that 3D data is shown in a 2D locked viewer.

I can open the individual `multiscale` datasets via `Open OME-Zarr from File System...` which displays them in 3D and all data is there.

This is the plate I am using for testing (2 wells, 4 channels, zyx): [test-plate.zarr.zip](https://github.com/mobie/mobie-viewer-fiji/files/13579832/test-plate.zarr.zip)

**Comment by tischi** [comment]
Well, for sure you are right 🤣 

```
	public boolean is2D()
	{
		return true; // for now...
	}
```

I will check whether the whole HCS plate stuff will also works for 3D....

**Comment by tischi** [comment]
Should work now, v4.1.3, on the MoBIE main update site.

**Comment by tibuch** [comment]
Works! Thanks for the :rocket:-fast fix!
