### ISSUE TITLE
Add option to invert the actual data?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1071]
The issue with doing this via the B&C dialog is that this will not be respected by BigWarp, where it would be very useful to have the same Contrast.

**Comment by tischi** [comment]
also ping @tibuch and @imagejan, in case you have EM data....

**Comment by tischi** [comment]
I implemented this now within the ColorConverter; so that actual data stays untouched. 

The `min` and `max` in the code below are the current contrast limit settings.

```
		final double v = invert ? max - realType.getRealDouble() : realType.getRealDouble() - min;
		int r0 = ( int ) ( scaleR * v + 0.5 );
		int g0 = ( int ) ( scaleG * v + 0.5 );
		int b0 = ( int ) ( scaleB * v + 0.5 );
		final int r = Math.max( Math.min( 255, r0 ), 0 );
		final int g = Math.max( Math.min( 255, g0 ), 0 );
		final int b = Math.max( Math.min( 255, b0 ), 0 );
		color.set( ARGBType.rgba( r, g, b, A ) );
		adjustOpacity( color, opacity );
```

**Comment by constantinpape** [comment]
> @constantinpape we would also need a JSON spec for this.

How about `InvertLUT`?

**Comment by tischi** [comment]
@constantinpape Serialisation: the `ImageDisplay` has now a new field `boolean invert;`, which defaults to `false`.

**Comment by constantinpape** [comment]
> @constantinpape Serialisation: the `ImageDisplay` has now a new field `boolean invert;`, which defaults to `false`.

Ok! I will add it to the spec later.

**Comment by constantinpape** [comment]
I have added it here: https://github.com/mobie/mobie.github.io/pull/107
