### ISSUE TITLE
Join [B]rightness and [O]pacity UI?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1072]
@martinschorb @imagejan @constantinpape @tibuch 

Currently, the Brightness and Opacity settings are two different UI elements. 

What about joining them into one?

That would also reduce the number of buttons in the UI, i.e., we could get rid of the `[O]`.

If we do this, shall we rename the `[B]` to something else? I would probably leave it...and just also add the opacity slider there to the same UI that pops up.

**Comment by constantinpape** [comment]
I think that this is a good idea to make the UI less crowded. We can either keep it at `[B]` or rename to `[B&O]`.

**Comment by tischi** [comment]
OK, this is done now, already in `main` branch, I will soon release a new MoBIE with that.
