### ISSUE TITLE
integration with `mastodon-sc`

### ISSUE THREAD

**Issue by JoOkuma** [mobie/mobie-viewer-fiji#1074]
Hi, 

Sorry for the naive question. I'm not very familiar with the Fiji ecosystem.

Does an ome-zarr loaded with Mobie work with [Mastodon](https://github.com/mastodon-sc/mastodon)?
If yes, how can I do that?

I can load the images in Fiji, but I couldn't make it work with Mastodon.

It looks like it should work because the ome-zarr is opened with big-data-viewer, right?

Thanks!

**Comment by tinevez** [comment]
Hello.
No not yet. We have not migrated the new tech to Mastodon yet.
@ksugar is still working on it.

**Comment by JoOkuma** [comment]
ok, thanks for the quick reply, @tinevez and @tischi

**Comment by tischi** [comment]
I am closing this as this seems rather a Mastodon issue.
