### ISSUE TITLE
Table range slider not closing when changing dataset

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1082]
Hi,
whatever table range slider window stays open when a dataset is closed to open another one.

**Comment by tischi** [comment]
What is a "table range slider"?

**Comment by martinschorb** [comment]
The "contrast" range slider for coloring a `regionDisplay` according to a table column. With its initial`valueLimits` set in the view.

![image](https://github.com/mobie/mobie-viewer-fiji/assets/35071867/e069ae73-3a6a-4ac2-8f20-0e3e96fb2831)

**Comment by tischi** [comment]
Thanks, I will look into it.

**Comment by tischi** [comment]
The window is generated by this class:

```
public class NumericAnnotationColoringModelContrastDialog extends JFrame implements ColoringListener
{
...
}
```

, which in fact already contains a `close()` method that could be called. However, right now I don't have a simple (non-ugly) idea how to call this method at the right moment.

Ideas:
- Create a `CloseWindowsListener` that would be implemented by this class, but then it would be consequent for all UI elements to implement this which seems a lot of infrastructure...probably least intrusive would be having a static class in MoBIE where `CloseWindowsListeners` could register themselves.
- Return the JFrame to the calling classes the instantiated this window, e.g. `TableView` and collect them there in a Collection and then close all of them when required, but again, seems like a lot of code to add an maintain...

**Comment by martinschorb** [comment]
How is it implemented for the Brightness and Opacity sliders? Are they bound to their BDV window? They close when the dataset is changed. Could it be implemented in a similar fashion?

Another option would be (I don't know if that's possible) to close all open dialogs when closing a dataset. Or maybe even all open GUI elements except MoBIE's main window.

**Comment by tischi** [comment]
> How is it implemented for the Brightness and Opacity sliders? Are they bound to their BDV window? They close when the dataset is changed. 

I just checked the code and I did not find anything that would close those windows upon the change of the dataset. Are you sure?

**Comment by martinschorb** [comment]
> > How is it implemented for the Brightness and Opacity sliders? Are they bound to their BDV window? They close when the dataset is changed.
> 
> I just checked the code and I did not find anything that would close those windows upon the change of the dataset. Are you sure?

True. This seems to be a more general thing then. So we need a way to close all those with the dataset. (?)

**Comment by tischi** [comment]
Maybe that could a way, each GUI could register itself in some global static list, which MoBIE would then close.

I think also when showing a new `exclusive` view all those windows should be closed?

**Comment by martinschorb** [comment]
I just realized that these dialogs stay open forever, even when closing the MoBIE main window. Only closing the entire Fiji (and thus stopping the Java process) will terminate them.

**Comment by tischi** [comment]
OK, then I think I could implement that these windows close when

1. The dataset is changed
2. MoBIE is closed
3. A new exclusive View is opened

That would already help, right?

**Comment by tischi** [comment]
Should work now once I cut a new release. Please reopen if some issues persit.
