### ISSUE TITLE
Visualize channels from multi-channel ome-zarr volume

### ISSUE THREAD

**Issue by JonasHell** [mobie/mobie-viewer-fiji#1093]
Hi,

I'm currently trying so set up a MoBIE project to visulize multi-channel fluorescence microscopy data.

I use bioformats2raw (https://github.com/ome/conda-bioformats2raw) to convert the data (.nd2 in this case) to zarr format. Then, I use the mobie python utils (https://github.com/mobie/mobie-utils-python) to create a project. For now, it's just one dataset containing one volume with a source entry for each channel. I added a view to load all the channels at once like Fiji would do. I can open the project with the Fiji MoBIE plugin. The problem now is that every source shows the same image (the first channel). If I open the zarr file using the python zarr package, everything looks normal and I can visualize the 3 channels using matplotlib.

The question now: Is the visualization of multi-channel data actually already implemented? If yes, what am I doing wrong?

I attach my dataset.json and a few screenshots:
[dataset.json](https://github.com/mobie/mobie-viewer-fiji/files/14097623/dataset.json)
![Screenshot from 2024-01-30 13-20-17](https://github.com/mobie/mobie-viewer-fiji/assets/57495083/92183e6d-30fb-4066-a7c5-090a0d65c61c)
![Screenshot from 2024-01-30 13-20-14](https://github.com/mobie/mobie-viewer-fiji/assets/57495083/6658500a-1706-41b7-af75-23f073d4f881)
![Screenshot from 2024-01-30 13-20-07](https://github.com/mobie/mobie-viewer-fiji/assets/57495083/4dbafd26-f775-42aa-b3f1-1dde509598c7)

Loosely realted to https://github.com/mobie/mobie-utils-python/issues/40

**Comment by constantinpape** [comment]
I had a quick look, and it seems to be correct in the dataset: 

![image](https://github.com/mobie/mobie-viewer-fiji/assets/4263537/a71a6644-c52e-4a44-b1ee-53bf6b263cb3)

@JonasHell can you check the underlying ome-zarr (at `images/ome-zarr/5488_5533.ome.zarr`) file and check if it actually has the correct channels? (Best to open it in napari).

- If yes (underlying data is correct): then the error is in MoBIE-Fiji and it does not handle the `channel` correctly.
- If no (underlying data is incorrect, the same channel is repeated multiple times): then the error is in MoBIE-python and something goes wrong when it's being copied.

**Comment by JonasHell** [comment]
I checked the data using the python zarr package and matplotlib where I can visualize the 3 different channels. I can also check with napari again :)
I don't know if this matters, but MoBIE python did not copy the data. I used the `move_only` functionality of `add_image` since the data was converted by `bioformats2raw`.

**Comment by JonasHell** [comment]
Also checked with `napari --plugin napari-ome-zarr data/all_volumes/images/ome-zarr/5488_5533.ome.zarr` and I can see 3 different channels.
![Screenshot from 2024-01-31 12-15-50](https://github.com/mobie/mobie-viewer-fiji/assets/57495083/75f5649a-dfbe-4496-af60-489dcf10b10d)

**Comment by constantinpape** [comment]
> I used the `move_only` functionality of `add_image` since the data was converted by `bioformats2raw`.

Ok, that's fine.

Thanks for checking @JonasHell. So this is an issue in MoBIE-Fiji then!
It's probably best if @tischi takes a look.

**Comment by tischi** [comment]
@constantinpape @tibuch 

I found that I had `channelIndex` in the java code to specify which channel to load, but @JonasHell had `channel` in the dataset.json. 

Could you both please let me know what you think is correct according to our current spec?

**Comment by tibuch** [comment]
According to the [spec](https://mobie.github.io/specs/mobie_spec.html#source-metadata) it should be `channel`.

I can't recall how we ended up with `channelIndex`.

**Comment by tischi** [comment]
then I screwed up and will change it in the Java code.

**Comment by JonasHell** [comment]
Awsome! Glad to hear it wasn't a big issue!
I tried it, everything seems to work. Thank you so much!! :)
