### ISSUE TITLE
collaborative projects and S3 keys

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1094]
Hi,

with @JonasHell 's project, we have the following scenario:

- data is provided by different labs
- the conversion to MoBIE format and integration into the project will happen at each site (local file system)
- image data is then uploaded to S3. This initially will be a single bucket. (In the future it might potentially even be served distributed from several distributed buckets.)

Could the "Open Project with credentials" dialog be adjusted such that 

- it can open projects from local FS and Github (instead of "full" S3 only)?
- the preferred data location can be selected as in the other dialogs to prefer local data if available?

Thanks!

**Comment by JonasHell** [comment]
@martinschorb @tischi 
I think this is implemented now, correct?

**Comment by tischi** [comment]
I had a chat with @martinschorb and yes I believe that this is implement (in fact has been implemented all along, but maybe not obviously so). I think the best would be to simply try it, using

`Open MoBIE Project With S3 Credentials...`

**Comment by JonasHell** [comment]
Sry I wasn't clear. I tried it and it works perfectly fine. Thanks!
My point was that from my side everything is fine and this issue can be closed :)
