### ISSUE TITLE
alpha blending mode on rotated canvas

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1100]
Hi,

when I show an alpha blending mode source on top of something and rotate the viewer canvas, the bounding box does not rotate leading to black "empty" regions.

no rotation:

![image](https://github.com/mobie/mobie-viewer-fiji/assets/35071867/940829c8-13cd-4e0a-beab-b7d3a763c0e6)

rotate the viewer (`z` and then right arrow key)

![image](https://github.com/mobie/mobie-viewer-fiji/assets/35071867/8ea64fcd-4d20-465e-a164-6e9d2962147d)

**Comment by tischi** [comment]
Do we have a project that I could access to reproduce this?

**Comment by martinschorb** [comment]
https://github.com/mobie/clem-example-project

`area2-tomo53` shows it already in the initial view. when rotating the canvas it becomes obvious...
![Screenshot from 2024-02-19 08-45-01](https://github.com/mobie/mobie-viewer-fiji/assets/35071867/45be240a-77e5-4477-975e-eec9661c6e5b)

**Comment by martinschorb** [comment]
This still seems to be an issue.

**Comment by tischi** [comment]
Should work now with latest Beta in Fiji:

<img width="659" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/9210f1c5-57d3-4b12-ad95-73f30153c692">
