### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1104]
@ctrueden @imagejan do you know what the issue could be: https://github.com/mobie/mobie-viewer-fiji/actions/runs/7977054903/job/21779050661 ?

```
  == Configuring Maven ==
  Performing deployment checks
  Error:  Spurious release.properties file is present
  Remove the file from version control and try again.
  Error: Process completed with exit code 1.
```

I think it is the first time I got this...

**Comment by imagejan** [comment]
@tischi you committed a `release.properties` and a `pom.xml.releaseBackup` with https://github.com/mobie/mobie-viewer-fiji/commit/6acf91de4141e408cae30bf3dde8847776d4a10d.

I am unsure how those got committed, the automated script shouldn't do that. Did you by accident commit those files manually? I recommend reviewing local and staged files after running the SciJava release script.

I assume it should just work if you remove the files.

**Comment by tischi** [comment]
Thank you @imagejan, should I add those two files to the .gitignore ?

**Comment by ctrueden** [comment]
@tischi It should work to add them to your .gitignore, although I have not tested it directly. My basis for claiming it should work is that [the `release-version.sh` script adds it with the `-f` flag](https://github.com/scijava/scijava-scripts/blob/b7eb4eef9cd10911a83e460d956fb01b1e92aec6/release-version.sh#L379), which forces it to be included in the git index when making the release, even if ignored by `.gitignore`. If you try adding it to `.gitignore` and it subsequently breaks your release workflow, let me know.

**Comment by tischi** [comment]
Hi @ctrueden, I am still struggling and don't understand what's going on here.

Latest attempt I [got again this](https://github.com/mobie/mobie-viewer-fiji/actions/runs/9888943122/job/27313941350) even though it said on the CLI:

```
❯ ../scijava-scripts/release-version.sh --skip-version-check --skip-license-update
Version? [5.2.3]: 
From https://github.com/mobie/mobie-viewer-fiji
 * branch              main       -> FETCH_HEAD
==========================================================================
NOTE: release.properties was committed to source control. Removing now.
==========================================================================
rm 'release.properties'
[main ec3fbcad] Remove $release_file
 1 file changed, 28 deletions(-)
 delete mode 100644 release.properties
```

Then in a previous attempt, where I had added the `release.properties` to `.gitignore` I got [the opposite error](https://github.com/mobie/mobie-viewer-fiji/actions/runs/9879371405/job/27285457797).

It seems to be neither happy with `release.properties` being present nor with it not being present 😅 . 

---

As a control: I have no problems releasing https://github.com/mobie/mobie-io

**Comment by imagejan** [comment]
Let's formulate a spec:
* `release.properties` MUST NEVER be part of any commit of your `main` branch,

but:
* `release.properties` MUST be present in the release commit (that is automatically created by `release-version.sh`, and not part of your `main` branch).

I usually run `release-version.sh` and then later remove any left-over files from my working directory when checking the next thing I commit. Proof-reading (and, if necessary, amending) commits is a good practice.

**Comment by imagejan** [comment]
For the record, it seems that `release.properties` was (accidentally?) committed here: https://github.com/mobie/mobie-viewer-fiji/commit/2c9f5349ba2ff158684a556286d84008d9ad207b

**Comment by tischi** [comment]
And, as we speak, it actually [ran through](https://github.com/mobie/mobie-viewer-fiji/actions) 🥳 

My theory:

1. `release.properties` MUST NOT be present in the project
2. `release.properties` MUST also NOT be mentioned in `.gitignore` (because otherwise `release-version.sh` cannot push it to github)

Could that be? It would explain why it worked now, because I think I never had this combination before.

**Comment by ctrueden** [comment]
Glad to hear that it's finally working! :sweat_smile: 

> `release.properties` MUST also NOT be mentioned in `.gitignore` (because otherwise `release-version.sh` cannot push it to github)

You would know better than I would, since you have actually tested it in practice, but... that would surprise me if true, because I use `git add -f` to add the file, so in theory, even if it's in the `.gitignore`, git should add it anyway?

**Comment by tischi** [comment]
Sooooo, the mystery continues...but I am not curious enough to resolve it right now 😉 
I'll close for now and get back to this once it hits me again.

Thank you @imagejan and @ctrueden both for your continued help.

**Comment by imagejan** [comment]
@tischi in https://github.com/mobie/mobie-viewer-fiji/commit/dbf9f69c5041f7418237edc0e6dd51044f169386 you manually committed a non-SNAPSHOT version, but didn't add any `release.properties` which is what `release-version.sh` usually does for you.

Conclusion: you CAN have `release.properties` listed in your `.gitignore`, but you MUST NEVER remove the `-SNAPSHOT` from the version on your main branch 😉

**Comment by ctrueden** [comment]
If it happens again, here is a way to get a more verbose log from the script:

1. Edit `release-version.sh`, prepending `set -x` at the very top.
2. Run with `DEBUG=1 release-version.sh` to get debugging output.

**Comment by tischi** [comment]
Seems like I am using the correct scripts:
```
❯ git pull
Already up to date.
~/Documents/scijava-scripts main !1                                                                                                                                                                                         
```

**Comment by tischi** [comment]
So confusing....
🤷
