### ISSUE TITLE
Remove move?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1117]
@K-Meech @constantinpape 

Currently we have:

```
            String[] addMethods = new String[]{ 
                    ProjectCreator.AddMethod.link.toString(),
                    ProjectCreator.AddMethod.copy.toString(), 
                    ProjectCreator.AddMethod.move.toString() };
```

I would remove the `move` choice, because:

1. less code to maintain for us
2. people could delete the image themselves after copying
3. if we (or the users) screw up we might accidentally delete their precious data

**Comment by K-Meech** [comment]
Happy to remove this - `copy` and `link` are the most used options anyway

**Comment by tischi** [comment]
OK, I will remove it then in the new-n5 branch.
