### ISSUE TITLE
Add 3D image to 2D dataset in Fiji project creator

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1119]
Hi @K-Meech,

in the new-n5 branch there is now a method: `ImagesCreator.addOMEZarrImage`

Inside there is: 

```
        if ( ! is2D( imageData ) && projectCreator.getDataset( datasetName ).is2D() ) {
            // FIXME: why not? Can't we change the project to be 3D
            throw new UnsupportedOperationException("Can't add a 3D image to a 2D dataset" );
        }
```

Could you please comment on this?

**Comment by K-Meech** [comment]
I looked into this some more. So it is possible to add a 3D image into a 2D dataset via the project creator - it will pop up a dialog to [warn about changing the dimension](https://github.com/mobie/mobie-viewer-fiji/blob/main/src/main/java/org/embl/mobie/lib/create/ui/ProjectsCreatorPanel.java#L499), then go ahead and do that if you accept. If you want to do it via a script, you would directly call `projectsCreator.getDatasetsCreator().makeDataset2D( datasetName, false );` then add the image.

So the check you linked above prevents you from accidentally adding a 3D image to a 2D dataset, but doesn't prevent you from doing so if you explicitly change the dataset from 2D to 3D.

**Comment by tischi** [comment]
Sounds great! So we can close the issue?!

**Comment by K-Meech** [comment]
Yes! All good from my side
