### ISSUE TITLE
Problems opening (additional) segmentation tables

### ISSUE THREAD

**Issue by Marei33** [mobie/mobie-viewer-fiji#1127]
Hi, I have problems when I try to open (additional) segmentation tables in the MoBIE-beta version.

1. When I have an open segmentation, it is not possible to append an additional .csv table from my file system via `Table > Load columns...`. 
Then the log window says: `Loading table chunk: /path/table.csv... ...done!`, but at the same time the console window opens and displays the following error:
![Screenshot 2024-04-05 at 17 18 41](https://github.com/mobie/mobie-viewer-fiji/assets/86373668/d55508d3-4fda-4918-96b5-910141681a65)

2. If I have closed a segmentation using the `X` button and then try to open it again by clicking on `view`, the program also throws an error:
![Screenshot 2024-04-05 at 17 27 26](https://github.com/mobie/mobie-viewer-fiji/assets/86373668/21d8813d-c2e3-41c3-b91c-4c068589c250)
![Screenshot 2024-04-05 at 17 28 23](https://github.com/mobie/mobie-viewer-fiji/assets/86373668/b5d65bb6-5703-423c-8fcb-91fc747a09f0)

**Comment by tischi** [comment]
Dear @Marei33,

1. I found one issue when opening tables that end with CSV. I uploaded a fix to MoBIE-beta, does that work for you?
2. Regarding "If I have closed a segmentation using the..."; this is another issue, can you please create a separate issue for this?

**Comment by Marei33** [comment]
Yes, thank you. That solves the issue! And I will create another issue for the other point.
