### ISSUE TITLE
Cannot reopen segmentation

### ISSUE THREAD

**Issue by Marei33** [mobie/mobie-viewer-fiji#1128]
Hi,

I have issues when I try to reopen segmentations. If I have closed a segmentation using the `X` button and then try to open it again by clicking on `view`, the program also throws an error:
![320054830-21d8813d-c2e3-41c3-b91c-4c068589c250](https://github.com/mobie/mobie-viewer-fiji/assets/86373668/b9b9e717-06ab-4cfb-aaca-53cde8404aca)
![320055278-b5d65bb6-5703-423c-8fcb-91fc747a09f0](https://github.com/mobie/mobie-viewer-fiji/assets/86373668/9bb3ab3d-91c6-488d-8480-16ed65b54d3f)

**Comment by tischi** [comment]
Should work now after an update.
