### ISSUE TITLE
Custom categorical colouring model

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#113]
It would be useful for making figures etc to have an option to set the 'color by column..' colours to a user-specified set.

Perhaps having another option under 'Coloring Mode' that would let you select a csv file from your computer with the colouring scheme? This would contain one column with the value, then columns for the corresponding r/g/b/a.

@tischi would this be possible? I'm happy to try implementing this, if you point me in the right direction.

**Comment by jhennies** [comment]
@tischi I second this issue, It would indeed be very useful. I think the csv file to specify the lookup table would be just perfect

**Comment by constantinpape** [comment]
@jhennies if I understood your description about this earlier your use case is slightly different.

I think you would want to have a custom color map for the segmentation independent of the 'color by column ...' functionality.
For both cases we would need to support a custom color map, but in your case, it would need to be specified in the `images.json` file under the `color` attribute.

@tischi we could either provide a path to some file on github in the `images.json` or (for small label spaces) define the color map in there already.

**Comment by tischi** [comment]
I guess we would need to support both:

1. loading a color map from disk (for development stage)
2. loading a color map from github (for deployment phase)

right?

**Comment by jhennies** [comment]
@constantinpape thanks for pointing this out.
@tischi yes, I'm on it

**Comment by jhennies** [comment]
@tischi I couln't attach a csv file here, so I quickly zipped it:
[colortable_fibsem.zip](https://github.com/mobie/mobie-viewer-fiji/files/5230214/colortable_fibsem.zip)

I added the seven lines that correspond to the labels in the fib-sem segmentations.
If there is any issue with this let me know.

Thanks!
Let me know if there

**Comment by tischi** [comment]
Hi All,

After having had a shower I have another idea:

I think the colormap could be just another table that one can add to all the other non-default tables, e.g., here:
https://github.com/mobie/platybrowser-datasets/tree/master/data/1.0.1/tables/sbem-6dpf-1-whole-segmented-cells

The table would have two columns `label_id` and `myARGBvalues` (the name of the second column can be anything).

The values in `myARGBvalues` would look like this (A-R-G-B):
`255-0-255-0`
`255-255-255-0`
etc...

Then, in `Color by column...` we add another Coloring Mode option `A-R-G-B Column`.

In terms of Development and Deployment I think we do not need to develop much, because people can fork the github repo and try things out there.

I also think it would be great if @K-Meech would implement this, with my help.
All the code is in `imagej-utils` (not in MoBIE). I would have time for a Skype later this afternoon (around 16:00 I think).

What do you think?

**Comment by constantinpape** [comment]
@tischi I really like that idea.
For Julian's use case, i.e. using a different color map from the start, we can then specify the relative path to this color map in 
the `color` attribute in `images.json`.

**Comment by tischi** [comment]
@constantinpape 
I think we can do it even easier in a sense that we do not have to change anything of the current code.
One would just add whatever colouring @jhennies likes to do to the default bookmark.

**Comment by constantinpape** [comment]
> I think we can do it even easier in a sense that we do not have to change anything of the current code.
> One would just add whatever colouring @jhennies likes to do to the default bookmark (including adding the additional table containing the colouring information).

I am not sure that will work.
This would mean we always need to add the segmentation to the default bookmark. Also, when the segmentation is removed and added again, how do we keep the colormap?

**Comment by tischi** [comment]
OK, that may be an issue.
However, do we need to specify the relative path? Couldn't we just reuse the same logic that we have for the bookmarks?
Example:
```
"color": "glasbey",
        "colorByColumn": "clusters",
        "tables": [
          "gene_clusters"
        ]
```

Only changing "glasbey" to "argbColumn".

**Comment by constantinpape** [comment]
> However, do we need to specify the relative path? Couldn't we just reuse the same logic that we have for the bookmarks?

Yes, that would also work.

**Comment by tischi** [comment]
ok, I'll look into implementing this together with @K-Meech in the next few days.

**Comment by K-Meech** [comment]
Sounds good to me @tischi. I'm around all afternoon so can skype anytime (my internet connection is still very slow, but should be ok)

**Comment by tischi** [comment]
@K-Meech 

Great! I'll let you know later. But let's anticipate around 16:00, ok?

1. You could already try whether you can clone imagej-utils and get this code running:
https://github.com/tischi/imagej-utils/blob/master/src/test/java/tests/TestAppendTables.java
That would be a good starting point for the development.
2. And you can try to see whether you understand this code: 
https://github.com/tischi/imagej-utils/blob/master/src/main/java/de/embl/cba/tables/color/ColumnColoringModelCreator.java
That's the place where we would add the new colouring mode.

**Comment by K-Meech** [comment]
@tischi  works for me. I'll take a look at the code you sent.
I also attach a zip of an example colour scheme table to test on.

[test_morphology_cluster_colour_scheme.zip](https://github.com/mobie/mobie-viewer-fiji/files/5231015/test_morphology_cluster_colour_scheme.zip)

**Comment by K-Meech** [comment]
@tischi - I looked at colouring for images.json, and this is actually already implemented! You can delete the commented lines here: https://github.com/mobie/mobie-viewer-fiji/blob/d9f154bea64697339ebea5e645dc7d59f1eb5a48/src/main/java/de/embl/cba/mobie/ui/viewer/SourcesPanel.java#L457, as you already do the same here: https://github.com/mobie/mobie-viewer-fiji/blob/d9f154bea64697339ebea5e645dc7d59f1eb5a48/src/main/java/de/embl/cba/mobie/ui/viewer/SourcesPanel.java#L504

**Comment by tischi** [comment]
Very well spotted! In fact, I also realised it this morning 😄

**Comment by K-Meech** [comment]
@jhennies - custom colouring should work now. Can you test it with your dataset? You'll need a table like the one I attached above (test_morphology_cluster_colour_scheme.zip) in the tables folder. Then modify your images.json file with lines for 'tables', 'tableFolder', 'colorByColumn' and 'color' - something like:

```
"3d-image-lbl" : {
	"color" : "Glasbey",
	"colorByColumn":"Test1",
	"tables": ["additional"],
	"contrastLimits":[0, 500],
	"storage": {
		"local": "local/3d-image-lbl.xml"
	},
	"tableFolder":"tables/3d-image-lbl",
	"type":"segmentation"
	}
```

**Comment by jhennies** [comment]
Working like a charm! Thanks @K-Meech
