### ISSUE TITLE
Beta - no console or log out for project creator

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1133]
Hi,

when an image is converted using the project creator, there is no status output in the console or log window. This was always very useful to know the status of the conversion. Can it be re-enabled?

**Comment by K-Meech** [comment]
@tischi No it doesn't work on that branch - I did a quick PR to fix this: https://github.com/mobie/mobie-viewer-fiji/pull/1136 .

**Comment by tischi** [comment]
Thanks @K-Meech !
