### ISSUE TITLE
InCarta File format for Mobie-Viewer ?

### ISSUE THREAD

**Issue by ThomasMicroscopy** [mobie/mobie-viewer-fiji#1137]
Is it possible to open IN Carta files (.xdce Metafile) with Mobie-Viewer?   I gave it a try in Fiji with Mobie, but didn't seem to work.

Molecular Devices is now favouring their IN Carta software with AI, which has a slightly different
file format than their MetaXpress file format (.htd). We would be quite interested in using a Plate Viewer for IN Carta files,
as IN Carta does not use a SQL database anymore (in contrast to MetaXpress), which makes storing and archiving easier for us.

**Comment by tischi** [comment]
Hi Thomas,

I unfortunately don't have the time (nor personell) to add support for new file formats.

I think the only sustainable way forward here would be see whether Bio-Formats can convert the file-format to the OME-Zarr HCS specification, which is supported by MoBIE.

@bugraoezdemir @joshmoore do you know about "IN Carta files (.xdce Metafile)" file format support in Bio-Formats?

If this is not supported by Bio-Formats then one should tell the company to make that happen!

**Comment by ThomasMicroscopy** [comment]
Actually, given that the .htd format gave such troubles so that you bypassed the Bio-Formats importer, if I understood you correctly, maybe it would work with the In Carta files as well, just parsing the tif files?

<img width="218" alt="Screenshot 2024-06-17 at 13 21 23" src="https://github.com/mobie/mobie-viewer-fiji/assets/126269188/57765c17-9463-4f13-8850-424d4fd0fddb">

**Comment by tischi** [comment]
Yes, that should work as well; could you share a minimal test data set with me?

**Comment by ThomasMicroscopy** [comment]
Ok, I prepare a small set.  If it works just on the TIFs, that would also solve the issue that IN Carta itself converts vom .xdce to jdce, but without touching the TIFs.

**Comment by ThomasMicroscopy** [comment]
The dataset I just sent includes also some z-planes. Can MoBIE deal with z-planes, I forgot. I guess it's enough to just select one z-plane and display that.     The images in the set I sent are very boring, and empty plate, just dirt and dust....

**Comment by joshmoore** [comment]
From the information on https://forum.image.sc/t/support-for-in-carta-hcs-files/97144/2 I'd say what's happened is that a new variant/format has now been created on top of .xdce. 😞

**Comment by ThomasMicroscopy** [comment]
Yes, indeed. I had only recently noticed that the xdce disappears after In Carta opens it.  But if the tif files can be read in plate format by MoBIE  just based parsing the file names, without either xdce, or jdce, then it would not matter.

**Comment by tischi** [comment]
Does that look good? One can even go through the different z-planes (using the mouse wheel).

<img width="958" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/3730b730-7d67-4641-910f-7baec254ad6d">

**Comment by ThomasMicroscopy** [comment]
Yes, looks right (don't remember if e04 is so dark), it's just an empty plate, so you see dirt, and out of focus dirt.

**Comment by tischi** [comment]
OK, I uploaded the changes; if you update Fiji you could try yourself.

**Comment by ThomasMicroscopy** [comment]
Hmm,  it updated MoBIE, but it generates an error, with basically the same dataset.
![smallIMG_2056](https://github.com/mobie/mobie-viewer-fiji/assets/126269188/b656a429-341e-4e51-887f-8dca43ba0558)

**Comment by tischi** [comment]
> Does the problem have anything to do that the button to open the file search dialog is missing?

Nope, I will make that button reappear.

> but it generates an error, with basically the same dataset.

Strange, let me check....

**Comment by tischi** [comment]
I uploaded a new version that will output a more informative error message.

Could you please run it again and post the new error message here?

The best would be if you copy and paste the actual text rather than posting a screenshot.

**Comment by tischi** [comment]
I will close this issue then and make new ones.
