### ISSUE TITLE
Delete view from UI

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1148]
There are several user requests that it would be great to enable _deleting_ a view from the UI.

@K-Meech is that something that you'd like to have a look at?

**Comment by K-Meech** [comment]
@tischi the next few weeks are super busy for me, so it would be a while before I could look at this. If you have time sooner - then go ahead! Otherwise I can look at it in a few weeks time.

**Comment by K-Meech** [comment]
@fstur unfortunately I haven't had the chance to implement this yet. I should have some time this week / next week to look into adding this though!

**Comment by tischi** [comment]
Hi @fstur,

We released a new version where this feature should be present. 

Could you please test it?

To access it: Right click in the BDV window and select "Delete view" from the drop down.

**Comment by tischi** [comment]
Nice!

Thanks @K-Meech !!
