### ISSUE TITLE
Enable gene search right click only for platybrowser

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#115]

**Comment by constantinpape** [comment]
Maybe this is overkill, but we could also generate this programaticly from a config. For example we could save a `preferences.json` somewhere and specify the behaviour for gene search there.
It could look something like this:
```json
{"name": "Search genes ...",
 "commandType": "local_search",
 "filePattern": "prospr-*"}
```
This would allow to reuse the functionality for other projects.

**Comment by tischi** [comment]
I think long term a good idea! 
I made a new issue for this: https://github.com/mobie/mobie-viewer-fiji/issues/116
You could re-post your idea there.

To quick-fix this specific issue, I just did:

```
		if ( projectLocation.contains( "platybrowser" ) )
		{
			BdvPopupMenus.addAction( bdv, "Search genes...", ( x, y ) ->
			{
```
