### ISSUE TITLE
Measure distance between two points

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1152]
Several people requested interest in measuring the distance between two points.

We should check what the current functionality provides and how to improve this.

Relevant classes:

- `CurrentLocationLoggerCommand`

ping @jhennies

**Comment by tischi** [comment]
To reliably also obtain the position of the mouse pointer, I think a keyboard shortcut would be needed to execute this command (unless we have other ideas)?

**Comment by tischi** [comment]
We could make the `CurrentLocationLoggerCommand` always remember the previous position and then simply always print the distance from the current to the previous position (easy feature and maybe helpful?).

**Comment by jhennies** [comment]
Can you check how it was done in an earlier version of MoBIE? I think in Mobie 1.x, the log current position output was giving you the position of the mouse pointer

**Comment by tischi** [comment]
> Can you check how it was done in an earlier version of MoBIE? 

Seems to have been [already for some time the window center](https://github.com/mobie/mobie-viewer-fiji/blob/c7752880bb35f920dd26b547d9df554115023169/src/main/java/org/embl/mobie/viewer/bdv/ViewerTransformLogger.java#L61).

**Comment by jhennies** [comment]
Ah, I missed that comment, sorry... Personally, I am already satisfied if I could get the current mouse position without the distance. But, considering there are use cases for a distance, your solution sounds good. It would be up to the user to do it correctly though, considering you would not be able to see the last point you clicked anymore. I would keep it simple, so good enough like this

**Comment by tischi** [comment]
@jhennies I uploaded a new version, how do you like it?

**Comment by jhennies** [comment]
Awesome, exactly how I need it, thanks!
