### ISSUE TITLE
Automatically close the registration windows once the transformations are accepted

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1166]
That ☝️  would be good, but I have not yet figured out how to do this...

See: https://imagesc.zulipchat.com/#narrow/stream/327238-Fiji/topic/Close.20Scijava.20Command.20UI

For instance that could be invoked in:

`ManualTransformationCommand.acceptManualTransform()`

**Comment by martinschorb** [comment]
Another request: could the original moving source be removed when the transformation is accepted? Then the active viewer would immediately show the result and not a duplicated source (original + transformed).

**Comment by tischi** [comment]
good point: please open a separate issue!
