### ISSUE TITLE
Keyboard shortcut for logging current location

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#117]
[ p ] does not work anymore.

**Comment by tischi** [comment]
@constantinpape @K-Meech @vzinche 

What about `[ Ctrl + L ]` as a shortcut to log the current location?

**Comment by constantinpape** [comment]
I find the shortcut pretty useful as I use the location feature quite often.
Ctrl + L would be good.

**Comment by K-Meech** [comment]
I use the location feature quite a lot too, so it's useful to have a keyboard shortcut. Happy to go with ctrl + L - but doesn't this currently shuffle the lookup table colours for the segmentation?

**Comment by tischi** [comment]
> Happy to go with ctrl + L - but doesn't this currently shuffle the lookup table colours for the segmentation?

arrgh, you may be right? Suggestions?

**Comment by vzinche** [comment]
Why don't we keep P for Position, as it was before?

**Comment by constantinpape** [comment]
> Why don't we keep P for Position, as it was before?

Only P doesn't work because it opens some big data viewer preferences now.

But we could go with ctrl + P.

**Comment by K-Meech** [comment]
Ctrl + P sounds good to me
