### ISSUE TITLE
Improve views saving UI

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1170]
ping @martinschorb

**Comment by tischi** [comment]
Hi @martinschorb,

I uploaded a new version with an improved View Saving dialog!

PLEASE TEST IT BEFORE THE COURSE !!

I will check also during the weekend and fix anything that you may find!

**Comment by martinschorb** [comment]
Looks good.
One thing though,  when you manually transform multiple sources at once, it opens a save view dialog for each single one. And it reverts the selections to the defaults. This can lead to transformed views of different channels ending up in different view groups. Could it instead either:
- create a single view containing all transformed sources
or
- somehow remember the selections for saving the view from the previous source

?

**Comment by tischi** [comment]
> somehow remember the selections for saving the view from the previous source

I will implement this for now.
