### ISSUE TITLE
Better UI symbols

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1174]
Hi @imagejan @constantinpape @martinschorb @tibuch,

What do you say about this? I feel it is a vast UX improvement 🕺 . 

<img width="674" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/85b9f4fc-92d0-42d6-84a2-b7430182bf7d">

https://github.com/mobie/mobie-viewer-fiji/tree/better-ui-symbols

**Comment by tibuch** [comment]
Fantastic!
What does the first button mean?😅

**Comment by tischi** [comment]
Focus

**Comment by imagejan** [comment]
"Focus" is very ambiguous in the context of a 3D volume... and I agree the button doesn't clearly convey the meaning of showing the entire layer/source (that's what it does, right?). How about one of those "page-fit" symbols like they're used e.g. in pdf viewers?

**Comment by constantinpape** [comment]
I agree that it looks much better overall but that the Crosshair Symbol is a bit unclear.

**Comment by tischi** [comment]
Could you all please post screenshots here of icons that you would prefer over the current focus icon?

**Comment by tischi** [comment]
And I think it would be more intuitive if the below would be moved from the "settings" to the "contrast" button:

```
	@Parameter( label = "Blending mode", choices = { BlendingMode.SUM, BlendingMode.ALPHA }, persist = false )
	String blendingMode = BlendingMode.SUM;
```

Would you agree?

**Comment by imagejan** [comment]
> Could you all please post screenshots here of icons that you would prefer over the current focus icon?
> 
> Or even better find some here: [icons8.com/icons](https://icons8.com/icons/)

![https://img.icons8.com/?size=100&id=r-AcTKDi8Aix&format=png&color=000000](https://img.icons8.com/?size=100&id=r-AcTKDi8Aix&format=png&color=000000)

![https://img.icons8.com/?size=100&id=g2lbyz6OsI9e&format=png&color=000000](https://img.icons8.com/?size=100&id=g2lbyz6OsI9e&format=png&color=000000)

**Comment by tischi** [comment]
<img width="120" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/6fb257d8-da82-4dc7-b865-fa8261b81337">

**Comment by tischi** [comment]
Here are many: https://icons8.com/icons/set/fit-to-page

**Comment by imagejan** [comment]
> Here are many: [icons8.com/icons/set/fit-to-page](https://icons8.com/icons/set/fit-to-page)

That's where I got the ones posted above, but GitHub messes up the link / embeds its own copy of the images...

**Comment by martinschorb** [comment]
I would rather use a CC icon set as this license sounds like a potential trap. https://icons8.com/vue-static/landings/pricing/icons8-license.pdf 
 I am pretty sure it is not compatible with MoBIE's current license.

**Comment by martinschorb** [comment]
something like this: https://icon-sets.iconify.design/

**Comment by tischi** [comment]
> I am pretty sure it is not compatible with MoBIE's current license.

Thanks for spotting this. I was only downloading the "free" ones, but there indeed seems to be a catch: https://icons8.com/license, so I will delete them again and not use them

**Comment by martinschorb** [comment]
ideally you would want a license without attribution required.
that's a cool and exhaustive one:
https://icon-sets.iconify.design/mdi/

**Comment by tischi** [comment]
@martinschorb could you help finding a good one for selecting the color? 
The other's I could find...

**Comment by tischi** [comment]
I am just drawing one myself now in Fiji:

<img width="422" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/a3292269-b25e-4c59-aebb-55a8d2d082b8">

**Comment by tischi** [comment]
@martinschorb shall I still release this before your course or you think that is too risky?

**Comment by imagejan** [comment]
> I am just drawing one myself now in Fiji:
> <img alt="image" width="422" src="https://private-user-images.githubusercontent.com/2157566/347393790-a3292269-b25e-4c59-aebb-55a8d2d082b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjAxNzgsIm5iZiI6MTcyMDYxOTg3OCwicGF0aCI6Ii8yMTU3NTY2LzM0NzM5Mzc5MC1hMzI5MjI2OS1iMjVlLTRjNTktYWViYi01NWE4ZDJkMDgyYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMTM1NzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI4NjIyOTFlMTZkNWQ0YWZiZWE3YzEyNzcwMDFlODkxMjc4ZTVjODA4YzdiYzgwNWZiMjM4MzQ3N2U5YjllYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UFzerVdeKrUVqbbByKysTen1t-b8D9fL0Fh6FCsZ4XY">

The only thing I dislike about this image is the lack of horizontal alignment between the green and blue circle 🙂

**Comment by tischi** [comment]
In fact, I redrew it to make the circles bigger, in summary, using the MIT licensed icons, it looks now like this:

<img width="250" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/dda34c11-1769-40bf-9d48-0cd96f167042">

The "fit to page" thing is not as pretty as the other ones, but I could not find a nice one with a MIT license. Maybe we could also just draw one ourselves. If there are any volunteers .... 😄 ?

**Comment by martinschorb** [comment]
Making all these changes to the GUI without updating the documentation just before running a course using that exact documentation is not necessarily perfect timing. :face_with_head_bandage:

**Comment by tischi** [comment]
I know! That's why I asked you (see above) whether I should update it but you did not answer...I thought it should be intuitive enough...did you struggle a lot? Hope it was still fine...?

**Comment by martinschorb** [comment]
I updated the main tutorial just now (in time ;-). In principle all the other screen grabs also need to be re-done.

**Comment by tischi** [comment]
OK....sorry again, due to bad git management on my side these GUI changes got intermixed with bug fixes that I also did for you and then it was too difficult to disentangle.

You should tell the students that we worked day and night the whole week to improve MoBIE for this course and that there is good probability that all this effort resulted in introducing new bugs a.s.o.

Basically, please tell them that they will work with a super hot release, for the better or worse...

**Comment by tischi** [comment]
And, believe me, I am as nervous 😰  as you whether all those changes done during this week will work now 🤞 🤞 🤞
