### ISSUE TITLE
Keyboard shortcut for Screenshot

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#118]
@constantinpape @K-Meech @vzinche @HernandoMV 

1. Do you frequently make screenshots, i.e. do we need a keyboard shortcut at all?
1. If so, what about `[Ctrl S]`?

**Comment by constantinpape** [comment]
I am not using screenshots that often, but if you want to make a shortcut Ctrl + S would be fine.

**Comment by vzinche** [comment]
We do need a shortcut, and I guess everybody using MoBIE for data analysis would need it as well. 
Ctrl + S sounds good!

**Comment by K-Meech** [comment]
I don't use the screenshot option that often, so I'm happy for it to stay in the right click menu. Happy with ctrl+s as a shortcut if you want one though. Although, doesn't this shortcut currently change the way the selected object is coloured?

**Comment by tischi** [comment]
> Although, doesn't this shortcut currently change the way the selected object is coloured?

...yeah, well spotted, so we need another one also here. That's a bit the issue with the shortcuts one runs out at some point....

**Comment by vzinche** [comment]
I've tried Ctrl+S a couple of times, and I don't get what it's doing. The first two clicks it changes the color of the selected object, on the third click it just selects all the objects. What was it originally planned for?

**Comment by vzinche** [comment]
Additionally, do we have a list of shortcuts anywhere? I remember them being in the help window of the platybrowser main menu, but now I don't seem to find it

**Comment by K-Meech** [comment]
I think the shortcuts are in the table menu now - under Help > Show Segmentation Image Help. 

@tischi Perhaps just leave the entry in the right click menu for now?  I think the problem is more that people don't know where to find these options. I don't think the readme mentions that this menu exists?

**Comment by vzinche** [comment]
For me clicking on Show Segmentation Image Help doesn't lead to anything :(
In any case, would probably make sense to move them to a more obvious place, like readme. 

Regarding the screenshots with right click, what I don't get is: for me it just shows another window with higher quality image, but still no way to save it, so I end up taking a screenshot of my screen. Would be great to have a way to save it locally. Or am I doing something wrong?

**Comment by tischi** [comment]
The new window can be saved from the Fiji UI.
Does that work for you?

**Comment by vzinche** [comment]
Stupid me. It does, thanks!

**Comment by tischi** [comment]
No keyboard short cut for now. Closing.
