### ISSUE TITLE
Showing a segments table if none is provided

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1184]
Hi @constantinpape,

Currently, we create, on the fly, a table for image segments, even if the user does not provide such a table to start with, but only opens a label image.

I cannot remember right now why this was useful, do you?

It must have been useful, I hope, because the code for this is quite involved and certainly was a lot of work....

**Comment by constantinpape** [comment]
I remember some of the background on this: @jhennies wanted to open segmentations without precomputed tables. The solution you found for this was computing the table on the fly. 

I assume it's necessary to have a table for opening the segmentation?! Otherwise it would have been  possible to open a segmentation without associated table directly.

**Comment by tischi** [comment]
Ah, it could indeed by that my code internally requires the presence of such a "segments table"; I need to check?

However, is there any benefit from actually ever displaying it?

**Comment by constantinpape** [comment]
> Ah, it could indeed by that my code internally requires the presence of such a "segments table"; I need to check?

Yes, I think that was the reason why you added it.

> However, is there any benefit from actually ever displaying it?

I am not really sure. I have not used this myself, as I usually create a MoBIE project with the python tools, which always add the table.

> The reason I am asking is that the rendering of such a "Lazy Segments Table" is a bit buggy (also discovered by @jhennies). And thus I am considering simply now showing it at all, i.e. removing the `[ ] T` checkbox for such cases.
> 
> If none of the two of you needs the visualisation of the table, I would like to remove the `[ ] T` and see whether anyone complains...

Yes, that's fine with me.
