### ISSUE TITLE
Not sure how to compile bvvpg

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1189]
Hi @ekatrukha,

I git pulled that latest bvvpg and could not compile it out-of-the-box. 

It gives me this choice to import a missing class:

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/869ee046-8aca-4bb9-8d32-ceb823e27dfa">

**Comment by ekatrukha** [comment]
This is strange that it shows `bvv-playground` 0.2.9, since in the `bvvpg` branch in pom it is 0.3.1, as it should be.
Maybe try Clean/Update maven on the project.
