### ISSUE TITLE
Multiple 'change animation settings...' entries

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#119]
Adding multiple volumes with tables, results in multiple 'change animation settings...' entries in the right click menu. e.g. with platybrowser datasets, opening the cell segmentation, and then the nuclei segmentation.
These change the animation settings for each table separately, but aren't labelled as to which volume they control. They still work fine, but it is a bit confusing.

**Comment by tischi** [comment]
This should be fixed now. I will upload to MoBIE-beta later today.
Please close this issue once you find it fixed. Thanks.
