### ISSUE TITLE
Add ShortType support for BVV

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1190]
```
Cannot display tissue in BVV, incompatible data type:
net.imglib2.type.numeric.integer.ShortType
```

Reproduce:

- Open PlatyBrowser
- Choose `tissue` segmentation (same drop-down as `cells` segmentation)

To be honest, this is probably some sort of bug when we stored the data and this should have been `UnsignedShortType` 😬 
Could we still support this?

**Comment by ekatrukha** [comment]
[This commit](https://github.com/mobie/mobie-viewer-fiji/commit/ffd0db1b02e98ba5a8b5f5e6bd5509e51fce13b9) should provide BVV support for datasets with arbitrary integer type (Long, Int, Byte, etc) or real type (Double, Float, etc) values.

If you can test it and it works, we can close this issue.

p.s. the tissue labels look very pretty in BVV after alpha range and alpha gamma adjustments:
![tissue](https://github.com/user-attachments/assets/2d985486-487f-48f0-8293-98c7f8ca1314)

**Comment by tischi** [comment]
OMG! This is nice!
I will test soon, travelling atm.

**Comment by constantinpape** [comment]
This looks amazing, and so much better than the old 3d viewer :)

**Comment by tischi** [comment]
Works!
