### ISSUE TITLE
Switching dataset freezes viewer in MoBIE-Beta

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#120]
Switching the dataset causes viewer to freeze. The initial dataset loads as expected, but upon switching it everything freezes without error message, see screenshot.
Note that this only happens with the version on the MoBIE-Beta side, not with the one on the normal update site.

I have tested this on my linux laptop and @jhennies also reported this on a Linux machine.
I have checked it for the two datasets https://github.com/mobie/covid-em-datasets and https://github.com/mobie/covid-tomo-datasets and the issue occurs for both of them.

![switch-ds-bug](https://user-images.githubusercontent.com/4263537/93224386-55bc7280-f771-11ea-8a34-bf6acf75b091.png)

**Comment by tischi** [comment]
I can reproduce this. Trying to find out why this happens....

**Comment by tischi** [comment]
@constantinpape 
Are you currently doing something on the "covid-em-datasets" repo? I am using this for debugging above issue but it seems your are changing stuff there?

**Comment by tischi** [comment]
- [ ] make sure the Swing UI (sources panel is fully visible before instantiating the new BDV)
- I asked also here: https://github.com/bigdataviewer/bigdataviewer-core/issues/108
- I added a workaround to the MoBIE-beta update site which works for me, does it work for you?

**Comment by constantinpape** [comment]
Yes, it works for me with the latest version on beta too.

**Comment by jhennies** [comment]
Yes, also works here, thanks @tischi

**Comment by tischi** [comment]
- [ ] to fix this on a fundamental level it seems I need to ship a newer version of bdv-core where this is fixed properly, see here: https://github.com/bigdataviewer/bigdataviewer-core/issues/108

**Comment by constantinpape** [comment]
@tischi looks like this problem is fixed in bdv-core. Are we using that version already and can we close this issue?
