### ISSUE TITLE
BVV screen is black for arapidopsis data

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1203]
Hi,

I adjusted the contrast to the see the data in BDV but then in BVV I cannot see anything:

<img width="1906" alt="image" src="https://github.com/user-attachments/assets/1cba3735-369e-40dd-9d25-b5d7247a8c0d" />

This is using the latest `bvvpg` branch with

```
		final ImageJ imageJ = new ImageJ();
		imageJ.ui().showUI();
		new MoBIE("https://github.com/mobie/arabidopsis-root-lm-datasets",  new MoBIESettings() );
```

Am I doing something wrong?

**Comment by tischi** [comment]
Same for the labels:

<img width="1890" alt="image" src="https://github.com/user-attachments/assets/25ebf25a-670e-42d3-aed8-a83e9b6bf439" />

**Comment by ekatrukha** [comment]
Done, I've updated the title of bvv window to "MoBIE BigVolumeViewer" in the latest commit.

**Comment by ekatrukha** [comment]
Oh, yes, I see now.
`Clip near distance` in the settings should be smaller than the `Camera position`.
In the new version of the command I think I fixed it,
I think your values are remains of the previous iteration.
BTW, try this trick with `Clip near distance` of 0 or 1 and camera position 1000 and **D** to sync views.

**Comment by tischi** [comment]
Amazing!

<img width="912" alt="image" src="https://github.com/user-attachments/assets/6c113852-8f16-4f8f-9f6d-6a7239320998" />

**Comment by tischi** [comment]
Wow, can't stop look at it, so nice!!!

<img width="912" alt="image" src="https://github.com/user-attachments/assets/189a95e8-a0f1-4577-ac12-6925bb8a2823" />

**Comment by ekatrukha** [comment]
yeah, I think fluorescence data really benefits from a 3D view, 
while EM is more 'crowded' and so harder to explore.
