### ISSUE TITLE
BVV segmentation visualization not working?

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#1205]
Hi @tischi  @ekatrukha ,
I tried visualizing segmentations using BVV in the platynereis dataset, but it does not work as expected for me / the segmentations are not rendered.

See a video of me trying to render segmentations:

https://github.com/user-attachments/assets/d26938e7-e0f4-4870-8c40-52c02bef7376

Is there anything else I need to do? I also get an error in the log:

```
Exception in thread "Fetcher-0" java.lang.NoSuchMethodError: net.imglib2.view.Views.flatIterable(Lnet/imglib2/RandomAccessibleInterval;)Lnet/imglib2/IterableInterval;
	at org.embl.mobie.lib.bvv.SourceToViewerSetupImgLoaderBvv$SourceArrayLoader.loadArray(SourceToViewerSetupImgLoaderBvv.java:212)
	at org.embl.mobie.lib.bvv.SourceToViewerSetupImgLoaderBvv$SourceArrayLoader.loadArray(SourceToViewerSetupImgLoaderBvv.java:175)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$0(VolatileGlobalCellCache.java:196)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:55)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:135)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:53)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:484)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:53)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:531)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:508)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:181)
```

**Comment by tischi** [comment]
Hi @constantinpape,

```
java.lang.NoSuchMethodError: net.imglib2.view.Views.flatIterable(Lnet/imglib2/RandomAccessibleInterval;)Lnet/imglib2/IterableInterval
```

This smells like something that is beyond our control. There have been a couple of breaking changes in ImgLib2 recently...

Could you please check whether you also get this when you start from a freshly downloaded Fiji and you only install the MoBIE plugin?

**Comment by ekatrukha** [comment]
Hello @constantinpape,


Thank you for testing!
Can you please check what is the version of your imglib2 in that Fiji installation?

And if your Fiji has BigStitcher update site activated.

I think Curtis was working on fixing it, so it could be a useful info.

Indeed, fresh install should work.

Cheers,
Eugene

**Comment by constantinpape** [comment]
> Can you please check what is the version of your imglib2 in that Fiji installation?

I have version 7.1.2.

> And if your Fiji has BigStitcher update site activated.

Yes, I have the BigStitcher update site active.

> Indeed, fresh install should work.

I will try with a fresh install.

**Comment by constantinpape** [comment]
I did a fresh installation and only added the MoBIE update site, but then it does not open BVV upon clicking `V`, but opens the old ImageJ 3D Viewer:

![image](https://github.com/user-attachments/assets/23a20e7f-2f97-48e7-a941-3d6226599544)

**Comment by tischi** [comment]
Hi @constantinpape, thanks for testing, you should check `B` (not `V`) to open **B**VV, does that work?

**Comment by constantinpape** [comment]
Yes, it works now! Though I think having two volume viewers is confusing (not something that has to be fixed now, but maybe to consider before announcing it).

**Comment by constantinpape** [comment]
It stops working after adding the BigStitcher Update site again. So the two plugins seem to be incompatible (because BigStitcher uses an older imglib2 version?!)

**Comment by ekatrukha** [comment]
On the opposite, it uses a newer version of imglib2 (uploading it from its update site), breaking [a lot of other plugins](https://forum.image.sc/t/labkit-crashes-when-the-bigstitcher-site-is-activated/105100/19?u=ekatrukha).

We can update to it, but the newer version of imglib2 is not shipped with Fiji by default. So again, then it will break a lot of other plugins.

And this all gets a bit complicated by anticipated migration to java 21 and holidays.

**Comment by constantinpape** [comment]
I see! From my end I would say that it's best that MoBIE is compatible with the version shipped by default Fiji. We could add some note that it's incompatible with BigStitcher, so whoever wants to use both would need separate Fiji installations. (And hopefully this will resolved in the migration.)

**Comment by tischi** [comment]
> It stops working after adding the BigStitcher Update site again. So the two plugins seem to be incompatible (because BigStitcher uses an older imglib2 version?!)

[There is a big discussion on this on the forum](https://forum.image.sc/t/labkit-crashes-when-the-bigstitcher-site-is-activated/105100/21?u=ekatrukha)! I think this is an issue with BigStitcher, which currently ships ImgLib2 core libraries that are not what comes with Fiji and thus breaks a lot of stuff. So, if you want to use BigStitcher right now, I would recommend to use a separate Fiji for that.

> Though I think having two volume viewers is confusing (not something that has to be fixed now, but maybe to consider before announcing it).

I am not sure, I would leave it for a while, because the renderings don't look the same. Segments look nicer in the old one and some users may appreciate this.

-------

Can we then close this issue?

**Comment by ekatrukha** [comment]
I think so, yes.
