### ISSUE TITLE
ViewerTransform animation issues

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#121]
- [ ] Changing to a new ViewerTransform via the "location" [ move ] leads to short flicker of new location
- [x] Changing to a new ViewerTransform via a Bookmark does not animate 

Interestingly doing the same moving to a position (not a viewertransform) does not have these issues. Why is that?

**Comment by tischi** [comment]
Probably makes sense to try this with the a `10.*` version of BDV.

**Comment by tischi** [comment]
The latter is due to this issue, which I also commented in the code:

```
// note: if this is trying to restore the default bookmark
// it may not do anything because bdv already automatically
// adapts the viewer transform when restoring the default view
// in case only one source was added
```

**Comment by constantinpape** [comment]
I think this one is outdated, I don't see the flicker in current MoBIE-beta.
