### ISSUE TITLE
Default Bookmark

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#123]
@constantinpape @K-Meech @vzinche 

For the default bookmark: 

Do you we
1. just want the default viewer transform to be applied (to help people that got lost rotating around), or
2. also all additional layers removed and only the layers shown that are specified in the default bookmark?

**Comment by constantinpape** [comment]
>     1. just want the default viewer transform to be applied (to help people that got lost rotating around), or
> 
>     2. also all additional layers removed and only the layers shown that are specified in the default bookmark?

That's a good question. I think that option 1 would actually be more useful, but it would mean that the default bookmark is treated differently than all other bookmarks.

**Comment by tischi** [comment]
> but it would mean that the default bookmark is treated differently than all other bookmarks.

That's already the case and in fact makes my code a bit messy. The reason is that in most cases the default bookmark currently does not come with a specified ViewerTransform. So I have to check whether this is present and if not add it on the fly (based on whatever BDV thinks is the nicest view) to the bookmark....

Maybe I could not do this and rather automatically build a "default view" bookmark (if none of that name exist already) which only contains a viewer transform. Or, I think we discussed this at some point, we add one more button: [ Return to default view ] which either brings you back to the view that is specified in the default bookmark, or, if nothing is specified, it brings you back to what bdv initially decided was a good view.

**Comment by vzinche** [comment]
What do you think about adding a keyboard shortcut for this? Like, Ctrl + D?
In a way bookmarks are used for a completely different purpose, and Default Bookmark is more similar to Ctrl+X/Y/Z of the BDV

**Comment by tischi** [comment]
> In a way bookmarks are used for a completely different purpose, and Default Bookmark is more similar to Ctrl+X/Y/Z of the BDV

Agreed! That's why I thought of adding an additional button to the MoBIE UI; but we could also put it into the context menu and add a shortcut if needed.

**Comment by constantinpape** [comment]
> Agreed! That's why I thought of adding an additional button to the MoBIE UI; but we could also put it into the context menu and add a shortcut if needed.

I agree it would be very helpful to have this feature.
I think for this I would prefer a new button in the UI + shortcut rather than context menu.

**Comment by tischi** [comment]
- [ ] Add button for default view to UI (fetch the view either from default bookmark or, if that does not exist, create a normalised view from whatever bdv shows first)
- [ ] Remove all the code that deals in a special way with the default bookmark

**Comment by vzinche** [comment]
I would still maybe add the shortcut, it's just much handier when you're browsing the BDV not to have to look for the main window

**Comment by constantinpape** [comment]
>  Remove all the code that deals in a special way with the default bookmark

To be a bit nitpicky, there still needs to be special code for the default bookmark that uses the default bdv view if there is no view in the bookmark.

> I would still maybe add the shortcut, it's just much handier when you're browsing the BDV not to have to look for the main window

No objections to adding a shortcut for this from my side :).

**Comment by tischi** [comment]
I changed my mind (agreeing with @vzinche) I will make it for now context menu and short cut.
Reasons: 
1. easier to do than to add a button
2. keeps the main UI more minimal
3. prettier to indicate the shortcut in the context menu than in the button

**Comment by tischi** [comment]
![image](https://user-images.githubusercontent.com/2157566/93495187-21ca8400-f90e-11ea-922c-54770926b505.png)
