### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#124]
Hi All, 

I am trying to assemble a list of the keyboard shortcuts:

Button1 = Left Mouse Button

## Current

- Toggle point overlays `Ctrl P`
- Search Genes `D`
- Select Segment `Ctrl Button1`
- View Segment in 3D `Ctrl Shift Button1` 
- Select No Segment `Ctrl Shift N`
- Move to next image set `Ctrl N` (not used in MoBIE, but I need it)
- Move to previous image set `Ctrl P (not used in MoBIE, but I need it)
- Shuffle Random Colours `Ctrl L`
- View binary mask as boundaries mask `Ctrl B`
- View label mask as binary mask `Ctrl M`
- Change Segment Selection Colouring `Ctrl S`
- Log Position and View `P` (does not work anymore)

## Suggested and discussion

- Toggle point overlays `Ctrl P`
   - I forgot: when do we actually need point overlays? 
   - [x] **I would remove this feature for now until we really need it.**
- Search Genes `D`
   - [x] **Remove shortcut, only context menu**
- Select Segment `Ctrl Button1`
- View Segment in 3D `Ctrl Shift Button1` 
   - [x] **Remove this as it is not useful anymore** 
      - EDIT: I may be useful for non MoBIE applications... => maybe to context menu
- Select No Segment `Ctrl Shift N`
   - [x] Issues:  If several segmentations are shown one in principle should be able to say for which one to apply this... this could be solved by removing the shortcut and using a context menu instead, however I use this quite often, so maybe we need a shortcut??
- Move to next image set `Ctrl N` (not used in MoBIE, but I need it for other projects)
- Move to previous image set `Ctrl P` (not used in MoBIE, but I need it for other projects)
- Shuffle Random LUT Colours `Ctrl L`
- View solid mask as boundaries mask `Ctrl B`
- View label mask as binary mask `Ctrl M`
- Change Segment Selection Colouring Mode `Ctrl S`
   - [x] **Only context menu**
      - I think one does not need it so often and also it is nice to be able to read which selection colouring mode one actually is using.
- Log Position and View `P` (does not work anymore)
   - [x] **Only context menu.**
   - Reasoning: it is important where the mouse is, so right-clicking into context menu would enforce the idea that the current mouse location is important, if it it just a keyboard short-cut the mouse could be anywhere (psychologically)

@K-Meech @constantinpape @vzinche 

0. Questions?
1. Did I miss some?
2. What do you think?

**Comment by vzinche** [comment]
>     * Toggle point overlays `Ctrl P`
I have no clue what that was for 
>     * Search Genes `D`
Good in context menu
>     * Select No Segment `Ctrl Shift N`
I would rather rename it to Unselect All or something like this. I am using it often and would vote for it to stay. Regarding multiple segmentations, I am pretty happy with the default behavior of unselecting in all segmentations. 
>     * Log Position and View `P` (does not work anymore)
I guess it's fine in context menu

**Comment by constantinpape** [comment]
Overall sounds very good!

> Select No Segment `Ctrl Shift N`
> 
>     * Issues:  If several segmentations are shown one in principle should be able to say for which one to apply this... this could be solved by removing the shortcut and using a context menu instead, however I use this quite often, so maybe we need a shortcut??

I agree, it can go to the context menu without shortcut, so that one can select for which segmentation to do this.
Minor comment, the name is a bit confusing, because when we do this all objects in the segmentation are still visible and marked in the table. I no that this is something else than selection (e.g. they are not shown in the 3d viewer), but naively when reading `Select No Segment` I would assume that no segment was highlighted.
Maybe call it `Undo selection`?

**Comment by tischi** [comment]
> Select No Segment Ctrl Shift N

@constantinpape I think @vzinche said that she would like to keep a shortcut and I think I agree as this is something I am also using very often. But with shortcut it will be difficult to distinguish for different segmentations.

> Maybe call it `Undo selection`?

Agree, this is a better name!

**Comment by tischi** [comment]
ok, that's how the context menu looks now if there is more than one segmentation.

I could nest the menu items even more, i.e. by segmentation such that we get rid of the `.  :  `, but that's a bit of work so I wonder if it is worth it?

Pro: it would look cleaner; Con: one would have to navigate one level deeper with the mouse.

![image](https://user-images.githubusercontent.com/2157566/93472226-ac9e8500-f8f4-11ea-9498-dd7570ba3cc7.png)

**Comment by constantinpape** [comment]
> @constantinpape I think @vzinche said that she would like to keep a shortcut and I think I agree as this is something I am also using very often. But with shortcut it will be difficult to distinguish for different segmentations.

Ok, we can keep the shortcut and in that case just do it for all segmentations?!

> Pro: it would look cleaner; Con: one would have to navigate one level deeper with the mouse.

Maybe something to make it look cleaner without much work:
Shorten the segmentation name by just keeping the first and last string when splitting by `-`,
i.e. `sbem-cells`, `sbem-nuclei`.
We also do this in the MoBIE menu, so I think that should be fine and it would make it look more concise.

**Comment by tischi** [comment]
I already decided to invest the work and now it looks like this:

![image](https://user-images.githubusercontent.com/2157566/93482170-b24d9800-f8ff-11ea-9420-77399b653138.png)

And those entries are automatically removed again when you remove the segmentation with the [ X ].
We could discuss to also remove them when making the image just invisible, but I need a break now... ;-)

Shortening the names would have raised some discussions anyway...

**Comment by tischi** [comment]
In principle this issue could be closed once I pushed it to MoBIE-beta and some people tested everything....

**Comment by vzinche** [comment]
:+1: for 
* calling it Undo selection
* keeping it as a shortcut that applies Undo to all segmentations
* adding it to the context menu nested (the way it is on your last pic). I think just listing all the options for all the segmentations might look terrifying when you have too many segmentations :)
