### ISSUE TITLE
Versions testing

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#126]
I uploaded a new version to the `MoBIE-beta` Update site. Could you please test it a bit and add a thumbs up if you think that this version would be good enough to make it into the `MoBIE` site (which right now has a rather crappy version where one cannot even change dataset, so the hurdle is rather low...). 

I am aiming to do this tomorrow after lunch...

@martinschorb @constantinpape @K-Meech @vzinche 

Thanks ❤️

**Comment by constantinpape** [comment]
I tried around a bit and so far there are two issues:
- [Color by column in bookmarks](https://github.com/mobie/platybrowser-datasets/issues/68) this was discovered by @K-Meech, and it might also have been an issue before this version
- [Bookmarks in tomo dataset](https://github.com/mobie/covid-tomo-datasets/issues/2)

**Comment by K-Meech** [comment]
I also just noticed there was an error in the argb column code I added (I fixed it and put a new pull request on imagej-utils @tischi )

**Comment by constantinpape** [comment]
@tischi I think with the coloring stuff is fixed this should be good to go.
Do you want to push another version to mobie beta with these fixes so we can give it another go or do you want to push to the mobie update site directly?

**Comment by tischi** [comment]
I uploaded the latest fixes to `MoBIE-beta`.
If I don't hear from any of you in the next one hour I will cut releases of the repos and then also push to `MoBIE`.

**Comment by vzinche** [comment]
I didn't see any MoBIE problems, but I suggest that we all proofread our bookmarks, because some of them don't seem to work any more. E.g, 5D-top-middle gives me java.lang.ArrayIndexOutOfBoundsException and 2C shows some random cells

**Comment by vzinche** [comment]
Oh, this one is probably from the viewer side #127

**Comment by tischi** [comment]
> but I suggest that we all proofread our bookmarks,

If you do this could you please also replace the viewer transform with a normalised viewer transform?

**Comment by constantinpape** [comment]
> If you do this could you please also replace the viewer transform with a normalised viewer transform?

Yes, I will check what's going wrong with the ids and then we should do this.

Unrelated: I think it's not possible to load a project from a git branch other than master right now, see #128.
It would be very useful to support this again for debugging (not necessarily in this release, but rather soon ;)).

**Comment by constantinpape** [comment]
@tischi did you update the normal mobie already / are you still planing to do it today?

**Comment by tischi** [comment]
working on it... letting you know once I am done.

**Comment by tischi** [comment]
Ok, both done, and actually me too ;) 
Felt like a real software release :)

**Comment by tischi** [comment]
Hi @K-Meech @vzinche @HernandoMV @yanschwab @martinschorb @jhennies,

I just updated MoBIE-beta.

If you think that version is good enough to become the new alpha, please add a thumbs up!

Thanks a lot for testing!

PS: @martinschorb when going through the issues I saw that there are still a number of very relevant and good suggestions from you that I did not yet find the time to work on. I'll try for our next release!

**Comment by tischi** [comment]
Ok, I released `mobie-0.5.3`
Fingers crossed that is works!
