### ISSUE TITLE
Bookmarks: contrastLimits

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#127]
In a bookmark I am coloring by column and want to set min-max value for the colorByColumn.

Before I was just just setting contrastLimits in the bookmark like [here](https://github.com/mobie/platybrowser-datasets/blob/4ad227b475fc90e9aedde1cdde76c1686dc97959/data/1.0.1/misc/bookmarks/manuscript_bookmarks.json#L804)
Now it sets these contrast limits for both colorByColumn and the segmentation layer.

Is there a way to set these values separately?

![Screenshot from 2020-09-18 15-13-19](https://user-images.githubusercontent.com/32451366/93601540-a6c2a580-f9c1-11ea-8cf1-31d6ca8297c1.png)

**Comment by tischi** [comment]
@constantinpape 
I think this is an actual issue (which we talked about some while ago, not sure we have an issue for it already).
![image](https://user-images.githubusercontent.com/2157566/93604795-2b172780-f9c6-11ea-964c-c955406493c5.png)
I wonder whether we need another entry in the bookmark for the `colorByColumn`, maybe something like `valueLimits`, which will determine how the values in the column are mapped onto the LUT, whereas `contrastLimits` controls more the alpha value (opacity) of the displayed colours. Frankly I would have to dig deeper into the code to understand what is actually going on there.

Short term solution: I can use the `contrastLimits` as `valueLimits` and then hard-code the values in the brightness [ B ] settings. For above figure 0 to 1000 looks good to me. @vzinche would 0 to 1000 work (also for our other figures)?

**Comment by vzinche** [comment]
Looks like all the other figures are also setting it to 0-1000, so I guess we could do it.

**Comment by tischi** [comment]
Done. Leaving issue open as this needs a better fix.

**Comment by vzinche** [comment]
@tischi 
Somehow this stopped working. Additionally, when I load [this bookmark](https://github.com/mobie/platybrowser-datasets/blob/4ad227b475fc90e9aedde1cdde76c1686dc97959/data/1.0.1/misc/bookmarks/manuscript_bookmarks.json#L798), and afterwards load [the next one](https://github.com/mobie/platybrowser-datasets/blob/4ad227b475fc90e9aedde1cdde76c1686dc97959/data/1.0.1/misc/bookmarks/manuscript_bookmarks.json#L978) the brightness for the later one is taken from the former one (0:40).

**Comment by tischi** [comment]
@vzinche 
Well spotted! 
Somehow I did not merge below this fix into the current master 😕 

```Java 
    private void setDisplayRange( BdvStackSource bdvStackSource, Metadata metadata )
    {
        if ( metadata.contrastLimits != null )
        {
            if ( metadata.colorByColumn == null )
            {
                bdvStackSource.setDisplayRange( metadata.contrastLimits[ 0 ], metadata.contrastLimits[ 1 ] );
            }
            else
            {
                // TODO: This should be configurable
                //   See issue: https://github.com/mobie/mobie-viewer-fiji/issues/127
                //   Note: the valueRange for the table (used in ColorByColumn) is set somewhere else, using the `contrastLimits`...
                bdvStackSource.setDisplayRange( 0, 1000 );
            }
        }
    }
```

Please update MoBIE-beta and try again.

**Comment by tischi** [comment]
@K-Meech @vzinche @constantinpape 
I think I know now where the 1000 comes from. If we applied a coloring model to a label mask image the image is converted to an 8-bit RGB image, where each color is displayed at its maximal brightness if one chooses contrastLimits from 0 to 255. If one chooses lower or higher max values all colors are brighter or dimmer, respectively. This is also how ImageJ behaves in this scenario (see below). So, if we set the maximum to 1000 we are telling bdv to paint the colors rather dim, which looks especially good (relatively brighter) if they are displayed on top of a greyish background (our EM), because the blending mode in BDV takes the **sum** intensity of all displayed image sources. This also means, the more stuff you show on top of each other, the dimmer you shouyld make each individual image source. For this reason, I wrote code for another project, where I also implemented and **avg** intensity blending mode, which can be better in certain (most?) cases (we can think about whether we would like to also have this in MoBIE). 

Could someone test how Napari behaves for these things?

![image](https://user-images.githubusercontent.com/2157566/94111746-c2580100-fe44-11ea-987b-776f2aa0b41d.png)
![image](https://user-images.githubusercontent.com/2157566/94111866-ea476480-fe44-11ea-8ab3-8a9f7d482d45.png)
![image](https://user-images.githubusercontent.com/2157566/94111915-f92e1700-fe44-11ea-9884-fb0d6832e5f3.png)

**Comment by vzinche** [comment]
I think this thread describes it nicely:
https://github.com/napari/napari/issues/79

**Comment by tischi** [comment]
@K-Meech 
Do you have the capacity to give this a go?
I think for sure we would need to add/support a field `valueLimits` to the bookmarks for `ColorByColumn` where the coloring model is numeric.

**Comment by K-Meech** [comment]
@tischi Sure! - happy to have a look into it. Although, it will probably have to wait until the week after next (it's the virtual arendt lab retreat next week)

**Comment by tischi** [comment]
@K-Meech 

cc @constantinpape @vzinche 

Your changes look good! Thank you!
Before I merge it though, we should coordinate with the others how to handle the transition period.

With Kimberly's changes a new field `valueLimits` will be supported for the bookmarks (see above) and the field `contrastLimits` will no longer be abused as `valueLimits` and the hack with setting the `contrastLimits` to `(0,1000)` by default also is gone. Thus, if we now change the bookmarks accordingly they will look wrong in the MoBIE update site. Ideally we find a solution  such that we can test stuff on MoBIE-beta without breaking MoBIE....

**Comment by constantinpape** [comment]
That sounds like we should make a branch for this and change the bookmarks to the new format there and then test it with the changes you push to the MoBIE beta site.

**Comment by constantinpape** [comment]
Ok, I made a new branch for this, feel free to push the relevant changes to it:
https://github.com/mobie/platybrowser-datasets/tree/value-limits

**Comment by tischi** [comment]
Changes should be in MoBIE-beta now.
Happy testing!

**Comment by K-Meech** [comment]
@vzinche Could you check your bookmarks? I think probably only your bookmark 6F needs changing in the branch Constantin made above. "contrastLimits" is now for the whole segmentation (usually 0, 1000 limits) and "valueLimits" are the limits for the column you're colouring by.

**Comment by vzinche** [comment]
Yup, I've just tested it (in value-limits) and it works!
@constantinpape, could I also use this branch to test the normalized view in the bookmarks? 
Somehow MoBIE doesn't work when I give it my platybrowser fork as the Project Location

**Comment by constantinpape** [comment]
> @constantinpape, could I also use this branch to test the normalized view in the bookmarks?

Sure

**Comment by K-Meech** [comment]
@vzinche @constantinpape I finally got around to changing the rest of the platy bookmarks to use normView in the 'value-limits' branch of platybrowser-datasets. Can we merge this branch now?

**Comment by constantinpape** [comment]
Works for me. Go ahead and merge, if that's also ok with @vzinche.

**Comment by vzinche** [comment]
OK with me :+1:

**Comment by K-Meech** [comment]
merged!
