### ISSUE TITLE
Tutorials / user guide

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#129]
For the more complex parts of mobie e.g. making your own project, using the 'advanced' mode, creating bookmarks etc... it would be useful to have some more detailed documentation, or tutorials, available. e.g. via Github pages or readthedocs.

e.g. we could have something similar to the napari project > https://napari.org/tutorials/, which is made with github pages.

@tischi @constantinpape @vzinche - what do you think? I'm happy to look into this if you think it would be useful.

**Comment by tischi** [comment]
Sure! I just wonder whether we should keep it low-tech and just add everything to the README.md (more portable and easier) or whether to go for github pages (looks more fancy).

Ideally we have a solution that works for both:  *.md files which can be viewed directly or via the github pages. Is that possible? 

I would **not** like to have "documentation duplication" where we have to update things in more than one place.

**Comment by vzinche** [comment]
I think it would be great to have documentation available.
Don't have any strong preferences regarding github pages vs Readme.
Probably I would still split the advanced stuff from the main project Readme not to confuse the users who don't want to do anything advanced

**Comment by K-Meech** [comment]
Github pages does let you use regular *.md files, but the formatting is slightly different I think. e.g. for napari, they have a separate repo for all their tutorials: https://github.com/napari/tutorials, where each individual page is a .md file e.g. https://github.com/napari/tutorials/blob/master/fundamentals/image.md.

**Comment by vzinche** [comment]
The formatting looks completely normal to me, given that github properly parses it (except for the image location, but we could definitely deal with it)

**Comment by vzinche** [comment]
Could we make a separate repo for the tutorials, but link the actual readme's from the main repo?

**Comment by K-Meech** [comment]
Sounds like a good plan to me! Then people can view in github, or view the fancy formatting in github pages.

**Comment by tischi** [comment]
> Could we make a separate repo for the tutorials, but link the actual readme's from the main repo?

Yes! @K-Meech: Go for it, I would say!

**Comment by K-Meech** [comment]
I put together a quick example in the repo: https://github.com/mobie/mobie.github.io e.g. I copied part of the readme as an example: https://mobie.github.io/tutorials/getting_started.html
Seems to all work well to me! I'll start adding some tutorials to the tutorials/ folder over the next few weeks.

**Comment by vzinche** [comment]
Looks really cool! I'll try to add a small annotation tutorial

**Comment by K-Meech** [comment]
@constantinpape @tischi @vzinche I've put drafts of a bunch of tutorials in the repo - you can see the index.md here: https://github.com/mobie/mobie.github.io/blob/master/index.md with links to all the other pages, or the nicely formatted github pages version here: https://mobie.github.io/ Let me know what you think! I've adapted the info from the original readme into the tutorials, as I figured it'd be nice to have all this info in the same place. The main missing parts now are tutorials on how to setup your own project...

**Comment by K-Meech** [comment]
I'm going to update these tutorials over the next few days to add more info on making projects etc. Let me know if there is anything else major missing

**Comment by K-Meech** [comment]
These are up to date now. @tischi - do you mind if I add a link to these tutorials (https://github.com/mobie/mobie.github.io/blob/master/index.md) to these readmes? https://github.com/mobie/mobie and https://github.com/mobie/mobie-viewer-fiji

**Comment by tischi** [comment]
Sure, go ahead!

**Comment by K-Meech** [comment]
I'll close this - we can make more issues for specific things we want to add to the tutorials
