### ISSUE TITLE
Bookmark browsing for many sources that are spatially separated

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#130]
...such kind of data it could be convenient if the bookmarks were somehow accessible from the table…otherwise I find it a bit cumbersome to find them in the bookmark drop-down.

Or, via right click, where the context menu would only show the bookmarks that are relevant for the data sources that the mouse pointer hits.

**Comment by constantinpape** [comment]
I agree that a simple list of bookmarks is a bit cumbersome to navigate.
For the covid-tomo project, I think the table is much more convenient; the bookmarks actually don't provide more functionality than the table.

But of course one could think of having multiple bookmarks per tomogram (or per spatially separated source).
Then having the bookmarks in the context menu would be an option.

**Comment by yanschwab** [comment]
I agree in principle, that the table entry is straight forward and makes it easy to sort the tomograms according to specific features (columns), but, the drop down list of bookmarks is quite easy. It's likely that the readers will use the excel table, that is annotated, to browse the files and select the particular tomograms they are interested in.
