### ISSUE TITLE
Contrast limits has no effect in "regular" Mobie update site version

### ISSUE THREAD

**Issue by jhennies** [mobie/mobie-viewer-fiji#138]
Hi @tischi,

in mobie from the regular update site the contrast limits setting in images.json has no effect on the startup brightness and contrast setting in BDV and the segmentation appears a bit dim.
In the mobie-beta version it works just fine. 

Can I ask you to update the main mobie update site? (It is quite important as the Covid publication goes online soon)
Or do you think there is a different issue?

Thanks in advance!

**Comment by tischi** [comment]
@K-Meech 
Do you think we could make the current MoBIE-beta the alpha?

**Comment by K-Meech** [comment]
I think it looks good to me. Although, some of the bookmark changes may need some adapting to. e.g. if the covid repos have multiple bookmark files (not just the default), they will no longer be automatically loaded. Don't know if that's a problem?

**Comment by tischi** [comment]
@K-Meech Regarging this, could you check with martin and julian whether MoBIE-beta works for them?

**Comment by K-Meech** [comment]
Sure - will do.

**Comment by jhennies** [comment]
@tischi for me the MoBIE beta works just fine
