### ISSUE TITLE
Annotate Skip None Default

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#139]
@vzinche @constantinpape 
I would like to change to default for `Skip None & NaN` to `False`. You can still change it by one click.

Reason: Normally, if people want to annotate they exactly want to annotate the ones which are not yet annotated, i.e., the ones that are `None`.

I think our use case where one wants to correct annotations is more rare.
Ok for you?

**Comment by constantinpape** [comment]
> I would like to change to default for `Skip None & NaN` to `False`. You can still change it by one click.

So this means the segments that are labeled `None` will not be skipped and we can set a label for this in the annotation mode?
If so, I agree; annotating the unlabeled is probably a more common use-case and should be supported.

**Comment by tischi** [comment]
> So this means the segments that are labeled None will not be skipped and we can set a label for this in the annotation mode?

Yes, and it is just one checkbox click to change this:

![image](https://user-images.githubusercontent.com/2157566/98358297-c754c680-2026-11eb-8736-97938651efe5.png)

**Comment by vzinche** [comment]
Fully support the idea!
