### ISSUE TITLE
Annotate Default Color for None

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#140]
@vzinche @constantinpape @K-Meech
 
Would it be Ok if I changed the default colour for the `None` objects to some dark grey (it would look like below)?
I think it is nicer to be able to see which segments actually exist in an image.

### Boundary mode (Ctrl + B)

![image](https://user-images.githubusercontent.com/2157566/98355466-72af4c80-2022-11eb-9fd5-e7b81e29e390.png)

### Filled mode

![image](https://user-images.githubusercontent.com/2157566/98355553-94a8cf00-2022-11eb-8bcd-2f2c3ad5b81d.png)

cc @ssgpers, potential future user of the Annotator.

**Comment by K-Meech** [comment]
Fine with me - but could it be optional? Having None displayed as transparent is very useful for me when making figures that only focus on a certain region / subset of cells.

**Comment by constantinpape** [comment]
Is it possible to change the colour to transparent?
If so, I think it's ok to change it.

**Comment by tischi** [comment]
> but could it be optional? 

1. Sure, just click on the `[ C ]` button next to `None` and you can change the colour to black (= transparent in our current blending mode).
2. I will **_only_** change this for the default of the anntotation mode! Otherwise the `None` and `NaN` and `0` and `0.0` will stay transparent as we are used to.

**Comment by K-Meech** [comment]
Ah ok - sounds good to me! If it's just for annotation mode, then it makes total sense.
