### ISSUE TITLE
Annotate: Selected vs not selected, how to indicate

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#141]
@vzinche @constantinpape @K-Meech @ssgpers
 
Any good ideas for how to indicate which object(s)  are selected **for annotation**?
I think the modalities that we have are still not ideal:

```
	public enum SelectionColoringMode
	{
		OnlyShowSelected,
		SelectionColor, // currently bright yellow
		SelectionColorAndDimNotSelected,
		DimNotSelected
	}
```

I think the issue with changing the selected objects colour is that you cannot see anymore as which class they were annotated in case they already had an annotation that you would like to change.

Currently I feel `DimNotSelected` is the relatively best, but it is hard to find the right dimming level, because _either_ it is not obvious enough _or_ one cannot easily see the colour of the dimmed (not selected) objects anymore. Also one does not want to make it too dark, because to select more objects you need to see where they are.

Any ideas?

**Comment by tischi** [comment]
What about a purple point overlay? I think we had this already in some other context.

![image](https://user-images.githubusercontent.com/2157566/98402397-816c2280-2067-11eb-9905-95733e8fb222.png)

**Comment by vzinche** [comment]
Sorry, I am fully lost in what's happening here. 
Can you explain the current logic? 
And what is this purple point overlay? :)
