### ISSUE TITLE
TableView: select row

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#142]
@constantinpape @vzinche @HernandoMV @jhennies 

I think we discussed this somewhere else but I cannot find it.

Should we change the behaviour when one clicks on a table row, such that it will only focus the selected segment in BDV, but does _not_ at the same time select it? This would imply that it is not shown in 3D unless it is selected within BDV, using `Ctrl Left-click`.

**Comment by vzinche** [comment]
If it only focuses, but doesn't select, will it still show only the clicked cell in color? Because this is what I would rather keep 

I am not an active 3D view user, but I am really satisfied with all the other behaviors of click vs select at the moment

**Comment by tischi** [comment]
No, all cells would keep their colour....

**Comment by constantinpape** [comment]
Would it be possible to have two different modes in the table:
- `Left-click`: only focus but do not select the cell
`Ctrl Left-click`: select the cell (current behaviour)

**Comment by tischi** [comment]
@constantinpape 

Excellent idea!

I even managed to implement this, listening to `JTable` events is a bit mysterious... ;-)

There are still two options now:

1. `Ctrl Left-click`: select the cell if it was not selected; do nothing if it was selected already
2. `Ctrl Left-click`: select the cell if it was not selected; deselect the cell if it was selected already 

Option 2 would be the same as it currently behaves when you ctrl+click on cells within bdv, I would thus favour this one for consistency.

Opinions?

**Comment by constantinpape** [comment]
yes, I am also for option 2.

**Comment by tischi** [comment]
I implemented it like this. Hope that's fine. Otherwise please reopen.
