### ISSUE TITLE
Open n5-aws-s3 the simple way

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#146]
@joshmoore

If you manage to build this repo, there is in fact a very easy way to load a n5-aws-s3 data set.

You just need to execute these lines of code:

```
		SpimData spimData = new XmlIoSpimData().load( "PATH/TO/mhcl4-n5-aws-s3.xml" );
		BdvFunctions.show( spimData );
```

The content of the `mhcl4-n5-aws-s3.xml`being:

```
<SpimData version="0.2">
  <BasePath type="relative">.</BasePath>
  <SequenceDescription>
    <ViewSetups>
      <Attributes name="channel">
        <Channel>
          <id>0</id>
          <name>0</name>
        </Channel>
      </Attributes>
      <ViewSetup>
        <id>0</id>
        <name>Setup0</name>
        <size>500 471 519</size>
        <voxelSize>
          <unit>micrometer</unit>
          <size>0.55 0.55 0.55</size>
        </voxelSize>
        <attributes>
          <channel>0</channel>
        </attributes>
      </ViewSetup>
    </ViewSetups>
    <Timepoints type="range">
      <first>0</first>
      <last>0</last>
    </Timepoints>
    <ImageLoader format="bdv.n5.s3">
      <Key>0.6.3/images/remote/prospr-6dpf-1-whole-mhcl4.n5</Key>
      <SigningRegion>us-west-2</SigningRegion>
      <ServiceEndpoint>https://s3.embl.de</ServiceEndpoint>
      <BucketName>platybrowser</BucketName>
      <Authentication>Anonymous</Authentication>
    </ImageLoader>
  </SequenceDescription>
  <ViewRegistrations>
    <ViewRegistration setup="0" timepoint="0">
      <ViewTransform type="affine">
        <affine>0.55 0.0 0.0 0.0 0.0 0.55 0.0 0.0 0.0 0.0 0.55 0.0</affine>
      </ViewTransform>
    </ViewRegistration>
  </ViewRegistrations>
</SpimData>
```

1. Let me know if that works for you. 
2. If yes, a next step would be to test whether that also works for the data that I uploaded to your s3 bucket.
3. It is then also easy to load multiple images into the same bdv. I can paste the code here once we have above basic example running.

**Comment by tischi** [comment]
@joshmoore

Could you enable `Anonymous` read access to your s3 storage where I am currently uploading the data to such that I could try reading data from there with a modified version of above xml?

**Comment by joshmoore** [comment]
@tischi : `idr-upload` can't be easily reconfigured since it's intended for private uploads. I can start migrating the data to a public bucket though.

**Comment by tischi** [comment]
@joshmoore
Ok, but I am also still copying into the big file. 
I sent you a mail.
