### ISSUE TITLE
Image data storage modality defaults to s3 for local projects on Windows

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#150]
Opening a local project on Windows e.g. Z:\Kimberly\repos\platybrowser-datasets, uses s3 as the image data storage modality. 
Is this an issue with the path structure for Windows?

**Comment by constantinpape** [comment]
I think the behavior is the same in Linux; I think right now the only way to open from file system is to use the expert mode:
`Advanced -> Open MoBIE Project Experts`, there you can select FileSystem explicitly.

**Comment by K-Meech** [comment]
Ah ok - I'll use Expert Mode instead then.

**Comment by tischi** [comment]
>  I'll use Expert Mode instead then.

Of course! Experts should use Expert Modes, always 😄
