### ISSUE TITLE
Annotation mode window "looses" gui elements for too many categories

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#151]
If a user adds many categories the lower part of the annotation gui vanishes and cannot be recovered by resizing the window and there is no scroll option, see the screenshot below.
This was reported on a mac, not sure if this is an issue on linux / windows as well.

![PastedGraphic-3](https://user-images.githubusercontent.com/4263537/100335258-10b88600-2fd5-11eb-8048-1ebdacb5ef35.jpg)

**Comment by tischi** [comment]
I should add a scroll option.

**Comment by tischi** [comment]
@K-Meech 
If you feel like learning more about Java Swing UI you could try to add something scrollable here :-)
But just if you think it is interesting/fun, otherwise it's my job, of course.

**Comment by K-Meech** [comment]
I can take a look - sure! I did something similar for one of the project gui windows - so hopefully the same will work here :)

**Comment by tischi** [comment]
Thanks a lot!

**Comment by K-Meech** [comment]
Pull request here: https://github.com/tischi/imagej-utils/pull/30 
Adds a scrollbar / all seems to work well! One minor issue is that it makes the panels wider than before - I couldn't find an easy fix for this though.

**Comment by tischi** [comment]
Thanks a lot @K-Meech !
Fixed in imagej-utils-0.5.7-SNAPSHOT.
Will be in MoBIE-beta upon next upload.
