### ISSUE TITLE
Add recent covid publication to "Open Published Projects"

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#153]
This is the publication
https://www.sciencedirect.com/science/article/pii/S193131282030620X
corresponding to these two repos:
https://github.com/mobie/covid-tomo-datasets
https://github.com/mobie/covid-em-datasets

**Comment by tischi** [comment]
@K-Meech 
Would you like to do this? You'd have to add it to the class `PublishedProjectsCreator`.

**Comment by K-Meech** [comment]
Sure! Pull request here: https://github.com/mobie/mobie-viewer-fiji/pull/154
