### ISSUE TITLE
Save Columns As doesn't work properly after columns moved

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#155]
In the whole-segmented-cells table I move some columns left and right (to have the necessary ones closer). Then I try to `save columns as`, I choose the names of the columns that I want, but what gets saved is not the content of the columns with the names I've chosen, but rather the content that was on these positions before I moved the columns.

For example, if I move the column `trace_id` to the second position, when I choose to save `trace_id` it actually saves `anchor_x` instead, which was originally on the second position.

**Comment by tischi** [comment]
Thanks for finding this out!
This is a bug and I will work on fixing it!

**Comment by tischi** [comment]
Fixed in imagej-utils-0.5.7-SNAPSHOT.
Fixed in MoBIE-beta next time I update update site.
