### ISSUE TITLE
Annotation from scratch doesn't work

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#156]
Maybe I am doing something wrong, but `Annotate -> Start new annotation` changes the color in the table, but doesn't update the label from None:
![Screenshot from 2020-12-07 10-41-31](https://user-images.githubusercontent.com/32451366/101335211-2ea9a480-3879-11eb-8299-accbac056bb1.png)

**Comment by tischi** [comment]
You mean if you press the button `1` it does not update the text in the table?
In other words: did you press `1`? If so, this is a bug!
MoBIE-beta?

**Comment by vzinche** [comment]
Yes, I select a cell by Crtl-clicking either a row in the table or the cell in the bdv window. Then I press `1`, the cell changes it's color to green both in the table and in the bdv, but doesn't change the label.
It's MoBIE-beta

**Comment by tischi** [comment]
Thanks! Bug! I will try to fix it today!

**Comment by tischi** [comment]
I cannot reproduce this using `imagej-utils-0.5.7-SNAPSHOT`:
![image](https://user-images.githubusercontent.com/2157566/101464879-86aade80-393f-11eb-9c2b-4d65762b32ee.png)
I will check later in MoBIE... 
(in meetings now for few hours)

cc @K-Meech, did you try the Annotator recently?

**Comment by vzinche** [comment]
Nevermind, this was my mistake. I gave my annotation the name that was already present in the table.

**Comment by tischi** [comment]
> I gave my annotation the name that was already present in the table.

Could you elaborate? Maybe we should throw an error in such a case?

**Comment by vzinche** [comment]
That's a good point, we should. 
Basically, when you start a new annotation, you have to name it, and this will be the column name. So in my case there was already a column with the same name in the table, so when I was assigning categories during the annotation, they were assigned to the wrong column. 
So what would be great is to add a check whether the new annotation name already exists, e.g. "There is already a column 'cell_type'. Please select a different name for your annotation" .
