### ISSUE TITLE
Interactive Scatter Plot

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#158]
A(nother) dream come true, at least for me!  

🎆 

I wanted to have this for a loooooong time but never got around to implement it properly.

Thanks to @bogovicj and @axtimwalde for very useful pointers regarding the implementation.

--------

![image](https://user-images.githubusercontent.com/2157566/101799570-99bed980-3b0c-11eb-8639-dd09a86c94b8.png)

![image](https://user-images.githubusercontent.com/2157566/101799649-b3602100-3b0c-11eb-810a-68c745196df3.png)

![image](https://user-images.githubusercontent.com/2157566/101800640-c7f0e900-3b0d-11eb-811c-986db79a4e05.png)

![image](https://user-images.githubusercontent.com/2157566/101799704-c541c400-3b0c-11eb-9a77-5f0abdb99bdb.png)

![image](https://user-images.githubusercontent.com/2157566/101799788-d8ed2a80-3b0c-11eb-9a31-daa57041535c.png)

# Scatter plot context menu

![image](https://user-images.githubusercontent.com/2157566/101799829-e1ddfc00-3b0c-11eb-96bc-1b201bc69210.png)

# Selection and Coloring

Of course, the selection and colouring models in the scatterplot and segmentation and table are identical 😃 

![image](https://user-images.githubusercontent.com/2157566/101803479-de4c7400-3b10-11eb-8a36-a8673f5657b6.png)

![image](https://user-images.githubusercontent.com/2157566/101803426-cd9bfe00-3b10-11eb-844f-428d1fcfd110.png)

![image](https://user-images.githubusercontent.com/2157566/101803441-d260b200-3b10-11eb-861e-26a820a6a25a.png)

# Testing

@vzinche @K-Meech @constantinpape
Would be awesome if you could test on MoBIE-beta! 
And I'd be more than happy to see few screenshots, e.g. of the UMap.

**Comment by vzinche** [comment]
Wow! That looks just amazing!
I've tried it, and it works for the values in the table, but not for my UMAPs. Could it be because the values are defined not for every segment (all the non-cells are NaN)? 
I attach the table. 
[try_plot_umap.zip](https://github.com/mobie/mobie-viewer-fiji/files/5674983/try_plot_umap.zip)

**Comment by tischi** [comment]
It should ignore `NaN`. What happens? Do you get an error?

**Comment by vzinche** [comment]
No, I just don't get anything plotted:
![Screenshot from 2020-12-11 08-59-59](https://user-images.githubusercontent.com/32451366/101878168-6d986c80-3b8f-11eb-82ba-e2a8e79ffc1a.png)

**Comment by K-Meech** [comment]
Looks great @tischi ! I get the same issue as @vzinche though for my gene UMAP - blank screen. The table is in the platybrowser dataset 1.0.0 under the cell segmentation tables as 'gene_umap.csv'

**Comment by tischi** [comment]
Interesting, inside imagej-utils-0.5.7-SNAPSHOT it works:

```
		List< ColumnBasedTableRow > tableRows = Tables.open( "src/test/resources/test-data/try_plot_umap.csv" );

		SelectionColoringModel< ColumnBasedTableRow > selectionColoringModel = SelectionModels.getDefaultSelectionColoringModel();

		TableRowsScatterPlot scatterPlot = new TableRowsScatterPlot(
				tableRows,
				selectionColoringModel,
				new String[]{ "umap_1", "umap_2" },
				new double[]{ 1.0, 1.0 },
				0.2 );

		scatterPlot.show( );
```

![image](https://user-images.githubusercontent.com/2157566/101891826-d9380500-3ba2-11eb-96d4-7300931c10d8.png)

I'll check whether this is something wrong within MoBIE...

**Comment by tischi** [comment]
@K-Meech @vzinche 
I found a couple of issues and hope I fixed them.
Could you please test again?

**Comment by K-Meech** [comment]
It's working now! One thing though, is that the y axis is flipped compared to a normal scatter plot. Still works great, but perhaps a bit unintuitive at first.
![Screenshot (197)](https://user-images.githubusercontent.com/24316371/101910234-8cf6c000-3bb6-11eb-9b90-abeac2e65dc5.png)

**Comment by tischi** [comment]
> One thing though, is that the y axis is flipped compared to a normal scatter plot. 

That is on purpose, because the image data also is flipped, see, e.g. `anchor_y`.
Convention for image data: `y=0` is at top.
You can simply scale the y-axis by `-1` in the GUI to change this.

**Comment by tischi** [comment]
@K-Meech 
Did you try to "Shift Left-Click" on a data point? It will move you to the cell in BDV.

**Comment by K-Meech** [comment]
Yes - I tried 'shift left-click' - works great!!

**Comment by vzinche** [comment]
Works for me as well!
![Screenshot from 2020-12-11 15-07-30](https://user-images.githubusercontent.com/32451366/101912980-b6b5e400-3bc2-11eb-8a77-d77561dad69e.png)

**Comment by vzinche** [comment]
The only comment is: I've tried Ctrl + Left-click, and I feel like it might be more convenient if it selected the cell instead of just moving the view there. @K-Meech, what do you think?

**Comment by K-Meech** [comment]
I agree @vzinche - it's a bit hard to tell which cell it is without zooming in a lot.

**Comment by tischi** [comment]
Mean to say:  "We have to think about it" :-) 
cc @constantinpape 

Do we maybe need different shortcuts for this?

In fact, in the table right now the behaviour is (correct me if I am wrong):

- Left Click: Focus only
- Ctrl Left Click: Focus and select

Maybe we want something similar for the scatterplot?

The issue with only "Left click" in bdv is that one also uses that to change the viewer plane, so using that may be tricky...

It would be nice to have the same shortcuts in all views...

Maybe (also for the table):

- Ctrl Left Click: Focus and Select
- Shift Left Click: Focus only

...and then just "Left click" would do nothing in all of the views?

What do you think?

**Comment by vzinche** [comment]
I honestly wouldn't mind just keeping the current Ctrl Left Click behaviour for the scatter plot. Not sure if Focus only is that necessary

**Comment by tischi** [comment]
(by the way: I have not implemented this yet, but the idea would be that if you focus/select a cell in the table or in bdv that the data point would also be centred in the scatter plot)

> I honestly wouldn't mind just keeping the current Ctrl Left Click behaviour for the scatter plot. Not sure if Focus only is that necessary

Ok, I think making Ctrl Left Click select and focus in the scatterplot makes sense!

I guess, even if you don't need it, it would not hurt to add Shift Left Click in the scatter plot as Focus Only?!

**Comment by K-Meech** [comment]
Sounds good to me! It's nice if all the views are using the same shortcuts

**Comment by tischi** [comment]
ok!

So for the table also 

- Ctrl Left Click: Focus and Select
- Shift Left Click: Focus only
- Left Click: nothing

?!

**Comment by K-Meech** [comment]
ah wait - I take it back. I think it's still good if left click in the table does something. Maybe just set that as the same as 'focus only'?

**Comment by constantinpape** [comment]
I think we had the discussion about the shortcuts somewhere else, but I can't find it right now.
In any case, my 2cents:
The shortcuts in the table and the scatter-plot should be the same and I think I would prefer the following options:
- Left Click: Focus
- Shift Left Click: Focus + Select

In BDV, I think we should only have:
- Shift Left Click:  Select

**Comment by tischi** [comment]
You mean Ctrl rather than Shift, right? (At least that's what we have right now)

**Comment by tischi** [comment]
Damn, hard lock down in BW from tomorrow on 😫 
We will have lots of time to discuss this 😉

**Comment by constantinpape** [comment]
> You mean Ctrl rather than Shift, right? (At least that's what we have right now)

Yes, I mean Ctrl.

**Comment by tischi** [comment]
I tried to implement @constantinpape 's suggestion.
Let me know how it works.

**Comment by vzinche** [comment]
I like how the selecting part work now!
But what is a bit weird: I keep selecting cells on the plot, it selects them in the bdv, but on the plot it updates the selection only when you move the plot

**Comment by tischi** [comment]
> But what is a bit weird: I keep selecting cells on the plot, it selects them in the bdv, but on the plot it updates the selection only when you move the plot

Thanks, I forgot to add below code to the scatter plot.
Should work now once we upload again to Fiji.

```
public void selectionChanged()
{
		bdvHandle.getViewerPanel().requestRepaint();
}
```

**Comment by tischi** [comment]
Should work now, please reopen if necessary.

**Comment by vzinche** [comment]
Okay, maybe one last suggestion: would it be possible to make the non-selected points not so dim? Right now if I select one I can hardly see the others
@K-Meech what do you think?

![Screenshot from 2020-12-15 14-55-27](https://user-images.githubusercontent.com/32451366/102223963-aa44ca80-3ee5-11eb-86f6-4f4162fcf1ab.png)

**Comment by tischi** [comment]
Should I make the brightness configurable?

**Comment by vzinche** [comment]
If possible!

**Comment by tischi** [comment]
@K-Meech 

Are we currently using this in the Bookmarks?

```
public enum SelectionColoringMode
	{
		OnlyShowSelected,
		SelectionColor,
		SelectionColorAndDimNotSelected,
		DimNotSelected
	}
```

If not, I would be tempted to get rid of `OnlyShowSelected` because this is now the same as `DimNotSelected` with maximal dimming (which is now configurable).

**Comment by K-Meech** [comment]
@tischi I don't think we're using this in the bookmarks - so go ahead! Makes sense to remove it, if the dimming is configurable now.

**Comment by tischi** [comment]
I changed it in imagej-utils-0.5.7-SNAPSHOT.
Will be in next upload.

**Comment by constantinpape** [comment]
This is all implemented now.
