### ISSUE TITLE
Dependency conflict in Fiji update

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#167]
When I try to update Fiji with the `Mobie-beta` update site, I get an error message indicating dependency conflicts:

![Screenshot from 2021-01-04 12-56-53](https://user-images.githubusercontent.com/4263537/103533658-cbb62800-4e8d-11eb-8f19-2bb44cbbec47.png)

This is on Linux, and I have only added the `Mobie-beta` update site.

**Comment by imagejan** [comment]
@constantinpape can you try re-running the updater to see if it suggests to delete the duplicate jar files?

It seems that the updater didn't delete the old versions after your last update, and you have two competing versions of each:

* `bio-formats_plugins`: `6.6.0` and `6.5.1`
* `n5-viewer_fiji`: `4.0.2` and `4.0.1`

**Comment by constantinpape** [comment]
@imagejan Yes, when I try to rerun the update it suggests to delete the duplicate jars and when I do this it fixes the issue.
Thanks!
