### ISSUE TITLE
Release version 0.5.4 (with OME ZARR support)

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#172]
@K-Meech 

I pushed a new version of MoBIE to MoBIE-beta )including support for loading ome.zarr files, s.b.).
Could you please have a look whether everything works and we could push this version to the MoBIE update site?

-------

@joshmoore

This version contains this command: 
Plugins › BigDataViewer › OME ZARR › Open OME ZARR From S3...

So far I tested it with:
- https://s3.embl.de/i2k-2020/em-raw.ome.zarr
- https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/4495402.zarr

Could you please also test it (maybe also with some other data, e.g., some multi-channel time-lapse)?
Maybe also put the URLs of the additional test data here and/or into our course document?

You just need to install/update MoBIE-beta for this: https://github.com/mobie/mobie-viewer-fiji#expert-usage-testing-latest-features

Also please let me know of anything that I could improve (e.g. feature requests) before the course.

**Comment by K-Meech** [comment]
@tischi I quickly tested the new MoBIE-beta, and everything seems to work ok! I didn't test the ome-zarr loading - do we have any example MoBIE projects with ome-zarr for testing?

**Comment by tischi** [comment]
> didn't test the ome-zarr loading - do we have any example MoBIE projects with ome-zarr for testing?

Not yet, for now we can only load individual image sources. But it would be already good if you tested the two examples that I gave up there.

**Comment by K-Meech** [comment]
The two examples above work for me. All looks good!

**Comment by tischi** [comment]
> The two examples above work for me. All looks good!

Nice! I hope that's the future 🚀  
Let's discuss more on Friday with @joshmoore

**Comment by jburel** [comment]
List of possible images https://blog.openmicroscopy.org/file-formats/community/2020/11/04/zarr-data/
I have opened  https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/9836844.zarr using commit f7b826b1032e4f9251a66f2cfc2b6df5f2d27832

**Comment by tischi** [comment]
> I have opened https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/9836844.zarr using commit f7b826b I only seem to have one timepoint available when viewing the image. ( I also need to get familiar with the viewer)

Which one in this list is it? 
https://blog.openmicroscopy.org/file-formats/community/2020/11/04/zarr-data/

When you press `P` you get a menu, where I can see four channels:
![image](https://user-images.githubusercontent.com/2157566/105370392-d39ef780-5c03-11eb-8a5e-eb7f2364f84f.png)

But I see **only one z-slice and one time point**. Could well be that I still have a bug in my code...

**Comment by jburel** [comment]
<img width="1014" alt="Screenshot 2021-01-21 at 16 18 34" src="https://user-images.githubusercontent.com/1022396/105379030-54f68a00-5c04-11eb-8c49-d47c9f18ce33.png">

**Comment by tischi** [comment]
@jburel 
Why are they there multiple times? Are they all the same?
![image](https://user-images.githubusercontent.com/2157566/105384754-ea991600-5c12-11eb-95f3-7462b73cfede.png)

**Comment by tischi** [comment]
The URLs to view them point to different locations:
- https://hms-dbmi.github.io/vizarr?source=https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/9836831.zarr
- https://hms-dbmi.github.io/vizarr?source=https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/9836832.zarr
- https://hms-dbmi.github.io/vizarr?source=https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/9836833.zarr
- ...

**Comment by tischi** [comment]
@jburel 
Are you sure the description on the web-page matches the actual file content?
I don't see what I am doing wrong (there seems to be nz=1 and nt=1):
https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/9836844.zarr
![image](https://user-images.githubusercontent.com/2157566/105386057-431ce300-5c14-11eb-90ab-1e35c06082e9.png)

**Comment by jburel** [comment]
@tischi you are correct the info in the page is not correct I double checked on idr and the image I picked has only one z and one t.
I will look at another one. I will also fix the blog entry

**Comment by jburel** [comment]
blog post updated

**Comment by tischi** [comment]
@K-Meech @constantinpape 
I updated the MoBIE (alpha) update site.
Could you please check that:
1. The ome zarr import works
2. One can now open local projects without using the expert mode

**Comment by K-Meech** [comment]
Works for me!

**Comment by constantinpape** [comment]
> @K-Meech @constantinpape
> I updated the MoBIE (alpha) update site.

You mean the regular MoBIE site by this, right?
(alpha usually means that something is in an earlier development cycle than beta, so calling it alpha here is pretty confusing)

> Could you please check that:
> 
>     1. The ome zarr import works

I don't have an ome zarr one at hand, I can check in a later release.

> 
>     2. One can now open local projects without using the expert mode

Yes, that works now and makes dealing with local projects much more convenient!

**Comment by tischi** [comment]
> You mean the regular MoBIE site by this, right?
(alpha usually means that something is in an earlier development cycle than beta, so calling it alpha here is pretty confusing)

yes, good point!
