### ISSUE TITLE
Grouping of images

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#173]
Grouping of images is currently determined based on the filename. Filenames are split on '-' and the first part used as the name of the group.

Would it be better / more flexible to do this based off a field in the images.json? e.g. 'group'

**Comment by constantinpape** [comment]
I overall agree, it would be better to group by a field in the json.
But I am not sure if we want to make the change now or wait to see how this could work with ome-zarr.ngff.
Maybe something to discuss tomorrow.

**Comment by constantinpape** [comment]
There is `menuItem` in the new spec for this now.
See here https://github.com/mobie/mobie-viewer-fiji/issues/200#issuecomment-803475881 if we still want to discuss the format.
