### ISSUE TITLE
Expert mode installation

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#177]
#### Expert usage (testing latest features)

To build the project from source, you will need Maven 3.3.9 or higher.

Perform step 1 as described above and then:

1. Add the Update Site `MoBIE-beta` to Fiji like this:
   - [ Help > Update.. ]
   - [ Manage update sites ]
   - [ Add update site ] and manually fill in the following fields:
      - Name: `MoBIE-beta` 
      - URL: `https://sites.imagej.net/MoBIE-beta`
      - It should look like this: <img width="350" alt="image" src="images/mobie-beta-update-site.png">
   - [ Close ]
2. Restart Fiji

**Comment by constantinpape** [comment]
This is described in https://github.com/mobie/mobie-viewer-fiji/blob/master/MOBIE-BETA.md now.
