### ISSUE TITLE
Project creator for 2D images writes too many levels

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#179]
Writing 2D images to n5 via the project creator makes too many downsampling levels. This converts the image properly, but slows the process down greatly.
Must be something wrong with the default settings of the n5 writer plugin in fiji.

**Comment by tischi** [comment]
How do the default settings look like?
Can you change the default setting to something else?

**Comment by K-Meech** [comment]
I've been looking at this with @constantinpape - it seems to be an issue with the calculated default chunks (subdivisions) in this function: https://github.com/bigdataviewer/bigdataviewer-core/blob/master/src/main/java/bdv/export/ProposeMipmaps.java#L54 

So I think for now I will add an option to enter the chunking / downsampling levels manually in the project creator. I'll put an issue on the bdv repo for the 2d defaults, and hopefully they can resolve it at some point.

**Comment by tischi** [comment]
> So I think for now I will add an option to enter the chunking / downsampling levels manually in the project creator.

If you think the defaults are good otherwise, why don't you rather automatically detect whether an image is 2D and then automatically change the levels in your code?

**Comment by K-Meech** [comment]
True - this would also work. I'd need to figure out a good way to calculate the default chunk sizes  / levels for 2D though... 
There are probably other situations where the defaults aren't great though - so having a manual option too is probably a good idea? I could just add a checkbox for 'use default export settings', then have another menu if this is left unselected.

**Comment by tischi** [comment]
sgtm

**Comment by K-Meech** [comment]
This error is also related to the voxel size e.g.
For an 8 bit image of size 8704x9044, and pixel dimensions of 0.0100320 x 0.0100320 x 1 microns the defaults work.

But an 8 bit image of 8704x9044, and pixel dimensoins of 10.0320 x 10.0320 x 1 nanometer doesn't work. The z downsampling and chunking aren't kept at 1.

**Comment by K-Meech** [comment]
Alright - I have manual input of downsampling levels/chunk size working now! It would be nice though to have a quick fix for the 2D case.
@tischi @constantinpape 
Any suggestions on how to calculate good values for these based on the image dimensions / voxel size?

**Comment by K-Meech** [comment]
Tobias will fix this on the main repo - see https://github.com/bigdataviewer/bigdataviewer_fiji/issues/21

**Comment by K-Meech** [comment]
@tischi @constantinpape - if you have a minute, can you take a look at the comments on this issue: https://github.com/bigdataviewer/bigdataviewer_fiji/issues/21? Any suggestions for the 2D defaults?

**Comment by constantinpape** [comment]
Is this still an issue @K-Meech?

**Comment by K-Meech** [comment]
The chunk size is now restricted to 1 in the z axis. The downsampling is not restricted to 1 though (this was discussed a lot in the issue linked above - and is probably necessary to make it display nicely when viewed in 3D)

It still writes quite a few levels, but it is **much** faster now - so I don't think it is an issue anymore.
