### ISSUE TITLE
Project creator settings persist

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#181]
Using manual settings for n5 / h5 export results in them persisting for the next image (even if it is set to default).
This is due to using IJ.run()... on ExportImagePlusAsN5Plugin - inside this plugin they set static variables that persist for the next run.

@tischi As a quick fix for this I think I will copy this class into mobie as you suggested here: https://github.com/mobie/mobie-viewer-fiji/issues/149#issuecomment-744412652 and I'll make a pull request against it at a later date.

In the long run, this will be much more stable than IJ.run() that seems to have lots of weird, and unexpected behaviour...

**Comment by tischi** [comment]
> In the long run, this will be much more stable than IJ.run() that seems to have lots of weird, and unexpected behaviour...

Yes

**Comment by K-Meech** [comment]
This is fixed in the latest master
