### ISSUE TITLE
Export downsampling defaults

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#186]
@K-Meech 
cc @constantinpape 
If you have time, could you try out downsampling 3^n instead of the current default 2^n?
How does that behave when you zoom in and out in bdv? Is it noticeably less smooth?

**Comment by K-Meech** [comment]
@tischi Could you clarify? Do you mean rather than using downsampling levels like:
(1,1,1), (2,2,2), (4,4,4), use (1,1,1), (3,3,3), (9,9,9)?

**Comment by tischi** [comment]
Yes,

**Comment by K-Meech** [comment]
Ok - I can try this tomorrow morning. I'm on a course this week, so it's a bit busy!

**Comment by tischi** [comment]
no worries, this is mere curiosity

**Comment by K-Meech** [comment]
Ok sure - next week then :)

**Comment by K-Meech** [comment]
I never got around to trying this. @tischi - should I still look into this?

**Comment by tischi** [comment]
I am still very curious but it is not important.
