### ISSUE TITLE
Project Creator UI improvements

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#187]
Based on suggestions from Matt:

- [x]  Increase size of dataset field to fit much longer names

- [ ]  divide up Affine field values into meaningful fields ( or perhaps provide more guidance in the tutorial on what these values mean)

- [ ]  same for manual export fields (again more guidance in tutorial would be useful)

- [x]  Add name of project to Edit MOBIE project... header (at least the first n letters)

- [x]  Be more explicit on project name vs folder name

- [x] Creating project could be clearer e.g. could have dialog for choosing name of project, then a window to choose the folder it is saved to (rather than doing this in one step)

- [x]  For editing a project, again make sure header of dialog is informative e.g. 'choose your mobie project folder'. And add checks that the folder you choose contains a valid MoBIE structure e.g. This folder does not contain a valid MoBIE project structure. Please choose a MoBIE project folder (that contains a ‘data’ folder at the top level).

- [ ]  Similar changes for opening a project

- [x]  Should also look at changing default compression mode. The bdv plugin uses Raw (no compresssion) by default

- [x]  Currently spaces anywhere in the filepath leads to images writing to the wrong location

**Comment by tischi** [comment]
>   divide up Affine field values into meaningful fields ( or perhaps provide more guidance in the tutorial on what these values mean)

Good idea. We could start with:
- 3D pixel size
- 3D translation
But we would also need the option to "simply" specify the full affine transform.

**Comment by K-Meech** [comment]
@constantinpape Any suggestions for the default compression type for n5 images?
The default in fiji is currently no compression at all.

**Comment by constantinpape** [comment]
> The default in fiji is currently no compression at all.

That's not good! I would go with gzip.

**Comment by K-Meech** [comment]
I split the one remaining issue off here: https://github.com/mobie/mobie-viewer-fiji/issues/412
