### ISSUE TITLE
Bookmark SourceTransform

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#189]
@K-Meech @constantinpape 
Related to this: https://github.com/mobie/mobie/issues/20

I tested the following code snippet and it produces a different output before and after applying a manual transform:
```
SpimData spimData = new XmlIoSpimData().load( "/Volumes/cba/exchange/Sultan/prospr_neuropile_0.4um.xml" );

final BdvStackSource< ? > bdvStackSource = BdvFunctions.show( spimData ).get( 0 );
final TransformedSource< ? > transformedSource = (TransformedSource) bdvStackSource.getSources().get( 0 ).getSpimSource();

Behaviours behaviours = new Behaviours( new InputTriggerConfig() );
behaviours.install( bdvStackSource.getBdvHandle().getTriggerbindings(), "behaviours" );

behaviours.behaviour( ( ClickBehaviour ) ( x, y ) -> {
		final AffineTransform3D transform3D = new AffineTransform3D();
		transformedSource.getSourceTransform( 0, 0, transform3D );
		System.out.println( "Transform: " + transform3D );
}, "Log transform", "L"  ) ;
```

yields, e.g.

```
Transform: 3d-affine: (0.4, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0)
Transform: 3d-affine: (0.3316150290220166, -0.16358711994900088, 0.15254745725025454, 27.131835373885878, 0.0, 0.27279934402499934, 0.29254148064766816, -58.07546240269676, -0.22367716138829874, -0.24252787898780048, 0.22616090596509314, 222.30865416109685)
```

If the transform is the one to be put into the XML, it could be thus very easy to capture manually modified `SourceTransform`s within MoBIE.

Proposal: People just add their data to a MoBIE project without specifying transformations. Then within MoBIE, using the manual transform, they move stuff around such that they like it. Then we record the changed transforms such that they could be stored into a bookmark.

I guess we would need to add a field `sourceTransform` to the bookmarks?!

What do you think?

**Comment by tischi** [comment]
If we want to implement this, we can get the `bdvStackSource`s, which contain the `TransformedSource`s, from the `Metadata`s in:

```
private Map< String, SourceAndMetadata< ? > > sourceNameToSourceAndCurrentMetadata;
```

**Comment by K-Meech** [comment]
Sounds good to me! 
We could just add sourceTransform to the bookmarks, and then save whatever the current state is when they 'save to bookmark...'
I think it would still be good (at some point) to support the grid view idea - as this would be useful when you have many, many sources and you don't want to manually move them all.

Good to support both though - gives the most flexibility!

**Comment by tischi** [comment]
> Sounds good to me!

Should I work on it? I may have time for it tomorrow.

**Comment by K-Meech** [comment]
If you have time - go for it! I'm on a virtual conference most of this week, so would probably only have time next week

**Comment by constantinpape** [comment]
@tischi so the proposal is to add `SourceTransform` to the bookmark, that will override the transformation in the xml when the bookmark is loaded?
And this way we could save the manual arrangement of sources in a bookmark.

I like this idea :).

**Comment by tischi** [comment]
Exactemente

**Comment by tischi** [comment]
I am implementing and we have a choice:

The `sourceTransform` in the Bookmark...
1. completely replaces the transform in the xml
2. is concatenated to transform in the xml

This choice also, of course, affects what I would save in the bookmark, i.e. the full transform or just the added bit.

I am unsure, I guess it depends whether people would use the information in the bookmarks for anything else than using them in MoBIE. Otherwise I guess it does not matter.

Now I am thinking: probably (2) is better in case we ever support stuff like thin-plate-spline transforms. Something were you would not like to duplicate the information in the bookmark, because this could be a lot of data.

**Comment by tischi** [comment]
...I will do (2) and call it `addedTransform`, OK?

**Comment by K-Meech** [comment]
Sounds good!

**Comment by constantinpape** [comment]
> ..I will do (2) and call it `addedTransform`, OK?

Yes, I agree 2 is a better solution. If someone needs these trafos they will be advanced enough to concatenate them from the json and the xml.

**Comment by constantinpape** [comment]
This is outdated now and replaced by
```json
{
  "view":
  {
    "sourceTransforms": {}
  },
    "viewerTransform": {}
  }
}
```
