### ISSUE TITLE
Save bookmark location

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#192]
@K-Meech 
```
		NameAndLocation bookmarkNameAndLocation = bookmarkSaveDialog();
		Bookmark currentBookmark = createBookmarkFromCurrentSettings(bookmarkNameAndLocation.name);
		ArrayList<Bookmark> bookmarks = new ArrayList<>();
		bookmarks.add(currentBookmark);

		if ( bookmarkNameAndLocation.location.equals( FileLocation.Project ) &&
				bookmarksJsonParser.getDatasetLocation().contains( "raw.githubusercontent" )) {
```

What about **_not_** asking for the location but just chose the project location?

**Comment by tischi** [comment]
If one opens the project from the file system, both options are the same isn't it?

<img width="222" alt="image" src="https://user-images.githubusercontent.com/2157566/108339448-bb58d300-71d7-11eb-8333-0340ebcc54ac.png">

**Comment by K-Meech** [comment]
True, but I included it more for the option to save bookmarks to an arbitrary location on your file system (and not just to the bookmarks folder of a project). e.g. if you're working on a public project like platybrowser, and you just want to save bookmarks of regions of interest to a random folder on your file system (without having a whole local project structure).

**Comment by tischi** [comment]
I understand...
Maybe: If the project location is `File_system`, then we don't ask? Otherwise we ask?

**Comment by constantinpape** [comment]
Maybe we should also add an option to replace the default bookmark when saving a bookmark (given that the user has write permissions for it).
I think that would be helpful for arranged grid views.

**Comment by K-Meech** [comment]
The issue is that I often use e.g. the platybrowser opened form the file system (but a shared file system! e.g. the arendt server), then I want to save my bookmarks to another location (i.e. my own group share). 
I get that the naming is a bit confusing though in that case!

@constantinpape I agree - it would be useful to have a way to change the default bookmark

**Comment by tischi** [comment]
https://github.com/mobie/mobie-viewer-fiji/issues/193

**Comment by constantinpape** [comment]
The current logic for saving views implements all we discussed here.
