### ISSUE TITLE
Bookmark refactoring

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#195]
@K-Meech 
We should split the `BookmarksManager` into several classes.
At least we should factor out a `BookmarkViewer` and `BookmarkCreator` and `BookmarkFileWriter` and maybe see what is left to then decide what else?

**Comment by K-Meech** [comment]
Yes - good plan! I can look at this later in the week, if you'd like.

**Comment by tischi** [comment]
Yes please thanks :)

**Comment by tischi** [comment]
The reason I want this cleaned up is that then it is easier to work on this: https://github.com/mobie/mobie/issues/20

😉

**Comment by tischi** [comment]
But it should not be too much work, maybe I'll manage still today.
