### ISSUE TITLE
Project Creator: Sorting into image groups

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#200]
@K-Meech 

Are you communicating that people should _not_ do this?
```
image-asdfss
sdf-iamge
asdf-asdfds
```
Because they all would end up in different groups (as per splitting the first "-") 

Is there maybe a way to make this more clear during the project creation?

**Comment by K-Meech** [comment]
Related to https://github.com/mobie/mobie-viewer-fiji/issues/173

Currently, this is not enforced in the project creator i.e. there's no guidance on file naming. 
I think it would be good at some point to switch to using a field in the images.json for this.

Then there could be 3 rows in the project creator:
-Dataset
-Group
-Image

**Comment by tischi** [comment]
@constantinpape This issue could also be relevant in terms of improving images.json

**Comment by constantinpape** [comment]
@tischi @K-Meech 
The new spec has a field `menuItem` now.
For now, I decided that it's a string `menuName/itemName`, let me know if you want a different format.
