### ISSUE TITLE
Exploring BDV Cards UI 

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#201]
@K-Meech @constantinpape 
I am playing with using the BDV cards for everything, such that we get rid of the whole MoBIE UI.
This is how the source selection could render (what do you think)?
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/2157566/109519247-593b8000-7aab-11eb-9a1c-4833dbaab615.png">

**Comment by constantinpape** [comment]
> This is how the source selection could render (what do you think)?

Looks good!

Do you want to add a few different cards for different UI elements (e.g. sources, bookmarks) or just a single card for the whole MoBIE UI? I think I would prefer just a single card, but I am not quite sure.

**Comment by tischi** [comment]
@K-Meech @constantinpape 

Not sure now what to do with the UI, I think having the UI elements inside BDV may be long term the better cleaner option but if, e.g. @yanschwab, really prefers the other way...

I could probably write the code such that it is modular, such that one could select upon startup the "legacy UI" vs. the "integrated UI".

**Comment by yanschwab** [comment]
I'm really found of the stand alone MoBIE interface yes (plus I love our little whale). then all the tools stay in place when I resize the BDV window, and I can organise my screen with the 3D viewer close to the BDV window, and the tables etc as I like ... please keep it

**Comment by K-Meech** [comment]
I would agree that it's probably cleaner to integrate with BDV, but I'm not sure it's as user-friendly.
1. It's a bit confusing having the 'Sources' card and 'MoBIE Sources' card
2. It ties you into whatever changes in Bdv. e.g. If they add more cards / features then this becomes more confusing for MoBIE users...
3. It's quite nice to be able to resize the controls and the bdv window separately :)

**Comment by constantinpape** [comment]
From my point of view the important argument for using the bdv sources menu is that it implements the grouped sources including the color / contrast setting logic already. (And of course that we could avoid code duplication.)

But I can see the argument for having a separate window that doesn't change when resizing the viewer.

@tischi would it be possible to replace our "sources" UI element with the BDV sources card instead?
Then we could still use the BDV features but keep the MoBIE menu.

> (plus I love our little whale)

Yes, I think we will keep the whale in any case :).

**Comment by tischi** [comment]
I am refactoring all the code right now such that we will be more flexible in the future whether to use the cards panel and/or the standalone UI. 
It is a bit of work, because for everything to work consistently my UI has now to listen to the BDV UI, e.g. for color changes of a Source. But OK, I am learning more BDV stuff this way...
For now I will keep the standalone UI and see whether we can make the grouped display adjustments work there as well.

**Comment by constantinpape** [comment]
I think we are happy with the current UI and given the recent changes for grid sources I am not so sure if we can merge in the BDV Cards UI. Closing this issue for now.
