### ISSUE TITLE
Removing HDF5 support from project creator

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#206]
Currently, the project creator lets you select hdf5, or n5 for the file format.
As hdf5 is not suitable for reading from s3 storage, removing it would be simpler to maintain.

@tischi @constantinpape - thoughts? 
@yanschwab - all your projects are in n5 right? There would be no issue for you if I remove hdf5 support?

**Comment by yanschwab** [comment]
No problem yes.

**Comment by constantinpape** [comment]
No concerns about dropping hdf5 support from my side.

**Comment by tischi** [comment]
OK, to drop it but try to write the code that we can easily add it back (and add OME).
Good practice to use Java interfaces at the right places ;-)
