### ISSUE TITLE
Gallery view of bookmarks/ different sources

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#207]
Hi,

as for the Covid dataset, we are finishing up another story with many hundreds of individual volumes (serial tomograms of centrioles).

Our idea is to make all data available through MoBIE in a gallery view with one viewer tile showing one centriole. We know the orientation of the major axis, so we could align all of the objects to appear parallel regardless of original volume orientation.

- The best implementation would be a `m x n` array of BDViewers that are synchronized.
- each viewer would show one bookmark featuring an object/structure of interest
- these can come from only one (all "synapses", ... in a large volume) or many individual sources (as in our case)
- the bookmarks define the orientation/view of each viewer
- In the UI, there would be buttons to bring back all viewers to the starting bookmark (or orthogonal views).

This would provide a very universal way of browsing similar features within a dataset and would likely be the best entry point for browsing the biologically relevant information linked in a publication.

Let me know what can be done from our side to support an implementation.

**Comment by constantinpape** [comment]
We are working towards something very similar here: https://github.com/mobie/mobie/issues/27.
The only difference to what you have described is that all the volumes are in a single bdv viewer instance, but also shown in a grid.
This is implemented as a bookmark already and eventually will support having overlays of multiple sources at the same grid position.
In addition you have a table that allows navigating to individual source positons (and can use the bookmark to navigate back to the grid overview).

**Comment by tischi** [comment]
ping @K-Meech @constantinpape 

Just last week we implemented an auto-grid display for many sources.

> The best implementation would be a m x n array of BDViewers that are synchronized.

This is currently out of scope, the current implementation shows them in one BDV:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/2157566/110500010-1146d980-80f9-11eb-8e89-3c2d7ebe0a5f.png">

This is generated from this bookmark:
https://github.com/mobie/covid-tomo-datasets/blob/grid-test/data/grid-test-dataset/misc/bookmarks/default.json
Based on these images:
https://github.com/mobie/covid-tomo-datasets/blob/grid-test/data/grid-test-dataset/images/images.json

Another new thing that we have now is a `addedTransform` which can be specified for each layer in the bookmark.
I think this is exactly what you need to specify a different view for each image=source=layer.

(co-posted with @constantinpape :)

**Comment by tischi** [comment]
@martinschorb 
I would suggest you create a small test project using a subset of the images and we see how the user experience is when displaying all the sources just in one BDV. OK?!

**Comment by martinschorb** [comment]
Cool,
this pretty much contains all we need. The xmls of the individual sources would then define the transformations on how to position the objects.

I will use this as a starting point and play a bit...

The idea of multiple viewers is based on the user wanting to freely rotate and move with respect to one target feature. I wonder what the other volumes in that single viewer will do in that case. 

Time to play!

**Comment by tischi** [comment]
> Also, there are some volumes with multiple objects

Would you like to **show the same volume multiple times**, focusing on different objects?
I'd have to check whether my code currently supports this....

**Comment by martinschorb** [comment]
> Would you like to **show the same volume multiple times**, focusing on different objects?

That's definitely an application. Think about a platy, where you want to provide a gallery of all "neuron-like" nuclei or synapses, or ...

**Comment by constantinpape** [comment]
@martinschorb fyi. we are discussing the format for the bookmark here: https://github.com/mobie/mobie/issues/27
And there is also an example bookmark for one of the new datasets; but it's still WIP.

**Comment by constantinpape** [comment]
This discussion has moved on in other issues.
