### ISSUE TITLE
UI Elements

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#224]
@K-Meech @constantinpape 
I am wondering whether the [T]able and Scatter[p]lot views should be next to [V]olume and [S]lice view check-boxes, such that they can be conveniently toggled on and off.
Main issue is that the scatter-plot is very hidden right now.

**Comment by constantinpape** [comment]
Table: we always show it and it should only be added removed with the segmentation source.
So we don't want the [T] for it. Ideally, we would add and remove it only with the segmentation source and also remove the `x` (close) of the table UI.

Scatterplot: yes, having it in the GUI with [p] whould be great. We should also add it to the `segmentationDisplay`. I would propose to add the following fields for it:
```
showScatterplot: true/false
scatterplotAxes: [xAxis, yAxis] 
```
x and y-axis would be the corresponding table column names with the format `sourceName:columnName`. And both axes need to be chosen from the same source.

**Comment by constantinpape** [comment]
@K-Meech @tischi any opinions on this?

**Comment by K-Meech** [comment]
Looks good to me! In the long run, we might want to add the other scatterplot parameters e.g. `Scale Factor X`, `Scale Factor Y` and `Dot Size Scale Factor`. The dot size is particularly useful to record when you have a lot of points in a plot.

**Comment by constantinpape** [comment]
> Looks good to me! In the long run, we might want to add the other scatterplot parameters e.g. `Scale Factor X`, `Scale Factor Y` and `Dot Size Scale Factor`. The dot size is particularly useful to record when you have a lot of points in a plot.

Ok, let's go with `showScatteplot` and `scatteplotAxes` for now and revisit this once @tischi comes around to implement and test the scatterplot state. I think if we want to add more fields we may want to nest the scatteplot fields in the spec (and maybe also the 3d viewer fields).

**Comment by constantinpape** [comment]
I have added the fields `showScatterPlot` and `scatterPlotAxes` now.

**Comment by constantinpape** [comment]
This is all implemented.
