### ISSUE TITLE
Keep track of ViewerState 

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#225]
For example, `SegmentationDisplay` could implement `ColoringListener` and `SelectionListener`, maybe also other `Listeners`.

**Comment by tischi** [comment]
Also add a `ViewerTransformChangedListener` and put as normalised `viewerTransform`.

**Comment by tischi** [comment]
@K-Meech @constantinpape 

I just had an idea which may be very easy (hope it's a good one):

```java
public class SegmentationDisplay extends SourceDisplay
{
	// JSON fields
        public double alpha;
        public String color;

        // Runtime objects
	public SelectionModel< TableRowImageSegment > selectionModel;
	public MoBIEColoringModel< TableRowImageSegment > coloringModel;
}
```

The selection and coloringModel can be just fields of the `SegmentationDisplay`, like this they will be naturally always up to date 😉 

In principle, we could even be fancy and write a custom JSON parser that directly instantiates the models, rather then keeping the JSON fields. 

However, what could be good is that we keep the JSON fields always in the state as they are during the first loading.

Then the work would be (a bit like it was) on @K-Meech to create new objects during the creation of the bookmarks:
```
segmentationDisplayForSaving =  new SegmentationDisplay();
segmentationDisplayForSaving.color = coloringModelToColor( segmentationDisplay.coloringModel );
...
```

But I think that could be fair enough because all the information is within one class.

**Comment by tischi** [comment]
EDIT: I added the `transient` keyword, which tells JSON to ignore those fields (quite handy).

**Comment by tischi** [comment]
I thought a bit more and I am very tempted to try to actually try to instantiate the classes that we need directly from the JSON.

For example:

```Java
public class SegmentationDisplay extends SourceDisplay
{
   // get rid of this...
   public double alpha;
   public String lut;

   // ..and make them fields of this:
   public MoBIEColoringModel< TableRowImageSegment > coloring;
}
```

I think this would only cause one more nesting in the JSON:

“coloring” : { “alpha” : 0.5, “lut”: “glasbey” }

What do you think? I think it may be much easier for us to keep track of the state of everything in Java and then also directly serialize into JSON without having to implement the “converters” that I was writing about in the first post of this issue.

**Comment by tischi** [comment]
...but let's wait with this. I think I first need to write more code and understand better how I actually instantiate these classes....

**Comment by K-Meech** [comment]
bookmark saving works now
