### ISSUE TITLE
New Look And Feel

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#235]
@constantinpape @K-Meech 

What do you prefer?

### Darcula 

whale BG color would need update of course...

<img width="483" alt="image" src="https://user-images.githubusercontent.com/2157566/114432402-f4526a00-9bc0-11eb-97af-153b2e31e581.png">

### Bright

<img width="475" alt="image" src="https://user-images.githubusercontent.com/2157566/114432519-13e99280-9bc1-11eb-89c0-a3fa1928e537.png">

**Comment by tischi** [comment]
Here is more information: https://www.formdev.com/flatlaf/themes/

**Comment by constantinpape** [comment]
I think I like bright more. Looks better with the whale (even with adjusted background).

**Comment by tischi** [comment]
Me bright, too => majority :-)
