### ISSUE TITLE
Don't open scatter plot by default

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#245]
I don't think the scatter plot should be opened by default when a segmentation is added.
- It's confusing, because yet another window appears.
- The choice of 'label_id' and 'anchor_x' is arbitrary and doesn't make much sense
- It's inconsistent with the view spec, where the default is "showScatterPlot": False

**Comment by tischi** [comment]
In fact, I kind of like to open it as a default (first class citizen).
@K-Meech what do you think?

The default columns should be anchor_x and anchor_y, is that not the case? Then this is a bug.
Would you think they make sense?

**Comment by K-Meech** [comment]
I'd probably agree with @constantinpape. The scatter plot is super useful, but only really for datasets where you have additional measurements in your table. I think the new 'P' checkbox already does a lot to make the scatterplot easier to find.
Also, for me the default is anchor_x vs anchor_y - seems like a good choice!

**Comment by constantinpape** [comment]
> I'd probably agree with @constantinpape. The scatter plot is super useful, but only really for datasets where you have additional measurements in your table. I think the new 'P' checkbox already does a lot to make the scatterplot easier to find.

Exactly.

> Also, for me the default is anchor_x vs anchor_y - seems like a good choice!

I didn't check this carefully, so I probably just mis-intepreted the scatter plot.
I am not sure if we even need a default if the scatterplot is not opened by default:
then the first time the user clicks 'P' you could just open the selection menu for which axes to show in the scatterplot.

If that's to complicated in terms of UI logic, then using anchor_x, anchor_y as defaults is fine.
(Also the resulting scatter plot is pretty arbitrary, but I can't think of a better option without any knowledge of the custom columns.)
