### ISSUE TITLE
Several issues with grid view

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#246]
# Grid view issues

I have tried the grid view for the zebrafish dataset and found a couple of issues.

## Opening the grid view does not change the field of view, does not open the grid table, does open a scatter plot:

When I select one of the grid views, I see this:
![Screenshot from 2021-04-21 22-01-27](https://user-images.githubusercontent.com/4263537/115614511-18632900-a2ee-11eb-9a26-48472b4752d7.png)

Instead, I would expect:
- a zoomed out view where we can see all grid positions
- that the image table opens so that it can be used to navigate to individual grid positions
- that the scatterplot does not show up. I just realized that this is somewhat unrelated, see #245

## Selecting another grid view does not fully remove the previous one

When I select another (smaller) grid view, I see this:
![Screenshot from 2021-04-21 22-05-15](https://user-images.githubusercontent.com/4263537/115615445-46953880-a2ef-11eb-9c9a-60888cd2dd06.png)
Somehow all sources from the previous grid view are still there; the segments are just not selected.

## Segmentations cannot be toggled

I cannot toggle segmentations anymore; notice that the "S" box is unchecked, but the segmentation is still visible.

![Screenshot from 2021-04-21 22-05-45](https://user-images.githubusercontent.com/4263537/115615664-89571080-a2ef-11eb-8f6b-a40c8c29ab2a.png)

**Comment by tischi** [comment]
@constantinpape I uploaded a new version. I will close this issue although I am not 100% sure what I have fixed.
I would be grateful if you would make individual small issues for all the remaining bugs. That's much easier for me to keep track of what has been fixed. Hope that's OK! Sorry in case you may have to raise some issues a second time!

**Comment by constantinpape** [comment]
Sure, no problem.
I will check again what works and what doesn't.

**Comment by constantinpape** [comment]
These issues are fixed now and grid views work very nicely.
See #255 and #256 for some smaller issues I noticed.

**Comment by tischi** [comment]
I uploaded the new version with above issues hopefully fixed.
