### ISSUE TITLE
Can't change which columns are shown in scatterplot

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#248]
e.g. if I open the zebrafish dataset, and add the first segmentation - the scatterplot appears with anchor_x and anchor_y.

If I then go to the Table menu and Plot > 2D Scatter Plot... with different columns, the scatter plot doesn't update.

**Comment by tischi** [comment]
Show we remove the menu item from the Table (just for MoBIE)?
I think managing the [ P ] and the table menu item at the same time could be a bit messy...

**Comment by constantinpape** [comment]
> Show we remove the menu item from the Table (just for MoBIE)?
> I think managing the [ P ] and the table menu item at the same time could be a bit messy...

How would you change the columns shown in the scatter plot then?

**Comment by tischi** [comment]
if there was no scatterplot I would show the UI as you suggested.

otherwise if you right-click into the scatterplot you can change the columns.

**Comment by constantinpape** [comment]
> if there was no scatterplot I would show the UI as you suggested.
> 
> otherwise if you right-click into the scatterplot you can change the columns.

Ok, that sounds good!

**Comment by K-Meech** [comment]
Yes - sounds like a good solution! We'll just have to make sure we document it properly - the right click options are often a bit hidden for new users

**Comment by tischi** [comment]
The issue with the Table Menu is that on a Mac, it appears on top of your screen and not at the top of the table window.
Thus it is easy to overlook (even I sometimes forget about it).

**Comment by tischi** [comment]
One can change this: 
`System.setProperty("apple.laf.useScreenMenuBar", "false");`
<img width="624" alt="image" src="https://user-images.githubusercontent.com/2157566/115705500-e47b1880-a36c-11eb-97ea-d122ee96e9d4.png">

**Comment by tischi** [comment]
@constantinpape
Do we have a json field for whether the ScatterPlot should be shown or not?
I could not find it...

**Comment by constantinpape** [comment]
Yes, `showScatterPlot` and `scatterPlotAxes` (to save the columns that are used for the axes), see https://mobie.github.io/specs/mobie_spec.html#view-metadata.

**Comment by tischi** [comment]
Do we want defaults for those? If yes, maybe we should put it in the spec?

**Comment by constantinpape** [comment]
> Do we want defaults for those? If yes, maybe we should put it in the spec?

`showScatterPlot`: yes, the default is `False`. I can add it to the spec description.
`scatterPlotAxes`: I don't think it makes much sense to add default values here, because this depends on the data at hand.

**Comment by constantinpape** [comment]
I have added it to the "description" for `showScatterPlot` now, see https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json#L149. (This is used to autogenerate the text on mobie.github.io).
For `scatterPlotAxes` I don't think we can find sensible defaults, so I would just leave that blank.

**Comment by tischi** [comment]
Thanks!
