### ISSUE TITLE
Show scatterplot UI when showing it the first time

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#249]
Refactor the code such that the scatterPlotViewer is only instantiated when needed.
Right now it always is instantiated.

**Comment by tischi** [comment]
Also the logic for whether to recreate or not should be moved out of the `UserInterfaceHelper` into the `ViewerManager`.

**Comment by vzinche** [comment]
Not sure whether it's the same issue, but for me starting a scatterplot from the table doesn't work at all. No errors, exceptions, no reaction whatsoever.

**Comment by vzinche** [comment]
Ah, nevermind, I've found the P option

**Comment by tischi** [comment]
> Not sure whether it's the same issue, but for me starting a scatterplot from the table doesn't work at all.

@vzinche I removed this from the table menu. Is that OK? Easier to maintain for me if there are not too many ways how to open the scatterplot.

**Comment by vzinche** [comment]
The first time you click on 'P' it allows you to choose columns, but afterwards it would just open the same plot. Is there a way to get a new plot (using new columns) without restarting the whole thing?

**Comment by tischi** [comment]
right click into the scatter plot

**Comment by vzinche** [comment]
Works, thanks :+1:
