### ISSUE TITLE
Viewing specific categorical variable

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#25]
A suggestion: would it be possible to view just a specific variable in a categorical column? e.g. for my clustering results, just see cells == 'Cluster3'. When the number of clusters becomes very large it can be difficult to keep track of them if they're all coloured at once in the main viewer.

**Comment by tischi** [comment]
Good idea. I will look into it at some point.

**Comment by tischi** [comment]
@K-Meech 
Probably could be achieved by means of: https://github.com/mobie/mobie-viewer-fiji/issues/65
Right?

**Comment by K-Meech** [comment]
Yes - sounds like it! Some general filtering tools would be very useful

**Comment by tischi** [comment]
Then I'll close this one.
