### ISSUE TITLE
Sources are listed in arbitrary order in the UI

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#254]
The sources seem to appear in some arbitrary order in the UI:
![Screenshot from 2021-04-23 19-45-09](https://user-images.githubusercontent.com/4263537/115909954-7d448d80-a46c-11eb-85fa-fc1894134682.png)
They should be ordered either alphabetically or in the same order as in `sources`.
(Which is always alphabetically, at least when generated with the python tool, see 
https://github.com/mobie/platybrowser-datasets/blob/spec-v2/data/1.0.1/dataset.json)

**Comment by tischi** [comment]
Thanks! Should be fixed now.

**Comment by constantinpape** [comment]
yes, fixed now
