### ISSUE TITLE
Grid view table is not closed when changing the view

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#255]
When changing to a different view from a grid view, the table stays behind.

See for example this, where I switched from "small-grid-view" to "default" in one of the zebrafish datasets
![Screenshot from 2021-04-23 19-51-03](https://user-images.githubusercontent.com/4263537/115910639-5e92c680-a46d-11eb-8e15-669d3810e458.png)

**Comment by tischi** [comment]
Thanks! Should be fixed!

**Comment by constantinpape** [comment]
yes, fixed
