### ISSUE TITLE
Order of UI elements

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#257]
The order of UI elements seems pretty random right now. See the current one for platybrowser and zebrafish below.
I think they should be ordered alphabetically and the bookmarks should maybe be somehow separated from the source menus.

![Screenshot from 2021-04-23 21-36-44](https://user-images.githubusercontent.com/4263537/115922715-8722bc80-a47d-11eb-8974-3c7b6758c2ef.png)
![Screenshot from 2021-04-23 21-43-38](https://user-images.githubusercontent.com/4263537/115922721-8853e980-a47d-11eb-9287-bc4c1d753776.png)

**Comment by tischi** [comment]
@constantinpape Do we enforce the name "bookmark" in the spec?

**Comment by tischi** [comment]
I somehow think the "uiSelectionGroup" should be free to choose whatever people like and then we just order alphabetically.
For our own projects we could just try not to have anything that is above than "b" and then the bookmarks would always be on top 😉

**Comment by constantinpape** [comment]
> I somehow think the "uiSelectionGroup" should be free to choose whatever people like and then we just order alphabetically.
> For our own projects we could just try not to have anything that is above than "b" and then the bookmarks would always be on top

I totally agree. There are also good use-cases for having different menu names to structure the views more, e.g. in platy were we could separate the paper figures from the rest.

But I do think we should have a separation between the source menus (which ofc also correspond to views internally) and the menus for views from `dataset.json`:`views`.

**Comment by tischi** [comment]
I think we need to discuss this in person. I will for now just push the alphabetic sorting.

**Comment by constantinpape** [comment]
Alphabetic sorting is fine here.
