### ISSUE TITLE
Mobie2 : Weird main menu size

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#258]
That's how it starts for me:
![Screenshot from 2021-04-26 16-20-48](https://user-images.githubusercontent.com/32451366/116098497-6c358f80-a6ab-11eb-9886-4bac79bca7ca.png)

**Comment by tischi** [comment]
@vzinche Which OS is that?
@constantinpape @K-Meech can you confirm this?

**Comment by vzinche** [comment]
Ubuntu 18.04.5 LTS

**Comment by vzinche** [comment]
Okay, it only happens when I am using two screens. 
With one it looks pretty normal:

![Screenshot from 2021-04-27 09-32-38](https://user-images.githubusercontent.com/32451366/116203638-2ecd1280-a73c-11eb-9536-47434c0ab4cc.png)

**Comment by tischi** [comment]
I found this thread: https://stackoverflow.com/questions/6322627/java-toolkit-getting-second-screen-size
I will try to tackle this at some point...

**Comment by vzinche** [comment]
In case it helps, Mobie1 is opening all the windows on the same (main) screen, while Mobie2 opens them on different ones side by side. So I could suspect it just treats both displays as one *really* wide screen

**Comment by tischi** [comment]
I think I fixed it. Please test tomorrow again and reopen the issue if needed.
