### ISSUE TITLE
Mobie2: Selecting a cell throws exception

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#259]
Selects the cell though

![Screenshot from 2021-04-26 16-23-06](https://user-images.githubusercontent.com/32451366/116098989-d0585380-a6ab-11eb-9b89-e3e100441b0e.png)

**Comment by vzinche** [comment]
Something similar with coloring by column:
![Screenshot from 2021-04-26 16-41-20](https://user-images.githubusercontent.com/32451366/116101654-4b226e00-a6ae-11eb-9fdb-83f6491788af.png)

**Comment by tischi** [comment]
Fixed.
Thanks for the post!
