### ISSUE TITLE
Updating MoBIE project creator for MoBIE2

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#265]
@tischi @constantinpape I'll start updating the MoBIE project creator soon to fit with the new spec.
Are there any major changes still to come? I can wait longer, if it's still changing.

**Comment by constantinpape** [comment]
I don't expect any big changes on the spec side, but I am not sure how much is still moving on the java front.

**Comment by tischi** [comment]
@K-Meech I will explain you the current state during our meeting tomorrow.

**Comment by K-Meech** [comment]
Just FYI - I'm going to start on this tomorrow! So if there are any imminent changes to the MoBIE spec, let me know :)

**Comment by constantinpape** [comment]
No major changes planed ;).
The last bigger change was this: https://github.com/mobie/mobie.github.io/issues/46.

**Comment by K-Meech** [comment]
@tischi Are you still using your own NFSImageLoader / N5S3ImageLoader etc in MoBIE2? Or have these moved to bdv playground?

**Comment by tischi** [comment]
I am still using them there should be nothing like this in the playground...

**Comment by K-Meech** [comment]
Ok - no problem! I just wasn't sure because they are still in the 'mobie' folder, rather than 'mobie2'.

**Comment by K-Meech** [comment]
@tischi @constantinpape I'm trying to adapt the project creator code to work for time series data.
In the dataset.json, there's a field for 'timepoints' - are we then assuming that all images in the dataset have the same number of timepoints?

**Comment by constantinpape** [comment]
> In the dataset.json, there's a field for 'timepoints' - are we then assuming that all images in the dataset have the same number of timepoints?

Good point, we haven't really specified this. But I think we don't need to expect that all images have the same number of timepoints. Rather, this should be the maximal number of timepoints.

What do you think, @tischi?

**Comment by K-Meech** [comment]
Ok - thanks! I'll keep track of the maximum number of timepoints :)

**Comment by K-Meech** [comment]
@constantinpape Just checking - what were the requirements for time series tables? Is it just the additional column 'timepoint'? So it's the same as the usual table, but with the segments listed for every timepoint?

**Comment by constantinpape** [comment]
Yes, exactl. See example here:
https://raw.githubusercontent.com/mobie/arabidopsis-root-lm-datasets/master/data/arabidopsis-root/tables/lm-cells/default.csv
