### ISSUE TITLE
endings of tables

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#266]
@constantinpape 
https://github.com/mobie/platybrowser-datasets/blob/cf7a12998ce569bdaaaf0f717cd9509d108f3319/data/1.0.1/dataset.json#L8009

Should I add the ".tsv" in the code?
I was not sure whether we force .tsv in the spec...we talked about it but I forgot...

**Comment by constantinpape** [comment]
Yeah, I think we should enforce the ending in the json here. I will fix it for the platy bookmarks and add it to the regex in the spec.

**Comment by tischi** [comment]
> I think we should enforce the ending in the json here

you mean add them explicitly?

**Comment by tischi** [comment]
...adding them explictly into the json would work for me. I don't see a major disadvantage and it is more explicit, which is less error prone.

**Comment by constantinpape** [comment]
Yes, exactly. It should be `vc_assignments.tsv` in the json. Then there is no need to guess the file extension (which could be both csv or tsv in the new spec).

**Comment by constantinpape** [comment]
I have updated it in the platybrowser repo.

**Comment by tischi** [comment]
Thanks!
