### ISSUE TITLE
Saving bookmarks to project

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#270]
I'm updating the bookmark saving code for MoBIE2.
Currently we support:
> Saving to file system
> Saving directly to github (with a github access token)

@tischi @constantinpape Do we want to support saving to s3 (now that projects can be entirely on s3)? I'm not sure how difficult this would be... Otherwise, we can just log a warning that says s3 isn't supported.

**Comment by constantinpape** [comment]
> Do we want to support saving to s3 (now that projects can be entirely on s3)? I'm not sure how difficult this would be... Otherwise, we can just log a warning that says s3 isn't supported.

In order to support saving directly to s3 we would need to solve upload from MoBIE to s3. That would be awesome, but I think we should focus on other things first; so I think for now it's ok if you print a warning that saving to s3 is not supported (yet).
