### ISSUE TITLE
Segmentations made with the project creator don't display in MoBIE2

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#274]
Segmentations made with the new project creator are not visible in MoBIE2.
They open with the corresponding table, and appear in the list of bdv sources, but are invisible. 

Importing the same source into an old style MoBIE project displays correctly, so it seems there is no problem with the n5 writing.
Weirdly, segmentations exported with ```mobie-utils-python``` do display correctly.

I'd assume this is something to do with changes to segmentation source display in bdv playground??

**Comment by constantinpape** [comment]
Can you share a project with one of the segmentations from your project creator.

**Comment by K-Meech** [comment]
Sure! I'll email you the link

**Comment by constantinpape** [comment]
The python utils contain validation functions that can be called from the command line, see https://github.com/mobie/mobie-utils-python/tree/spec-v-02#from-the-command-line.

These are using the jsonschema + some additional validation.

To use it, you need to be on the latest version of the `spec-v-02` branch, see how to set up a development env here: https://github.com/mobie/mobie-utils-python#installation.

Let me know if you think any of the validation errors should actually be valid.

**Comment by K-Meech** [comment]
@constantinpape the jsonschema currently needs lower case lut names e.g. 'glasbey', while java internally uses uppercase e.g. https://github.com/tischi/imagej-utils/blob/713123fccb8b4ac1c6f2f8a4821b33974cb4c594/src/main/java/de/embl/cba/tables/color/ColoringLuts.java 'Glasbey'. 

We mentioned this in a previous issue (https://github.com/mobie/platybrowser-datasets/issues/68), so internally java converts lower case to upper case. 

It might be simpler to change the schema to also use upper case?

**Comment by constantinpape** [comment]
> We mentioned this in a previous issue ([mobie/platybrowser-datasets#68](https://github.com/mobie/platybrowser-datasets/issues/68)), so internally java converts lower case to upper case.
> 
> It might be simpler to change the schema to also use upper case?

We use lowercase everywhere in the spec, so changing it to uppercase only for the colors would look pretty weird.
How much work is it for you to change this upon serialization on the java side?

**Comment by K-Meech** [comment]
That's fair. It would need some changes in imagej-utils, but it shouldn't be too bad. I'll take a look and get back to you.

**Comment by K-Meech** [comment]
Turns out this is an easy fix. So I'll add it to my PR for the new project creator.
