### ISSUE TITLE
'is2d' in dataset.json is not read correctly by mobie

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#275]
There's currently a mismatch between the Java code and the json schema for 'dataset.json'

In the Java code: 'is2D'
In the schema: 'is2d'

This means that this field is not read from the file, and just set to the default of 'false'.

@constantinpape Could we maybe change the schema to use 'is2D'? Otherwise, I can change the java side of things, but it needs changes in both mobie + imagej-utils

**Comment by constantinpape** [comment]
I will change it in the schema.

**Comment by constantinpape** [comment]
Done. @K-Meech if you are using the mobie-utils validation scripts, you need to delete `~/.mobie/*.json` (or what this maps to in windows...) for updating this. (The mobie-utils download the schema to this folder and I am currently not checking for changes in the spec, so it needs to be removed manually.)

**Comment by K-Meech** [comment]
Thanks! All working now
