### ISSUE TITLE
Issue with time-series colours beyond timepoint 0

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#276]
Colours of segmented objects in the viewer and table match well for timepoint 0. Beyond timepoint 0, they no longer match.

e.g. with the spec-v2 branch of the arabidopsis dataset + current mobie-beta, go to a timepoint beyond 0 and ctrl+click on a segment in the viewer. It doesn't appear in a colour that matches the table.

**Comment by tischi** [comment]
I am not sure this is the issue, but it could be. There are cells with label indices `0.0` at ll time points >0 in the arabidopsis data set. Time point 0 is the only one that does not have this issue. I am not sure now, but I do seem to remember that the label index 0 is not allowed according to our specs, is it? @constantinpape

**Comment by constantinpape** [comment]
Good point. I removed the zero label here: https://github.com/mobie/arabidopsis-root-lm-datasets/tree/new-data-spec3

**Comment by constantinpape** [comment]
Oh sorry, I have moved everything into https://github.com/mobie/arabidopsis-root-lm-datasets/tree/spec-v2 already and removed the other branch. Please try again with the "spec-v2" branch.

> I added this to the code. OK?

Yes, that's good.

**Comment by tischi** [comment]
I fixed it. The label source color converters where not listening to time point change.
