### ISSUE TITLE
Add support for OpenOrganelle

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#285]
# Add support for open organelle datasets

Open organelle is a Janelia initiative to make detailed EM volumes and segmentations of cells publicly available: https://openorganelle.janelia.org/.
They use an n5 flavor with similar metadata encoding as ome.zarr and all data is available on s3. Hence, it would be great if we could support opening their datasets in MoBIE.

I think this involves 3 distincts steps:
- [x] Create loaders to read the open organelle data
- [x] Integrate the loaders with MoBIE
- [x] Create mobie projects for the OpenOrganelle data

## Create loaders

The open organelle data format is fairly close to our current data format and I have a branch with a prototype for the loaders already: https://github.com/mobie/mobie-viewer-fiji/tree/oo. So for this first step the changes from this branch would need to be cleaned up and merged and we need a standalone check for opening the data, see [this example](https://github.com/mobie/mobie-viewer-fiji/blob/464b666d7cc9c1c45f9c863c8437f4da738e7586/src/main/java/de/embl/cba/mobie/n5/open_organelle/OpenOrganelleS3Reader.java).

## Integration with MoBIE

Currently, MoBIE only properly supports the bdv.xml file format (n5 or h5) and so there also is no real mechanism to extend the file format support.
We are working on this in https://github.com/mobie/mobie.github.io/issues/49. Once this is implemented, we need to define the open organelle format so that it can be added to the spec and parsed by the viewer.

## MoBIE projects for OpenOrganelle

Once loaders and integration with spec and viewer are done, we would need to generate the MoBIE projects, that are then used as entry point for the viewer. See the project specification [here](https://mobie.github.io/specs/mobie_spec.html).

## Advanced

Some additional things to explore / ideas:
- Add segmentation tables to the OpenOrganelle data
- Write scripts to autogenerate the MoBIE OpenOrganelle projects.

**Comment by KateMoreva** [comment]
Loader to read the open organelle data is working for the Hela example (PR [#290](https://github.com/mobie/mobie-viewer-fiji/pull/290))

**Comment by constantinpape** [comment]
I have added a test project for the open organelle integration now: https://github.com/mobie/open-organelle-test.
So the next step will be to make it possible to open this project in MoBIE.

**Comment by constantinpape** [comment]
The open-organelle loader has been merged (#290).
The next step is to enable opening a full MoBIE project with open-organelle data. We should first enable opening a project with bdv.ome.zarr data, which should be simpler to implement.
Once that done, to test opening the open organelle project:
- Clone https://github.com/mobie/open-organelle-test (the repo is currently private, so we need to open it from the local filesystem instead of github)
- Open it via "Plugins->MoBIE->Open MoBIE Project ..." and enter the path to where the repo was cloned.

**Comment by constantinpape** [comment]
We have a first test project at https://github.com/mobie/open-organelle-test that loads `jrc-hela2` rawdata + an organelle prediction.
Waiting for feedback from @bogovicj to see how to continue with this.

**Comment by bogovicj** [comment]
Thanks for the ping, I'll talk to the team.
