### ISSUE TITLE
PlatyBrowser doesn't start after the last update

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#286]
![Screenshot from 2021-06-01 15-37-56](https://user-images.githubusercontent.com/32451366/120332846-6c026280-c2ef-11eb-8200-2b43d346f066.png)

@constantinpape  were you moving to some new format?

**Comment by vzinche** [comment]
Yes

**Comment by constantinpape** [comment]
Ok, then this is expected. MoBIE-beta currently doesn't work with `master`, instead you need to use the version from the regular update site.
Or you can use beta and this branch: https://github.com/mobie/platybrowser-datasets/tree/spec-v2

**Comment by vzinche** [comment]
Ah, okay, I didn't know, thanks!

**Comment by vzinche** [comment]
@constantinpape , is it normal that in spec-v2 I cannot load any columns from the project? It just directly offers me to choose locally

**Comment by constantinpape** [comment]
> @constantinpape , is it normal that in spec-v2 I cannot load any columns from the project? It just directly offers me to choose locally

No, that should work. Can you make an issue in the mobie-fiji repo and describe this?
