### ISSUE TITLE
No option to load project tables

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#287]
When adding columns to a table, it doesn't even offer to load from project:
![loadfromproject](https://user-images.githubusercontent.com/32451366/120456070-8f7fe880-c395-11eb-84ed-3168b5f079ae.gif)

**Comment by K-Meech** [comment]
@tischi I can look into this issue. I need to refactor that part anyway to stop depending on ```selectPathFromProjectOrFileSystem``` from imagej-utils

**Comment by K-Meech** [comment]
This is fixed on the latest mobie beta
