### ISSUE TITLE
Opacity for image sources is not used by the viewer

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#289]
`opacity` is a part of the display settings both for `image`and `segmentation` sources. Currently, it is only used for `segmentation` though and is not read correctly for `image`.
Also, afaik, it can be set neither for `image` nor for `segmentation` via the UI.

The plankton em project that @K-Meech and me are preparing is using opacity for `image` data, I can share it soon so that we have an example to check this.

**Comment by tischi** [comment]
It can be set by pressing the **[ O ]** button.

**Comment by constantinpape** [comment]
> It can be set by pressing the **[ O ]** button.

Ok, indeed that works.
But it seems that for `image` sources it is not properly loaded from the metadata.

**Comment by tischi** [comment]
Should work now.
