### ISSUE TITLE
Bookmarks or Views?

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#294]
@constantinpape I noticed that the java project creator, and mobie-utils-python use different conventions for where to put the default view.

Do you have a preference? At the moment, I put it under the ui selection group 'views' because we got rid of all the bookmark mentions in the spec. I think you are still using 'bookmark' though?

**Comment by constantinpape** [comment]
I still call it bookmarks for the ui selection group, because I think it's a bit more intuitive for most users.

**Comment by K-Meech** [comment]
Makes sense - I'll change the project creator to match
