### ISSUE TITLE
Multiple sources with table in a segmentationDisplay

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#295]
After @K-Meech bringing up these problems in #291 I realized that we have not really defined what should happen if we have multiple sources with tables in a segmentation display. (And that I probably misunderstood what's happening here).

## Scenario 1: Multiple sources in one display no grid view

We have a view that contains this:
```json
"sourceDisplays": [
{"segmentationDisplay": {
  "sources": ["segA", "segB"],
  "tables": ["tabA", "tabB"]}
}]
```
What should happen? I see two options and both currently have issues.
1. Both sources are loaded with separate tables, see my sketch here https://github.com/mobie/mobie-viewer-fiji/issues/291#issuecomment-856645869. Problem: we only have a single view for these two sources, so there will only be 1 element for them in the main menu, but we have two (or more) corresponding image layers and tables.
2. We merge the tables into a single "ui-table" by using "label-id" and "label_image" columns to keep unique rows. Problem: we still have two (or more) layers that are displayed on top of each other and cannot be selected independently. Note that we face this problem also with imageDisplays that have multiple sources per display (if we don't have a grid view).

## Scenario 2: Multiple sources in one display with grid view.

We have a view that contains this:
```json
"sourceDisplays": [
{"segmentationDisplay": {
  "sources": ["segA", "segB"],
  "tables": ["tabA", "tabB"]}
}],
"sourceTransforms": [
{"grid": {"sources": [["segA"], ["segB"]]}}
]
```

What should happen? Here the case is clear: we want case 2 from above, because the grid transform will move the sources onto separate spatial locations.

## How do we resolve this?

I think the best way is to go with option 2, because then we have the same with and without grid view (having different behavior would make the implementation too complex). I think the case of having multiple sources in one display without a grid tramsformation, or some other transformation that separates the sources spatially, does not make much sense, so it's ok that this will result in a weird viewer state.
Note that in the current implementation the case for the grid view does not quite work as expected yet, I will post more details in a second.

@K-Meech I think for the issue of loading columns from the project that means that you will need to do some filter and only show the tables that are available for all segmentations. (Sorry I said something different earlier, but I did not understand the full problem yet).

**Comment by constantinpape** [comment]
The case of multiple segmentations with table in a grid view seems to not be working correctly yet (tested with latest MoBIE-beta):

When loading [this grid view](https://github.com/mobie/zebrafish-lm-datasets/blob/spec-v2/data/membrane/dataset.json#L1298) only the rows for the first image (`056F633...`) are present in the UI-table, the others are missing:

![Screenshot from 2021-06-08 13-48-40](https://user-images.githubusercontent.com/4263537/121179658-44b41400-c860-11eb-8676-78edae339ad3.png)

**Comment by tischi** [comment]
⬆️ used to be working. Maybe some bug was introduced.
[This is the code that should handle this](https://github.com/mobie/mobie-viewer-fiji/blob/4cb090be86c7c0cdc9ac5d5dc5c4a968f62440c9/src/main/java/de/embl/cba/mobie/view/ViewerManager.java#L280), but currently only works for the default table. Maybe that's the issue?

**Comment by constantinpape** [comment]
> [This is the code that should handle this](https://github.com/mobie/mobie-viewer-fiji/blob/4cb090be86c7c0cdc9ac5d5dc5c4a968f62440c9/src/main/java/de/embl/cba/mobie/view/ViewerManager.java#L280), but currently only works for the default table. Maybe that's the issue?

We only have the default table in this view, so I think it must have stopped working again.

**Comment by K-Meech** [comment]
I agree that option2 (merging the tables) makes the most sense.
Then for full consistency, 'load columns...' would need to grab the table names from every source's table folder, and only keep those that are present in every one. This shouldn't be too difficult, but will mean this operation could be quite slow if there are many sources combined, and the table data is being loaded from remote.

**Comment by constantinpape** [comment]
> This shouldn't be too difficult, but will mean this operation could be quite slow if there are many sources combined, and the table data is being loaded from remote.

I wouldn't worry about speed to much for now. If this turns out to be too slow then you could try to use multi-threading, I would hope that this would make it much faster. (For loading large grid view @tischi has done this and it has improved the process significantly).

**Comment by tischi** [comment]
> We only have the default table in this view, so I think it must have stopped working again.

I fixed a bug in imagej-utils and it works again in the current master.

**Comment by K-Meech** [comment]
Great! I'm fixing 'load columns' for the multi-segmentation tables now. So should be done sometime today.

**Comment by tischi** [comment]
> I'm fixing 'load columns' for the multi-segmentation tables now.

I worked on making this nicer (in another repo) such that one only needs to update the tableRows and the JTable is updated automatically:

https://github.com/tischi/segmentation-annotator/blob/d712204d7ef773b88fb4e895f1cba6dccbe6e30c/src/main/java/de/embl/cba/segmentationannotator/TableView.java#L155

If you want you could try to copy this logic over to MoBIE when you are at it (maybe it simplifies things a bit, I am not sure). Otherwise I could do it later.

**Comment by K-Meech** [comment]
Thanks @tischi . I'll finish up fixing the bit I'm on, then it's probably easiest if you switch it over to the new logic yourself :)

@constantinpape Could you add an example to the zebrafish dataset, where there's a table listed in a segmentation display with multiple segmentations? e.g. adding it to an example grid view?

**Comment by constantinpape** [comment]
@K-Meech done: https://github.com/mobie/zebrafish-lm-datasets/blob/new-data-spec/data/membrane/dataset.json#L1798-L1801

**Comment by K-Meech** [comment]
Thanks @constantinpape - I think you need to add the table extension though e.g. "shape_CFOR_pca_measured.tsv". At least, this is what we did with the platy bookmarks: https://github.com/mobie/platybrowser-datasets/blob/spec-v2/data/1.0.1/dataset.json#L2251

**Comment by constantinpape** [comment]
You're right. I fixed it.

**Comment by K-Meech** [comment]
Ok - there is an issue with loading these multi-segmentation tables with additional tables. 
Currently, opening the remote zebrafish dataset, and viewing the bookmark 'small-grid-view' leads to the following error:
```
Exception in thread "Thread-18" java.lang.NullPointerException
	at de.embl.cba.tables.imagesegment.ColumnBasedTableRowImageSegment.getCell(ColumnBasedTableRowImageSegment.java:226)
	at de.embl.cba.tables.tablerow.DefaultTableRowsModel.getColumn(DefaultTableRowsModel.java:85)
	at de.embl.cba.tables.tablerow.JTableFromTableRowsModelCreator.createJTable(JTableFromTableRowsModelCreator.java:34)
	at de.embl.cba.mobie.table.TableViewer.configureJTable(TableViewer.java:296)
	at de.embl.cba.mobie.table.TableViewer.show(TableViewer.java:123)
	at de.embl.cba.mobie.view.ViewerManager.initTableViewer(ViewerManager.java:94)
	at de.embl.cba.mobie.view.ViewerManager.showSegmentationDisplay(ViewerManager.java:279)
	at de.embl.cba.mobie.view.ViewerManager.showSourceDisplay(ViewerManager.java:205)
	at de.embl.cba.mobie.view.ViewerManager.show(ViewerManager.java:167)
	at de.embl.cba.mobie.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:443)
	at java.lang.Thread.run(Thread.java:748)
```

I imagine this is something to do with this code here: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/view/ViewerManager.java#L299

@tischi Could you take a look, if you have time? It's probably something to do with not handling merging columns of the same name in multiple tables into one column in the new table.

**Comment by tischi** [comment]
Could you pull imagej-utils and mvn clean install?
I changed something there that may fix this...

**Comment by K-Meech** [comment]
I still get the same error after updating imagej-utils

**Comment by tischi** [comment]
> where there's a table listed in a segmentation display with multiple segmentations

This [indeed does not work yet](https://github.com/mobie/mobie-viewer-fiji/blob/3f33a6852553ff96f45b3597dce19dd263f6491a/src/main/java/de/embl/cba/mobie/view/ViewerManager.java#L307). I will look into it.

@K-Meech did you already implement something along those lines (Load Columns)? Then I may be able to reuse some of your code...

**Comment by K-Meech** [comment]
Not yet - but I'll need really similar code for loading columns for these multi-segmentation tables. 
If you could get that part working on master, then I can pull it into my branch and get it working for loading columns too :)

**Comment by tischi** [comment]
Ok, I will work on it an try to make the code reusable.

**Comment by tischi** [comment]
I started working on it but it may take some time...
I get the feeling that the current table model does in fact not work when concatenating several tables into one. I think some ground work may need to be done...

**Comment by K-Meech** [comment]
@tischi @constantinpape How should we handle loading columns from the filesystem for tables with multiple sources?

For now, I'd probably just disable this option when there are multiple sources. A normal table with just the label_id can't be loaded, as we don't know which source to load it for (without some additional gui step where you choose the source)

Otherwise, we could require a table with both ```label_id``` and ```label_image_id``` columns, but this is a bit confusing given that it's different from the way we structure all the other tables.

**Comment by K-Meech** [comment]
When I say filesystem, I mean from an arbitrary location on the filesystem i.e. not inside the project

**Comment by constantinpape** [comment]
> @tischi @constantinpape How should we handle loading columns from the filesystem for tables with multiple sources?
> 
> For now, I'd probably just disable this option when there are multiple sources. A normal table with just the label_id can't be loaded, as we don't know which source to load it for (without some additional gui step where you choose the source)
> 
> Otherwise, we could require a table with both `label_id` and `label_image_id` columns, but this is a bit confusing given that it's different from the way we structure all the other tables.

Yes, let's just disable it for now.

**Comment by K-Meech** [comment]
We currently support choosing which column to merge by when you 'load columns..':  https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/table/TableViewer.java#L399

@tischi @constantinpape Do we want to keep this? It complicates things, as a lot of the table loading assumes merging on label_id for all tables (or grid_id for grids). If we still want it, then I guess it should be another field in the spec?

**Comment by tischi** [comment]
> Do we want to keep this?

I think we should skip this in the UI as this will create a mess is people choose the wrong columns.

**Comment by K-Meech** [comment]
Yes - I agree. I'll take it out for now.

**Comment by K-Meech** [comment]
This is resolved in the current master. Tables are merged for multi-source
