### ISSUE TITLE
Mobie version 0.6.1 does not support label images without table

### ISSUE THREAD

**Issue by jhennies** [mobie/mobie-viewer-fiji#296]
@constantinpape here the issue we briefly chatted about yesterday...

When adding a label image without table information in Mobie v0.6.1, I get the following error:

```
Adding source: em-raw...
Adding source: em-supervoxels...
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Visualisation of label images without tables is not supported.
	at de.embl.cba.mobie.ui.SourcesDisplayManager.show(SourcesDisplayManager.java:412)
	at de.embl.cba.mobie.ui.SourcesDisplayManager.show(SourcesDisplayManager.java:362)
	at de.embl.cba.mobie.ui.UserInterfaceComponentsProvider.lambda$null$0(UserInterfaceComponentsProvider.java:124)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

The same dataset works fine in Mobie version 0.5.6

Below some 'minimal' mobie_utils dataset generation with which I was able to reproduce the problem (mobie_utils version 0.1.1).
It generates a mobie dataset with an empty raw and an emtpy segmentation image. To reproduce the problem, open the generated dataset in Mobie and add the seg-raw dataset (i.e. the segmentation). For the Mobie v 0.6.1 this should result in the error above

```
import os
from mobie.initialization import make_dataset_folders
from pybdv.converter import normalize_output_path
from pybdv.util import get_key, open_file
from pybdv.metadata import write_n5_metadata, write_xml_metadata, validate_attributes
from mobie.metadata.datasets import add_dataset
from mobie.metadata.image_dict import add_to_image_dict
from mobie.metadata.bookmarks import add_bookmark

mobie_project_path = os.path.join(
    '/path/to/your/test/dir',  # <------ Define a target path here!
    'data'
)

dataset_name = 'my_dataset'

# Set up the folder structure
dataset_folder = make_dataset_folders(mobie_project_path, dataset_name)


def make_empty_dataset(name, type):

    # Generate the data path of the image
    data_path = os.path.join(
        mobie_project_path, dataset_name,
        'images', 'local', '{}.n5'.format(name)
    )

    # Make an empty dataset
    data_path, xml_path, is_h5 = normalize_output_path(data_path)

    base_key = get_key(is_h5, timepoint=0, setup_id=0, scale=0)
    with open_file(data_path, 'a') as f:
        # Create the full sized dataset
        f.create_dataset(base_key, shape=(256, 256, 256), compression='gzip',
                         chunks=None, dtype='uint16')

    resolution = (0.01, 0.01, 0.01)
    write_n5_metadata(data_path, ((1, 1, 1),), resolution, 0, 0, overwrite=False)

    # validate the attributes
    attributes = {'channel': {'id': None}}
    enforce_consistency = True
    attributes_ = validate_attributes(xml_path, attributes, 0, enforce_consistency)

    # write bdv xml metadata
    write_xml_metadata(xml_path, data_path, 'um', resolution, False,
                       setup_id=0, timepoint=0, setup_name=None, affine=None,
                       attributes=attributes_, overwrite=False, overwrite_data=False,
                       enforce_consistency=enforce_consistency)

    # Generate some settings files
    add_to_image_dict(dataset_folder, type, xml_path)


make_empty_dataset('em-raw', 'image')
make_empty_dataset('seg-raw', 'segmentation')

add_bookmark(dataset_folder, 'default', 'default',
             layer_settings={'em-raw': {'contrastLimits': [0., 255.]}}, overwrite=True)

# Finalize the dataset
add_dataset(mobie_project_path, dataset_name, is_default=True)
```

**Comment by constantinpape** [comment]
In general, segmentations without table should still be supported. We will check this again once the new spec is fully integrated.

**Comment by tischi** [comment]
I think it was never supported, to be honest. But we could try to support it.
Either (a) MoBIE works without table or (b) the MoBIE project generators create a minimal table if none is provided.
I think I would prefer (b).

**Comment by jhennies** [comment]
I'm not sure about (b)

The reason I need this is that I am displaying supervoxels, which can be quite a lot of unique object IDs for a large dataset. 
I don't know how Mobie does the lookup with a table, but I assume it might become quite a large table with potential slow lookup.

**Comment by tischi** [comment]
OK, I can then work on making MoBIE without any table.

**Comment by jhennies** [comment]
I'm just surprised then that it then works with the older Mobie version. The tables folder in my mobie project is empty and it just generates random colors for the supervoxels, just as I need it.

**Comment by tischi** [comment]
Ok, then I remembered it wrongly. Apparently it did use to work. I'll have a look!

**Comment by constantinpape** [comment]
> Apparently it did use to work. I'll have a look!

Yes, it used to work, I have also used it before.
Also the way the spec is written right now means it should def. work.


> The tables folder in my mobie project is empty and it just generates random colors for the supervoxels, just as I need it.

Just to clarify: you should not have a tableFolder if you don't have tables and it should not be listed in the json.

**Comment by jhennies** [comment]
> Just to clarify: you should not have a tableFolder if you don't have tables and it should not be listed in the json.

It's generated by default by the ```make_dataset_folders``` function (the one I use in the code snipped above), it never bothered me because I need it for segmentations later on anyways. 
And there is definitely no tables stuff in the json, if there was, it would error out anyways, I think.

**Comment by constantinpape** [comment]
> And there is definitely no tables stuff in the json, if there was, it would error out anyways, I think.

Ok, as long as it's not listed in the json it's fine.

**Comment by constantinpape** [comment]
deprecated in favor of #321
