### ISSUE TITLE
Feature request for Scatterplot: selection by drawing a rectangle 

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#300]
Right now the only option to select a group of cells is to Ctrl-Click each of them. It would be much easier to be able to, let's say, hold Ctrl and draw a rectangle on the scatterplot to select all the dots (cells) within this rectangle. 

If something like this is easy to add, that would be great. If not, I guess it's not worth bothering

**Comment by tischi** [comment]
@NicoKiaru the BdvSelector has a rectangle selection function, does it?

Do you think that could be [used here](https://github.com/mobie/mobie-viewer-fiji/blob/96b65900139f0b3190ffcf99a51837a17b68c621/src/main/java/de/embl/cba/mobie/plot/ScatterPlotViewer.java#L275)?

This is only one source, rendering multiple points, and we want to select a subset of points.

I guess that means whether one could use BDVSelector to just provide functionality to interactively put a 2D bounding box onto BDV and listen to its `RealInterval`?

**Comment by NicoKiaru** [comment]
I think you need to rewrite it to select a bunch of points.

I've done something along these lines here : https://biop.github.io/ijp-imagetoatlas/registration.html

The code is somewhere here I think : https://github.com/BIOP/ijp-imagetoatlas/blob/40f138f65afc1796796552f432dc1b9ffa968532/src/main/java/ch/epfl/biop/atlas/aligner/SelectionLayer.java#L75

But I'm not sure...

**Comment by tischi** [comment]
@vzinche I had a brief look. I think what could be quite easy to implement a right-click menu item where you can specify that all points are selected that are closer than **an adjustable radius** around where you clicked. So, a circular selection tool rather than a rectangular. Would that be useful or do you prefer a rectangle?

**Comment by vzinche** [comment]
@tischi, that also sounds good, thanks!

**Comment by vzinche** [comment]
@tischi, I was just wondering if you still remember about this one :)
If it is actually easy to implement, would be really great to have this one because right now I am doing **a lot** of clicking

**Comment by tischi** [comment]
I am not sure how easy it will be and I am still involved in the EMBO course. 
I may only get to it next week (maybe I will find some time tonight)...

**Comment by vzinche** [comment]
No worries, I just thought you might have some code templates for this. No pressure :)

**Comment by tischi** [comment]
I will work on it today. I don't want you to get arthritis 😄

**Comment by tischi** [comment]
@vzinche 
I think it was easier than I thought.
I put the jar on `/g/cba/exchange/Valentyna`.
Can you access it?
You have to replace that one in the Fiji.app/jars folder.

**Comment by vzinche** [comment]
Thanks a lot, I could copy it :+1: 
How do I adjust the radius now?

**Comment by tischi** [comment]
`Right click > Configure point(s) selection...`

**Comment by tischi** [comment]
I am not sure how to best deselect points in this mode....

With just "selecting" one point it was in fact a _toggle mode_: If it was selected selecting again would deselect it.

I think toggling for many points is not so intuitive. Let me know what you think.

**Comment by vzinche** [comment]
> `Right click > Configure point(s) selection...`

I've moved the mobie-2.0.0-SNAPSHOT.jar to the Fiji.app/jars, but I somehow don't see this option

**Comment by vzinche** [comment]
> I am not sure how to best deselect points in this mode....
> 
> With just "selecting" one point it was in fact a _toggle mode_: If it was selected selecting again would deselect it.
> 
> I think toggling for many points is not so intuitive. Let me know what you think.

That's a good question. Toggle mode feels 'the cleanest', but it can be counterproductive for selecting multiple points. The other option would be to allow deselecting only in point-wise mode (or with Ctrl-N) ?

**Comment by tischi** [comment]
It should be there (right click into the scatter plot window).
But somethings weird, as I cannot even open a MoBIE project in my Fiji right now: https://github.com/mobie/mobie-viewer-fiji/issues/333

**Comment by tischi** [comment]
@vzinche 
Are you sure?
For me it is there:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/2157566/124148039-8fa3fe80-da8f-11eb-8ed6-540a968f37da.png">

**Comment by tischi** [comment]
> I've moved the mobie-2.0.0-SNAPSHOT.jar to the Fiji.app/jars, but I somehow don't see this option

Did you also **re**move the old one? Maybe you have two versions in parallel there?

**Comment by tischi** [comment]
I replaced the jar again in `/g/cba/exchange/Valentyna`, but should be the same..
You could still try to use this one.

**Comment by vzinche** [comment]
I didn't remove it, I just renamed it, and it seems it was still using the old version. 
Anyways, now it looks like it works well! Lots of thanks!

![Screenshot from 2021-07-01 17-37-19](https://user-images.githubusercontent.com/32451366/124151733-28884900-da93-11eb-80ab-7c89d2b1b3bf.png)

**Comment by tischi** [comment]
Cool!
And once you used it a while maybe we could chat about the deselect options.
So I'll leave the issue open.
