### ISSUE TITLE
Add basic CI

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#303]
We have no CI at all here, which makes evaluating PRs a bit difficult.
I understand that this is not so easy for tests that involve the GUI (though I am sure there are some workarounds for this), but for starters having something that checks the build would already be very helpful.

**Comment by tischi** [comment]
We should factor out the ome-zarr into a separate repo and then add CI. 
I know how to get this done.
I think we should do this ASAP (e.g. tomorrow) such that Josh et al. can use it during ELMI and do not have to depend on the whole MoBIE repo.

@KateMoreva 
If I create an empty repository for you, could you copy everything into it that is needed for OME.ZARR?

**Comment by KateMoreva** [comment]
> We should factor out the ome-zarr into a separate repo and then add CI.
> I know how to get this done.
> I think we should do this ASAP (e.g. tomorrow) such that Josh et al. can use it during ELMI and do not have to depend on the whole MoBIE repo.
> 
> @KateMoreva
> If I create an empty repository for you, could you copy everything into it that is needed for OME.ZARR?

Thank you, yes.
I have only one question. As the work over support of the new `ome.zarr` is in progress right now (I'll try to finish with the main features as quickly as possible), I should move only the files for the old version (if the logic would not be implemented by that time)?

**Comment by tischi** [comment]
Yes only the old files. And then, ideally, change your PR to work against the new repository. 
If that is too annoying, you can still do the PR against the mobie-fiij-viewer and then move it over after we merged.

**Comment by tischi** [comment]
I made the repo: https://github.com/mobie/bigdataviewer-ome-zarr
Please don't forget to also copy the `.gitignore` file.

**Comment by KateMoreva** [comment]
Thank you, ok.

**Comment by tischi** [comment]
@KateMoreva Just wanted to say that I think making the new repo work with the old files would be rather high priority because @joshmoore and others would like to demonstrate this at a conference next week. So, ideally, if we could finish this by tomorrow it would be great! Let me know if you need help!

Regarding the class paths, I think

`de.embl.cba.bdv.ome.zarr`

could be a start (so no `mobie`).

**Comment by KateMoreva** [comment]
> @KateMoreva Just wanted to say that I think making the new repo work with the old files would be rather high priority because @joshmoore and others would like to demonstrate this at a conference next week. So, ideally, if we could finish this by tomorrow it would be great! Let me know if you need help!
> 
> Regarding the class paths, I think
> 
> `de.embl.cba.bdv.ome.zarr`
> 
> could be a start (so no `mobie`).

Thank you.
I am working on this task right now.
In the progress of making a runnable version, which would be cleaned up after that.
Renamed the project according to your suggestion.

**Comment by constantinpape** [comment]
Just a quick update on this: we will add CI for the image loaders / writers in `bigdataviewer-imageloaders`. I think it would still be good to add CI here that builds MoBIE.

**Comment by K-Meech** [comment]
I'm currently updating the project creator code and, if I have time, I'll probably add a few small tests to make it easier to modify in future.
Were we going to add CI to this repo too? And do we want it to just build MoBIE, or also run a few tests?
I'm happy to look into adding this.

**Comment by constantinpape** [comment]
> Were we going to add CI to this repo too? And do we want it to just build MoBIE, or also run a few tests?
> I'm happy to look into adding this.

Yes, it would be great to add CI here in order to catch build issues and things like #423 earlier!
I would suggest using github actions (https://docs.github.com/en/actions). @KateMoreva and @tischi would know more about how to best add the tests with junit and how to run them via maven.

**Comment by tischi** [comment]
@K-Meech yes, please! Adding CI would be great! To get started I think we should use the same procedure as we did for bdv-imgloader, as done by @KateMoreva. Maybe you and @KateMoreva could chat by some means about how to do this.

**Comment by K-Meech** [comment]
Ok - sounds good! I'll email @KateMoreva to set something up :)

**Comment by K-Meech** [comment]
@tischi @constantinpape Do you want this repo on the scijava maven repository too? Or just build/run tests?

**Comment by K-Meech** [comment]
I don't think it should be too difficult. All the secrets we need are added into the mobie organisation already, so we don't need to do that over again. I'll give it a go - and see what happens!

**Comment by imagejan** [comment]
If this repo build fine using `mvn` from the command line, adding CI should be as easy as running [`github-actionify.sh`](https://github.com/scijava/scijava-scripts/blob/main/github-actionify.sh) from `scijava-scripts`.

**Comment by K-Meech** [comment]
Thanks for the info @imagejan! I'm trying to run this on Windows via git bash, and it's erroring with ```[ERROR] Could not determine GitHub repository slug```. Perhaps a similar error to this one you had with traversify.sh?https://github.com/scijava/scijava-scripts/issues/15

**Comment by imagejan** [comment]
@K-Meech strange that you got an error, the xmllint line seems to be fine in the new script, but test on Windows Git Bash myself now.

I opened https://github.com/mobie/mobie-viewer-fiji/pull/427 with updates to `pom.xml` (never hardcode `scijava.app.directory`, @tischi, that should be in your local IDE config; and some updates for forum and maven repository) and added CI with the SciJava script on MacOS.

**Comment by tischi** [comment]
> never hardcode scijava.app.directory, @tischi, that should be in your local IDE config

That sounds awesome! Do you happen to know how to realize this for IntelliJ?

**Comment by imagejan** [comment]
@tischi it's documented here for Eclipse (although it needs to be updated from `imagej.app.directory` to `scijava.app.directory`):

https://imagej.net/develop/eclipse#option-2-install-dependencies

I guess something similar should be available in IntelliJ?! Maybe also @haesleinhuepf can advise. If you find out, it'd be awesome if you also add it to the documentation in https://imagej.net/develop/intellij ;-)

**Comment by tischi** [comment]
@NicoKiaru do you happen to know how to specify the scijava.app directory within IntelliJ rather than baking it into the pom?

**Comment by NicoKiaru** [comment]
> @NicoKiaru do you happen to know how to specify the scijava.app directory within IntelliJ rather than baking it into the pom?

Unfortunately no... I hardcode it and modify it when I need to upload to an update site. BTW I really need to look at this new way of making CI. You are using github actions now it seems...

**Comment by imagejan** [comment]
@tischi @NicoKiaru I'm not using IntelliJ, but according to the docs, it should be something like `-Dscijava.app.directory=/path/to/your/Fiji.app` in the "Runner" tab of the Maven Run Configuration:

https://www.jetbrains.com/help/idea/run-debug-configuration-maven.html#runner

**Comment by tischi** [comment]
> I'm not using IntelliJ, but according to the docs, it should be something like -Dscijava.app.directory=/path/to/your/Fiji.app in the "Runner" tab of the Maven Run Configuration:

In fact for installing the project I also don't use IntelliJ but just maven. I found out that there is works like this:

```
mvn clean install "-Dscijava.app.directory=/Users/tischer/Desktop/Fiji/Fiji-MoBIE-beta.app"
```

Thanks @imagejan for the great help!

**Comment by ctrueden** [comment]
> Do you happen to know how to realize this for IntelliJ?

For setting `scijava.app.directory` outside your `pom.xml`? My advice is to set it in your `~/.m2/settings.xml`. This is an IDE-independent place. It may be that certain IDEs do not respect this file though; I'm not sure. Certainly that works for the `mvn` CLI tool.

As for the "`github-actionify.sh` doesn't work in Git Bash on Windows" problem... it does look a lot like scijava/scijava-scripts#15, doesn't it? But I think the quoting looks correct (i.e. matching @imagejan's fix) in the `github-actionify.sh` code, no?

Probably more robust would be to change the script not to use `xmllint` at all, but something else. Perhaps we could do:
```bash
scmConnection=$(mvn -B -q -Denforcer.skip=true -D3dthing=yes -Dexec.executable=echo -Dexec.args='${project.scm.connection}' --non-recursive validate exec:exec 2>/dev/null)
repoSlug=$(echo "$scmConnection" | sed 's_.*github.com[:/]\(.*\)_\1_')
```
The reason I didn't do it before is because it's slower than `xmllint`, taking on the order of seconds to return as opposed to a fraction of a second.

Or we could keep it fast but hacky, with:
```
repoSlug=$(grep connection pom.xml | sed 's;.*github.com[/:]\(.*/.*\)</connection>;\1;')
```
I don't feel strongly; whatever works across all these environments is fine with me.

**Comment by NicoKiaru** [comment]
One note, for github actionify on windows, we had to install xmllint "manually". It's in some documentation in here:
https://c4science.ch/w/bioimaging_and_optics_platform_biop/image-processing/version-control/

In particular:

```
Follow the answered procedure described in:

https://stackoverflow.com/questions/19546854/installing-xmllint

OR

Copy the xmllint folder located at \\svfas6.epfl.ch\biop\biop\Informatics\Software Library\XMLLINT at the C:\ and add the bin folder to the PATH system environment variable, eg Path : C:\xmllint\bin
```

**Comment by ctrueden** [comment]
@NicoKiaru I replaced the usages of xmllint with grep: scijava/scijava-scripts@352a9e95c5495ed3fa70526cdedab8ea9945821a. Please give it a try and let me know if it works better for you on Windows.

**Comment by NicoKiaru** [comment]
@ctrueden it worked (tested on a new repo), thanks!
