### ISSUE TITLE
MoBIE Update fails

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#306]
Hi,

I try to updateMoBIE-beta and get:

<img width="1039" alt="Screenshot 2021-06-15 at 10 55 35" src="https://user-images.githubusercontent.com/35071867/122024122-6e24f080-cdc8-11eb-987c-37955d764b88.png">

**Comment by martinschorb** [comment]
It is the same for the release channel:

<img width="1039" alt="Screenshot 2021-06-15 at 14 16 44" src="https://user-images.githubusercontent.com/35071867/122050993-62dfbe00-cde4-11eb-82ef-600603bf2533.png">

**Comment by tischi** [comment]
@martinschorb thanks for spotting this!

This is very strange as I don't think I touched the MoBIE update site for quite some time.

I had a look at  https://sites.imagej.net/MoBIE/jars/
and indeed only found below jar, which has a slightly more recent date (2020-09-18) then the one that it is looking for (2020-09-14).

<img width="654" alt="image" src="https://user-images.githubusercontent.com/2157566/122055970-72add100-cde9-11eb-8036-59aaf291ebf7.png">

@frauzufall @ctrueden do you have an idea how this could have happened, i.e. the updater asking for an older version of a jar than what is stored on the update site?

**Comment by martinschorb** [comment]
The release MoBIE works now. Beta still fails. Could you share a Fiji with MoBIE Beta (Mac) somewhere, so I can continue testing?

**Comment by tischi** [comment]
> The release MoBIE works now.

Super weird... why is it working "now"? Did you change anything on your side?

**Comment by martinschorb** [comment]
OK, weird. After uninstalling MoBIE release and then immediately installing Beta in the same update procedure, it managed...

**Comment by martinschorb** [comment]
No idea. There was an update of the affected jar through the Java-8 repo, but after that I only got the release to install.
Now it did it. Let me check if it works in the end...

**Comment by martinschorb** [comment]
seems to work. There was some library mess-up in the first restart but now looks like everything is updated to the beta packages.

**Comment by tischi** [comment]
I think the safest workflow is (in fact for any update site):

1. New Fiji
2. Update Fiji once without activating, e.g. MoBIE (this will pull all the updates from the Java8 update site)
3. Restart
4. Only now activate the, e.g. MoBIE update site

**Comment by martinschorb** [comment]
> * New Fiji
> 
> * Update Fiji once without activating, e.g. MoBIE (this will pull all the updates from the Java8 update site)
> 
> * Restart
> 
> * Only now activate the, e.g. MoBIE update site

That is exactly what I did initially. Strange. I'll report if something similar happens again.
