### ISSUE TITLE
.mrc file format

### ISSUE THREAD

**Issue by yanschwab** [mobie/mobie-viewer-fiji#309]
Hi all, 
do you know if this file format is supported for creating a project?

**Comment by K-Meech** [comment]
Hi @yanschwab - if you can open it as a normal image stack in imageJ, then it's supported! The project creator can then convert it to n5 via adding the 'current open image'

In the end all files must be n5 though, so you can't use .mrc directly

**Comment by K-Meech** [comment]
If you still have issues, let me know @yanschwab
