### ISSUE TITLE
Do we support "true" 2D data?

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#310]
Do we support true 2d data in MoBIE, @tischi? As far as I can see, we have so far solved this by adding a singleton axis, e.g. [here](https://github.com/mobie/yeast-clem-datasets/blob/main/data/yeast/images/local/em-raw-overview.xml#L16).
But it would be good to support data with only 2 dimensions, which is more natural for 2d images.
This came up in 2 different places now:
- Opening 2d data does not work here in [this PR](https://github.com/mobie/bigdataviewer-ome-zarr/pull/9) by @KateMoreva?
- I am working on adding a Covid-IF example project. There it would be much easier to add the data as 2d.

**Comment by KateMoreva** [comment]
> Do we support true 2d data in MoBIE, @tischi? As far as I can see, we have so far solved this by adding a singleton axis, e.g. [here](https://github.com/mobie/yeast-clem-datasets/blob/main/data/yeast/images/local/em-raw-overview.xml#L16).
> But it would be good to support data with only 2 dimensions, which is more natural for 2d images.
> This came up in 2 different places now:
> 
> * Opening 2d data does not work here in [this PR](https://github.com/mobie/bigdataviewer-ome-zarr/pull/9) by @KateMoreva?
> * I am working on adding a Covid-IF example project. There it would be much easier to add the data as 2d.

Yes, I could not create a solution to open 2d files. There either IndexOutOfBoundExeptions or the pathName to the data contains more folders than needed due to the extra dimension in usedGridPosition.
Probably I add the singleton dimension in the wrong way.

**Comment by tischi** [comment]
I don't think SpimData can be 2D...

@NicoKiaru how do you open 2D images with with bdv-bf? Are you adding a singleton dimension somewhere to make the data appear 3D? Could you please point us to the code?

**Comment by constantinpape** [comment]
@tischi how are you doing it in the PlateViewer? The input data we have there is 2d!

**Comment by tischi** [comment]
I don't use `SpimData`, but directly construct my own `Source`, which internally is comprised of `RandomAccessibleInterval`s (`rai`) and there indeed I add a singleton dimension to make it `3D`:

```
rai = Views.addDimension( cachedCellImage.getRAI(), 0, 0);
```

**Comment by NicoKiaru** [comment]
> 
> 
> I don't think SpimData can be 2D...
> 
> @NicoKiaru how do you open 2D images with with bdv-bf? Are you adding a singleton dimension somewhere to make the data appear 3D? Could you please point us to the code?

Yes, I'm always adding a 3rd dimension, but it's done inside the image loader of spimdata object. Bdv always need a third dimension.

https://github.com/BIOP/bigdataviewer-bioformats/blob/9acc6c75f9c0d27dd41248c8857b2a6e5f39e94c/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvSourceUnsignedByte.java#L100-L102

**Comment by constantinpape** [comment]
Ok, so I guess we would also need to add an extra source for this?!

**Comment by tischi** [comment]
A `Source` just wraps 3D `RAI`s. I don't think we need an "extra" source.

If you provide me code to reproduce the 2D error then I will try to look into it.

**Comment by constantinpape** [comment]
> A `Source` just wraps 3D `RAI`s. I don't think we need an "extra" source.
> If you provide me code to reproduce the 2D error then I will try to look into it.

Ok. Could you please provide such an example after cleaning up https://github.com/mobie/bigdataviewer-ome-zarr/pull/9, @KateMoreva.

**Comment by KateMoreva** [comment]
> > A `Source` just wraps 3D `RAI`s. I don't think we need an "extra" source.
> > If you provide me code to reproduce the 2D error then I will try to look into it.
> 
> Ok. Could you please provide such an example after cleaning up [mobie/bigdataviewer-ome-zarr#9](https://github.com/mobie/bigdataviewer-ome-zarr/pull/9), @KateMoreva.

The current version opens the black image instead of 2d, because the reader is trying to find files in the non-existent directory. For example, It is looking for the path ./yx.ome.zarr/s0/0/1/1 when there is only ./yx.ome.zarr/s0/0/0

**Comment by tischi** [comment]
> Please use the command from https://github.com/KateMoreva/bigdataviewer-ome-zarr/tree/open_s3_command

Dear @KateMoreva I could not find the code to open from S3 without an XML. 
Could you please point me to it?

**Comment by constantinpape** [comment]
@tischi the link is in the comment above: https://s3.embl.de/i2k-2020/ngff-example-data/v0.3/yx.ome.zarr

**Comment by tischi** [comment]
OK, I tried this: "https://s3.embl.de/i2k-2020/ngff-example-data/v0.3/yx.ome.zarr"
Can I somehow see how the blocks are actually called within the zarr file?

**Comment by tischi** [comment]
I don't have to browse them myself, a screenshot would do...

**Comment by constantinpape** [comment]
```
pape@mokshi:~/Work/data/ngff/v0.3$ tree -R yx.ome.zarr/
yx.ome.zarr/
├── s0
│   ├── 0
│   │   ├── 0
│   │   ├── 1
│   │   ├── 2
│   │   └── 3
│   ├── 1
│   │   ├── 0
│   │   ├── 1
│   │   ├── 2
│   │   └── 3
│   ├── 2
│   │   ├── 0
│   │   ├── 1
│   │   ├── 2
│   │   └── 3
│   └── 3
│       ├── 0
│       ├── 1
│       ├── 2
│       └── 3
├── s1
│   ├── 0
│   │   ├── 0
│   │   └── 1
│   └── 1
│       ├── 0
│       └── 1
└── s2
    └── 0
        └── 0
```
All the data is also available on the EMBL share here: `/g/kreshuk/data/ngff/v0.3`

**Comment by tischi** [comment]
@KateMoreva 

There are a couple of issues, tackling them now (and tomorrow):

- [X] the `dataBlockIndices` (fka `usedGridPosition`) for a 2D image must only have 2 indices. They were [initialized](https://github.com/mobie/bigdataviewer-ome-zarr/blob/a48a5d5502f6c5003a50684c8e5390e855cc81d4/src/main/java/de/embl/cba/bdv/ome/zarr/loaders/N5OMEZarrImageLoader.java#L731) as `new long[3]` which yielded the wrong paths, i.e. one index to many (e.g., `0/0/0` instead of `0/0`)
- [X] the case `is2D = true` could never be reached because `is2D` was always `false`. I added something [here](https://github.com/mobie/bigdataviewer-ome-zarr/blob/a48a5d5502f6c5003a50684c8e5390e855cc81d4/src/main/java/de/embl/cba/bdv/ome/zarr/loaders/N5OMEZarrImageLoader.java#L171) to, if appropriate, set `is2D = true` 
- [ ] we are having some 2D to 3D dimension mismatch [here](https://github.com/mobie/bigdataviewer-ome-zarr/blob/a48a5d5502f6c5003a50684c8e5390e855cc81d4/src/main/java/de/embl/cba/bdv/ome/zarr/loaders/N5OMEZarrImageLoader.java#L626). Not sure yet what is going on. Will have a look tomorrow.

I made a branch to contain the fixes: https://github.com/mobie/bigdataviewer-ome-zarr/tree/open_s3_command

**Comment by KateMoreva** [comment]
> @KateMoreva
> 
> There are a couple of issues, tackling them now (and tomorrow):
> 
> * [x]  the `dataBlockIndices` (fka `usedGridPosition`) for a 2D image must only have 2 indices. They were [initialized](https://github.com/mobie/bigdataviewer-ome-zarr/blob/a48a5d5502f6c5003a50684c8e5390e855cc81d4/src/main/java/de/embl/cba/bdv/ome/zarr/loaders/N5OMEZarrImageLoader.java#L731) as `new long[3]` which yielded the wrong paths, i.e. one index to many (e.g., `0/0/0` instead of `0/0`)
> * [x]  the case `is2D = true` could never be reached because `is2D` was always `false`. I added something [here](https://github.com/mobie/bigdataviewer-ome-zarr/blob/a48a5d5502f6c5003a50684c8e5390e855cc81d4/src/main/java/de/embl/cba/bdv/ome/zarr/loaders/N5OMEZarrImageLoader.java#L171) to, if appropriate, set `is2D = true`
> * [ ]  we are having some 2D to 3D dimension mismatch [here](https://github.com/mobie/bigdataviewer-ome-zarr/blob/a48a5d5502f6c5003a50684c8e5390e855cc81d4/src/main/java/de/embl/cba/bdv/ome/zarr/loaders/N5OMEZarrImageLoader.java#L626). Not sure yet what is going on. Will have a look tomorrow.
> 
> I made a branch to contain the fixes: https://github.com/mobie/bigdataviewer-ome-zarr/tree/open_s3_command
Thank you! I got stack on the third point, as for points 1 and 2 they were left that way in order to avoid indexOutOfBound [here](https://github.com/mobie/bigdataviewer-ome-zarr/blob/a48a5d5502f6c5003a50684c8e5390e855cc81d4/src/main/java/de/embl/cba/bdv/ome/zarr/loaders/N5OMEZarrImageLoader.java#L626) and in other places.

**Comment by KateMoreva** [comment]
I think that `ArrayIndexOutOfBoundsException` in `createArray(N5OMEZarrImageLoader.java:630)` is coused becouse dataBlock arrays and cellDimentions have differnt dimensions.
Examples 
For 2D image:
![image](https://user-images.githubusercontent.com/48569608/122809445-cbdc9f80-d2d6-11eb-9828-e416617a281b.png)
For 4D image:
![image](https://user-images.githubusercontent.com/48569608/122809582-f62e5d00-d2d6-11eb-8af4-cfbd0293f08a.png)

**Comment by tischi** [comment]
> I can send all the changes that I tried before if you think that different dimensions of dataBlock arrays and cellDimentions could be the case.

Thanks, but let me have a look first!

**Comment by tischi** [comment]
Works now:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/2157566/122874431-46d3a380-d333-11eb-8633-d30196e4a00f.png">

The trick was to throw away the singleton dimension in the `createArray` function:

```
if ( is2D )
                cellDims = Arrays.stream( cellDims ).limit( 2 ).toArray();
```

Shall I merge my branch into something?

**Comment by KateMoreva** [comment]
> Works now:
> <img alt="image" width="640" src="https://user-images.githubusercontent.com/2157566/122874431-46d3a380-d333-11eb-8633-d30196e4a00f.png">
> 
> The trick was to throw away the singleton dimension in the `createArray` function:
> 
> ```
> if ( is2D )
>                 cellDims = Arrays.stream( cellDims ).limit( 2 ).toArray();
> ```
> 
> Shall I merge my branch into something?

Thank you a lot! 
I tried to throw away the singleton dimension earlier and thus faced problems.

**Comment by KateMoreva** [comment]
I'll try to open one more 2d file. If it works I think we should merge.

**Comment by tischi** [comment]
So I merge into master?

**Comment by KateMoreva** [comment]
> So I merge into master?

Yes. I think it is better to merge now. Thank you
