### ISSUE TITLE
Fix label_id as the first column in a table

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#312]
This is how a segmentation table looks for me now:
![Screenshot from 2021-06-21 09-24-19](https://user-images.githubusercontent.com/32451366/122723585-6e633700-d273-11eb-8125-bc2ece61fabd.png)

It seems the columns are sorted alphabetically? That is not too bad, but would be great to fix the 'label_id' as the first one

**Comment by constantinpape** [comment]
It looks like the ordering of columns changed from "as loaded from the tsvs" to "alphabetically". I think we should rather stick with "as loaded from the tsvs", if that is still possible in the current table model.
cc @K-Meech @tischi

**Comment by tischi** [comment]
>  I think we should rather stick with "as loaded from the tsvs"

Done via https://github.com/tischi/imagej-utils/commit/0b98b83f11ed63cabc08df7f5837296e372b5b1e
