### ISSUE TITLE
Add source dropdown (in project creator) doesn't respond to mouse actions

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#314]
@martinschorb I split this into a separate issue to keep track.

The add source dropdown doesn't respond to mouse actions. It does respond to using arrows on the keyboard.

This works on Windows, but not on Mac.

**Comment by K-Meech** [comment]
@yanschwab - could you also try this on your mac? (I'm trying to figure out if it's mac specific, or something else)

- Create a mobie project
- add a dataset
- click the 'add' button on the sources row
- does clicking the dropdown work?

**Comment by K-Meech** [comment]
This happens on yannnick's mac too - so it definitely looks like a mac specific problem. I'll look into it.

**Comment by K-Meech** [comment]
@tischi Could you maybe look into this? It seems to be a mac specific problem, so it's really hard to debug on my PC. You have a mac right?

**Comment by tischi** [comment]
I think the issue is that `setMoBIESwingLookAndFeel();` for some reason does not work well together with the `GenericDialog`. Thus, either (a) don't use the `setMoBIESwingLookAndFeel();` during the project creation or (b) don't use `GenericDialog`. I would vote for (a) to be on the safe side.

**Comment by K-Meech** [comment]
This should be fixed in the current master

**Comment by K-Meech** [comment]
This might still be an issue. Another mac user just reported this.
@tischi - could you maybe check this on your mac? You'd just need to open the project creator, click 'add' on the source row, and tell me if the dropdown menu responds or not.

**Comment by K-Meech** [comment]
@tischi Could you check this if you have time? (see above comment) Thanks!

**Comment by tischi** [comment]
Looks good:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/2157566/163403492-382e7d67-fdb0-4a9e-9330-5821ca7cb3d1.png">
