### ISSUE TITLE
Error opening project made with project creator

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#315]
@martinschorb I split this into another issue to keep track.

It seems that Create new MoBIE dataset creates the additional "dataset" subfolder, while MoBIE looks for the files in the top directory.
```
java.io.FileNotFoundException: /Users/schorb/code/mobie-multiview/test0001/data/project.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
```
while the project JSON is:
```
/Users/schorb/code/mobie-multiview/test0001/Testcrop1/data/project.json
```

**Comment by K-Meech** [comment]
@martinschorb Which filepath did you give to 'Open MoBIE Project...'?

**Comment by martinschorb** [comment]
That's `.../test0001`

**Comment by K-Meech** [comment]
Ah ok - this is something that changed from the last version.
When you ```Create new MoBIE project...```  you give a project name (for you - "Testcrop1"), and a folder to save that project in (for you ''/Users/schorb/code/mobie-multiview/test0001/''). This then creates a project of that name within that folder.

So, to open this you have to give the path ```/Users/schorb/code/mobie-multiview/test0001/Testcrop1``` not  ```/Users/schorb/code/mobie-multiview/test0001/```
