### ISSUE TITLE
Shortcut 'Change random coloring seed' doesn't work 

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#316]
It works if I right click and select 'Change random coloring seed' in the menu, but neither Ctrl-L nor Ctrl-Shift-L don't work for me. 
I'm on Ubuntu 18.04.5 LTS

**Comment by constantinpape** [comment]
I think we decided to deprecate most of the short cuts and just have this functionality in the context menu, to avoid having to maintain and document both. Correct me if I am wrong about this particular one, @tischi @K-Meech.

**Comment by vzinche** [comment]
Why not the other way around? Keep the shortcuts and deprecate the context menu? 
Imho, going through random colors from the context menu is *incredibly* annoying.

**Comment by K-Meech** [comment]
We decided to keep the ctrl+l shortcut and ctrl+shift+N shortcuts - see here: https://github.com/mobie/mobie-viewer-fiji/issues/242 So this is a bug.

**Comment by tischi** [comment]
The shortcuts that are mentioned should work => 🐛
