### ISSUE TITLE
BDV Screenshot - why did it stop suggesting pixel size?

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#317]
In the previous version it used to suggest you pixel size (based on your screen size?). So just using the default option always returned you a screenshot equal in size to your bdv window. Now it just suggests 1 by default

**Comment by tischi** [comment]
We are using now the `ScreenShotMakerCommand` from another repository.

@NicoKiaru I guess suggesting default values based on the current size of one pixel in the BDV window is tricky when using the SciJava Commands? Could this be done by some `Preprocessor`?

**Comment by NicoKiaru** [comment]
You can try with "initialiser", it may work. Alternatively, a button with a callback that fills in the pixel size will surely work.

**Comment by tischi** [comment]
Thanks! I think the button is a great idea, because I would be afraid that _the initializer overwrites the persist values_, which would be annoying... do you know how that works?

**Comment by NicoKiaru** [comment]
No idea... I'd go for trial and errors

**Comment by vzinche** [comment]
@tischi, where did the screenshot option disappear? I can't seem to find it all now

**Comment by tischi** [comment]
@vzinche should work now again (available once we pushed to MoBIE beta)

**Comment by constantinpape** [comment]
This is fixed.
