### ISSUE TITLE
Segmentations without table

### ISSUE THREAD

**Issue by jhennies** [mobie/mobie-viewer-fiji#321]
Hi @constantinpape and @tischi,

I am currently switching to the Mobie beta (Mobie-2.0.0) and converting my code using https://github.com/mobie/mobie-utils-python/pull/21.

Again (as in #296 ) I'm trying to use a segmentation without supplying a table for it. 

Is this currently supported? 
I can generate the project like this using mobie-utils (but am also not 100% sure if I did everything corretly). The result is a mobie project without any table information in the dataset.json (see below).

When I try to load the project into Mobie, the raw data works just fine. However when adding the segmentation it gives me this error: 
```
Exception in thread "Thread-110" java.lang.NullPointerException
	at de.embl.cba.mobie.view.ViewerManager.fetchSegmentsFromTables(ViewerManager.java:313)
	at de.embl.cba.mobie.view.ViewerManager.showSegmentationDisplay(ViewerManager.java:269)
	at de.embl.cba.mobie.view.ViewerManager.showSourceDisplay(ViewerManager.java:205)
	at de.embl.cba.mobie.view.ViewerManager.show(ViewerManager.java:167)
	at de.embl.cba.mobie.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:446)
	at java.lang.Thread.run(Thread.java:748)
```

I guess it's trying to fetch a table, looking closer at the error message, so it probably answers the question of whether it's supported... 
Could it be supported though?

PS: the dataset.json:
```
{
  "is2D": false,
  "sources": {
    "em-seg": {
      "segmentation": {
        "imageData": {
          "bdv.n5": {
            "relativePath": "images/bdv-n5/em-seg.xml"
          }
        }
      }
    },
    "em-raw": {
      "image": {
        "imageData": {
          "bdv.n5": {
            "relativePath": "images/bdv-n5/em-raw.xml"
          }
        }
      }
    }
  },
  "timepoints": 1,
  "views": {
    "default": {
      "isExclusive": false,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "em-raw",
            "opacity": 1.0,
            "sources": [
              "em-raw"
            ]
          }
        }
      ],
      "uiSelectionGroup": "bookmark"
    },
    "em-seg": {
      "isExclusive": false,
      "sourceDisplays": [
        {
          "segmentationDisplay": {
            "lut": "glasbey",
            "name": "em-seg",
            "opacity": 0.5,
            "sources": [
              "em-seg"
            ]
          }
        }
      ],
      "uiSelectionGroup": "segmentations"
    },
    "em-raw": {
      "isExclusive": false,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "em-raw",
            "opacity": 1.0,
            "sources": [
              "em-raw"
            ]
          }
        }
      ],
      "uiSelectionGroup": "images"
    }
  }
}
```

**Comment by constantinpape** [comment]
Yes, we def. want to support this, and it's also supported in the specification. But indeed the error you support indicates that it's not working in the viewer now.
I think the best way for us to work on it is if you can put this example data somewhere we can access is (emcf share would be good as both @tischi and me have access to it).

Also, to make sure the project is valid (according to the specification), you can run the python validator. If you install `mobie-utils-python` (e.g. via `pip install -e .`) it's available on the command line:
```
$ mobie.validate_project -i /path/to/proj
```

**Comment by jhennies** [comment]
Thanks @constantinpape! 
I'll make a small example project that reproduces the issue and that is small enough such that I can easily upload it. 
Will let you know where it is when it's there.

**Comment by jhennies** [comment]
The example can be found here:
/g/emcf/hennies/for_constantin/mobie_no_table_test/

To get around this issue https://github.com/mobie/mobie-utils-python/issues/25, I commented the respective assertion out and manually corrected the source xmls.

The validation (after commenting the assertion back in)
```
from mobie.validation import validate_project
validate_project('/data/tmp/mobie_no_table_test/data')
```
 then succeeds:
```
The project at /data/tmp/mobie_no_table_test/data is a valid MoBIE project.
```

**Comment by constantinpape** [comment]
> The example can be found here:
> /g/emcf/hennies/for_constantin/mobie_no_table_test/

@tischi once you have time could you try to make the viewer work without table for Julian's example?

**Comment by tischi** [comment]
@jhennies @constantinpape 
Does that look correct?
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/2157566/123233993-d9627700-d4da-11eb-8617-4bafb806e4c0.png">

**Comment by jhennies** [comment]
Yes, perfect! It was just a toy example, so the segmentation does not make any sense ;)

**Comment by tischi** [comment]
@K-Meech Upload this fix to MoBIE-beta, when you feel like it.

**Comment by K-Meech** [comment]
@jhennies @tischi This fix is on MoBIE-beta now.

**Comment by K-Meech** [comment]
@tischi General question on this. 
At the moment, I'm uploading by changing the 'scijava.app.directory' line to my Fiji, mvn clean install, and then uploading to the update site. When I do this though, I see that a lot of jars that come from the Java-8 update site have modified versions. Isn't the ```pom-scijava``` supposed to mean we are using the same versions of everything as ImageJ? Or does this pom lag behind what is actually in imageJ?

**Comment by tischi** [comment]
> When I do this though, I see that a lot of jars that come from the Java-8 update site have modified versions. Isn't the pom-scijava supposed to mean we are using the same versions of everything as ImageJ? Or does this pom lag behind what is actually in imageJ?

Excellent observation. Unfortunately the scijava parent pom does not include the versions shipped with the Java8 update site. And currently there is no way known to me to specify those versions in a convenient way in a pom. I had a longer discussion about this with @ctrueden on gitter; Curtis and @hinerm were going to look into it, but I am not sure there is a solution just yet?
