### ISSUE TITLE
Support changing the resolution of objects shown in the 3d

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#323]
In the old mobie, there was an option in the context menu to change the resolution of the 3D objects. (and also to read it from this view parameter - https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json#L61)

This is not yet supported in the new mobie.

**Comment by K-Meech** [comment]
@tischi Could you also look at this one if you had time? I'm trying to show a lot of segments in the 3d viewer, so it'd be great to be able to reduce the resolution here.

**Comment by K-Meech** [comment]
Also, just to note, this isn't exactly the same as it was in the old MoBIE. We agreed here (https://github.com/mobie/mobie.github.io/issues/2#issuecomment-803969585) to make resolution3dView an array of resolutions [x_resolution, y_resolution, z_resolution], rather than the single double that it was previously.

**Comment by tischi** [comment]
Should I then choose the resolution level where the voxel spacing is less than or equal to the requested in all dimensions?

**Comment by K-Meech** [comment]
Yes - sounds good!

**Comment by tischi** [comment]
I do it now slightly more conservative: I pick the level where the spacings are equal to or larger than the requested.

**Comment by tischi** [comment]
Works now, one can change, the resolution.

New feature: It will only do this for the segmentation sources that are under the mouse in BDV when right clicking to get the context menu.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/2157566/124709555-e41a0480-defb-11eb-8553-d40b71c502f8.png">

**Comment by K-Meech** [comment]
Thanks @tischi! Just re-opening for some minor issues I found while using this:
- currently, updating the resolution via the context menu does not update the resolution of meshes already shown in the 3D viewer
- if you provide a resolution that is too low, then it errors because there are no voxels left for that segmentation. It would be nice to  provide some message asking people to try a higher resolution.

**Comment by tischi** [comment]
> currently, updating the resolution via the context menu does not update the resolution of meshes already shown in the 3D viewer

I am not sure we always want this... maybe some people want to show certain meshes with higher resolution?
Maybe a checkbox: redraw all segments?

> if you provide a resolution that is too low, then it errors because there are no voxels left for that segmentation. It would be nice to provide some message asking people to try a higher resolution.

Do you have an example for this? I don't think I have ever seen this error.

**Comment by K-Meech** [comment]
A checkbox sounds like a good plan! 

You can get this error by e.g. 
- open the platy dataset, and add the cell segmentation. 
- Configure the voxel size to 10x10x10
- Select a segment
- Click the v checkbox

You get the message below. Where it might be good to ask people to try a higher resolution.
![Screenshot (311)](https://user-images.githubusercontent.com/24316371/124776982-cc607180-df37-11eb-8d0b-af5d33f52129.png)

**Comment by tischi** [comment]
Interesting!
The lowest magnification label maps may not have all the labels anymore!
I will work on this.

**Comment by constantinpape** [comment]
@tischi @K-Meech  Is this fixed by #538 now and can be closed?

**Comment by K-Meech** [comment]
Yes this is fixed now and can be closed.
