### ISSUE TITLE
Transforms specified in bookmarks bet ignored (Beta)

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#325]
Hi,

it seems that the current beta does not apply any transforms specified in bookmarks.

Check Constantin's example project:

`/g/emcf/pape/mobie-test-projects`

bookmark2 should be rotated by 90 degrees.

**Comment by constantinpape** [comment]
Thanks for reporting, @martinschorb. We will double check. (Note to myself update the yeast project so that this can be easily checked.)

**Comment by tischi** [comment]
@martinschorb 

`/g/emcf/pape/mobie-test-projects/data/croptest1/dataset.json` specifies no rotation for crop-bookmark2, does it?
```
    "crop-bookmark2": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "image-group-0",
            "opacity": 1.0,
            "sources": [
              "covidtomo"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "crop": {
            "max": [
              1.8,
              1.35,
              0.2
            ],
            "min": [
              0.55,
              1.05,
              0.0
            ],
            "shiftToOrigin": false,
            "sourceNamesAfterTransform": [
              "covidtomo-cropped2"
            ],
            "sources": [
              "covidtomo"
            ]
          }
        }
      ],
```

**Comment by constantinpape** [comment]
@tischi I made a new branch for the yeast project https://github.com/mobie/yeast-clem-datasets/tree/move-trafo.
I have moved out the translation into the source transforms there. (As usual with affines there is multiple ways of doing this, so it might be that the trafo is not correct now, but at least you can check if it's actually being read from the json.)

**Comment by martinschorb** [comment]
> `/g/emcf/pape/mobie-test-projects/data/croptest1/dataset.json` specifies no rotation for crop-bookmark2, does it?

I duplicated the dataset to `croptest2` to test the transforms. There bookmark2 contains the affine

**Comment by tischi** [comment]
@martinschorb I am astonished that you can open this dataset. For me it crashes, because this is _not_ a `relativePath`, but rather an absolute path, which we currently do not support (cc @constantinpape).

`cat /g/emcf/pape/mobie-test-projects/data/croptest2/dataset.json`

```
 "is2D": false,
  "sources": {
    "covidtomo": {
      "image": {
        "imageData": {
          "bdv.n5": {
            "relativePath": "/Users/schorb/code/mobie-multiview/_KM140520_Grid3_c154.xml"
          }
        }
      }
    }
  },
```

**Comment by constantinpape** [comment]
I don't know where the abs path is coming from; def. not from my python tools.

**Comment by martinschorb** [comment]
I did that manually to check whether the transform issue comes from python tools or MoBIE.

**Comment by tischi** [comment]
@martinschorb  And you can open this with MoBIE-beta? I cannot... and it should not work...
@constantinpape do we want to add support for an `absolutePath` to the spec (I think we do not have this already, do we)?

**Comment by constantinpape** [comment]
> @constantinpape do we want to add support for an `absolutePath` to the spec (I think we do not have this already, do we)?

No, we don't support this right now and I don't think we should.

**Comment by martinschorb** [comment]
OK, I now changed it to a relative path. In fact it did not work for me either when the data sits on a network share.
It still looks like there is no transform applied for the second bookmark.

**Comment by tischi** [comment]
Thanks! I will try to look at it, but there's the EMBO course this week.....

**Comment by martinschorb** [comment]
OK, I think I found out what is happening:

It is a general BDV behaviour and not due to some MoBIE-specific problem.
I have tried to pass the trafo to BDV using the XML and it behaves exactly the same.

When there's only a single source (or apparently also `view`), BDV will adjust its viewer axes to that source, no matter what its trafo says. This means the `Shift+X/Y/Z` commands and also the initial viewer orientation is orthogonal to the source **independent of its trafo**.

So what we need to achieve with `bookmarks` or `views` is to change that behaviour in the viewer. I guess this worked before with the spec1 bookmarks. But the new logic seems to append/apply the additional transformation to the source instead of directing the viewer.

**Comment by martinschorb** [comment]
![Screenshot 2021-07-01 at 08 27 40](https://user-images.githubusercontent.com/35071867/124077028-4b8d0b80-da47-11eb-941d-b308f9ff4ae5.png)

Left is original orientation (in accordance to viewer XYZ), right is transformed source. The only difference you can see are the coordinate associations inside BDV. The viewer orientation is locked to the source.

**Comment by martinschorb** [comment]
So a `view` or `bookmark` in a multi-source (or multi-`view`) scenario needs to bake that extra trafo to the source while leaving the viewer bound to the physical coordinates.

**Comment by constantinpape** [comment]
Thanks for looking into this, @martinschorb. I think that this is not actually a bug though:

> When there's only a single source (or apparently also `view`), BDV will adjust its viewer axes to that source, no matter what its trafo says. This means the `Shift+X/Y/Z` commands and also the initial viewer orientation is orthogonal to the source **independent of its trafo**.

Yes, that is the expected behaviour. `sourceTransforms` only change the transformations applied to the source and do not specify the viewer transform, so if the viewer transform is not given BDV will use some default (heuristic) viewer transform.
I.e. the `sourceTransforms` are there to specify the correct transformations of sources **relative** to each other.

If you want to enforce a specific viewer transformation, you can use the `viewerTransform` field in the `view`. It can be specified in addition to `sourceTransforms`; so for your use case I assume it would be sufficient to set the viewer transform to the identity to prevent bdv from going to the default view.

**Comment by martinschorb** [comment]
OK, I think this was a conceptual mixup with the `viewerTransform`.
