### ISSUE TITLE
Segment selection colouring mode

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#332]
In the old MoBIE, there was a context menu option to change the segment selection colouring mode e.g. to show selected segments in yellow only, to dim the non-selected segments etc.

This still needs to be migrated to MoBIE2.

**Comment by K-Meech** [comment]
@tischi Would you have time to look at this? This would be very useful for making figures :)

**Comment by tischi** [comment]
This is already there, is it?
`Change opacity of non-selected segments`

**Comment by tischi** [comment]
Then I think the only thing that is missing is whether the color of the selected objects should their normal color or whether you would like all of them to have one specific color, is it?

**Comment by K-Meech** [comment]
Yes - that's right. It'd be useful to be able to show selected segments all in one colour.

**Comment by tischi** [comment]
OK! 

While Implementing this I will get rid of this:
```
private SelectionColoringMode selectionColoringMode;
```
Because I think we just need the `opacityNotSelected` and `selectionColor` variables to full specify the rendering.

**Comment by tischi** [comment]
If `selectionColor` is `null` the selected segments will have their normal color.
