### ISSUE TITLE
Segment selection based on table values

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#337]
It would be very useful to be able to make selections based on the table. e.g. For a particular column, select:

- segments with a particular value
- segments with a value greater than some value
- segments with a value smaller than some value

**Comment by tischi** [comment]
Code like this could be a starting point: https://www.tutorialspoint.com/how-can-we-filter-a-jtable-in-java

But maybe one finds even better examples with more googling..

**Comment by constantinpape** [comment]
See also discussions in #65

**Comment by K-Meech** [comment]
I'll have a look at this, and see how difficult it is to implement.

**Comment by K-Meech** [comment]
Ok - this works now! I'll make a PR soon :)
I've added this as options to the 'select' table menu e.g. see below for selecting all of gene cluster 11 (muscles)
![Screenshot (310)](https://user-images.githubusercontent.com/24316371/124773886-43483b00-df35-11eb-9fb1-dac7dda92a91.png)

**Comment by constantinpape** [comment]
This is so nice! Will this already work for image tables? (This will be amazing for the covid-if example where we could use the selection feature to show positive / negative results)

**Comment by K-Meech** [comment]
I don't think it works for image tables yet - but should be an easy fix! Once you have the project set up, we can get it working for that too.

**Comment by tischi** [comment]
> I don't think it works for image tables yet 

Why not? Isn't that the same as object tables?

**Comment by K-Meech** [comment]
I just tried it out on one of the zebrafish grid views. Selecting rows in the table works (here I just selected everything with a grid id> 5), but this is not reflected in the viewer.
I think this is more of a general issue that, at the moment, selecting rows in a grid view table moves to that position but doesn't do any of the other things selecting a segment normally does e.g. dimming the other segments / supporting different opacities and colours for selected objects etc. @tischi I don't know how hard this would be to add? Ideally, the scatter plot would also be supported for grid tables.

![Screenshot (319)](https://user-images.githubusercontent.com/24316371/124886836-86a1b880-dfcc-11eb-97eb-26e8c8cd6a75.png)

**Comment by tischi** [comment]
@K-Meech Did you try to just move the view a bit in BDV? Maybe there just is a repaint call missing somewhere?

**Comment by tischi** [comment]
Just tried it myself and that's not the case. I will look into it now.

**Comment by constantinpape** [comment]
> Ideally, the scatter plot would also be supported for grid tables.

Yes, scatterplot would be awesome to have as well!

**Comment by tischi** [comment]
Found the bug. Below lines of code were missing in the `ListItemsARGBConverter`:

```
final int alpha = ARGBType.alpha( color.get() );
color.mul( alpha / 255.0 );
```

**Comment by tischi** [comment]
Fixed via https://github.com/mobie/mobie-viewer-fiji/commit/d03aadc4c4ee5e5b6345610fc4c13bf0c388a718

**Comment by constantinpape** [comment]
> Found the bug.

Do scatter plots also work then?

**Comment by tischi** [comment]
> Do scatter plots also work then?

No, this is more work.

**Comment by constantinpape** [comment]
> No, this is more work.

Ok, I think this would also be great to have for the covid plate.

**Comment by K-Meech** [comment]
I'll make a separate issue for the grid view scatter plots and close this one
