### ISSUE TITLE
Blending modes

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#338]
I implemented a hack where plain zero voxel values are indicating the absence of a source.

This allows below visualisation, where both tomograms are with an `averageOccluding` blending mode:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2157566/124604657-70301b80-de6b-11eb-8341-8e2e480c9b68.png">

It would be better to find out where a source ends in another way then checking for a zero pixel value.

How should we handle label images in such a setting?
I guess they should never be occluded? @martinschorb 

@constantinpape could you add a label image to this branch of the yeast data set?
https://github.com/mobie/yeast-clem-datasets/tree/spec-v2-blending-modes

**Comment by constantinpape** [comment]
> This allows below visualisation, where both tomograms are with an `averageOccluding` blending mode:

This looks awesome!

> It would be better to find out where a source ends in another way then checking for a zero pixel value.

I am also not sure what would be a better solution here.



> @constantinpape could you add a label image to this branch of the yeast data set?
> https://github.com/mobie/yeast-clem-datasets/tree/spec-v2-blending-modes

Done, I have added "em-segmentation" to the dataset.

**Comment by martinschorb** [comment]
> I implemented a hack where plain zero voxel values are indicating the absence of a source.

Could MoBIE issue a warning when signed-type sources are detected? Otherwise there will be transparent patches in a source that will look funny...

**Comment by tischi** [comment]
> Could MoBIE issue a warning when signed-type sources are detected?

I am not even sure whether we are supporting signed type sources at all? Do you have such data for testing?

**Comment by tischi** [comment]
@constantinpape as expected also the segmentation layer is occluded right now:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2157566/124711319-38be7f00-defe-11eb-8a94-8a4bce512878.png">

Would that ever be useful? Or should I (for now) try to just hard-code that label masks are never occluded?

**Comment by tischi** [comment]
Right now the two tomograms are averaged and they are occluding the overview EM. 

<img width="280" alt="image" src="https://user-images.githubusercontent.com/2157566/124714473-1a5a8280-df02-11eb-84a3-58a88f0e7a24.png">

I am wondering: is this it a re use-case that the occluding layer contains several images that should be averaged?

I am asking, because I just realized that I have a handle on the sequence in which the user adds the sources to the BDV. Thus I _think_ I could implement a logic that an `occluding` image occludes **only all** the images that were added **before** that image, but images that were added later would not be occluded. That feels useful to me, because I think the tomograms should occlude the low res EM, but it should be possible to have the fluorescence image (and segmentations) on top; and I don't think we could achieve this with the current logic.

**Comment by constantinpape** [comment]
> @constantinpape as expected also the segmentation layer is occluded right now:
> Would that ever be useful? Or should I (for now) try to just hard-code that label masks are never occluded?

I am not sure if occluding the label masks would ever be useful. But I would not mind adding `blendingMode` to `segmentationDisplays` as well, in case someone has a use-case for this; we should just default to the option without occlusion.

> That feels useful to me, because I think the tomograms should occlude the overview EM and the high-res tomogram should occlude the low-res tomogram, but it should be possible to have the fluorescence image (and segmentations) on top;

That makes sense. Do we need to change something in the spec to enable this?

**Comment by martinschorb** [comment]
> is it a relevant use-case that the occluding layer contains several images that should be averaged?

Yes, in CLEM, you would be interested in the high-mag EM image plus the fluorescence overlay.

**Comment by martinschorb** [comment]
Although that would be 'sum' at least for the fluorescence sources.

**Comment by tischi** [comment]
@constantinpape I just discussed in person with @martinschorb and we concluded that my proposal should be good and that we can even now limit the choices to `sum` and `sumOccluding` and can get rid of the averages.

**Comment by constantinpape** [comment]
> my proposal should be good and that we can even now limit the choices to `sum` and `sumOccluding` and can get rid of the averages.

Ok, works for me. Do we need any changes in the spec now (other than removing the average modes?)

**Comment by tischi** [comment]
No other changes required.  

It works 🥳  and I find it awesome (note how the high-res tomogram is occluding the low-res and how the segmentation layer is on top)! 

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/2157566/124732963-04ee5400-df14-11eb-924d-e85d95ead23a.png">

Same view, but with the low-mag tomogram toggled off:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/2157566/124733024-16cff700-df14-11eb-9e6e-9b10d3700381.png">

**Comment by tischi** [comment]
How should we do it in the UI?

Add for each source a checkbox with a small `o` for occluding?

<img width="618" alt="image" src="https://user-images.githubusercontent.com/2157566/124735589-74fdd980-df16-11eb-8144-ad272be43c65.png">

**Comment by constantinpape** [comment]
> No other changes required.

Ok, just to make sure we now have `blendingModes: [sum, sumOccluding]` for both `imageDisplay` and `segmentationDisplay`. 

> Add for each source a checkbox with a small `o` for occluding?

Sounds good, but in the example screenshot you posted it's not a checkbox?!

**Comment by tischi** [comment]
> but in the example screenshot you posted it's not a checkbox?!

not yet, I just posted it there for reference to see how it looks right now. 
The `[ O ]` button is for opacity...

**Comment by constantinpape** [comment]
> The `[ O ]` button is for opacity...

okay, makes sense.

**Comment by constantinpape** [comment]
I updated the spec now (remove average blending modes, add blending modes to segmentation).
We also found in the meeting that blending modes can be set via the context menu already and decided to not add it to the MoBIE GUI for now.
@tischi I will close this issue for now, just reopen if necessary.

**Comment by tischi** [comment]
there is a  context menu for now.
