### ISSUE TITLE
LAF

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#341]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/2157566/124759749-4a207f00-df30-11eb-9691-1d8eb084ad9e.png">

cc @K-Meech

**Comment by K-Meech** [comment]
@tischi I'm fixing the various laf issues at the moment.
Could you check what the default laf is on a mac? On windows, swing opens by default with the 'Metal' laf, which is the ```crossPlatformLookAndFeel```, rather than the ```systemLookAndFeel```

**Comment by tischi** [comment]
Do you have a java command for me how to find this out?

**Comment by K-Meech** [comment]
I think I've sorted this now - so no worries. I'll make a PR soon, then it'd be great if you could test on mac
