### ISSUE TITLE
Image selection for grid views

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#344]
Split discussion of grid view image selection from https://github.com/mobie/mobie-viewer-fiji/issues/337

Selection of images in a grid view, doesn't currently support all the features available for segmentations. e.g.
- selecting images by ctrl + left click in viewer
- shuffling colours with ctrl + L
- deselecting images with ctrl+shift+N
- changing opacity of non-selected images with ```configure opacity of non-selected segments```
- changing colour of selected images with ```configure colouring of selected segments```

@tischi @constantinpape Do we want to support these features for images too? It becomes a bit complicated when you are also showing segmentations in a grid view though...

**Comment by tischi** [comment]
I am not sure either...

For the context menu we could make the text more generic, e.g. `Configure non-selected image regions opacity` and then somehow figure out what is currently shown under the mouse cursor. 

For the keyboard shortcuts I don't know...

**Comment by K-Meech** [comment]
Resurrecting this issue, as more people in the lab are starting to use grids. @tischi - How about moving some of these features also to the menu at the top of the table? e.g. shuffling colours, deselecting images, and so on... Then this makes it easy to know which set of tabular data is being referred to if e.g. you are showing segmentations + grids at the same time

**Comment by constantinpape** [comment]
@K-Meech do you think @KateMoreva's work of creating grids from the UI in #416 is relevant here?

**Comment by K-Meech** [comment]
@KateMoreva's work will be super useful for making grids! But this issue is more about after you have your grid + grid table set up - how can you interact with it in mobie? A lot of the stuff we support for segmentations right now like shuffling the colours etc.. isn't yet supported for sourceAnnotationDisplay + its table.

**Comment by KateMoreva** [comment]
Let's divide this into tasks and implement them, then. :)

**Comment by KateMoreva** [comment]
What are the most needed functions?

**Comment by K-Meech** [comment]
Ideally all of them ;) But I think most urgent is probably being able to shuffle the colours, and to deselect all images. I think all of the points raised in the top of the issue (apart from being able to select images with ctrl + left click in the viewer) could be solved by adding entries to the table menu. E.g. under Select add 'Select None' and under Color add 'Shuffle Colours' or something  like that...

**Comment by tischi** [comment]
I think this all works now.
