### ISSUE TITLE
UI inconsistency in annotation dialog

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#353]
The annotation dialogs also suffer from the Mac gaphics issues. (see #314)

It even changed in the middle of using it from looking good to being weird...

![Screenshot 2021-07-15 at 12 52 43](https://user-images.githubusercontent.com/35071867/125777115-8f6d1113-9b76-4f92-9fc4-885016c627f5.png)

After this, all categories looked like the lowest one and also the dropdowns in the menus became unresponsive.

**Comment by K-Meech** [comment]
Thanks for reporting @martinschorb - I will try to fix all these mac display issues today

**Comment by K-Meech** [comment]
This is fixed on the current master.
