### ISSUE TITLE
Loading a table throws an exception

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#354]
Loading the [attached table](https://github.com/mobie/mobie-viewer-fiji/files/6822697/clust_spectral_l2_emb80_fmaps48_4_text_ps4_onlynucl_emb80_cntrs_1_nonucl_emb80_cntrs_3_w_pointcontr0611_n20.csv) throws the following error, but still loads the table. This didn't happen in the previous Mobie versions
![Screenshot from 2021-07-15 13-20-40](https://user-images.githubusercontent.com/32451366/125780450-260061fc-21af-48cb-91dd-55c427dafdf2.png)

**Comment by vzinche** [comment]
I am loading this table from my FileSystem to the default cell table

**Comment by constantinpape** [comment]
It works for me on latest MoBIE-beta, so I think the issue is fixed:

![Screenshot from 2021-08-12 11-05-34](https://user-images.githubusercontent.com/4263537/129170107-2e9885bc-b282-4ce9-814a-f42259667d36.png)
