### ISSUE TITLE
Support manual transformation of sources in bdv

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#363]
In normal BDV, sources can be transformed via the top BDV window menu (Tools > Manual Transform). Then, moving in the bdv window transforms the active source.

In the current MoBIE-beta, this does not work:
- all displayed sources move together when you manually transform (i.e. you can't move only one source)
- when you click 'Manual Transform' again to disable it, it resets any transforms you did

cc @tischi @constantinpape

**Comment by tischi** [comment]
I fixed this by adding the the right click menu command for manual source transformation from bdv-playground.
@NicoKiaru, could you please point us to the documentation, if you have some?

**Comment by NicoKiaru** [comment]
Unfortunately, there's no documentation... It's working like the Manual Transform tool except that you are in the referential of the moving source instead of the fixed source.

**Comment by tischi** [comment]
@NicoKiaru  And what's the difference between mutate and append?

**Comment by NicoKiaru** [comment]
For an AbstractSpimSource, there's a model which stores a chain of transforms M0, M1 ... Mi:

M = M0.M1.M2.M3

In mutate you do : M3' = M3.M' ( and thus M = M0.M1.M2.M3' )

In append you do M = M0.M1.M2.M3.M' ( the last transformation is stored in the model )

You have different behaviour depending on the underlying Source ( Transformed, Warped, etc), all is done in this class:

https://github.com/bigdataviewer/bigdataviewer-playground/blob/44355493b13f1df3fb04b18cb89de6da4bf3f20b/src/main/java/sc/fiji/bdvpg/sourceandconverter/transform/SourceTransformHelper.java

**Comment by tischi** [comment]
Currently we do not care about the SpimSource, because we serialize differently.
In our case we are dealing currently with TransformedSource.
I would like to hard code this choice for the user in MoBIE.
What do you think is the better option? does it matter?

**Comment by NicoKiaru** [comment]
For transformed sources, you can either keep one transformed source and concatenate the new transformed into the one contained in transformed source:

M <- M x M'

Or keep a chain of Transformed Source to hold all steps

https://github.com/bigdataviewer/bigdataviewer-playground/blob/44355493b13f1df3fb04b18cb89de6da4bf3f20b/src/main/java/sc/fiji/bdvpg/sourceandconverter/transform/SourceTransformHelper.java#L69-L72

That's up to you!

**Comment by tischi** [comment]
OK I think I get it now

- mutate: keep one transformed source and concatenate the new transform into the one contained in transformed source
- append: have a chain of TransformedSource to hold all steps

@K-Meech @martinschorb what do you think we should do? I am not sure: for serialization mutate would be easier (and the JSON would look simpler) but we would loose the "history" of the transformations.

**Comment by K-Meech** [comment]
I think it'd be nice to maintain at least some of the steps - e.g. if you already have an ```affine``` in your ```sourceTransforms``` which came from some registration program, it'd be useful if saving a view with a manual transform too didn't overwrite this completely.  

I don't know how hard this would be, but maybe you could have one chain of Transformed source, but then mutate? i.e. all the ```sourceTransforms``` from the json are applied to make a Transformed source, then this is wrapped in another transformed source. All manual transforms are applied here (with mutate), so that if you do a series of small manual transforms, you still end up with one affine at the end, and not loads of them.

Then, when you save a view, you get a ```sourceTransforms``` with all the original affine transforms + a new one that contains the result of all the manual transforms.

Would that work??

**Comment by tischi** [comment]
I have the feeling that if we do "append" then you we do whatever we like during the serialization. Whereas if we do "mutate" that information would be lost. So, maybe the only reason right now to do "mutate" could be visualization performance, but my feeling is that this does not matter for us.

Maybe I just leave the choice for now and you could experiment what you get when you try to serialize? I would expect that for "append" you should be getting `TransformedSource( TransformedSource( TransformedSource( ... )))`.

Do you want to give it a try?

**Comment by K-Meech** [comment]
Sure! I'll give it a go, probably next week :)

**Comment by constantinpape** [comment]
@K-Meech what's the status on this? Did you give it a try?

**Comment by K-Meech** [comment]
I haven't tried this yet! I might have some time tomorrow, otherwise it will have to be after my week off :)

**Comment by tischi** [comment]
I tried with "append" and I got this error:

```
Cannot append a transformation to a source of class : TransformedSource
You can try 'mutate' or wrap as transformed Source
```

@NicoKiaru Do you have an idea why this happens?

**Comment by NicoKiaru** [comment]
You cannot append a transformation to a `TransformedSource` because a `TransformedSource` can only hold a single affine transform, and not several ones. You can mutate it: M <- M.M' or you can create another TransformedSource which transform your previous `TransformedSource` (wrap), but you cannot append it.

**Comment by tischi** [comment]
@NicoKiaru Thanks! We are just using `public class ManualTransformCommand implements BdvPlaygroundActionCommand` from the playground for this. I don't understand how we would "create another TransformedSource". Is there an example for this?

**Comment by NicoKiaru** [comment]
Right, we should add an explicit 'wrap as transformed source' in the `ManualTransformCommand` command. Do you think you can do it ? If you're lost in the code, let me know before wasting hours.

**Comment by tischi** [comment]
> Right, we should add an explicit 'wrap as transformed source' in the ManualTransformCommand command. Do you think you can do it ?

I will try (might take some days, because of other stuff). I will ping you when I either did it or got lost 😄

**Comment by tischi** [comment]
@NicoKiaru 

This is the current code:

```Java
public static SourceAndConverter append(AffineTransform3D affineTransform3D, SourceAndConverterAndTimeRange sacTR) {
        if (sacTR.sac.getSpimSource() instanceof AbstractSpimSource) {
            if (SourceAndConverterServices.getSourceAndConverterService().getMetadata(sacTR.sac,SPIM_DATA_INFO)!=null) {
                return appendNewSpimdataTransformation(affineTransform3D, sacTR);
            } else {
                return createNewTransformedSourceAndConverter(affineTransform3D,sacTR);
            }
        } else {
            System.err.println("Cannot append a transformation to a source of class : "+sacTR.sac.getSpimSource().getClass().getSimpleName());
            System.err.println("You can try 'mutate' or wrap as transformed Source");
            return createNewTransformedSourceAndConverter(affineTransform3D,sacTR);
        }
    }
```

I don't understand the error messages. In fact, the code does wrap another (i.e. "append") TransformedSource around the input, which may or may not have been already a TransformedSource, which I would say is fine.

**Comment by tischi** [comment]
Aaaah, I guess your point is that the object hash code will change and thus is it not really an "append"? So, we should add an option "wrap"?!

**Comment by tischi** [comment]
Here is the PR: https://github.com/bigdataviewer/bigdataviewer-playground/pull/242

**Comment by tischi** [comment]
I rediscovered the (known) issue that if the Source is not a TransformedSource to begin with, we have to create a new SourceAndConverter object if we transform it and thus all the references to the previous SAC don't work anymore. For example in below code it cannot find the new SourceAndConverter and thus we cannot change its opacity anymore:

```
public static JButton createOpacityButton( List< SourceAndConverter< ? > > sourceAndConverters, String name, BdvHandle bdvHandle )
	{
		JButton button = new JButton( "O" );
		button.setPreferredSize( PREFERRED_BUTTON_SIZE );

		button.addActionListener( e ->
		{
			UserInterfaceHelper.showOpacityDialog(
					name,
					sourceAndConverters,
					bdvHandle );
		} );

		return button;
	}
```

I see two options:

1. We always wrap a Source into a TransformedSource before showing it (this is what Tobias is doing in BDV).
2. We replace the `SourceAndConverter` in our `Map< SourceName, SourceAndConverter >`. This would however require that we everywhere (e.g. in above code snippet) change our code such that the images are never directly accessed by their SourceAndConverter hashcode but always "freshly" fetched from the map by their `sourceName`. 

In fact the two options are not exclusive.
I wonder whether we should try to do (2) anyway to be more consistent with our data model (we should make a new issue for this).

@K-Meech do you have a feeling for this (given that you recently look into the `Map< name, sac >` stuff?

**Comment by K-Meech** [comment]
@tischi I think 2 sounds good - it would make everything more consistent anyway, so we are always accessing via the sourceName.

**Comment by tischi** [comment]
@K-Meech But I think I will do (1) for now as well, because that should be fast and give you something to work on the serialization of the TransformedSources. We can then do (2) later, OK?

**Comment by K-Meech** [comment]
Sure - sounds good!

**Comment by tischi** [comment]
Frustrating; the `mutate` option should work now, but somehow it did does not display the transformed source after one is finished. I have a feeling something's messed up with which sources are actually displayed in BDV. 
The `wrap` option works, but then we have to somehow get a handle on the new SourceAndConverter and update this in our `Map< name, SAC >`.

**Comment by tischi** [comment]
OK, I figured it out. It works now with the normal BDV way of thing this, i.e. pressing T and it will transform the "current" source (to be selected in the BDV window).

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/2157566/134499864-ecb978eb-7fff-4fc3-bfb1-107562d923ca.png">

Once this has been merged https://github.com/mobie/mobie-viewer-fiji/pull/458
every source will be a TransformedSource and then we can serialize the transformations.

**Comment by K-Meech** [comment]
@tischi - is there a good example project to use for testing this? Ideally one that contains complicated transforms in the views e.g. grids, affine, crops + has sources that get renamed after transformation.

**Comment by tischi** [comment]
It does not have to be perfect. The one we need it to work on "right now" (for the publication) would the one from @martinschorb 

I think it is this one?

```
new MoBIE("/g/emcf/pape/clem-example-project", MoBIESettings.settings().imageDataFormat( ImageDataFormat.BdvN5 ) );
```

**Comment by constantinpape** [comment]
@K-Meech I am not quite sure if the project on EMCF is up-to-date.
You can also find all the data on s3 / github:
https://github.com/mobie/clem-example-project
