### ISSUE TITLE
Opening openOrganelle dataset from github via MoBIE does not work

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#366]
Opening https://github.com/mobie/open-organelle-test via mobie does not work.
When trying to open the dataset I get the following error:

![Screenshot from 2021-07-21 20-50-23](https://user-images.githubusercontent.com/4263537/126543581-681e31b8-fd08-474a-a12d-3ce902d18d8d.png)

To reproduce:
- Start Fiji with MoBIE-beta
- Select "Plugins->MoBIE->open->Open MoBIE project...."
- Enter https://github.com/mobie/open-organelle-test as "Project Location"

cc @KateMoreva @tischi

**Comment by KateMoreva** [comment]
> Opening https://github.com/mobie/open-organelle-test via mobie does not work.
> When trying to open the dataset I get the following error:
> 
> ![Screenshot from 2021-07-21 20-50-23](https://user-images.githubusercontent.com/4263537/126543581-681e31b8-fd08-474a-a12d-3ce902d18d8d.png)
> 
> To reproduce:
> 
> * Start Fiji with MoBIE-beta
> * Select "Plugins->MoBIE->open->Open MoBIE project...."
> * Enter https://github.com/mobie/open-organelle-test as "Project Location"
> 
> cc @KateMoreva @tischi

@constantinpape, I think the problem is, that we do not have a dynamic file format chooser yet.
You can open this dataset using:

```
public class OpenOpenOrganell
{
    public static void main( String[] args )
    {
        final ImageJ imageJ = new ImageJ();
        imageJ.ui().showUI();
        try {
            new MoBIE("https://github.com/mobie/open-organelle-test",
                    MoBIESettings.settings().imageDataFormat( ImageDataFormat.OpenOrganelleS3) );
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by constantinpape** [comment]
Thanks for checking @KateMoreva; I will wait till @tischi has implemented dynamic file choosing and pushed it to the new release then and check again.
(@tischi I would like to send this to John and the other Janelians then to demonstrate opening open-organelle in MoBIE)

**Comment by tischi** [comment]
I have updated MoBIE-beta.

**Comment by constantinpape** [comment]
![Screenshot from 2021-07-22 11-51-25](https://user-images.githubusercontent.com/4263537/126620868-58e9ea95-9261-4118-b48a-be0dd355ed40.png)

Works now! I will add some more things to the example project and send around an update mail about it later.

**Comment by tischi** [comment]
Before sending it around to "all" Janelians maybe let's first optimize things in a smaller circle (us and John)?

**Comment by constantinpape** [comment]
> Before sending it around to "all" Janelians maybe let's first optimize things in a smaller circle (us and John)?

Ok, I will show you the example later then we can see how to continue.
