### ISSUE TITLE
Issues with open organelle boundary chunks

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#369]
There are some issues with the open organelle boundary chunks, see screenshot below.

I suspect that this is caused by the fact that the data is written with zarr, which writes out n5 boundary chunks differently from n5-java or z5py: it writes the whole boundary chunks (padded with zeros) instead of truncating it. It should be possible to adapt this in the n5 reader though.

![Screenshot from 2021-07-22 11-59-48](https://user-images.githubusercontent.com/4263537/126621931-b43d663a-248f-49d7-a594-85f0dd58201c.png)

**Comment by constantinpape** [comment]
@bogovicj @axtimwalde: the issue here is that we are reading n5 data with full instead of truncated border chunks (written with zarr-python, I assume).
We are using n5-java internally to read the data. Is there an (easy) way to correctly read the full boundary chunks with it?

Thanks!

**Comment by axtimwalde** [comment]
Not sure what n5-java is, but you could use n5-imglib2 which is cropping this as intended.
```java
var img = N5Utils.open(n5, dataset);
```
returns the expected img regardless of whether any chunks hang over or not.

**Comment by constantinpape** [comment]
> Not sure what n5-java is,

Ah sorry, I mean the "original" n5 repo: https://github.com/saalfeldlab/n5.

> but you could use n5-imglib2 which is cropping this as intended.

We are not using `n5-imglib2`; I think for historic reasons because our n5 reader code is derived from Tobias original bdv n5 reader, which did not use it.

Anyway, thanks for the pointer, we can see if it's easier to switch to `n5-imglib2` or see how `N5Utils.open` deals with this issue.

**Comment by constantinpape** [comment]
I guess the relevant function is [copyIntersection](https://github.com/saalfeldlab/n5-imglib2/blob/9c51034a490daab9c1b8a503f6cfc745813afd8d/src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5CellLoader.java#L316)

**Comment by tischi** [comment]
Yes, sounds very familiar. I think we are using this in (some of) the readers....
@KateMoreva can you please check?

**Comment by constantinpape** [comment]
> I think we are using this in (some of) the readers....

Yes, we are probably using it when reading zarr data.

**Comment by KateMoreva** [comment]
In `N5OmeZarrReader` we have method` copyTransposed` which is quite similar to this one.

**Comment by tischi** [comment]
ok, so maybe we can add it to the openOrganelle reader?!

**Comment by KateMoreva** [comment]
> ok, so maybe we can add it to the openOrganelle reader?!

Ok, I think we can.
@constantinpape, in the result there should not be the right part of the picture or it should also be fully visible?

**Comment by KateMoreva** [comment]
> In `N5OmeZarrReader` (and `N5S3ZarrReader `and `N5ZarrReader`) we have method` copyTransposed` which is quite similar to this one.

But method is unused

**Comment by axtimwalde** [comment]
It's `copyIntersection` combined with the shortcuts in `createCopy` so you don't do unnecessary stuff.

**Comment by KateMoreva** [comment]
Yes, did not notice at the first time, OmeZarrImageLoades are using createCopy from N5CellLoader.

**Comment by KateMoreva** [comment]
@constantinpape, is this the right image?

![image](https://user-images.githubusercontent.com/48569608/126679913-18e4695e-b22f-4391-aa56-5cb3db582651.png)

**Comment by constantinpape** [comment]
> Possibly solved in [Mr 373](https://github.com/mobie/mobie-viewer-fiji/pull/373)
> 
> @constantinpape, is this the right image?

Yes, that is the correct image.
