### ISSUE TITLE
Mobie crashes after the last update

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#372]
Am I doing something wrong? When I open the spec-v2 branch I get this error:

![Screenshot from 2021-07-22 16-22-26](https://user-images.githubusercontent.com/32451366/126655475-108f8f23-05db-4294-86d9-d65ec61b1970.png)

**Comment by vzinche** [comment]
That's mobie beta

**Comment by constantinpape** [comment]
> Am I doing something wrong? When I open the spec-v2 branch I get this error:

Are you trying to open platy-browser or some other project?

**Comment by vzinche** [comment]
platy-browser

**Comment by vzinche** [comment]
Nevermind, I still had the version from today morning. Works now, thanks
