### ISSUE TITLE
Opening BdvOmeZarrS3 is not working with current MoBIE-beta

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#374]
The project at `https://s3.embl.de/i2k-2020/project-bdv-ome-zarr` can be opened, but no data is loaded. Looks like all blocks are loaded as empty.
Maybe this happens because the reader does use the incorrect dimension separator?
I will double check that the actual data is ok once I have ome.zarr + napari working (hopefully Monday).

Note that opening the BdvOmeZarr dataset locally at `/g/kreshuk/pape/Work/mobie/covid-em-datasets/ngff-example/data` works.
This should be the same data!

cc @KateMoreva

**Comment by KateMoreva** [comment]
```
public class OpenRemoteBdvOmeZarr {
    public static void main(String[] args) throws IOException {
        final ImageJ imageJ = new ImageJ();
        imageJ.ui().showUI();
        new MoBIE("https://s3.embl.de/i2k-2020/project-bdv-ome-zarr", MoBIESettings.settings().gitProjectBranch( "master" ).imageDataFormat(ImageDataFormat.BdvOmeZarrS3));
    }
}
```

Works for me

**Comment by KateMoreva** [comment]
Could you please send the command that you used and the result?

**Comment by constantinpape** [comment]
I opened via Fiji:
`Plugins->MoBIE->Open->Open MoBIE project ...`, enter `https://s3.embl.de/i2k-2020/project-bdv-ome-zarr`.

This opens the project, but the image is empty and the log records block misses:

![Screenshot from 2021-07-22 20-43-25](https://user-images.githubusercontent.com/4263537/126695617-1c5f87bf-06ad-4eec-b04e-62b4137af911.png)

**Comment by KateMoreva** [comment]
Hm, something strange is heppening:
![image](https://user-images.githubusercontent.com/48569608/126696602-377a7516-9e29-494a-a619-2649264df0fe.png)
![image](https://user-images.githubusercontent.com/48569608/126696641-60664885-ff3e-4159-8f8a-a44ba3ae0bbb.png)
![image](https://user-images.githubusercontent.com/48569608/126696658-8d3c137a-0a89-4830-b633-7310745f45f6.png)

**Comment by constantinpape** [comment]
Ok, I just tried again and now I can see the data... Indeed very weird. 
Do you know why it prints all the `dataBlockIndices`? Is this some left over debug output? (I also see it now).
Something else I notice now: the pixel size is not correctly read from the xml metadata and set to "pixel". Instead it should be read from the xml, as for BdvN5.

**Comment by KateMoreva** [comment]
Yes, i think dataBlockIndices might be left from debaging.
OMEZarrS3Reader is used for reading this file and it has: 

``
   public SpimData readKey(String key) throws IOException {
        N5OMEZarrImageLoader.logChunkLoading = true;
        HashMap<String, Integer> axesMap = new HashMap<>();
        N5S3OMEZarrImageLoader imageLoader = new N5S3OMEZarrImageLoader(serviceEndpoint, signingRegion, bucketName, key, ".", axesMap);
        SpimData spimData = new SpimData(null, Cast.unchecked(imageLoader.getSequenceDescription()), imageLoader.getViewRegistrations());
        return spimData;
    }
```

**Comment by KateMoreva** [comment]
> Something else I notice now: the pixel size is not correctly read from the xml metadata and set to "pixel". Instead it should be read from the xml, as for BdvN5.

Ok, thanks, I will work over it. Is there anything else strange apart from pixel size reading? :)

**Comment by constantinpape** [comment]
> > 
> 
> Ok, thanks, I will work over it. Is there anything else strange apart from pixel size reading? :)

No the rest looks good. I guess the issue with the empty data was just some access issues with the s3 bucket, maybe also due to some transient problems with my local connection.

**Comment by KateMoreva** [comment]
> Хорошо, я просто попробовал еще раз, и теперь я вижу данные ... Действительно, очень странно.
> Вы знаете, почему он все печатает `dataBlockIndices`? Это какой-то остаток отладочной информации? (Я тоже это сейчас вижу).
> Я заметил кое-что еще: размер пикселя некорректно считывается из метаданных xml и установлен на «пиксель». Вместо этого его следует читать из xml, как для BdvN5.

@constantinpape , sholud it be like that? 

![image](https://user-images.githubusercontent.com/48569608/127897487-b2a27167-ef3a-4a6e-983b-35d0563d974c.png)

**Comment by KateMoreva** [comment]
> > Хорошо, я просто попробовал еще раз, и теперь я вижу данные ... Действительно, очень странно. 
> > Вы знаете, почему он все печатает `dataBlockIndices`? Это какой-то остаток отладочной информации? (Я тоже это сейчас вижу). 
> > Я заметил кое-что еще: размер пикселя некорректно считывается из метаданных xml и установлен на «пиксель». Вместо этого его следует читать из xml, как для BdvN5.
> 
> @constantinpape , должно быть так?
> 
> ![изображение](https://user-images.githubusercontent.com/48569608/127897487-b2a27167-ef3a-4a6e-983b-35d0563d974c.png)

Does ome.zar (non bdv) have units? I could not find one in examples.

**Comment by KateMoreva** [comment]
@constantinpape, please check https://github.com/mobie/mobie-viewer-fiji/pull/386, bdv.ome.zarr should have size according to it's   <voxelSize> in xml.

**Comment by constantinpape** [comment]
> @constantinpape , sholud it be like that?

Yes, this looks good.

> > 
> 
> Does ome.zar (non bdv) have units? I could not find one in examples.

No,ome.zarr does not have units yet; support for this is still work in progress. (This is one of the reasons we are currently supporting the bdv.ome.zarr version.)

**Comment by constantinpape** [comment]
This is all fixed now.
