### ISSUE TITLE
image loader refactoring

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#381]
Hi @constantinpape and @KateMoreva,

I am having a look at out current code for loading images.

A few thoughts:

1. currently we are using the work `Reader` for two very different things: (a) for the N5-based classes that read data blocks (e.g. `N5S3ZarrReader`) and (b) for classes that take an URI and return a `SpimData` object (e.g. `OMEZarrReader`. This is very confusing. What about we call (b) `...SpimDataOpener` instead?
2. I feel that splitting things up into multiple (n5 and ome-zarr) repositories might be too ambitious right now. What about we just create one `bigdataviewer-imageloaders` repository and, in there, spent some time to get the code very clean and without any code duplication. Inside this repository we can try to separate things by means of putting them into different packages. If we are done with this, we can see if it actually makes sense to factor out some packages into different repositories.

What do you think?

**Comment by KateMoreva** [comment]
I highly support bouth points.

**Comment by constantinpape** [comment]
I don't quite understand point 1, but we can discuss this in the meeting. I am fine with point 2.

**Comment by constantinpape** [comment]
This is being implemented in https://github.com/mobie/mobie-viewer-fiji/pull/405 and the related PR in `bigdataviewer-imageloaders`. I will close this issue already to keep discussion in the PRs.
