### ISSUE TITLE
Optimize zoom level for high-resolution sources

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#385]
Hi,

we often experience interpolation artifacts when looking at high-resolution EM data.
This is especially obvious when browsing reconstructed tomograms.

I would love to have a functionality that would adjust the display zoom factor such that the interpolation would use even ratios (1:n) instead of BDV's fully flexible interpolation scales.

Example: I choose a source, align the display with Shift+Z. Now what would be amazing: a button/shortcut to adjust the data to screen display scaling from the current 0.4425 to 0.5 to minimize interpolation artifacts.

ping @NicoKiaru
Revive of:
https://github.com/bigdataviewer/bigdataviewer-playground/issues/88

**Comment by NicoKiaru** [comment]
I won't have time to work on this. And it could be a bit complicated when dealing with multiple sources and with rotations. 

Ping @tischi

**Comment by tischi** [comment]
I am closing this as this feels like a bdv-core issue that we cannot tackle here easily.
