### ISSUE TITLE
Additional shiftToOrigin field for sourceTransform grid or ShiftToOriginTransformation

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#388]
@constantinpape @martinschorb 

For making a grid in x&y, it is nice if the sources are optionally centered around zero along the z-dimension. 

I see two options for this:

1. Add a `shiftToOrigin` flag to the gridSourceTransformer
2. Add another transformation option, called `shiftToOriginTransformer`

What do you think? Option 1 would keep the JSON smaller, thus maybe better?

**Comment by constantinpape** [comment]
I guess this is related to https://github.com/mobie/mobie-utils-python/issues/29#issuecomment-888943730?
I would vote for option 1 as well to keep the json smaller.

**Comment by constantinpape** [comment]
I can update the tomo project and add `shiftToOrigin` to the grid transform later.
I will ping you when it's there.

**Comment by tischi** [comment]
ok, thanks! let's do it like this then.

**Comment by constantinpape** [comment]
Ok, looking at this again I am not sure if `shiftToOrigin` is really the correct term here.
I would rather call this `center`. What do you think, @tischi?

**Comment by martinschorb** [comment]
> center

Or something like `centeredOrigin`

**Comment by constantinpape** [comment]
> Or something like `centeredOrigin`

Yes, that also fits, but I think rather `centerOrigin` or `centerAtOrigin`.

**Comment by tischi** [comment]
`centerAtOrigin` sounds nice!
could we also change this in the crop transformation?

**Comment by constantinpape** [comment]
> `centerAtOrigin` sounds nice!

Ok.

> could we also change this in the crop transformation?

Sure, I will change it there as well.

**Comment by constantinpape** [comment]
Done. I have not updated anything in the tomo project yet though.
 @martinschorb you can pass `center_at_origin=True/False` to `get_grid_view`, `get_grid_source_transform` and `get_crop_source_transform` now. Please give it a try and let me know if you run into any issues.

**Comment by tischi** [comment]
should I change it in the Java code and update MoBIE-beta or should I wait?

**Comment by tischi** [comment]
https://github.com/mobie/mobie-viewer-fiji/pull/391

**Comment by tischi** [comment]
What should the default values be? Maybe `false`?

`CropSourceTransformer: boolean centerAtOrigin = false;`
`GridSourceTransformer: boolean centerAtOrigin = false;`

**Comment by constantinpape** [comment]
> should I change it in the Java code and update MoBIE-beta or should I wait?

I think you can update this already, it's not used anywhere except the new tomo project.

> `CropSourceTransformer: boolean centerAtOrigin = false;`
> `GridSourceTransformer: boolean centerAtOrigin = false;`

For crop I would say that it should be true.

**Comment by tischi** [comment]
OK, I merged it.
@martinschorb let me know when you want to test it then I can update it in MoBIE-beta.

**Comment by martinschorb** [comment]
Whenever it fits, I will give it a go.

**Comment by tischi** [comment]
I have uploaded it to MoBIE-beta.

**Comment by constantinpape** [comment]
The relevant trafos have `centerAtOrigin` now.
