### ISSUE TITLE
git default branch name has changed

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#392]
Hi,

github has changed the default branch name to "main".

However, the default branch in MoBIE is still "master".

This means new github repositories are not opened with the standard "Open MoBIE Project".

I suggest moving all repositories to "main".
This however  is creating trouble since we want to stay backwards compatible for MoBIE v1 viewers...
We could keep a "master" branch as a copy for some time for backwards compatibility reasons, however when v2 is released, this should point to "main" by default.

Could you update the beta already this way?

**Comment by constantinpape** [comment]
> github has changed the default branch name to "main".
> 
> However, the default branch in MoBIE is still "master".

Well, it updates it when creating it properly through github, but not when just creating a repository without any files and then pushing a local repo (this is my usual way of doing this).
So if it's possible we should look for both a "main" and a "master" branch.
If that's too much effort, I'm fine with switching to "main" as a default.

> This however is creating trouble since we want to stay backwards compatible for MoBIE v1 viewers...

The old and new viewer will be incompatible in any case, so as soon as we update everything to the new spec and push the new viewer to the main update site users will need to update their MoBIE.

> We could keep a "master" branch as a copy for some time for backwards compatibility reasons, however when v2 is released, this should point to "main" by default.

We should not have both "master" and "main" in the same repository, this can lead to a lot of confusion.

**Comment by martinschorb** [comment]
> not when just creating a repository without any files

that will probably soon depend on the version of `git` used.
https://git-scm.com/docs/git-init

**Comment by tischi** [comment]
I think also given https://github.com/mobie/bigdataviewer-imageloader/issues/14 it feels like changing master to main is what we should do?! 
I would not worry too much about backwards compatibility because normal users anyway don't specify the branch when opening a MoBIE project via Fiji.

**Comment by constantinpape** [comment]
Changing to `main` is fine with me.

**Comment by constantinpape** [comment]
We will change everything to `main` before releasing MoBIE2.

**Comment by constantinpape** [comment]
The branch names are all changed to `main` now.
