### ISSUE TITLE
Sources are added inactive/invisible in latest mobie beta

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#397]
On the latest mobie beta, new sources are added inactive/invisible. 
e.g. open the spec-v2 branch of the platybrowser, the raw data is added, but invisible. Manually toggling the 'active' checkbox in the bdv source settings shows it again.

**Comment by constantinpape** [comment]
@tischi I assume the problem is that you set the `visible` default to false, but it should be true.

**Comment by tischi** [comment]
not sure what's going on:

```
public abstract class SourceDisplay
{
	// Serialization
	protected String name;
	protected double opacity = 1.0;
	protected boolean visible = true;
```

@K-Meech maybe you could debug into it when you find some time?

**Comment by K-Meech** [comment]
@tischi I'll take a look :)
