### ISSUE TITLE
ome zarr logging

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#401]
@KateMoreva 

There still is some logging left:
```
Path0.0
readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/nuclei_WellG06_0007.ome.zarr/s3/0.0
Path0.0
readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/nuclei_WellH06_0007.ome.zarr/s3/0.0
Path0.0
```

Could we also remove this?

**Comment by KateMoreva** [comment]
> @KateMoreva
> 
> There still is some logging left:
> 
> ```
> Path0.0
> readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/nuclei_WellG06_0007.ome.zarr/s3/0.0
> Path0.0
> readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/nuclei_WellH06_0007.ome.zarr/s3/0.0
> Path0.0
> ```
> 
> Could we also remove this?

It was before me, though you need it.

**Comment by KateMoreva** [comment]
> @KateMoreva
> 
> There still is some logging left:
> 
> ```
> Path0.0
> readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/nuclei_WellG06_0007.ome.zarr/s3/0.0
> Path0.0
> readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/nuclei_WellH06_0007.ome.zarr/s3/0.0
> Path0.0
> ```
> 
> Could we also remove this?

Done https://github.com/mobie/mobie-viewer-fiji/pull/402
