### ISSUE TITLE
grid view position order

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#404]
> I think that is the usual issue: I have written the positions with python using C-order, i.e. "yx", you are reading them with Java using F-order, i.e. "xy".

I am fine with yx order, even though I find xy more intuitive. 
@K-Meech as a Java and Python person what do you think?

**Comment by K-Meech** [comment]
I would also find xy more intuitive. But yx is also fine - we just have to make sure we're explicit in the docs about this

**Comment by constantinpape** [comment]
Ok, @tischi let's see if you get the correct grid layout for the covid plate if you intepret the order as yx before we decide on this.

**Comment by constantinpape** [comment]
I suggest we fix this as "yx" position order; I will update the description in the spec accordingly. Feel free to repoen this if there's still any need for discussion.
