### ISSUE TITLE
Changing opacity for segmentations

### ISSUE THREAD

**Issue by jhennies** [mobie/mobie-viewer-fiji#407]
On the earlier version of Mobie one could change the opacity of a segmentation in Settings -> brightness & color
in Mobie 2.0.0 the segmentations do not appear here anymore.

I would be very useful to be able to change this for example when showing an organelle segmentation on top of a cell segmentation. 
For example to generate a very faint cell segmentation overlay with a more prominent mitochondria overlay like so (from mobie-v0.5.2):

![image](https://user-images.githubusercontent.com/6114948/128701341-ea6ad990-6928-49bb-bd8a-4c794083bcb3.png)

**Comment by constantinpape** [comment]
You should see a button `O` next to the segmentation name in the MoBIE UI, which can be used to change the opacity.

(I am closing this, please reopen if this button is not there or is not working for you.)

**Comment by jhennies** [comment]
Thanks @constantinpape, I missed this button :)
