### ISSUE TITLE
Transformed sources: names and visibility

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#409]
@constantinpape 

I am a bit confused now. Do we actually properly specify which sources to display and to keep for further processing?

For example in the CropTransform: Let's say there is one input source and one cropped output source with a `sourceNameAfterTransform`. Right now, I am removing the input source from the list of sources. This has two consequences: (i) I think one cannot crop another region from the same source, simply because it is not anymore in my internal list of sources (this is probably bad for sure); (ii) the uncropped input source will not be displayed (this may be desired, maybe not?!). 

So somehow (also, as discussed, for the `MergedGridSource`) I feel we have to keep the untransformed sources, even if we will never show them.  

What also may be an issue in this respect is that we currently allow to transform sources without changing their names. Thus, in theory the cropped source could have the same name as the input source, which would make it very difficult to crop the input source again, because one does not know to which source to refer to.

I am not sure:

1. maybe we have to _require_ a new name for each transformed source to avoid ambiguities? 
2. maybe we have to be more explicit about whether the sources that are the _input_ to a transform should still be _displayed_ or not (I think we have to internally _keep_ them anyway, but maybe sometimes without display)?

**Comment by constantinpape** [comment]
> Maybe we have to logically do the `sourceTransforms` _before_ the `sourceDisplays` and then in the displays only specify the source names that we actually really want to show, after the transforms?

Yes, I think this makes sense. Just for context, I think our troubles here arise because we did not fully think about the `sourceNamesAfterTransform` or  `mergedSourceName` when we designed the view concept; i.e. we assumed that there was no need to ever change source names when applying transforms.

I think the solution you propose also make sense, just to recap:
- first, we apply the `sourceTransforms` and add all sources involved to the current view; if they specify a `sourceNamesAfterTransform` or `mergedSourceName`, they are added with this name, otherwise they keep the default source name
- then we go through the `sourceDisplay`. For each source, we check if it's in the active sources already (i.e. added by a transform), if not the source is added to the current view

I think this would work very well; with one minor caveat: it is possible now to specify sources in the `sourceTransforms` that are then not referenced in the `sourceDisplays`. We could either raise a runtime error for that case, or just discard these sources.

Let me know if this is what you intended, I can adapt the spec / python library accordingly and then update the covid-if project.

**Comment by tischi** [comment]
> first, we apply the sourceTransforms and add all sources involved to the current view

What do you mean by "add all sources"? 

Let's say there are some `sourceDisplays`. Each of them will have a list of sources that it wants to display. These sources could either be "raw sources" or "transformed sources". "Raw sources" can just be loaded and the "transformed sources" will be specified by the source transforms of that `view`. 

I think the issue is when to load all the sources that are "involved in the view", either as input to a transformation or to be used directly.  

I see two options:

1. The java code figures out along the fly if a source (either as input to a transformation or to be displayed directly) needs to be loaded.
2. We add a list of sources that are going to be needed to the whole view.

I would go for option 1 (and internally in the Java code write something to initially fetch all the needed sources and load them efficiently in parallel); something like `List< Source > rawSources = fetchRawSources( view.transforms, view.displays )`; And then one could `List< Source > allSources = rawSources.append( view.transform( rawSources ) )` and then `view.display( allSources )`, where  display just grab the sources that they need (all pseudo code).


> it is possible now to specify sources in the sourceTransforms that are then not referenced in the sourceDisplays

I would not consider this an issue. If someone makes a JSON where more sources are being transformed than actually displayed this is not very efficient but also not a problem.

I still wonder whether we **should strictly require that the name of a source changes when it is being 
transformed**. I think that would remove any ambiguities; in fact I think my pseudo code above would not really work otherwise.

Maybe we could discuss tomorrow during or after our MoBIE zoom?

**Comment by constantinpape** [comment]
> What do you mean by "add all sources"?

Add all sources specified in the `sourceTransforms` to the active (or however you want to call it) sources for this view.

> I see two options:
> 
>     1. The java code figures out along the fly if a source (either as input to a transformation or to be displayed directly) needs to be loaded.
> 
>     2. We add a list of sources that are going to be needed to the whole view.

I would also prefer option 1.

> I would not consider this an issue. If someone makes a JSON where more sources are being transformed than actually displayed this is not very efficient but also not a problem.

Ok, that's fine.

> I still wonder whether we **should strictly require that the name of a source changes when it is being transformed**. I think that would remove any ambiguities; in fact I think my pseudo code above would not really work otherwise.

I don't really see why transforms would always need to change the source names. And I don't see the ambiguity whether a source is raw or transformed. As simple python pseudocode:
```python
# create three sets, containing all the sources add to this view, the ones that are transformed and the ones that are raw 
# elements in set are always unique
view_sources = set()  # all sources added to this view
transformed_sources = set()
raw_sources = set()

# add sources from transforms to this view
for trafo in source_transforms:
  if "sourceNamesAfterTransform" in trafo:
    sources_in_trafo = set(trafo["sourceNamesAfterTransform"])
  elif "mergedSourceName" in trafo:
     sources_in_trafo = set([trafo["mergedSourceName"]])   # this is always a single name, so make it a set with one element
  else:
     sources_in_trafo = set(trafo["sources"])
  assert len(sources_in_trafo - transformed_sources) == 0  # make sure that the 'output' source names of this trafo are not added already; otherwise this would be ambiguous
  transformed_sources = transformed_sources.union(sources_in_trafo)

# add sources from source displays in this view
for display in source_displays:
    for source in display["sources"]:
      if source not in transformed_sources:  # we haven't seen this source before, so it's raw
        raw_sources.add(source)
     view_sources.add(source)  # add to the view sources

# additionally, this is how we could find sources specified in transforms, but not in displays:
only_transform_sources = transform_sources - view_sources
```

**Comment by tischi** [comment]
Note to self I made a branch to work on this: https://github.com/mobie/mobie-viewer-fiji/tree/sourcesAndTransforms

- Implement a `List< SourceName > = fetchSources( view )`
  - look into all displays and transforms and aggregate all `List< Source >`
  - then open all all the ones that are raw sources (the list may also contain transformed sources which first need to be created, s.b.)
- Implement a `Map< SourceName, SourceAndConverter >` which is transformed and change the transformers API accordingly

**Comment by constantinpape** [comment]
@tischi I updated the views in the covid project as discussed

**Comment by tischi** [comment]
@constantinpape 

Do I remember right that:

1. we wanted to rename the grid transform to transformedGrid? and the mergedGrid to just grid?
2. we can change the fields of the transformedGrid to also just be lists without the gridIds?

**Comment by tischi** [comment]
I think I implemented everything and will also merge now with master.
