### ISSUE TITLE
Nested transforms of individual sources

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#414]
@constantinpape @K-Meech 

(Mainly a note to self) This is a bit of a challenge:

```
          "grid": {
            "mergedGridSourceName": "plate_nuclei",
            "positions": [
              [
                4,
                5
              ],
              [
                4,
                6
              ]
            ],
            "sources": [
              "E06_nuclei",
              "E07_nuclei"
            ]
          }
```

At that point my code does not know anymore that `"E06_nuclei"` is comprised of several individual "site" sources that should all also be moved to the new well grid position.

I am thinking now that I could do something like:

```
if ( "E06_nuclei" instanceof MergedGridSource )
{ 
      individualSources =  "E06_nuclei".getMergedSources() // It knows of which sources it was composed
      ...and then also translate all the individualSources
}
```

**Comment by tischi** [comment]
I have it almost working:
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/2157566/129215968-cb586d98-f262-4460-836b-141fe485d017.png">

There is some offset issue that I could not figure out yet.
It could be a bit annoying, because the RAIs of the site images have an offset of (0,0) while in the current code the RAIs of the merged images my have a non-zero offset which creates a mess.

I have one idea now: I should not place the RAIs centrally with margins in all directions but maybe just add some space towards bottom right. This may make all of this easier.

I am not sure I will still do this before my vacation...

**Comment by tischi** [comment]
@constantinpape and @KateMoreva, debugging above issue I found the the source transforms of the ome.zarr images are looking a bit suspicious:

For example at the 3rd resolution level it looks like this:
```
3d-affine: (8.0, 0.0, 0.0, 3.5, 0.0, 7.948717948717949, 0.0, 3.4743589743589745, 0.0, 0.0, 1.0, 0.0)
```
Are the odd numbers (e.g., 7.948717948717949) also what is stored in the zarr files or is there something going on during the reading?

I cannot open the zarr folders from home, I think due to too bad network connection.

**Comment by constantinpape** [comment]
> Are the odd numbers (e.g., 7.948717948717949) also what is stored in the zarr files or is there something going on during the reading?

In this case we don't store any of the affines in the zarr file; the data is stored as pure ome.zarr, which does not specifying support any transformations (including pixel size) yet.

**Comment by constantinpape** [comment]
@tischi: I double checked this and neither transformation, nor scale factors of the MIP levels are directly read from the ome.zarr file:
- transformation: information is not available in vanilla ome.zarr yet, I think we just set it to identity (which is fine here).
- scale factors: this information is not explicitly stored in the ome.zarr, but is calculated from the extents in the different levels: https://github.com/mobie/bigdataviewer-imageloader/blob/cacefde8e46725647eac5524d03c83302cdc0608/src/main/java/de/embl/cba/n5/ome/zarr/loaders/N5OMEZarrImageLoader.java#L463-L485

This explains the numbers you see, which occur because the shape is not perfectly divisible by 2 in one of the dimensions.

**Comment by tischi** [comment]
@constantinpape could you please add a view that simply shows a single image?

**Comment by constantinpape** [comment]
Done. In the menu `test/single_nucleus`.

**Comment by tischi** [comment]
@K-Meech @KateMoreva I think have fixed the MergedGridView now.

For testing, e.g. scatterplot, please use `/g/kreshuk/pape/Work/mobie/covid-if-project/data` with the current master. Then use the bookmark: `plate: default_with_tables`.

**Comment by K-Meech** [comment]
Great! Would it be possible to move this project somewhere else? I don't have access to the Kreshuk lab server... @constantinpape ?

**Comment by constantinpape** [comment]
@K-Meech the project is too large to move it completely and @KateMoreva only has access to the kreshuk server.
But I will make a smaller version on emcf and ping you when it's there.

**Comment by constantinpape** [comment]
@K-Meech you can find a smaller version here: `/g/emcf/pape/covid-if-project/data`.

**Comment by K-Meech** [comment]
@tischi @KateMoreva I can't build the current master. It complains about this line: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/n5/zarr/N5OMEZarrImageLoader.java#L77 I guess this need to point to the new repo now?

**Comment by tischi** [comment]
@K-Meech yes, I think I may have screwed something up here because I merged my master with the current master on github. @KateMoreva could you make the current master on github work again?
I guess we just need to remove the n5.zarr package completely?

Please not that I did the following change in the N5OMEZarrImageLoader:

```
if (dimensions.length < 3 && dimensionsOfLevel0.length < 3) {
					for (int d = 0; d < 2; d++) {
						mipmapResolutions[level][d] = Math.ceil( 1.0 * dimensionsOfLevel0[d] / dimensions[d] );
					}
					mipmapResolutions[level][2] = 1.0;
				} 
```

I added a `Math.ceil( ... )` there. I guess we should do this now in the bdv-imageloader repo!

**Comment by tischi** [comment]
@K-Meech I removed the n5 package and pushed it. Seems to work now.

**Comment by tischi** [comment]
@KateMoreva should be depend on `bigdataviewer-imageloader` `1.0.2-SNAPSHOT`?! Such that we have the latest version? I am asking because the version I had was still doing the chunk loading logging, which is something I think we disable quite some time ago.

**Comment by KateMoreva** [comment]
> @KateMoreva should be depend on `bigdataviewer-imageloader` `1.0.2-SNAPSHOT`?! Such that we have the latest version? I am asking because the version I had was still doing the chunk loading logging, which is something I think we disable quite some time ago.

I think so, I will add the Math.ceil( ... ) to all versions and you can move to the 1.0.2-SNAPSHOT

**Comment by tischi** [comment]
I just added the Math.ceil to the SNAPSHOT already.

**Comment by constantinpape** [comment]
`Math.ceil` is not a good solution here, because it can lead to very wrong estimates for the scale factors. The issue is that sometimes the extent of the data is not divisible by the downscaling factor. In that case, there is a "half" pixel in the downsampled version and the extent can either be rounded up or down. If it is rounded up, the result of `Math.ceil` will be off by 1!
Instead, we should round to the nearest integer. 
Eventually the scaling factors should be added to the ngff spec, see https://github.com/ome/ngff/issues/53. But in the meantime we should implement a robust solution.

**Comment by tischi** [comment]
Yes, makes of course complete sense, thanks! 
Done in https://github.com/mobie/bigdataviewer-imageloader/commit/df9aeac48639cd92da2754b46b3f295c465e05d1

**Comment by tischi** [comment]
BTW: Unlike python in Java `Math.round` is in fact doing what you would expect it to do (i.e. what you get taught in German schools) 😄 .

**Comment by tischi** [comment]
@constantinpape I suffered some more hours but now I also managed to center the sources within the grid view, including the margins:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/2157566/132025940-0dc1045e-9754-4204-a1d8-74e419a63c6a.png">



Thus, I think that everything should work to at least start making a nice plate view figure for the publication 🥳  I also tried the scatterplot and it seems to work.
I will thus now close this issue for now (fingers crossed).

**Comment by constantinpape** [comment]
Awesome, thanks @tischi. I will give it a try once we have the new version on MoBIE-beta, and also add the new dataset to the clem project so that you can work on the second figure.
