### ISSUE TITLE
Support ome-zarr in project creator

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#420]

**Comment by K-Meech** [comment]
@tischi @constantinpape I will probably need to update the views/bookmarks code as part of this. What is the latest version of the dataset.json spec? Should I be basing everything off ```/g/kreshuk/pape/Work/mobie/covid-if-project/data``` project?

**Comment by constantinpape** [comment]
Yes, the covid project is up-to-date.

**Comment by K-Meech** [comment]
At the moment, there's an option in the project creator to 'link' to an existing image. i.e. to put a relative path in the image xml, rather than copying over an image that is already in bdv format.

@constantinpape - can you use relative paths with normal ome.zarr? i.e. could I replace the dataset paths in "multiscales" to be relative ones to some arbitrary location on the filesystem?

**Comment by constantinpape** [comment]
> @constantinpape - can you use relative paths with normal ome.zarr? i.e. could I replace the dataset paths in "multiscales" to be relative ones to some arbitrary location on the filesystem?

That's currently not supported, though there is an ongoing discussion about the topic, see https://github.com/ome/ngff/issues/13.
Note that we still have the xml for the `bdv.ome.zarr` filetype, so for these you can still write the link into the xml. But for `ome.zarr` this is currently not possible; we would need to add `absolutePath` to the spec; but I would rather just disallow / throw an error in the project creator for this case.

**Comment by K-Meech** [comment]
Ok! I'll add the link in the xml for bdv.ome.zarr, and otherwise throw an error.

**Comment by K-Meech** [comment]
@constantinpape How does remote metadata work for ome.zarr.s3?
i.e. in the 'source' in the 'dataset.json' - what path would I give?

**Comment by constantinpape** [comment]
You specify the `s3Address`, which is the full URI of the zarr container on the s3 store, i.e. `<SERVICE_ENDPOINT>/<BUCKET_NAME>/<PATH_IN_BUCKET>`,
e.g. something like `https://s3.embl.de/platynereis/1.0.0/images/segmentation.ome.zarr`.
For reference, this is the python code that produces the metadata https://github.com/mobie/mobie-utils-python/blob/spec-v-02/mobie/metadata/remote_metadata.py#L79-L87

**Comment by K-Meech** [comment]
This is on the develop branch now
