### ISSUE TITLE
bigdataviewer-imageloader dependency

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#421]
@K-Meech @KateMoreva 
The current master of mobie was not compatible with the current master of bigdataviewer-imageloader (1.0.2-SNAPSHOT). I think there was an easy fix though. 
In general, on which version of bigdataviewer-imageloader do we want mobie-viewer-fiji to depend on?

**Comment by KateMoreva** [comment]
> @K-Meech @KateMoreva
> The current master of mobie was not compatible with the current master of bigdataviewer-imageloader (1.0.2-SNAPSHOT). I think there was an easy fix though.
> In general, on which version of bigdataviewer-imageloader do we want mobie-viewer-fiji to depend on?

Right now it should be 1.0.2-SNAPSHOT, or I can create v1.0.2, if there would not be much new functionality in the nearest future.
