### ISSUE TITLE
Lets make the working proces clear

### ISSUE THREAD

**Issue by KateMoreva** [mobie/mobie-viewer-fiji#422]
It seems that we have a bit of chaos in the project (because we make PR, and commit to` master` without knowing about each other work).
Let structurize the working process a bit.
I suggest following several rules:

- We have the `master` branch - MoBIE version that is ready for delivery.
We _do not push there_ anything except **hotfixes** (when we find out about critical bud in the production version). 

- And the `develop` brunch - the one in which we push new features.
**New functionality** and non-critical **bugs** is added through **PR**. Thus everyone would be able to see what was changed.
We merge the `develop ` branch into master (updating MoBIE version) once all functionality is working as it should.

@tischi, @K-Meech, @constantinpape 

What do you think?

**Comment by tischi** [comment]
Good idea! 

I am sorry for probably being the source of the mess!

Could you make such a `develop` branch?

**Comment by KateMoreva** [comment]
No problem, it was just me, who became tired of resolving conflicts with `master` and of getting lost in my branches with fixes :)
Sure it will be ready in minutes.

**Comment by tischi** [comment]
Great! Thanks a lot!

I am not sure whether this is too ambitious but maybe we could even try to always have a situation where the current master branch only has dependencies on repositories that are (i) on maven and (ii) that are _not_ SNAPSHOT versions. 

Like this it would be easy for outside collaborators and non Java geeks to build the current master without too much hassle.

One thing I am also not sure about is how all of this relates to the MoBIE-beta update site. If we want people to test stuff we have to ship relatively preliminary versions to the update site. In other words, would we consider publishing the `develop` branch to MoBIE-beta as bad practice or not?

**Comment by KateMoreva** [comment]
> I am not sure whether this is too ambitious but maybe we could even try to always have a situation where the current master branch only has dependencies on repositories that are (i) on maven and (ii) that are _not_ SNAPSHOT versions.

It is quite possible.

**Comment by KateMoreva** [comment]
> One thing I am also not sure about is how all of this relates to the MoBIE-beta update site. If we want people to test stuff we have to ship relatively preliminary versions to the update site. In other words, would we consider publishing the `develop` branch to MoBIE-beta as bad practice or not?

I don't think it is a bad practice. But it is better to make some timetable of deployment or announce a new MoBIE publication in one place (if it is in such a way, please let me know where:) ).

**Comment by constantinpape** [comment]
Thanks for taking the initiative on the @KateMoreva. Indeed we need to structure the dev process better, given that we are quite actively developing here and I think your proposal is very good for this.

> I am not sure whether this is too ambitious but maybe we could even try to always have a situation where the current master branch only has dependencies on repositories that are (i) on maven and (ii) that are _not_ SNAPSHOT versions.

Yes, I think that would be very good practice.

> One thing I am also not sure about is how all of this relates to the MoBIE-beta update site. If we want people to test stuff we have to ship relatively preliminary versions to the update site. In other words, would we consider publishing the `develop` branch to MoBIE-beta as bad practice or not?

I think for now we are stuck to deploying to MoBIE-beta, as long as we haven't fully released spec-v2 (i.e. update all MoBIE projects so that the main/master branch is on v2). I hope that we can do this in the next 2 weeks, and then start pushing updates to the main MoBIE update site again. After that, we can indeed use MoBIE-beta to test experimental features and push to it from the dev branch.

>  But it is better to make some timetable of deployment or announce a new MoBIE publication in one place (if it is in such a way, please let me know where:) ).

This is a good idea in general ;). We should think about this before the publication; one option would be to use image.sc for announcements.

**Comment by tischi** [comment]
OK! I will from today on mainly work the the develop branch!

**Comment by K-Meech** [comment]
Sounds good! I'll make PRs against the develop branch from now on :)
+1 for having the master branch track the main mobie update site, and develop the beta mobie update site.

Once we've got everything sorted and back in master, it'd be great if we could be more formal about tagging releases from master too. This makes it super easy to find back a specific version + easier for other developers to follow any progress (as you can watch a repository for only releases!)

**Comment by tischi** [comment]
> Once we've got everything sorted and back in master, it'd be great if we could be more formal about tagging releases from master too. 

Yes, that would be awesome!
