### ISSUE TITLE
OME ZARR missing from BigDataViewer menu

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#424]
In the current MoBIE-beta, the commands to open OME ZARR from s3 / the filesystem are missing from `Plugins->BigDataViewer`. I guess this got lost in some of the refactoring of the imageloader code.

cc @tischi @KateMoreva

**Comment by KateMoreva** [comment]
> In the current MoBIE-beta, the commands to open OME ZARR from s3 / the filesystem are missing from `Plugins->BigDataViewer`. I guess this got lost in some of the refactoring of the imageloader code.
> 
> cc @tischi @KateMoreva

The bug should be fixed the commands are in the current master `https://github.com/mobie/mobie-viewer-fiji/tree/master/src/main/java/de/embl/cba/mobie/command`.

**Comment by tischi** [comment]
Yes, this is fixed in the latest develop branch. I will upload once the other bug with the S3 loading is fixed.
