### ISSUE TITLE
Javadoc errors in CI

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#429]
We now have basic CI running, but it fails because of issues with the javadoc.

@tischi Where should this link (https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/bdv/render/AccumulateOccludingProjectorARGBFactory.java#L42) point? AccumulateMixedProjectorARGB doesn't seem to exist anymore.

Also - where should this one point? https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/bdv/render/AccumulateOccludingProjectorARGBFactoryAdapter.java#L10

**Comment by tischi** [comment]
To be honest, since we don't do JavaDoc consistently anyway, I would simply delete all JavaDoc, at least the ones that throw errors.
