### ISSUE TITLE
Ci and the develop branch

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#431]
We now have working ci on this repo!
At the moment this runs when there's a pr against master, or pushes to master.
Prs trigger building/testing, and pushes trigger building + testing + releases to the maven repository.

How do we want to handle the develop branch?
I think it should also be triggered for PRs and for pushes (as this is the branch we will mostly be working on). Do we want it to also release straight to the maven repository?
@tischi @KateMoreva @constantinpape

**Comment by tischi** [comment]
Just to clarify, what's the difference of the develop and the master branch?

Would the idea be that the master branch contains the code that is shipped to the Fiji MoBIE update site? (I know, currently not the case, but that could be our aim...)

**Comment by K-Meech** [comment]
I think in the long run the master branch would be == main Fiji MoBIE update site, and the develop branch would be == MoBIE Beta update site.

**Comment by constantinpape** [comment]
> Do we want it to also release straight to the maven repository?

No, I wouldn't do releases straight to the maven repo for develop. I would rather stay with a model where we make releases to MoBIE-beta manually from develop, given that there might be quite a lot of PRs / pushing when developing a new feature.

Otherwise what you propose sounds very good.

**Comment by tischi** [comment]
> make releases to MoBIE-beta manually from develop,

...release to maven repo is not the same as release to the Fiji update site. "Release" to MoBIE or MoBIE-beta is always a "manual" process that is not included in the CI, afaik.

I think SNAPSHOT versions are typically released to maven in the Fiji community. Thus we could consider that **develop** contains the SNAPSHOT versions while **master** should only contain release versions.

Maybe, e.g., for people at EBI or OME it may be useful to be able to depend on SNAPSHOT versions of MoBIE for testing. Then it would be good if those SNAPSHOT versions _are_ on maven...

I would have also time for a zoom this afternoon (or even right now) if we think we should discuss this...

**Comment by constantinpape** [comment]
> I would have also time for a zoom this afternoon

I would have time in the afternoon except for 3PM to 4PM.

**Comment by K-Meech** [comment]
I'd be free this afternoon for a zoom too! Might be easier to just discuss in person.

**Comment by KateMoreva** [comment]
I have lectures today. I Will be free after 16 if you need me

**Comment by constantinpape** [comment]
> I have lectures today. I Will be free after 16 if you need me

We scheduled a meeting a bit earlier now, we will update you on what we discussed here.

**Comment by constantinpape** [comment]
@KateMoreva so we discussed in the meeting to also push the snapshot versions from the develop branch to maven. @K-Meech will implement this for the viewer repository and we can then later adapt this for the other repository.

We also decided to change the group-id and project structure to "org.embl.mobie" and we want to rename the "bidataviewer-imageloader" repository to "mobie-io". It would be great if you could do these changes for the imageloader repository.

Did I forget anything, @tischi @K-Meech?

**Comment by K-Meech** [comment]
No - looks good @constantinpape !

Also, ci is working on the develop branch for this repo now :) @KateMoreva all you have to do is add 'develop' to both your workflows like here: https://github.com/mobie/mobie-viewer-fiji/pull/434/files
