### ISSUE TITLE
Ui tests with Ci

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#436]
It would be good to add some more basic tests to mobie e.g. to check opening the platybrowser.

I had a quick attempt at this here: https://github.com/K-Meech/mobie-viewer-fiji/commit/fa4580302441022246e0558ad856daa46b4825ba This test runs fine locally, but fails on the actual ci pipeline. Seems like it can't handle opening the imageJ gui :( So we'll have to find another way around it e.g. just checking an image can be accessed from the platybrowser with no display.

**Comment by KateMoreva** [comment]
> It would be good to add some more basic tests to mobie e.g. to check opening the platybrowser.
> 
> I had a quick attempt at this here: [K-Meech@fa45803](https://github.com/K-Meech/mobie-viewer-fiji/commit/fa4580302441022246e0558ad856daa46b4825ba) This test runs fine locally, but fails on the actual ci pipeline. Seems like it can't handle opening the imageJ gui :( So we'll have to find another way around it e.g. just checking an image can be accessed from the platybrowser with no display.


I can add spimData test specifically for the platybrowser.

**Comment by K-Meech** [comment]
@KateMoreva - it'd be great if you could add a test! So, you would open one of the platybrowser datasets as a spimData object?

**Comment by KateMoreva** [comment]
> @KateMoreva - it'd be great if you could add a test! So, you would open one of the platybrowser datasets as a spimData object?

I think the quickest solution is to create a test like https://github.com/mobie/mobie-io/blob/main/src/test/java/spimdata/OpenOrganelleSpimDataTest.java. But as it is one special dataset we can have needed constants in advance.

**Comment by K-Meech** [comment]
Sounds good!
