### ISSUE TITLE
Create Project with OME-ZARR: What happens to voxel size?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#440]
@K-Meech When creating a MoBIE project and saving the image as ome-zarr (without the bdv) does that mean that the voxel sizes are lost? Because the current ome-zarr spec does not yet contain the transformations? If that's the case we should maybe disable this option until this is fixed?!

**Comment by K-Meech** [comment]
Yes - at the moment the voxel size info is lost! (as there's nowhere to store it in the current spec)
I can disable it. Otherwise, we could add a warning that voxel size isn't retained for plain ome-zarr?

**Comment by tischi** [comment]
> Otherwise, we could add a warning that voxel size isn't retained for plain ome-zarr?

I would disable it for now.
