### ISSUE TITLE
crops don't work in current Beta

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#442]
Hi,

the crop definitions in
https://github.com/mobie/centrioles-tomo-datasets

do no longer work in the current beta.
Have the specs changed, or is this a problem with the viewer?

**Comment by constantinpape** [comment]
The crop metadata in the project is still valid. You can always check this via the commandline with `mobie.validate_project -i <PATH_TO_PROJECT>`. So I think the current mobie beta does not handle the crops correctly.

@martinschorb can you please add an example image of how it looks now, how it should (roughly) look with the crop applied and how to reproduce the view in MoBIE?

@tischi can you have a look at Martin's example and see if there's something wrong with the crop transform?

**Comment by martinschorb** [comment]
Hi,

Here's what I would expect and how it looked previously.

![Screenshot 2021-09-14 at 14 50 47](https://user-images.githubusercontent.com/35071867/133260915-00dfff32-a9fd-47c2-91f0-dca235348bd6.png)

Here's what I get now. Basically the same as the uncropped tomogram.

![Screenshot 2021-09-14 at 14 49 51](https://user-images.githubusercontent.com/35071867/133260953-eac6fd46-e531-459e-a21b-8ca4cdce8ee1.png)

**Comment by martinschorb** [comment]
and this is independent on whether I load it from local or remote.

**Comment by constantinpape** [comment]
And this is the default view you get when opening https://github.com/mobie/centrioles-tomo-datasets?

**Comment by martinschorb** [comment]
This is the view I get when opening the view shown in the dropdown. It is the exactly identical whether I choose the view from the "Centrioles"(which should be cropped) or the "Tomograms" (which should show this full view) selector.

So it looks to me that neither the transform nor the crop is applied. Does this have anything to do with the `sourceNamesAfterTransform`?

This is the last crop of the views:

Is something wrong with the `name` or `sources` in the general definition? Does the main `sources` need to point to the `xx_crop` source?


```JSON
"SM_02_Grid2_c264_c2_crop": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "SM_02_Grid2_c264_c2",
            "opacity": 1.0,
            "sources": [
              "SM_02_Grid2_c264"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "affine": {
            "parameters": [
              0.7669431053511951,
              -0.5066103937152996,
              0.3938834626306295,
              0.0,
              0.5066103937152996,
              0.8547468278728989,
              0.11293258706345709,
              0.0,
              -0.39388346263062934,
              0.11293258706345716,
              0.9121962774782959,
              0.0
            ],
            "sourceNamesAfterTransform": [
              "SM_02_Grid2_c264_c2_tfm"
            ],
            "sources": [
              "SM_02_Grid2_c264"
            ]
          }
        },
        {
          "crop": {
            "max": [
              1.726851786587702,
              2.6282388705116886,
              0.41465700107812375
            ],
            "min": [
              0.726851786587702,
              1.6282388705116886,
              -0.5853429989218762
            ],
            "sourceNamesAfterTransform": [
              "SM_02_Grid2_c264_c2_crop"
            ],
            "sources": [
              "SM_02_Grid2_c264_c2_tfm"
            ]
          }
        }
      ],
      "uiSelectionGroup": "Centrioles"
    }

**Comment by constantinpape** [comment]
Ok, I see...

Indeed probably the "sourceNamesAfterTransform" is the issue. The `"sources"` in `"sourceDisplays/imageDisplays"` should be `["SM_02_Grid2_c264_c2_crop"]`, so that the transformed source instead of the original source is shown.

**Comment by martinschorb** [comment]
OK, that is probably the relevant change.

I will try to replace the source name...

**Comment by martinschorb** [comment]
OK, I forgot to update the correct git branch. It now finds it, but it does not like it...:

```

java.lang.RuntimeException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.sources
	at de.embl.cba.mobie.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:53)
```

**Comment by constantinpape** [comment]
@martinschorb the metadata looks correct now, so I think this needs to be debugged on the viewer site.
Could you please update the project so that we can easily reproduce this? I.e. push the updated metadata to github and let us know which view to select for which the crop feature does not work as expected.

**Comment by constantinpape** [comment]
> OK, I forgot to update the correct git branch. It now finds it, but it does not like it...:
> 
> ```
> 
> java.lang.RuntimeException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.sources
> 	at de.embl.cba.mobie.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:53)
> ```

The metadata is not valid:
```
centrioles-tomo-datasets$ mobie.validate_project -i data
Traceback (most recent call last):
  File "/home/pape/Work/software/conda/miniconda3/envs/main/bin/mobie.validate_project", line 33, in <module>
    sys.exit(load_entry_point('mobie', 'console_scripts', 'mobie.validate_project')())
  File "/home/pape/Work/mobie/mobie-utils-python/mobie/validation/project.py", line 64, in main
    validate_project(args.input)
  File "/home/pape/Work/mobie/mobie-utils-python/mobie/validation/project.py", line 55, in validate_project
    assert_equal=assert_equal)
  File "/home/pape/Work/mobie/mobie-utils-python/mobie/validation/dataset.py", line 20, in validate_dataset
    validate_with_schema(dataset_metadata, "dataset")
  File "/home/pape/Work/mobie/mobie-utils-python/mobie/validation/utils.py", line 54, in validate_with_schema
    jsonschema.validate(instance=metadata, schema=schema)
  File "/home/pape/Work/software/conda/miniconda3/envs/main/lib/python3.7/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: {'0': ['CTRL_02_Grid3_c550'], '1': ['B-ALL_00_Grid5_c0116'], '2': ['B-ALL_00_Grid5_c0250']} is not of type 'array'

Failed validating 'type' in schema[1]['properties']['grid']['properties']['sources']:
    {'description': 'The sources this transformation is applied to.',
     'items': {'$ref': '#/definitions/name'},
     'minItems': 1,
     'type': 'array'}

On instance['grid']['sources']:
    {'0': ['CTRL_02_Grid3_c550'],
     '1': ['B-ALL_00_Grid5_c0116'],
     '2': ['B-ALL_00_Grid5_c0250']}
```
Here the problem is that `sources` in grids should be a list, not a dictionary/map. (This has recently changed.)

**Comment by martinschorb** [comment]
OK, I fixed it. I mixed up the dataset.json with the one from my WIP grid branch.
