### ISSUE TITLE
layer hierarchy

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#448]
When looking at multiple different resolution EM acquisitions at the same time, the "sum" projection is not appropriate.

I suggest using occluding layers, but then, it needs to be independent on the order of when views are displayed.

I could foresee two scenarios:

- in the list of active views at the bottom of the MoBIE main window, each occluding view would get a button to change the layer order. (optional button only for occluding sources)
- in the view definition in the JSON, this order could be pre-defined. (0 for the highest magnification, 99 for the lowest)

The function(s) to create the views (in the python package) could automatically assign the order based on the pixel sizes of the associated source (checking all other occluding sources already present in the dataset).

**Comment by martinschorb** [comment]
Another option would be a "normalized projection" mode that would apply the blending/opacity after mapping the source intensity/contrast to the display intensites.

**Comment by constantinpape** [comment]
>     * in the view definition in the JSON, this order could be pre-defined. (0 for the highest magnification, 99 for the lowest)

Can you explain this point a bit more? Currently, our blending mode is very simple:
```json
                        "blendingMode": {
                            "description": "The mode for blending multiple image sources.",
                            "type": "string",
                            "enum": ["sum", "sumOccluding"]
                        }
```
If I understand your proposal correctly, we would need to add some kind of order / priority to this? That would mean we need to change `blendingMode` to be a more complex type or add an extra field like `blendingOrder` or so.

**Comment by martinschorb** [comment]
> ... or add an extra field like `blendingOrder` or so.

that's what I would suggest. It would only take effect when the `BlendingMode` is occluding and define which source should be shown on top of which.

On top of that, if we want to show different EM sources (or "non-sparse" information sources, like any brightfield imaging) at the same time, an additional `normalized` or `average` mode is still necessary.

Think of combining EM, BF light microscopy and X-Ray. A Sum would only result in white regions when one source of that kind gets added to an existing view regardless of already existing contrast and opacity settings.

**Comment by constantinpape** [comment]
> > ... or add an extra field like `blendingOrder` or so.
> 
> that's what I would suggest. It would only take effect when the `BlendingMode` is occluding and define which source should be shown on top of which.
> 
> On top of that, if we want to show different EM sources (or "non-sparse" information sources, like any brightfield imaging) at the same time, an additional `normalized` or `average` mode is still necessary.
> 
> Think of combining EM, BF light microscopy and X-Ray. A Sum would only result in white regions when one source of that kind gets added to an existing view regardless of already existing contrast and opacity settings.

All of this sounds good to me, but I defer decisions to @tischi who actually knows how the blending is working.
From the spec side adding the proposed changes (a new field like `blendingOrder` and `normalized` or `average` as additional values for `blendingMode`) would be easy.

**Comment by tischi** [comment]
@martinschorb 

I think we should discuss this in person while playing with the current version.

Currently, in the UI, you can:
- change the opacity `[ O ]`
- change the occlusions (right click "set Blending mode")
  - this will only be applied the sources that are both at the mouse cursor _and_ visible => you can address any source individually by en/disabling sources; checkbox `[  ] S`
- change the order of the sources (for this you have to remove the sources from the current view and add them back in the order that you like).

While some of this is not super convenient I would like to understand how far that is getting us in principle.

**Comment by martinschorb** [comment]
I will play a bit to get familiar with these functionalities. Then we could maybe meet on Monday afternoon?

**Comment by tischi** [comment]
Monday afternoon is a bit full for me. Today or Tuesday would be better.

**Comment by martinschorb** [comment]
Just to summarize the action points:
- introduce `occludingOrder` or similar to sort the views of a dataset according to level

**Comment by martinschorb** [comment]
- check that import of views generated with 'Save current Settings as View' works

**Comment by martinschorb** [comment]
see https://github.com/mobie/mobie-viewer-fiji/issues/454

**Comment by constantinpape** [comment]
> Just to summarize the action points:
> 
>     * introduce `occludingOrder` or similar to sort the views of a dataset according to level

@tischi @martinschorb 
I can add this to the spec, but before that:
- Which type is this? Integer?
- Also, it should be optional, so that we don't need to update all projects.

**Comment by tischi** [comment]
I would say let's please wait with this until we wrote the current publication.
I don't want to touch the code more than absolutely necessary at this point.

**Comment by martinschorb** [comment]
> Let's please wait with this until we wrote the current publication.
> I don't want to touch the code more than absolutely necessary at this point.

oops... 😆
