### ISSUE TITLE
Transformation serialisation

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#451]
@K-Meech are we already trying to serialize the source transforms to the JSON?
I think this would require some code like `instanceof TransformedSource` and `getFixedTransform()`...

**Comment by K-Meech** [comment]
At the moment, it saves whatever transforms were already in the view e.g. if you load a view with affine transforms, then try to save another view, it should keep those. Anything added (e.g. manual transformations) aren't currently recorded.

**Comment by tischi** [comment]
Could you work on this? This is essential for the manual transforms to work (which would be awesome).

**Comment by K-Meech** [comment]
I can do - but probably not until the end of next week. I'm back in the lab now - so I'll be using the microscopes :)
