### ISSUE TITLE
grid view for sources of different sizes

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#455]
@martinschorb could you please make a grid view for me where the first source is smaller than the other ones? I need this for testing my latest changes.

**Comment by martinschorb** [comment]
Our favourite centrioles branch grid-test2 - the "centriole grid" should have different crop sizes.

**Comment by tischi** [comment]
The centriole grid view still has the bugs that I described in the other issue (and that @constantinpape fixed in the python tools), thus the cropped source is not shown (and thus I cannot use it for testing).

**Comment by martinschorb** [comment]
![Screenshot 2021-09-21 at 16 30 09](https://user-images.githubusercontent.com/35071867/134190178-82324b2a-a55f-41ab-8657-9f4278a3e562.png)

This is how it look to me. `grid-test2` and the `centriole-grid` view. Transformations and crops are correct. The bottom-left source is the biggest and seems to define the grid dimensions.

**Comment by tischi** [comment]
Sorry, I was using the wrong branch.
In fact, it does not work for you yet, since I did not yet push the changes 😸 
The margins are too small in your case.
But for me it does work:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/2157566/134302716-8151bf16-433f-469a-b6bc-f0abfbbaeaff.png">
