### ISSUE TITLE
Wrapping of Sources into TransformedSources

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#465]
@K-Meech 

I just now understood that you are now also wrapping here:
https://github.com/mobie/mobie-viewer-fiji/blob/9553a097624ed40df48124e9ab140c705c7f1189/src/main/java/org/embl/mobie/viewer/view/ViewManager.java#L250

Then I guess we can remove it here?!
https://github.com/mobie/mobie-viewer-fiji/blob/9553a097624ed40df48124e9ab140c705c7f1189/src/main/java/org/embl/mobie/viewer/MoBIE.java#L305

**Comment by K-Meech** [comment]
Yes - I guess so! I wrap all the sources (after any sourceTransformers are applied), so it should still work fine.

**Comment by K-Meech** [comment]
I'll remove it, and make a PR
