### ISSUE TITLE
Performance issues when many sources are displayed

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#474]
Hi,

it feels like MoBIE is getting slower and slower the more sources were shown inside its BDV window.
Could it be that it still keeps metadata information from sources in memory even if they are removed from the list of active items?

Relates to:
https://github.com/mobie/mobie-viewer-fiji/issues/471

also there: "old" and discarded sources are still present inside the viewer.

**Comment by K-Meech** [comment]
Linking this issue here too, in case it's related: https://github.com/mobie/mobie-viewer-fiji/issues/329

**Comment by tischi** [comment]
@martinschorb 
did this improve? can we close?
