### ISSUE TITLE
Make centerAtOrigin=true the default

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#482]
@constantinpape @martinschorb 
I have a feeling that `centerAtOrigin=true` is the better default for the grid views than `false`.
At least for the CLEM Hela example it produces a more expected behaviour for the tomos-transformed view:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/2157566/136437720-480fb265-473d-49d7-b27b-f1efd153c2da.png">

What do you think?

**Comment by constantinpape** [comment]
Yes, I agree True makes more sense here.

**Comment by tischi** [comment]
Done.
