### ISSUE TITLE
Scale bar incorrect

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#498]
The scale bar does not show the correct distance any more. (On current MoBIE-beta):
![Screenshot from 2021-11-03 11-00-02](https://user-images.githubusercontent.com/4263537/140040667-a9981d07-bd83-43aa-87b2-4b1e468dc22b.png)

**Comment by tischi** [comment]
I am actually not so sure where BDV get's the scaling from...
@KateMoreva could it be that we are not loading the voxel size metadata from the images anymore? did something change there?

**Comment by K-Meech** [comment]
I tried running with my local version which is from this commit: https://github.com/mobie/mobie-viewer-fiji/commit/a146cc51e9e7b74e4268814df16cf571c3b36c08 and everything works fine (same for the table etc issues @constantinpape reported). So it's probably changes from @KateMoreva 's PR.

**Comment by tischi** [comment]
Then I think the changes are probably in `mobie-io`, because not much changed here.

**Comment by KateMoreva** [comment]
I'll check it today

**Comment by tischi** [comment]
@KateMoreva it seems working in fact. I don't know what happened to the version that I uploaded to MoBIE-beta. Thus, no need for you to do anything.

**Comment by constantinpape** [comment]
Fixed.
