### ISSUE TITLE
Selecting table row navigates to wrong location

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#500]
Selecting a table row moves to a wrong location outside of the dataset (current MoBIE-beta):

Initial View:
![Screenshot from 2021-11-03 11-05-24](https://user-images.githubusercontent.com/4263537/140041742-3e13fb75-3a92-45fd-a644-246c3b8eafb9.png)

After selecting Row 26:

![Screenshot from 2021-11-03 11-05-43](https://user-images.githubusercontent.com/4263537/140041921-5cabb72e-8127-4921-aab6-074217e79db7.png)

Going to the anchor position via "move" (this works)

![Screenshot from 2021-11-03 11-07-16](https://user-images.githubusercontent.com/4263537/140041840-cb1d19f9-2852-44ad-b584-3958a3c32add.png)

Note that it seems to always navigate to the same (wrong) position.

**Comment by tischi** [comment]
this is because the scaling in BDV is wrong, i.e. is related to the other issue.

**Comment by constantinpape** [comment]
Fixed
