### ISSUE TITLE
blosc CI causes github build to fail

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#518]
@K-Meech @constantinpape 
Did we always have this issue that the CI is not working?
https://github.com/mobie/mobie-viewer-fiji/runs/4141735409?check_suite_focus=true#step:6:103

**Comment by tischi** [comment]
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/2157566/140789270-2b6bce16-f22a-467e-8b30-32cd1d273c2b.png">

**Comment by constantinpape** [comment]
I am not sure if that always happend, but it can probably be fixed by installing lib blosc.
See here how to install with apt in gh actions: https://stackoverflow.com/questions/57982945/how-to-apt-get-install-in-a-github-actions-workflow
And blosc can be installed by `sudo apt install libblosc-dev`

**Comment by tischi** [comment]
@KateMoreva was this ever an issue in `mobie-io`?

**Comment by tischi** [comment]
Not sure we can easily fix this, because [this](https://github.com/mobie/mobie-viewer-fiji/blob/86a8100f87c63cb4d88cc4a757e667612d365d8e/.github/workflows/build-main.yml#L37) points to [this](https://github.com/mobie/mobie-viewer-fiji/blob/develop/.github/build.sh), which is not our code.

@ctrueden & @imagejan it looks like we would need to add a `sudo apt install libblosc-dev` into the github action build script in order to compile Saalfeld's n5 code. Can we do this?

**Comment by KateMoreva** [comment]
> @KateMoreva was this ever an issue in `mobie-io`?

I do not think so, but I needed to load this library at some point for mobie-viewer-fiji.

**Comment by tischi** [comment]
Hm, interesting, maybe the "default Ubuntu", which I think the build script is using has changed?

**Comment by constantinpape** [comment]
> Not sure we can easily fix this, because [this](https://github.com/mobie/mobie-viewer-fiji/blob/86a8100f87c63cb4d88cc4a757e667612d365d8e/.github/workflows/build-main.yml#L37) points to [this](https://github.com/mobie/mobie-viewer-fiji/blob/develop/.github/build.sh), which is not our code.
> 
> @ctrueden & @imagejan it looks like we would need to add a `sudo apt install libblosc-dev` into the github action build script in order to compile Saalfeld's n5 code. Can we do this?

@tischi please read https://stackoverflow.com/questions/57982945/how-to-apt-get-install-in-a-github-actions-workflow more carefully; this does not require changing any build scripts. Instead, you would need to add an additional `step` to the yaml file, e.g. [here](https://github.com/mobie/mobie-viewer-fiji/blob/86a8100f87c63cb4d88cc4a757e667612d365d8e/.github/workflows/build-main.yml#L29).

**Comment by tischi** [comment]
@constantinpape thanks! I overlooked that the fetching of the operating system already happens in the `build.yaml`; I thought this was a step that only happens later in the `build.sh`. Then I can try!

**Comment by constantinpape** [comment]
> I overlooked that the fetching of the operating system already happens in the `build.yaml`; I thought this was a step that only happens later in the `build.sh`.

That would be magic, as you need the os to run the `build.sh` script ;).

**Comment by tischi** [comment]
Cool! [This](https://github.com/mobie/mobie-viewer-fiji/blob/9970a7f8d74d8638bc46723961c492a0c14b3691/.github/workflows/build-main.yml#L37) seems to work.

This cloud CI/CD stuff is still magic to me, just spinning up a computer for us... 🧙 

Thanks @constantinpape!


The deployment to maven still [failed](https://github.com/mobie/mobie-viewer-fiji/runs/4143914917?check_suite_focus=true) but I think that is another issue.
Maybe just that we cannot deploy the same version twice?

**Comment by imagejan** [comment]
@tischi wrote:
> Maybe just that we cannot deploy the same version twice?

Exactly. That's the contract of "deployment": once a version is deployed, it is guaranteed to never ever change.

Solution: cut a new release version :smile:
