### ISSUE TITLE
Running tests with maven fails

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#520]
I don't manage to run tests of MoBIE that include ImageJ using `mvn install`.

```	
@Test
public void testSmallGridView() throws IOException
{
	final ImageJ imageJ = new ImageJ();
	imageJ.ui().showUI();
	final MoBIE moBIE = new MoBIE( "https://github.com/mobie/zebrafish-lm-datasets", MoBIESettings.settings().gitProjectBranch( "main" ).imageDataFormat( ImageDataFormat.BdvN5S3 ) );

	final Map< String, View > views = moBIE.getViews();
	moBIE.getViewManager().show( views.get( "small-grid-view" ) );
}
```

throws me:

```
java.lang.IllegalArgumentException: Invalid service: sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService
        at tests.TestRemoteZebrafish.testSmallGridView(TestRemoteZebrafish.java:27)
Caused by: java.lang.IllegalArgumentException: Invalid service: sc.fiji.bdvpg.scijava.services.SourceAndConverterService
        at tests.TestRemoteZebrafish.testSmallGridView(TestRemoteZebrafish.java:27)
Caused by: java.lang.ExceptionInInitializerError
        at tests.TestRemoteZebrafish.testSmallGridView(TestRemoteZebrafish.java:27)
Caused by: java.lang.RuntimeException: 
No _hooks field found in ij.IJ
It appears that this class was already defined in the class loader!
Please make sure that you initialize the LegacyService before using
any ImageJ 1.x class. You can do that by adding this static initializer:

        static {
                LegacyInjector.preinit();
        }
```

...and when I add

```
	static {
		LegacyInjector.preinit();
	}
```

I am getting this:

```
[ERROR] testSmallGridView  Time elapsed: 0.012 s  <<< ERROR!
java.lang.ExceptionInInitializerError
        at tests.TestRemoteZebrafish.<clinit>(TestRemoteZebrafish.java:19)
Caused by: java.lang.NoSuchFieldException: _hooks
        at tests.TestRemoteZebrafish.<clinit>(TestRemoteZebrafish.java:19)
```

Running the test using the Run button in IntelliJ works without the LegacyInjector:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/2157566/140898084-86478791-8130-4203-bb8f-97f2fdc6cf6b.png">

@imagejan @ctrueden @nicoKiaru, do you have any idea how to make this work with maven? In particular it would be great if that would work the the github actions.

**Comment by ctrueden** [comment]
> do you have any idea how to make this work with maven?

The issue is not really with Maven, but with which classes get loaded in conjunction with imagej-legacy trying to do its class patching via javassist.

I tried to look into this, but there is no `TestRemoteZebrafish` class on the main branch. I see it's on the linked PR, but I can't easily browse around the source tree of a PR via the web interface. And I cannot afford to clone it locally while on the bus (as an aside: please do not commit large files to git repositories. I wasted 50MB of bandwidth trying to clone this—only getting to 12% before hitting ^C).

Anyway, when debugging this (unfortunately rather common) problem, what I look for first is any `ij.*` classes declared as part of the class definition itself. If you have an `ij.<something>` class as a **method argument**, a **method return value**, a **field type**, or a **supertype**, it will get recursively loaded when your class is loaded, and only _after_ the class is loaded with the static initializer block run, which is now too late to patch the `ij.*` classes because some of them have already been loaded. Change your API not to expose any ImageJ 1.x classes in the class definition itself. It is OK to use the `ij.*` classes as local variables, though.

If you look through all your code and don't find anywhere where `ij.*` classes are being exposed, ping me again and I can take a closer look.

**Comment by tischi** [comment]
Thanks for the answer.

Our `main` branch is very much out of date.
This is the branch to look at: https://github.com/mobie/mobie-viewer-fiji/tree/develop

> Change your API not to expose any ImageJ 1.x classes in the class definition itself.

Does that mean, e.g., that nowhere in the code we should not have `ImagePlus` in any method call?

**Comment by tischi** [comment]
This is [one of the tests for reference](https://github.com/mobie/mobie-viewer-fiji/blob/6edbbace01ab732b75de0ba0abeb3d441bcac496/src/test/java/tests/TestRemoteZebrafish.java#L25)

**Comment by tischi** [comment]
I checked and we have tons of `ImagePlus` in method calls. Removing them is not possible. Does that mean the tests cannot be run via maven?

**Comment by tischi** [comment]
Ok, I think I found the difference. The culprit simply seems to be code in the actual tests:

```
final ImageJ imageJ = new ImageJ();
imageJ.ui().showUI();
```

If I comment them out in the tests, it would not throw the legacy error.

However, I _think_ I need those lines because otherwise I get:
```
java.lang.IllegalArgumentException: Invalid service: sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService
        at tests.TestRemoteZebrafish.testSmallGridView(TestRemoteZebrafish.java:27)
Caused by: java.lang.IllegalArgumentException: Invalid service: sc.fiji.bdvpg.scijava.services.SourceAndConverterService
        at tests.TestRemoteZebrafish.testSmallGridView(TestRemoteZebrafish.java:27)
Caused by: java.lang.ExceptionInInitializerError
``` 

@NicoKiaru I think we had this discussion: Is there any other way to initialize those services _without_ calling `ImageJ imageJ = new ImageJ();`?

**Comment by NicoKiaru** [comment]
Couldn't you just swap these lines ?

`
imageJ.ui().showUI();
final ImageJ imageJ = new ImageJ();
`

I think once you've run `imageJ.ui().showUI()` you're safe ?
take care to static initialization

**Comment by NicoKiaru** [comment]
Is the bigdataviewer-playground version up to date ? I think I had these issues but not anymore. There are plenty of tests in BigDataViewer-Playground which are running nicely.

Do you put these lines at the beginning of your tests ?

```
final ImageJ imageJ = new ImageJ();
imageJ.ui().showUI();
```

Can you link to a failing test ? Not just a copy paste of the code.

**Comment by NicoKiaru** [comment]
Oups,  found it!

**Comment by NicoKiaru** [comment]
> @NicoKiaru I think we had this discussion: Is there any other way to initialize those services without calling ImageJ imageJ = new ImageJ();?

Really not easily.

**Comment by tischi** [comment]
> take care to static initialization

How do I do this? Sorry for my ignorance...

I tried this:

```
public class TestRemoteZebrafish
{
	static {
		LegacyInjector.preinit();
	}

	final static ImageJ imageJ = new ImageJ();

        @Test
	public void run()
	{
              imageJ.ui().showUI();
              final MoBIE moBIE = new MoBIE( "https://github........
        }
```

But this gives me now:

```
java.lang.ExceptionInInitializerError
        at tests.TestRemoteZebrafish.<clinit>(TestRemoteZebrafish.java:19)
Caused by: java.lang.NoSuchFieldException: _hooks
        at tests.TestRemoteZebrafish.<clinit>(TestRemoteZebrafish.java:19)
```

Where line 19 is: `LegacyInjector.preinit();`

> Is the bigdataviewer-playground version up to date ? 

```
<bigdataviewer-playground.version>0.3.13</bigdataviewer-playground.version>
```

**Comment by NicoKiaru** [comment]
Ok, so I don't know.

What I would try is to make this static:

`public void testSmallGridView() throws IOException`

but I don't see what this would change.

and then add little by little the lines in here:

https://github.com/mobie/mobie-viewer-fiji/blob/6edbbace01ab732b75de0ba0abeb3d441bcac496/src/test/java/tests/TestRemoteZebrafish.java#L29-L42

until it fails (hoping that it works when all is removed)

Also getting rid of this temporarily:

https://github.com/mobie/mobie-viewer-fiji/blob/6edbbace01ab732b75de0ba0abeb3d441bcac496/src/test/java/tests/TestRemoteZebrafish.java#L46-L61

**Comment by tischi** [comment]
Thanks, I will try later.
I just had a look at the bdv-playground and I don't see how you run the tests with maven. In the pom of this repo I have:
```
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.1</version>
			</plugin>
		</plugins>
	</build>
```

But I did not find something like this in the playground. So how do you actually run the tests?

**Comment by tischi** [comment]
@NicoKiaru I think I did what you suggested but without success...

Now, whenever I am adding 

```
static {
		LegacyInjector.preinit();
	}
```

I am getting 

```
java.lang.ExceptionInInitializerError
Caused by: java.lang.NoSuchFieldException: _hooks
```

for the line with the `LegacyInjector.preinit();`. 

Could it be that this is because @NicoKiaru does this as well in the playground?

```
@Plugin(type=Service.class)
public class SourceAndConverterService extends AbstractService implements SciJavaService, ISourceAndConverterService
{

    protected static Logger logger = LoggerFactory.getLogger(SourceAndConverterService.class);

    static {
        LegacyInjector.preinit();
    }
```

**Comment by ctrueden** [comment]
> nowhere in the code we should not have `ImagePlus` in any method call?

It depends! 😇 

Sometimes you can get away with it, depending on exactly which classes are getting loaded when.

Other times, you can avoid it by using `Object imp` arguments, and always passing `ImagePlus` objects to those methods, and then casting them back to `ImagePlus` in the method itself.

And yet other times, you may find you don't ever need to pass an `ImagePlus` around anywhere at all.

But it depends on your needs, and how "original-ImageJ-centric" your code is.

**Comment by ctrueden** [comment]
> But I did not find something like this in the playground. So how do you actually run the tests?

The `pom-scijava` parent brings in the maven surefire config. All you need is tests in `src/test/java`, and a junit dependency with test scope, and the `@Test` annotation on your tests. You don't need anything else in your project POM besides the junit dependency.

To actually run the tests from the command line, use:
```
mvn test
```
This runs the Maven build lifecycle up to and including the test phase.

**Comment by ctrueden** [comment]
> Could it be that this is because @NicoKiaru does this as well in the playground?

Shouldn't be a problem to call `preinit` in multiple places. If it's already been done, it should just be a no-op...

**Comment by ctrueden** [comment]
I took another look at the mobie-viewer-fiji repository, develop branch. For me, the project builds and all tests pass.

I also looked at whether you really need to be depending on `net.imagej:imagej` (i.e. the whole kit-and-kaboodle), and I don't think you do. At least: `src/main` code's only usages of `net.imagej.ImageJ` are for main methods, for testing, which could be migrated into src/test or downstream. If the intent is for this component to be reused as a library, it is best not to depend on the entire `net.imagej:imagej`, but rather only the pieces of SciJava/ImgLib2/ImageJ2 that you actually need.

If you are still having preinit woes somewhere, please tell me where to look, and I can try to figure it out.

**Comment by tischi** [comment]
Thanks a lot @ctrueden I will further work on this, first of all applying your patch!

@K-Meech I will remove the `main` methods from your classes. I don't think it is good practice to have them anyway. If needed, please put the code to execute your classes in `/src/test` instead.

**Comment by tischi** [comment]
@ctrueden 

Thanks again a lot for all the help! Really very much appreciated!

The reason all tests worked for you was that I commented out the ones that fail 😄 

I made a new branch: https://github.com/mobie/mobie-viewer-fiji/tree/tests

In this branch, [this](https://github.com/mobie/mobie-viewer-fiji/blob/110b75e94c13a219c2b7a6251ce514eb944b9e3a/src/test/java/tests/TestRemoteZebrafish.java#L29-L48
) fails for me upon `mvn test`, with the error:

```
[ERROR] testSmallGridView  Time elapsed: 0.01 s  <<< ERROR!
java.lang.ExceptionInInitializerError
        at tests.TestRemoteZebrafish.<clinit>(TestRemoteZebrafish.java:19)
Caused by: java.lang.NoSuchFieldException: _hooks
        at tests.TestRemoteZebrafish.<clinit>(TestRemoteZebrafish.java:19)
```

If you have any further ideas, let us know!

**Comment by ctrueden** [comment]
I looked a bit more last night. I learned that `ImagesCreatorTest` is one of the problem classes, because:
```
mvn -Dtest=org.embl.mobie.viewer.projectcreator.ImagesCreatorTest,tests.TestRemoteZebrafish test
```
Causes `TestRemoteZebrafish` to fail, but if you run `TestRemoteZebrafish` alone, it works (triggering lots of GUI actions, at least).

And if you add the `LegacyInjector.preinit()` static initializer block to `ImagesCreatorTest`, then the above two-test invocation works. But running _all_ the tests still doesn't work, because there are other classes that also trigger premature loading of ij classes.

So this morning, I just applied the big hammer and added the static preinit to all classes that import an `ij` class. And all the tests pass now. #528 

If it bothers you, you can try removing static preinit blocks from individual classes, whittling it down to the core needed to avoid this issue. Or you could refactor the code a bit to isolate the `ij` class usages into fewer classes that are used everywhere you need to lean on such functionality.

Unfortunately, this is the price we pay for combining ImageJ2+ImageJ with capabilities beyond what the original ImageJ was designed for.

**Comment by tischi** [comment]
@ctrueden 

Thanks a lot!!!

I merged your changes and now it indeed runs all the tests locally 🥳 

Now, as expected, tests that show graphics are not working in the github actions:

```
 No X11 DISPLAY variable was set, but this program performed an operation which requires it.
  	at tests.TestRemoteZebrafish.testTransformedGridView(TestRemoteZebrafish.java:48)
  
  Error:  testSmallGridView  Time elapsed: 0.097 s  <<< ERROR!
```

Do you think we could handle this, e.g. running the tests using something like `xvfb-run`? 

Of course, rewriting our tests to run headless without showing any graphics could also be possible, although maybe challenging for something like MoBIE that really is all about showing stuff..

**Comment by ctrueden** [comment]
> Do you think we could handle this, e.g. running the tests using something like `xvfb-run`?

Yep, the GitHub Actions page has [a section on xvfb](https://imagej.net/develop/github-actions#testing-things-which-cannot-run-headless). It was copied from the old Travis page though; I'm not sure if it's 100% correct or if anyone is successfully doing it. If you find it needs adjustment, please edit, thanks!

**Comment by tischi** [comment]
@ctrueden I could not get the old solution to work, but after some googling and trying I found this to work 😎 

```
...
      - run: sudo apt-get install xvfb
      - name: Execute the build
        run: xvfb-run --auto-servernum .github/build.sh
        env:
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
...
```

How do I add this solution to [our documentation](https://imagej.net/develop/github-actions#testing-things-which-cannot-run-headless)? Is the content for this site hosted on github?

**Comment by imagejan** [comment]
> How do I add this solution to our documentation? Is the content for this site hosted on github?

@tischi there's a small link "Edit this page" in the top right corner of the page that leads you here:
https://github.com/imagej/imagej.github.io/edit/main/_pages/develop/github-actions.md

**Comment by tischi** [comment]
@imagejan Thanks a lot! This link really is small 😄 
Here we go: https://github.com/imagej/imagej.github.io/pull/212
