### ISSUE TITLE
Restricting CI/CD...

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#535]
I don't get why it is running for those branches:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/2157566/141961642-6e78103d-df9c-4214-af9d-1ca99e6e9689.png">

**Comment by K-Meech** [comment]
It's setup to run for all PRs at the moment. I guess we'd have to add something extra to exclude draft PRs.

**Comment by tischi** [comment]
In fact there is a dedicated script`build-pr.yml` in the github actions for the PR.
Not sure what to do here. Maybe it is not so bad if this is running...

**Comment by tischi** [comment]
Maybe let's just try not to open PRs prematurely.
