### ISSUE TITLE
MoBIE opens tables for segmentations that are not selected

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#540]
When opening a view that has a segmentation with a table, the table is always opened, even if the segmentation is **not** shown by default in the view.
This behaviour is weird, but might be due to the fact that we do not have a "showTable" field in the spec for the segmentationDisplay.

@tischi: I think there are two ways to fix this:
- when opening a view with a segmentation show the tables only if the segmentation is selected (i.e. "visible:True")
- add an optional field "showTable" to the spec (default: True). Then it's the responsibility of the project creator to make sure that showTable is set to false if the segmentation is not shown by default. With this approach it would also be feasible to show a segmentation, but not the table when opening a view.

I would be fine with either solution, let me know what you prefer. (And in the second case I could update the spec and the example below.)

Example: 
- Open https://github.com/mobie/covid-if-project
- This opens the tables for "cell segmentation" and "nucleus segmentation" although these sources are not set to visible in the view:
![aaaaaa-mobie-tables](https://user-images.githubusercontent.com/4263537/142633702-129c3ed0-30e6-42ba-b734-fe444c79f380.png)

**Comment by tischi** [comment]
Thanks for finding this.

Turns out, in Java we do have a `showTable` field already:


```
public abstract class AnnotatedRegionDisplay< T extends TableRow > extends AbstractSourceDisplay
{
	// Serialization
	protected String lut = ColoringLuts.GLASBEY;
	protected String colorByColumn;
	protected Double[] valueLimits = new Double[]{ null, null };
	protected boolean showScatterPlot = false;
	protected String[] scatterPlotAxes = new String[]{ TableColumnNames.ANCHOR_X, TableColumnNames.ANCHOR_Y };
	protected List< String > tables; // tables to display
	protected boolean showTable = true;
```

However, in `public void initTableViewer( SegmentationSourceDisplay display  )` I show the table anyway, not even looking at this field 😄 

Maybe we just use this field both in the code and in the JSON?
I guess we need to leave the default at `true` in order not to have to rewrite too many JSON files?

**Comment by constantinpape** [comment]
@tischi I double checked this now, and we have `showTable` in the spec already. 

> I guess we need to leave the default at `true` in order not to have to rewrite too many JSON files?

Yes, the default should be `true`.

For the segmentationDisplays in https://github.com/mobie/covid-if-project (default) the `showTable` field is set to `false` now.
But the table is still opened when opening the view. Could you please have a look and fix the behaviour in MoBIE s.t. it does not open the tables by default for this view?

**Comment by constantinpape** [comment]
This is fixed now.
