### ISSUE TITLE
Navigation does not work for segmentation table in mergedGrid

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#541]
Navigating to segments via selecting rows in the tables or segments in the image does not work for segmentations in a merged grid. There are two issues:
- when selecting a segment the viewer navigates to a wrong location (outside the image space), see second screenshot below
- the selection applies to all cells with the same id, not just the cell with this id in the image at hand. we somehow need to take the image-id into account here.

The example is from https://github.com/mobie/covid-if-project using the "cell segmentation".

![aaa-nav1](https://user-images.githubusercontent.com/4263537/142634667-fc17d7c1-afdd-421b-9422-7dbab874fd11.png)
![aaa-nav2](https://user-images.githubusercontent.com/4263537/142634674-61211599-13b6-4001-9bbb-c889f50a448a.png)
![aaa-nav3](https://user-images.githubusercontent.com/4263537/142634690-a08b59db-6462-4bf7-b7d0-ca5a8f78e7d5.png)

**Comment by tischi** [comment]
Thanks @constantinpape,
I found quite a couple of bugs! 
I filed a PR.

**Comment by tischi** [comment]
@constantinpape 

The navigation to the sites (images) works now (not merged yet), but as @K-Meech pointed out, it does not go to the correct cell within the image. 

In which units are the anchor coordinates? Could it be that there is something off?

Another idea: maybe the x and y coordinates are switched or flipped or mirrored?

**Comment by constantinpape** [comment]
> In which units are the anchor coordinates? Could it be that there is something off?
> 

The units are in relative image coordinates. I.e. for each segmentation the coordinates go from 0 to 1024 (here we use 'pixels' with scale factor 1 as physical coordinate space, but in general this would be in physical coordinates).
So you have to offset these coordinates with the relative position of the image in the grid.

> Another idea: maybe the x and y coordinates are switched or flipped or mirrored?

I don't think so, as I use the same code as everywhere else for computing the table here and this was never an issue before.

**Comment by tischi** [comment]
OK, there is some deeper issue...

The coloring of the label sources is solely done via the label index in the image. 

Now, for a `MergedGridSource` this does not work, because several objects in the same source can have the same label index...

I am in fact not quite sure how to fix this right now...

**Comment by constantinpape** [comment]
@tischi I have added `encodeSource: True` to  the well grids for all the segmentations in `covid-if` now.

**Comment by tischi** [comment]
Thanks! Seems to work 🥳 

However, are you sure about the x and y axis not being mixed up in the cell's anchor points?

In below example I am specifically selecting/highlighting cells with low values in their x-coordinate and they all show up at the top of the image (where the low y-coordinates should be):

<img width="827" alt="image" src="https://user-images.githubusercontent.com/2157566/142934267-8546f064-4edb-478e-a644-fc311cb06ec7.png">

**Comment by constantinpape** [comment]
I can double check the x and y issue once we have the new working version on MoBIE or MoBIE-beta.

**Comment by K-Meech** [comment]
Ok! The new version is now on MoBIE-beta.

**Comment by constantinpape** [comment]
Indeed something with the anchors is wrong, but it's not a simple switch of x and y. I will investigate further and let you know once it's fixed.

**Comment by constantinpape** [comment]
The anchors should be correct in all tables now. I still have some issues with the navigation though: when trying to select a segment in an image I get the following error:
```
Exception in thread "Thread-401" java.lang.ClassCastException: de.embl.cba.tables.imagesegment.DefaultImageSegment cannot be cast to de.embl.cba.tables.tablerow.TableRowImageSegment
	at org.embl.mobie.viewer.segment.BdvSegmentSelector.toggleSelectionAtMousePosition(BdvSegmentSelector.java:90)
	at org.embl.mobie.viewer.segment.BdvSegmentSelector.run(BdvSegmentSelector.java:144)
	at org.embl.mobie.viewer.bdv.view.SliceViewer.lambda$null$5(SliceViewer.java:122)
	at java.lang.Thread.run(Thread.java:748)
```
(On latest MoBIE-beta)

Could you please check this issue, @tischi @K-Meech?

**Comment by tischi** [comment]
I will have a look...

**Comment by tischi** [comment]
Do you know the repo where Julian had the example data where there are segmentations **without tables**? I think I'll need this to clean up the code.

**Comment by K-Meech** [comment]
Same for me. I can't reproduce it on MoBIE-beta.

**Comment by jhennies** [comment]
@tischi The test project is in /g/emcf/hennies/for_constantin/mobie_no_table_test

**Comment by tischi** [comment]
@constantinpape can you check the version number of mobie in your MoBIE-beta? Maybe it did not download the latest?

**Comment by constantinpape** [comment]
Ok, I tried again and now the error is gone works. Not sure what was going on there...

Regarding the coordinates in the tables:
I am sure that they are correct now because I am validating them for all segmentations (https://github.com/mobie/covid-if-project/blob/main/check_anchors.py#L52).

Maybe we are interpreting y and x different here ... but it would be easiest if you could just check this by switching the columns when loading @tischi, then I don't have to upload new tables for debugging.

**Comment by tischi** [comment]
I am on a retreat now. I would look into it on Monday.
@K-Meech if you feel like testing this, go ahead!

**Comment by tischi** [comment]
@constantinpape I had another look and I think I need some help.

Is there any logic as to how the label_ids are given? I my code often the labeling starts in some corner of the image, but here I cannot see any correlation between label_id and anchor points. Is this normal?

<img width="955" alt="image" src="https://user-images.githubusercontent.com/2157566/143618116-28972eae-7ecf-4428-9572-5dad9fee9554.png">
 
-----

Could you please for the image `cell_segmentation_WellE06_0000` just give me one cell (with a screenshot) where you know the label_id and which has a distinct shape such that I can find it back? Because I think at the moment the whole assignment from table row to image segment is wrong as color by column does not give the expected coloring when coloring by n_pixels. Bigger cells show be more yellow using viridis, which clearly is not the case:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/2157566/143618440-779a276e-1f2a-4d96-aaa5-1ebf968ace12.png">

**Comment by tischi** [comment]
Couple of other ideas for the debugging:
- a view with just a single site (no grid transformation)
- the current default view but with the normal grid transformer (without merging)

**Comment by constantinpape** [comment]
> Is there any logic as to how the label_ids are given? I my code often the labeling starts in some corner of the image, but here I cannot see any correlation between label_id and anchor points. Is this normal?

The segmentation is based on a seeded watershed from nuclei segmented with stardist. So this boils down to how stardist assigns ids to nuclei; no idea if this follows any systematic and in general you cannot rely on any pattern of id assignments because segmentations are invariant under relabeling.

> Could you please for the image `cell_segmentation_WellE06_0000` just give me one cell (with a screenshot) where you know the label_id and which has a distinct shape such that I can find it back?

That's label-id 132:
![label132](https://user-images.githubusercontent.com/4263537/143624896-3fcfe85c-3836-4c05-9983-70147bf2321f.png)

Here's the python script to get it, you can change the label id with the `-l` argument:
https://github.com/mobie/covid-if-project/blob/main/view_segment.py

> * a view with just a single site (no grid transformation)
> 

`bookmarks->single_image`

> * the current default view but with the normal grid transformer (without merging)

`plate->default_transform_grid_with_tables_with_segmentations`

**Comment by tischi** [comment]
Thanks! That helps! In the single image view:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/2157566/143636523-6913099e-2b30-4cb6-be72-01915859a577.png">

So, label index seems to be OK, but the coordinates in the table are different from the the coordinates of the cell in BDV (see upper right corner of BDV). `(0,0)` is the upper left corner of the image in BDV. I guess you could also check yourself. Any ideas?

**Comment by tischi** [comment]
@constantinpape I think I found something else. In `cell_segmentation_WellE06_0000` in the image there appear to be cells with label indices that are higher than the largest label index in the table.

**Comment by constantinpape** [comment]
> In `cell_segmentation_WellE06_0000` in the image there appear to be cells with label indices that are higher than the largest label index in the table.

I am pretty sure that this is not the case, because I am testing that the ids in the cell segmentation and in the table are identical: https://github.com/mobie/covid-if-project/blob/main/check_anchors.py#L31-L32 (and this tests runs through without error)

**Comment by tischi** [comment]
Hm, this is mysterious...
Did you also see my [comment above](https://github.com/mobie/mobie-viewer-fiji/issues/541#issuecomment-980431198) about the anchor point of cell `132`?

**Comment by constantinpape** [comment]
> Hm, this is mysterious...
> Did you also see my [comment above](https://github.com/mobie/mobie-viewer-fiji/issues/541#issuecomment-980431198) about the anchor point of cell `132`?

Yes, I am not sure what's going on there but it maybe that the coordinate origin is different between python and BDV here.
(I guess this could be the case because we have the first true 2d project here.)
I will try to check this by comaring the image in MoBIE and napari later.

**Comment by tischi** [comment]
> I will try to check this by comparing the image in MoBIE and napari later.

Thanks! Another thing to double check could be whether maybe the assignment of the tables to the images got mixed up at some point? I am not sure, but maybe good to have in the back of your mind when you are looking in it. It cannot be an issue with the MergedGridSource however, because the issue with the wrong anchor points is already there when we are loading just a single image...

**Comment by constantinpape** [comment]
> Thanks! Another thing to double check could be whether maybe the assignment of the tables to the images got mixed up at some point?

Yes that's it, for some reason it got shuffled in the spec ...
I will fix it.

**Comment by constantinpape** [comment]
@tischi I fixed the table paths now and it works as expected for the single image.
It still looks a bit weird for the grid but I only checked very briefly, so not sure.
Time for you to have another look ;).

**Comment by tischi** [comment]
@constantinpape 
1. Yes, the single image works now!
2. The `default_transform_grid_...` view does not work for me in a sense that all sites end up on the same position. Could you please double check that the JSON is correct for that view? I would then double check the code.

**Comment by constantinpape** [comment]
> 2\. The `default_transform_grid_...` view does not work for me in a sense that all sites end up on the same position. Could you please double check that the JSON is correct for that view? I would then double check the code.

Ok, I will check it later.

**Comment by tischi** [comment]
In fact I had a glance and I have one suspicion. The flag `centerAtOrigin` now defaults to `true`. I guess if we build grids of grids (as we do for the sites, wells, plate), we may loose what the first grid has done if we don't set `centerAtOrigin = false` at the right places. But I am not sure yet, I have to dig a bit...

**Comment by tischi** [comment]
@constantinpape 

I [fixed this](https://github.com/mobie/covid-if-project/commit/a9c22bd7f045fb9b2ef6d6b94af98d8db74088f4) and it is now working for the transformed grid.

I will have a look now at the merged grid.

**Comment by tischi** [comment]
@constantinpape 

For me it also navigates to the correct position for the merged grid.

I will ping you once this is on MoBIE beta.

**Comment by K-Meech** [comment]
@tischi @constantinpape latest version is on MoBIE beta now :)

**Comment by constantinpape** [comment]
Everything working on MoBIE-beta now. Thanks!
