### ISSUE TITLE
Add a test for opening project directly from s3

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#552]
The plankton fibsem project is completely uploaded to s3: `https://s3.embl.de/plankton-fibsem`.
And I just checked that it can be opened - seems to all work fine :).
We should add a test that opens this project to make sure it stays that way ;).

**Comment by tischi** [comment]
Done via https://github.com/mobie/mobie-viewer-fiji/commit/8e78f3d14d2b124969d9d907b2cb2659c4309beb

It opens indeed :)

Anything we could test there in particular?

**Comment by constantinpape** [comment]
Not sure what exactly you can test in the current CI tests; maybe if datasets and views are available and can be loaded?
If that's possible then you could test for the datasets:
- `cell1`
  - `views`: `Figure6F`, `fibsem-cell`, `fibsem-cilia`, `fibsem-raw`
- `cell2` 
  - `views`: `FigureS20F`, `fibsem-nucleus`, `fibsem-raw`
- `choanocyte-chamber`:
  - `views`: `fibsem-segmentation`, `fibsem-raw`

**Comment by tischi** [comment]
I am simply opening all available views: https://github.com/mobie/mobie-viewer-fiji/commit/51050012970c664cf6906c3b3cb92168f6478ac6

Seems like a good way to test projects in general (unless it would take to long).
What do you think?

**Comment by constantinpape** [comment]
> I am simply opening all available views: [5105001](https://github.com/mobie/mobie-viewer-fiji/commit/51050012970c664cf6906c3b3cb92168f6478ac6)

I think it would be good to also check that all the datasets above can be loaded (as far as I can see you only open the default one in the test) and to also check that some of the names - or the number of views - are as expected. Otherwise you might miss bugs that prevent opening other datasets or just drop all the views and iterate over an empty list.
