### ISSUE TITLE
Screenshot not working?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#555]
Giulia wrote an e-mail that the screenshot is not working for her in the CLEM example project.

**Comment by tischi** [comment]
- [ ] It shows Pixels as the unit even though the images are in micrometer...?!

**Comment by tischi** [comment]
> So from the Users POV, I would find more “dumb proof”  if the descriptions were more unambiguous, like "image size in pixels xy"
And the first line could be about the “binning” or the “resolution”, I am not sure about the best phrasing, maybe you have a better idea for it.  In the second place, I think the default value should be 512 or 1024, something that clearly points out to the size of the image. 
Hope this helps and I am happy to do more dumb proofing as we progress.

**Comment by tischi** [comment]
pixel unit: https://forum.image.sc/t/change-scijava-parameter-label-at-runtime/60574/3

**Comment by tischi** [comment]
I called it now "Screenshot Sampling" and it will automatically add the correct unit.
I don't know how to tell the user the number of pixels. I feel that the pixel size (sampling) is the scientifically most interesting/accurate information. I admit that it will require a bit of thinking on the user side though: They need to have a look at the current scale bar and guess how many pixels this will be.

...just had an idea how to add a callback that would show this information...!

**Comment by tischi** [comment]
🥳 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/2157566/145004262-ae267436-42f1-49a1-bdd8-985aae30a850.png">

It will update the capture size when you modify the sampling.

**Comment by K-Meech** [comment]
@tischi This fix is on MoBIE-beta now :)
