### ISSUE TITLE
AWS credentials issues

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#568]
@tischi, I don't know what you changed today about the AWS data storage, but now I can't open the platybrowser:
![Screenshot from 2022-01-14 18-48-31](https://user-images.githubusercontent.com/32451366/149561750-52b264f7-9d9d-47a1-9044-4f64770d3145.png)

**Comment by tischi** [comment]
I changed nothing, but I can reproduce it!

**Comment by titansmc** [comment]
Permissions have been fixed on the server side, we will investigate to find out what could have happened

**Comment by tischi** [comment]
Thanks!
