### ISSUE TITLE
Project Creator does not remember last choice

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#570]
It would be amazing if the Project Creator would remember the recent choices in the UI (such as the image file format). You could achieve this by storing the user choices in some static variables (if you use GenericDialog). If you use Commands the recent choices are remembered automatically.

**Comment by tischi** [comment]
@K-Meech I would give this a high priority.

**Comment by K-Meech** [comment]
I'm on it :) I'm fixing a bunch of stuff in the project creator over the next couple of days
