### ISSUE TITLE
Project creator affine

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#579]
@K-Meech 

I guess the affine is **on top of** the voxel size calibration, is it? Could you make this more clear in the project create?

<img width="624" alt="image" src="https://user-images.githubusercontent.com/2157566/150812066-8e852e2d-28e6-4ba4-b9f2-3cd8ce57df8f.png">

**Comment by K-Meech** [comment]
This was added quite early on - so it actually is directly the affine that goes in the xml i.e. including the voxel size calibration! It should probably be changed so it instead just adds it to the view

**Comment by tischi** [comment]
Yes, I think so. Could change it like this?
And than maybe:` [ ] Add additional registration view`?
And below this we put the UI for entering the affine?

**Comment by tischi** [comment]
Maybe better to leave it as it was but remove the option to create a view.
Let's just always create a view and if the affine is not the identity (you can check this on Java) add it to the view.

I would also suggest to have

```
row 1       1, 0, 0, 0
row 2       0, 1, 0, 0
row 3       0, 0, 1, 0
```

in the UI instead of the 12 numbers. Then it is very clear even without reading the help. 

What do you think?

**Comment by K-Meech** [comment]
Changing the affine to three rows sounds good! Makes it easier to see what's going on

For the view, I'd prefer not to get rid of this option. Sometimes, if you want to do something complicated with e.g. grids. It might be useful to be able to add an image (and have it be converted / made into a source etc), but not have its own view. I.e. if for some reason you have images that you only ever want to be viewed together.

Maybe there could just be another checkbox like, ```[] Add affine transform to view``` with the 3 rows of numbers below it?

**Comment by tischi** [comment]
> For the view, I'd prefer not to get rid of this option. Sometimes, if you want to do something complicated with e.g. grids. It might be useful to be able to add an image (and have it be converted / made into a source etc), but not have its own view. I.e. if for some reason you have images that you only ever want to be viewed together.

Yes, I thought about this as well, but you can't create a grid (or in fact any multi image) view with the project creator. I feel for the beginner users always having a view is good (they will otherwise wonder (i) "what is a view?" and (ii) "why can't I see my image?"). They could delete the view manually from the dataset.json if needed.

We could have a `Project Creator Expert Mode` at some point, but for the basic one I would keep it as simple as possible.
