### ISSUE TITLE
Add view to Project for S3

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#580]
@K-Meech 

Can we do this already (see title)?

**Comment by K-Meech** [comment]
Do you mean directly adding a view to the S3? If so, this isn't possible at the moment. You can only add it to a local project, or directly to github. The github stuff is still not the best / could do with some improvements though.

**Comment by tischi** [comment]
> Do you mean directly adding a view to the S3?

Yes, if the bucket has write access then we should be able to write an object there (i.e. replace the `dataset.json`).

[This handles the credentials](https://github.com/mobie/mobie-io/blob/26a07e4af364c6e47f66ed6340f9d1dde2074e68/src/main/java/org/embl/mobie/io/util/S3Utils.java#L59)

I think it could be great to add a `writeFile` method [here](https://github.com/mobie/mobie-io/blob/develop/src/main/java/org/embl/mobie/io/util/FileAndUrlUtils.java) that works for file system, github and s3 store.

What do you think? 
@constantinpape @KateMoreva

**Comment by constantinpape** [comment]
I agree, it would be great if we can write this to s3 as well (given that the user has write permissions)

**Comment by tischi** [comment]
I checked the code and it looks like yes.
