### ISSUE TITLE
Voxel size units

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#583]
@K-Meech 

I think the project creator needs to decide on one unit, maybe micrometer?!

Right now the affine transform would be wrong if the other images are scaled in micrometer units.

![image](https://user-images.githubusercontent.com/2157566/150947254-34f44b2b-b6a6-436c-9322-98aa7a26358f.png)

**Comment by K-Meech** [comment]
Yes - that's right! It just takes the size set under Image > Properties, but doesn't take the unit into account. I guess I should just warn of this somewhere? It's a bit hard to directly convert stuff as e.g. nanometer can be written nanometer, nanometre, nm, NM etc...

**Comment by tischi** [comment]
> It's a bit hard to directly convert stuff as e.g. nanometer can be written nanometer, nanometre, nm, NM etc...

I think the Bio-Formats library can do this for you...
@joshmoore is there something that tries to extract the pixel size from an ImagePlus?

**Comment by joshmoore** [comment]
_from_ an ImagePlus, I don't know. In the case that the ImagePlus was loaded with Bio-Formats, the underlying (meta)data should have pixel size incl. unit parsed if it was specified.

**Comment by tischi** [comment]
@K-Meech then maybe ask on the forum.
maybe there is some Java code to achieve this.

**Comment by K-Meech** [comment]
@constantinpape - how are units handled in python project creation? If someone adds an image with micron units, and another in nanometer - do you convert? Do you only accept certain strings for units? E.g. micron vs micrometer?

**Comment by K-Meech** [comment]
Ok - I've started looking into this. With the suggestions from the forum thread, I can convert between the different units now / check if different units are equivalent.
I don't think it's a good idea to hard-code a specific unit for project creation (e.g. micrometer). If you use MoBIE for something that's a lot bigger, like plants etc, this will get pretty annoying. We could instead specify a certain unit for the project, or dataset (although this would need to be stored somewhere in the spec?), and then convert whatever comes in to this unit.

I think the easiest solution for now is just to add details to the documentation / maybe as a message to the add dialog itself to tell people they need to consistently use the same unit. I will anyway implement something that takes the given unit and tries to find the equivalent unit from those recommended in the v0.4 ome-zarr spec. for this issue: https://github.com/mobie/mobie-io/issues/74

Thoughts? @tischi @constantinpape

**Comment by tischi** [comment]
I think the easiest may be for now:

1. take the first unit that is acceptable (UTF8) as the `projectVoxelUnit` 
2. throw an error when an image is added where `imp.getUnit() != projectVoxelUnit` or where `! imp.getUnit().isUTF8()`

**Comment by K-Meech** [comment]
The project creator now enforces a particular unit (determined by the first image added)
