### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#587]
@K-Meech 

I tried to make a new release that uses the latest mobie.io but I got those test errors.
Do you have any idea?

To reproduce:
```
git checkout tischi
git pull
mvn clean install
```

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.398 s - in tests.TestRemotePlanktonS3
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ImagesCreatorTest.addSegmentationBdvOmeZarr:227->testAddingSegmentationInCertainFormat:169 ? NullPointer
[ERROR]   ImagesCreatorTest.addSegmentationOmeZarr:237->testAddingSegmentationInCertainFormat:169 ? NullPointer
[ERROR]   ImagesCreatorTest.copyImageBdvOmeZarr:257->testCopyingImagesInCertainFormat:193 ? NullPointer
[ERROR]   ImagesCreatorTest.copyImageOmeZarr:262->testCopyingImagesInCertainFormat:193 ? NullPointer
[ERROR]   ImagesCreatorTest.linkToImageBdvOmeZarr:247->testLinkingImagesInCertainFormat:182 ? NullPointer
[ERROR]   ImagesCreatorTest.moveImageBdvOmeZarr:272->testMovingImagesInCertainFormat:204 ? NullPointer
[ERROR]   ImagesCreatorTest.moveImageOmeZarr:277->testMovingImagesInCertainFormat:204 ? NullPointer
[ERROR]   RemoteMetadataCreatorTest.createRemoteMetadataBdvOmeZarr:84->testAddingRemoteMetadataForCertainFormat:65 ? NullPointer
[INFO] 
```

**Comment by K-Meech** [comment]
I'll have a look. Is it the main or develop branch?

**Comment by K-Meech** [comment]
Ok - so I had a very quick look. And I think the issue is that while the readers have been updated for version v0.4, the writers haven't (this is on my todo list - but haven't done it yet!). As some of the files I use in the writing are also used in the reading, they're giving unexpected effects. e.g. the .zattrs file of an ome-zarr file written with project creator, now looks like this:

```
{
  "multiscales": [
    {
      "axes": [
        "z",
        "y",
        "x"
      ],
      "datasets": [
        {
          "path": "s0",
          "transformations": null
        }
      ],
      "name": "testImage",
      "type": "Average",
      "version": "0.3.0",
      "transformations": null
    }
  ]
}
```
where before it contained no 'transformations'. I can look into this when I update the writing code.

**Comment by tischi** [comment]
@constantinpape 
Should I release it on MoBIE-beta anyway (s.a.)? 
If it is not very important I would prefer not to...

**Comment by constantinpape** [comment]
@tischi I need it to demo 0.4 for the meeting tomorrow, so it would be really good if we can release it anyways.

**Comment by constantinpape** [comment]
@K-Meech if you still have time today could you make the MoBIE-beta release and write here?
If not, could you try to get it out tomorrow before 10, @tischi?

**Comment by tischi** [comment]
OK, I'll release now anyway...

**Comment by tischi** [comment]
@constantinpape done. let us know if it works for what you want to show.

**Comment by constantinpape** [comment]
Thanks @tischi. I can open ome.zarr v4, but I am not quite sure if all the metadata is read correctly. For example, this is the data from https://minio-dev.openmicroscopy.org/idr/v0.4/2022-01-05/idr0062/6001240.zarr (a dataset the OME folks are using)
![image](https://user-images.githubusercontent.com/4263537/151325703-61537fa2-aa95-4ba8-82f7-1514001556c6.png)

I will check with data I know better later and write a proper issue if I can identify issues.

**Comment by constantinpape** [comment]
See https://github.com/mobie/mobie-io/issues/52 for the current issues with reading 0.4 data.

**Comment by K-Meech** [comment]
The changes @KateMoreva just made to the develop branch of mobie-io, mean that these tests pass now. I would still wait for the other reading issues to be fixed though / for me to check the writing.
