### ISSUE TITLE
Create a project with Java scripting

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#591]
How are you doing in terms of Java API for the ProjectCreator?
It would be really good if one could create/edit a project by means of Java scripting (Groovy or Jython).

**Comment by K-Meech** [comment]
Good point! Do I need to do anything extra to make it available via Groovy or Jython? I think most of the functions are already there on the Java side + I could easily add a page to mobie.github.io to show how to do this.

**Comment by tischi** [comment]
You do not need to do anything special!

If the Java API works you just create an example script and test that it works in the Fiji script editor in MoBIE-beta.

This would be super useful for larger projects!

**Comment by K-Meech** [comment]
I'm going to close this, as this is now possible on the latest MoBIE/MoBIE-beta - with details here: https://mobie.github.io/tutorials/scripting_project_creator.html
