### ISSUE TITLE
Automatically split and add multi-channel images

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#599]
@K-Meech 

I guess multi-channel support is not enable yet?

Could we at least throw a more informative error?

<img width="671" alt="image" src="https://user-images.githubusercontent.com/2157566/153838195-caf08a56-cce5-4cd7-b30a-87f72193bf9d.png">

**Comment by K-Meech** [comment]
@tischi - I'm working on this now. We already have an issue for this here: https://github.com/mobie/mobie-viewer-fiji/issues/586. So I'll close this one.
