### ISSUE TITLE
Support time properly in project creator

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#602]
I currently don't read the ImagePlus 'frame interval', when converting. So anything other than 1 frame == 1 second, will be scaled wrong in the output.

**Comment by tischi** [comment]
> Do I just drop all the 'frame interval' data (i.e. how many seconds per frame) when writing to these formats?

I would still write it even though BDV cannot (yet) consume this, because, being optimistic, also other platforms than MoBIE/BDV may be able to open such data in the future.

**Comment by K-Meech** [comment]
Ok - sounds good. I'll write this for ome-zarr, but not for n5 (as I don't think there's a place for it to go in the xml?)

**Comment by tischi** [comment]
> as I don't think there's a place for it to go in the xml?

Correct, there is no place for it in the BDV-XML, afaik.

**Comment by K-Meech** [comment]
This was added in https://github.com/mobie/mobie-io/pull/69
