### ISSUE TITLE
Save current view: add new view to UI

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#606]
@K-Meech 

Could you try to change the code such that `Save current view` also adds the view to the MoBIE UI? (1) I think this is more intuitive. (2) I would need this for this: https://github.com/mobie/mobie-viewer-fiji/issues/605, because otherwise one cannot access the cropped source.

**Comment by K-Meech** [comment]
Yes - sounds good, I'll add this. Should this only happen when you save directly to the project, or also when you save to an arbitrary location on the filesystem?

**Comment by tischi** [comment]
Thanks! 
I think it should always happen.
