### ISSUE TITLE
Project Creator: Image dimensions

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#613]
@constantinpape @K-Meech 
I am writing a 2-D image and I am getting this:

```
cat SEM_Section_Set_1_0005.ome.zarr/.zattrs 
{
  "multiscales": [
    {
      "axes": [
        {
          "name": "z",
          "type": "space",
          "unit": "micron"
        },
        {
          "name": "y",
          "type": "space",
          "unit": "micron"
        },
        {
          "name": "x",
          "type": "space",
          "unit": "micron"
        }
      ],
      "datasets": [
        {
          "path": "s0",
          "coordinateTransformations": [
            {
              "type": "scale",
              "scale": [
                0.01,
                0.01,
                0.01
              ]
            }
          ]
        },
        {
          "path": "s1",
          "coordinateTransformations": [
            {
              "type": "scale",
              "scale": [
                0.01,
                0.02,
                0.02
              ]
            }
          ]
        },
        {
          "path": "s2",
          "coordinateTransformations": [
            {
              "type": "scale",
              "scale": [
                0.01,
                0.04,
                0.04
              ]
            }
          ]
        },
        {
          "path": "s3",
          "coordinateTransformations": [
            {
              "type": "scale",
              "scale": [
                0.02,
                0.08,
                0.08
              ]
            }
          ]
        },
        {
          "path": "s4",
          "coordinateTransformations": [
            {
              "type": "scale",
              "scale": [
                0.04,
                0.16,
                0.16
              ]
            }
          ]
        },
        {
          "path": "s5",
          "coordinateTransformations": [
            {
              "type": "scale",
              "scale": [
                0.08,
                0.32,
                0.32
              ]
            }
          ]
        },
        {
          "path": "s6",
          "coordinateTransformations": [
            {
              "type": "scale",
              "scale": [
                0.16,
                0.64,
                0.64
              ]
            }
          ]
        },
        {
          "path": "s7",
          "coordinateTransformations": [
            {
              "type": "scale",
              "scale": [
                0.32,
                1.28,
                1.28
              ]
            }
          ]
        }
      ],
      "name": "SEM_Section_Set_1_0005",
      "type": "Average",
      "version": "0.4"
    }
  ]
}
```

1. Is this on purpose that it is written as a 3-D image?
2. What about the down-sampling scales? ...there is nothing to downsample in the z-direction...

**Comment by K-Meech** [comment]
1. Yes - I'm writing it as a 3D image, because a lot of the writing code is the same as N5. I don't think N5/bigdataviewer supports not having 3 spatial dimensions? So it seemed easier to just write a z dimension of 1 for this case.
2. This is related to this issue: https://github.com/mobie/mobie-viewer-fiji/issues/179 There was a lot of discussion on the BigDataViewer issue too: https://github.com/bigdataviewer/bigdataviewer_fiji/issues/21 I think the chunk size is restricted to 1 in the z axis, but not the downsampling.  It was a bit complicated to find defaults that always display nicely when viewed in 3D in BigDataViewer.

**Comment by tischi** [comment]
I think we should test this.

I am pretty sure that the code of @KateMoreva can also read 2-D images into BDV.

**Comment by constantinpape** [comment]
> I am pretty sure that the code of @KateMoreva can also read 2-D images into BDV.

Yes, it can. For example: https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/yx.ome.zarr

**Comment by K-Meech** [comment]
Yes, it can be read. The issue is that the core of the ome-zarr writing code, is a lot of N5 writing code with small changes. Therefore, to write only 2D I'd need to make more extensive changes. I can look into it, but it will take a bit of time to fix.

**Comment by constantinpape** [comment]
> Yes, it can be read. The issue is that the core of the ome-zarr writing code, is a lot of N5 writing code with small changes. Therefore, to write only 2D I'd need to make more extensive changes. I can look into it, but it will take a bit of time to fix.

Ok, then I think we should move ahead with the release without changing this.
(Eventually it would be nice to have though.) Note that in this context the `is2D` flag is also relevant: https://github.com/mobie/mobie.github.io/blob/master/schema/dataset.schema.json#L11-L14

**Comment by tischi** [comment]
I am also not so sure whether we actually may want to save it 3-D in order to be able to assign a voxel size (for rendering) in z.

See here: https://github.com/ome/ngff/issues/103

**Comment by constantinpape** [comment]
> I am also not so sure whether we actually may want to save it 3-D in order to be able to assign a voxel size (for rendering) in z.
> 
> See here: [ome/ngff#103](https://github.com/ome/ngff/issues/103)

Indeed, to specify the slice thickness we need to save it as 3d data with a singleton dimension

**Comment by tischi** [comment]
Then let's leave it as is.
