### ISSUE TITLE
Project creator: default signin region

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#614]
@constantinpape 

Should we set the default S3 SignIn region to `""`?

**Comment by constantinpape** [comment]
yes, that's ok

**Comment by K-Meech** [comment]
I'll add this to the PR I'm currently working on

**Comment by K-Meech** [comment]
@constantinpape Is there somewhere to write the signing region for ome-zarr? At the moment, I only add the "s3Address" into the dataset.json. (for n5 the signing region  goes in the xml)

**Comment by constantinpape** [comment]
Done: https://github.com/mobie/mobie.github.io/commit/067bd401e34603e0c9c28d04c240500d19b3a996
The signingRegion can now be added like this:
```json
"ome.zarr.s3": {"s3Address": "...", "signingRegion": "us-east-1"}
```
(Note that it is optional)
