### ISSUE TITLE
ViewsSaver API

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#617]
@K-Meech 

To automatically save views I would need three new public methods in `ViewsSaver`:

```
public boolean saveViewToProject( View view, String viewName, boolean overwrite ); // without UI, projection location should be automatically determined from moBIE.

public boolean saveViewToFileSystem( View view, String viewName, String path, boolean overwrite  ); // without UI

public boolean saveViewToFileSystem( View view, String viewName, boolean overwrite  ); // pops up UI to choose the file path
```

Could you please add those?

They should return `false` if `overwrite` was `false` and the `viewName` exists already and they could thus not save it.

Sounds good?

**Comment by tischi** [comment]
I updated the comment above (in case you look only at the mail).

**Comment by tischi** [comment]
Probably better than returning a boolean would be for your methods to throw a `FileAlreadyExistsException`. Then the person (me) calling these methods can decide what to do in this case.

So, for example:

```
public boolean saveViewToProject( View view, String viewName, boolean overwrite ) throws FileAlreadyExistsException
```

Or something like this...

**Comment by tischi** [comment]
@K-Meech Should I work on it (you are busy, right)?

**Comment by K-Meech** [comment]
That would be great - thanks!
