### ISSUE TITLE
Project 2D?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#623]
@K-Meech 

I think we should give the user the choice whether a created project is 2D.

For example, I have a use-case where I start of with only 2D images, but then I would like to stack them in 3D (serial section TEM).

**Comment by K-Meech** [comment]
I guess this could be chosen right at the start (when the project is first created). Then for a 3D project we allow 2D + 3D images to be added, and for 2D, only allow 2D.

**Comment by K-Meech** [comment]
As the 'is2D' is specific for each dataset, I think I'll add this as a checkbox to the dialog for making a new dataset.
