### ISSUE TITLE
We cannot always close the ImgLoader

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#624]
```
MoBIE.closeSourceAndConverter( SourceAndConverter< ? > sourceAndConverter )
	{
		SourceAndConverterServices.getBdvDisplayService().removeFromAllBdvs( sourceAndConverter );
		String sourceName = sourceAndConverter.getSpimSource().getName();
		final ImgLoader imgLoader = sourceNameToImgLoader.get( sourceName );
		if ( imgLoader instanceof N5ImageLoader )
		{
			( ( N5ImageLoader ) imgLoader ).close();
		} else if ( imgLoader instanceof N5OMEZarrImageLoader ) {
            ( ( N5OMEZarrImageLoader ) imgLoader ).close();
        }

		sourceNameToImgLoader.remove( sourceName );
		SourceAndConverterServices.getSourceAndConverterService().remove( sourceAndConverter );

		// TODO - when we support more image formats e.g. OME-ZARR, we should explicitly close their imgloaders here too
	}
```

If one `imgLoader` serves several `sourceAndConverter` (such as for example when creating a `MaskedSource` from a `Source`) than this is not correct and can lead to the disappearance of that other source from BDV.

**Comment by tischi** [comment]
Maybe we also have to add to the 

MoBIE.sourceNameToImgLoader;

not only when loading a source but also when showing a view of any source, like this we could know whether the same image loader serves several sources.

A list `imgLoaderToSourceName` or even better `imgLoaderToSourceAndConverter` may be handy for this.

**Comment by tischi** [comment]
Indeed, _not closing_ the `imgLoader` would fix the issue.

@K-Meech I think we added this "because of you" 😄 
Could you describe again in which circumstances this was necessary?

Was it important get rid of the fetchers are was it an issue of the cache (memory)?

```
    imgLoader.close() {
        if (isOpen) {
            synchronized (this) {
                if (!isOpen)
                    return;
                if (fetchers != null)
                    fetchers.shutdown();
                cache.clearCache();
                isOpen = false;
            }
        }
    }
```

For the fetchers we may not need it anymore as we have shared queues now...maybe...

**Comment by K-Meech** [comment]
Yes this was probably related to this issue: https://github.com/mobie/mobie-viewer-fiji/issues/329
Leaving the imageloaders open + not clearing the caches was consuming a lot of memory!

**Comment by tischi** [comment]
I removed the closing of the image loaders for now from `develop`: https://github.com/mobie/mobie-viewer-fiji/commit/d9edcdba6727f4504263fc910e0ff17453dd9ccd

(probably a bad idea, but fixing this another way feels like quite some work...)

If you have a chance to test what happens now would be interesting. But first we would need to see whether for the platy-browser image data format we actually have and use the image loaders with the shared queue.

**Comment by tischi** [comment]
Closing, let's hope this works with the new "clear" button.
