### ISSUE TITLE
Add OME-Zarr files - Project creator

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#627]
I tried to add a couple of OME-Zarr images to a MoBIE project. I used the exporter shipped as part of BDV in Fiji to create those.

The project creator expects an XML file when adding images. The exporter however, does not create such. 

Does MoBIE need an XML?

**Comment by constantinpape** [comment]
> I used the exporter shipped as part of BDV in Fiji to create those.

Can you please specify exactly what you mean by this? What is the exact name of the plugin / how do you open it in the plugin menu?

> The project creator expects an XML file when adding images. The exporter however, does not create such.
> 
> Does MoBIE need an XML?

MoBIE does not need an xml for ome.zarr.

**Comment by martinschorb** [comment]
> Can you please specify exactly what you mean by this? What is the exact name of the plugin / how do you open it in the plugin menu?

plugins -> BigDataViewer -> OME ZARR -> Export current image as OME Zarr

**Comment by constantinpape** [comment]
> > 
> 
> plugins -> BigDataViewer -> OME ZARR -> Export current image as OME Zarr

I see. This plugin is part of the MoBIE installation and managed by @K-Meech. We have recently changed a few things in there for ome.zarr v0.4 export. This is not fully released (release is planned in the next few days). I can ping you once that is done; it probably doesn't make much sense to test with the current release.
(Please correct me if anything I wrote here is wrong, @K-Meech).

**Comment by martinschorb** [comment]
OK, I will try to import them using mobie-utils-python.

**Comment by K-Meech** [comment]
Yes - that's right. It would be best to wait for the full release, as some parts have been updated.
It should already be supported though if you go to 'add bdv format image', and make sure you select 'ome.zarr' as the image format in that dialog. (at least on MoBIE-beta)

**Comment by martinschorb** [comment]
OK, will try Beta and let you know.

**Comment by martinschorb** [comment]
Confirm Beta OME-Zarr works! 🚀 

I noticed some sampling issue in the downsampled chunks. This can be noticed in the corners:
![Screenshot 2022-03-02 at 15 25 12](https://user-images.githubusercontent.com/35071867/156380541-6244b354-ae58-44ef-9578-cc97b75ab8a3.png)

However, the project (`/g/emcf/Hamburg_XRay/MoBIE`) cannot be opened in MoBIE (release).

**Comment by K-Meech** [comment]
This chunking was an issue here: https://github.com/mobie/mobie-viewer-fiji/issues/572 which is now resolved in the latest version.
I think the version on MoBIE-beta has this fix, so if you write it again, it should hopefully disappear. Otherwise, you will have to wait for the full release.
