### ISSUE TITLE
Add, view, remove all buttons

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#630]
@constantinpape @martinschorb @K-Meech 

I maybe had an idea:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/2157566/156509976-82731527-501a-4016-bf56-4848cff27b37.png">

What about instead of only the [view] button there would also be an [add] button.

The [view] button would behave as if the view was "exclusive" and automatically remove all currently present sources before showing the view.

The [add] button would add the sources on top of what is currently visible already.

This may have some advantages:

1. We don't need the `isExclusive` tag anymore in the JSON spec
2. It gives more flexibility, maybe one really wants to overlay a complex view (that now typically would be exclusive) onto something that is visible already
3. I think it would cover Martin's request for a "remove all" button
4. Whenever the [view] button is pressed we can close the `ImageLoaders` and thereby clean up all the caches, otherwise we leave them open (@K-Meech would know what I am talking about)

What do you think?

In fact, now writing this, even simpler may be just that the current [view] button would always behave as [add] and we just add one more [remove all] button. This may be less clutter in the UI then two buttons and easier to understand. 

Or, for backward compatibility, we still support the `isExclusive` tag, but in the spec discourage setting it to true, because it removes flexibility, and we add a [remove all] button.

I think those are now three options 😄

**Comment by tischi** [comment]
Should we call it `add` now? It used to be called `view`. 
I feel would leave it as `view` which is more neutral in a sense that it could mean that the view is exclusive.

**Comment by martinschorb** [comment]
what about `add view` ?

**Comment by tischi** [comment]
`add view` is a bit long...

<img width="550" alt="image" src="https://user-images.githubusercontent.com/2157566/156581624-3a7e8d35-9b22-48ff-b473-2e9ed666d995.png">


I called the new button now `clear`. Is that the best name? It will remove all currently shown images from the viewer and close the ImgLoaders....

**Comment by K-Meech** [comment]
```clear``` sounds good to me

**Comment by martinschorb** [comment]
I suggest moving the clear button down below `location` to just above the sources/view list. (in the center where there is the `...` now)

**Comment by constantinpape** [comment]
I would also leave it at `view`.

> I suggest moving the clear button down below `location` to just above the sources/view list. (in the center where there is the `...` now)

I agree.

**Comment by constantinpape** [comment]
Is this all implemented now, @tischi?
