### ISSUE TITLE
float contrast limits crash

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#634]
Hi,

I have generated float OME-Zarr files. I can nicely open them in MoBIE-Beta, but when clicking `B` to change brightness it crashes.

Does that beta already contain the latest code supporting float type and negative intensities?

If you want to try, here's the files I just created using mobie-python-utils.

```
/g/emcf/Hamburg_XRay/MoBIE_new
```

**Comment by tischi** [comment]
Works 🥳 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/2157566/156613367-d7b8b1eb-a310-477b-a3cf-74375cbef114.png">


MoBIE-beta is not updated yet.

**Comment by tischi** [comment]
But VoxelSize is wrong (**pixels**)!
Is it also wrong in the OME-Zarr?

**Comment by martinschorb** [comment]
I provided
```Python
unit = 'micrometer'
resolution = [0.1625]*3
```

to `mobie.add_image`

@constantinpape am I doing something wrong?

**Comment by martinschorb** [comment]
script is here:
https://github.com/mobie/hamburg-xray-datasets

**Comment by K-Meech** [comment]
It might be that the mobie-io fix for reading the unit isn't on MoBIE-beta yet. I think the last github actions run on mobie-io failed - so I don't think the latest is on maven yet either. The version might need bumping in mobie-io again.

**Comment by constantinpape** [comment]
@martinschorb your script is correct and the data is as well (I just checked on `/g/emcf/Hamburg_XRay/MoBIE_new`). @tischi are you sure that you are the latest mobie.io develop branch according to https://github.com/mobie/mobie-io/issues/82#issuecomment-1056647104 it should be fixed there.

**Comment by tischi** [comment]
works!
