### ISSUE TITLE
Github actions failures

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#637]
All the 'build PR' runs succeed, but the 'build' runs fail. I.e. it works when a pull request is made, but then fails when it is merged into the develop or main branch.

It errors with:
```
  == Configuring Maven ==
  Performing deployment checks
  Error:  Release version, but release.properties not found
  You must use release-version.sh to release -- see https://imagej.net/develop/releasing
  Error: Process completed with exit code 1.
```

**Comment by tischi** [comment]
I am not sure that's it, but in general, only the first build will pass, because then the new jar cannot be shipped to maven anymore, because it does exist already (maybe unless we mark it as SNAPSHOT).

**Comment by K-Meech** [comment]
Yes - that will be some of the failures (when we don't increase the version, or -SNAPSHOT it). But, the last version on maven is 2.1.4, and develop is on 2.1.6 - so it seems like it really is failing in some cases...

**Comment by tischi** [comment]
Then it is probably the failure with the bdv.n5 plantkon?
You could check,e .g., here: https://github.com/mobie/mobie-viewer-fiji/runs/5446419586?check_suite_focus=true

**Comment by imagejan** [comment]
@K-Meech @tischi you shouldn't be committing release tags (i.e. those _not_ containing `-SNAPSHOT` to the main branch. Your `pom.xml` currently has:

https://github.com/mobie/mobie-viewer-fiji/blob/6444081cfa07c1e9389a7115fc7206f2802d882a/pom.xml#L12

If you want to make use of the SciJava tooling for releases, you need to always have `-SNAPSHOT` versions. The `release-version.sh` script will make sure to generate a release version and add and push a release tag (that will not be part of the main branch) that will trigger a release deployment. This is intended to ensure that there's always only a *single* commit pointing to a release version, and there's no ambiguous information about which commit corresponds to the deployed release.

**Comment by imagejan** [comment]
Also: I noticed that you don't define `ciManagement` in your POM:

https://github.com/mobie/mobie-viewer-fiji/blob/6444081cfa07c1e9389a7115fc7206f2802d882a/pom.xml#L72-L74

It seems to didn't set up CI with [`github-actionify.sh`](https://github.com/scijava/scijava-scripts/blob/main/github-actionify.sh).

**Comment by K-Meech** [comment]
Thanks @imagejan for the info! So we should keep everything as -SNAPSHOT, then run ```release-version.sh``` locally and push this to the master branch to make a release? Is that right?

Also, what should go in the ```ciManagement``` field? I thought we had set it up with github-actionify, so strange it is empty.

**Comment by imagejan** [comment]
> then run `release-version.sh` locally and push this to the master branch to make a release?

`release-version.sh` will take care of pushing the tag (provided you have configured push access correctly from the command line).

> I thought we had set it up with github-actionify

It seems @tischi tried to set it up manually in https://github.com/mobie/mobie-viewer-fiji/commit/ecfc0c202c2911f1274a5976e80c5ffba8f0b209

I suggest re-running `github-actionify.sh`, that will (hopefully) fill the `ciManagement` tag as required.

**Comment by K-Meech** [comment]
Ok - thanks @imagejan

@tischi @constantinpape @KateMoreva - what are  your preferences here (for the mobie-viewer-fiji and mobie-io repos)? To use the scijava way, we would need to keep everything as -SNAPSHOT and then use ```github-actionify.sh``` to make any releases.  If we bump the patch version for every fix though, this means we'd have to run this script a lot which is not ideal...

**Comment by tischi** [comment]
I think having SNAPSHOT versions and using the Scijava scripts is good.

Using SNAPSHOT will resolve the issue with the maven build failures and we will always have updated SNAPHOT versions on maven, which means that we do not have to build dependencies locally, which also means that it is not such an issue if we do not bump the patch version (which was mainly for us to keep better track).

Does this make sense?

**Comment by constantinpape** [comment]
I agree that it would be good to use SNAPSHOTs and the `release_version.sh` script to make proper releases is good.

> and then use `release_version.sh` to make any releases. If we bump the patch version for every fix though, this means we'd have to run this script a lot which is not ideal...

Why do you think this is not ideal, @K-Meech?

**Comment by K-Meech** [comment]
Sounds good! I was only concerned that if we want to bump the patch version for every small fix, then we have to remember to run this script every time to get that on maven (as a release version). If we're happy to just keep things at SNAPSHOT, then this is no problem!

Would we then only make releases for versions that end up in MoBIE-beta, or the main MoBIE site?

**Comment by constantinpape** [comment]
> Would we then only make releases for versions that end up in MoBIE-beta, or the main MoBIE site?

Ideally we would make a release for all the MoBIE-beta releases and would always push the exact same version onto MoBIE main (but ofc not every release needs to go onto main).
Would this work with our current setup?

**Comment by K-Meech** [comment]
Sounds good. Yes - that would work. I'd just need to re-run a few things to get the releases working + move both the main and beta branches to a SNAPSHOT version.

**Comment by tischi** [comment]
Thanks @K-Meech for taking care of this!

**Comment by constantinpape** [comment]
With #643 merged everything should be ready for the new release (including the main release). Do you have time to do that on Monday @tischi @K-Meech? (I am happy to do testing of new releases then)

**Comment by tischi** [comment]
@constantinpape 
I have no time on Monday, but I could do this tomorrow.
MoBIE-beta is fully functional now @K-Meech?

**Comment by constantinpape** [comment]
> @constantinpape
> I have no time on Monday, but I could do this tomorrow.

That's fine, just ping me when it's ready to be tested.

**Comment by K-Meech** [comment]
This is updated now + the actions are running properly
