### ISSUE TITLE
Improve ImageJ.net website

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#646]
@K-Meech Can you edit below website? (Top right corner there is an explanation).
https://imagej.net/plugins/mobie
If so, could you improve this a little bit, e.g. by providing a link to our github.io page?

**Comment by K-Meech** [comment]
It says I can't edit directly - I'd have to make a fork and then make PRs to change things. 
That's fine though - I can look at this later in the week.

**Comment by tischi** [comment]
I improved it somewhat. 
Will close for now.
