### ISSUE TITLE
N5 files no longer change setup name to match mobie image name (project creator)

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#655]
Writing N5 files now leaves the setup name as 'channel 1' etc, rather than changing it to match the image name. This is fine for most things, but causes issues with e.g. grid views.

I'll fix this next week.

**Comment by K-Meech** [comment]
Also, I should add a test for this to the project creator tests.

**Comment by K-Meech** [comment]
This is fixed on the current develop branch now. @tischi - can I update MoBIE-beta to the current develop branch? Or is there anything wip on there still?

**Comment by tischi** [comment]
Sure go for it!
I think in principle `develop` should _always_ be OK to be uploaded to MoBIE-beta.

**Comment by K-Meech** [comment]
Ok great - I'll do that then :)
