### ISSUE TITLE
Opening large grid view via s3 fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#662]
I am trying to open a large grid view via s3:
https://github.com/mobie/covid-if-project : `plate->full_grid`

Opening it fails: it takes roughly 3 minutes loading a lot of images and then just closes fiji:

https://user-images.githubusercontent.com/4263537/161942775-3b68cfed-205e-44be-b6dd-e60678499994.mp4

Note that this project can be loaded locally (but also takes quite some time) from
`/g/kreshuk/pape/Work/mobie/covid-if-project`

**Comment by tischi** [comment]
Can you please add a view _without_ tables?
I think the tables take even longer than the images...
Then we can optimize image loading first and think about the tables later.

**Comment by constantinpape** [comment]
I have added `merge-grid-no-tables` now.
See https://github.com/mobie/mobie-viewer-fiji/issues/664#issuecomment-1090163185 for the corresponding transformedGrid view.

**Comment by tischi** [comment]
My first suspicion was that the multi-threading is different for local and remote, but it looks like we have the `sharedQueue` implemented for both `OmeZarr` nor `OmeZarrS3`:

https://github.com/mobie/mobie-io/blob/ab0361989b4e1e9f1e6187a18b48e59cb50bd69b/src/main/java/org/embl/mobie/io/SpimDataOpener.java#L64

However, not yet for `BdvOmeZarr` nor `BdvOmeZarrS3`...

See also here:
https://github.com/mobie/mobie-viewer-fiji/blob/f8e4891f7b37d5ce712b7f358e2fc2e58bf42d57/src/main/java/org/embl/mobie/viewer/MoBIE.java#L347

But @constantinpape we are using `OmeZarrS3`, isn't it?

- [ ] Anyway, @tischi should check with `VisualVM` whether the `sharedQueues` are properly working.

**Comment by tischi** [comment]
It does use this code `OMEZarrS3Opener.readURL(path, sharedQueue)` but it looks like that this is not working properly (too many Fetcher threads):

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/2157566/162163364-512a2309-fd65-48a8-9934-bea86836fe78.png">

@KateMoreva could you please double-check whether the `sharedQueues` are really used in ``OMEZarrS3Opener.readURL(path, sharedQueue)`?

**Comment by constantinpape** [comment]
> However, not yet for `BdvOmeZarr` nor `BdvOmeZarrS3`...

I don't think we need the shared queues for this, since both data formats are not needed any more since we have ome.zarr v0.4, which can store resolution information.

**Comment by constantinpape** [comment]
> But @constantinpape we are using `OmeZarrS3`, isn't it?

Yes.

**Comment by KateMoreva** [comment]
@constantinpape, could you please try again with the new `develop`?

**Comment by constantinpape** [comment]
> @constantinpape, could you please try again with the new develop?

@tischi can you please give this a try?

**Comment by tischi** [comment]
Looks good ❤️ much less threads (I will upload to MoBIE-beta later so @constantinpape can test).

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/2157566/163347039-c82913cb-96d1-453d-9f78-e2e868bcc9b3.png">

**Comment by tischi** [comment]
@constantinpape the eagle has landed (on MoBIE-beta).

**Comment by constantinpape** [comment]
Yes, it works now! (Still takes fairly long to load via s3, but let's tackle this later.)
