### ISSUE TITLE
Select table position from image

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#663]
Is it possible to select a table position from the image location in the grid views?
I tried both with `Ctrl + Left` and `Shift + Left`, but it does not do anything.

For some more context: I have a grid view with a table `sites` and then activate (only) the `sites` in the image. Now I would like to somehow get from the image position to the corresponidng table row; this would be very helpful for navigation:

![image](https://user-images.githubusercontent.com/4263537/161945626-c9e1a3cb-5e21-49ae-b6a8-3403e081b7c1.png)

**Comment by tischi** [comment]
Hm, good point. I thought this should work.
Do you have a minimal example, e.g. with only one well?
Such that I could have a look...

**Comment by constantinpape** [comment]
> Do you have a minimal example, e.g. with only one well?

If you just open the project at https://github.com/mobie/covid-if-project it will open a small grid with only 2 wells.
(view: `default`) This can be opened without issues from s3, so should be fine for you to test this.

**Comment by tischi** [comment]
It looks like this is not supported yet.

It also looks like there is no quick fix but one should spend at least half a day to fix this properly.

### Current

The `SliceViewer` (i.e. BDV) implements this code:
```
final BdvSegmentSelector segmentBdvSelector = new BdvSegmentSelector( bdvHandle, is2D, () -> viewManager.getSegmentationDisplays() );

behaviours.behaviour(
	( ClickBehaviour ) ( x, y ) ->
			new Thread( () -> segmentBdvSelector.run() ).start(),
	"Toggle selection", "ctrl button1" ) ;
```

`viewManager.getSegmentationDisplays()` only returns the currently visible `SegmentationSourceDisplay`, which is used for segments in label mask images, but whole images (e.g. in a grid view) are colored by and linked to a table by an `AnnotatedIntervalDisplay`.

Potentially good news: Both `SegmentationSourceDisplay` and `AnnotatedIntervalDisplay` inherit from `AnnotatedRegionDisplay`.

### Future

Could the `Ctrl+Left click` work on `AnnotatedRegionDisplay` and thus cover both `SegmentationSourceDisplay` and `AnnotatedIntervalDisplay` (along with generalizing the `BdvSegmentSelector` to an `BdvRegionSelector`)?

**Comment by constantinpape** [comment]
> Could the `Ctrl+Left click` work on `AnnotatedRegionDisplay` and thus cover both `SegmentationSourceDisplay` and `AnnotatedIntervalDisplay` (along with generalizing the `BdvSegmentSelector` to an `BdvRegionSelector`)?

That sounds good! I guess one question is what happens if multople `AnnotatedRegionDisplay`s are activated, e.g. a segmentation and a sourceDisplay. How does this currently work for the case when two (overlapping) segmentations are active?

**Comment by tischi** [comment]
> How does this currently work for the case when two (overlapping) segmentations are active?

```
for ( SourceAndConverter< ? > sourceAndConverter : segmentationSourceAndConverters )
{
    ...
    segmentationDisplay.selectionModel.toggle( segment );
}
```

It just toggles the selection of all of them, which I guess is good?

**Comment by constantinpape** [comment]
> It just toggles the selection of all of them, which I guess is good?

Yes, that's good! (And also good if we add support for sourceDisplays)

**Comment by tischi** [comment]
This works now with `Ctrl + Left Click` in the image.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/2157566/164912232-011e926a-4c42-48ab-a2ff-bfef1254ef81.png">

Annoyingly the BDV window also centers on the, e.g., site that was clicked on (_when selecting in the BDV window_), i.e. it makes the thing that you clicked on move away under your mouse. 

- [ ] I think this is not the case for a segmentation label? Find the difference and implement the same for the annotated regions.

**Comment by tischi** [comment]
In fact, it also centers the BDV window on the segment for label mask images, when selecting them in the BDV window.
I find that annoying. 

Opinions?
@constantinpape @K-Meech ?

**Comment by constantinpape** [comment]
It works now, thanks! This makes navigation of large grid views so much easier.

> In fact, it also centers the BDV window on the segment for label mask images, when selecting them in the BDV window.
> I find that annoying.

Yes, I also find it annoying and would vote for not changing the view when selecting sources or segments via `Ctrl + Left` in the viewer. (it should still center when clicking on a row in the table though).

**Comment by K-Meech** [comment]
I agree with @constantinpape

**Comment by constantinpape** [comment]
All done and working.
