### ISSUE TITLE
display annotation as borders 

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#670]
Hi,

it would be amazing to show annotations as border lines around images instead of just color overlay.

**Comment by tischi** [comment]
Class that generates the annotation overlay: `TableRowsIntervalImage`

Code and class that generates boundaries (from SegmentationAnnotator repo):
```
NeighborhoodNonZeroBoundariesConverter2< T > boundariesConverter = new NeighborhoodNonZeroBoundariesConverter2< T >( rai );
			RandomAccessibleInterval boundaries = NeighborhoodViews.neighborhoodConvertedView(
					rai,
					boundariesConverter,
					new HyperSphereShape( boundaryWidth ) );
```

It seems to be an option to wrap the Source that is created inside `TableRowsIntervalImage` into a `LabelSource` which has methods for toggling the boundaries (the code for this can be copied from the `LabelSource` in the SegmentationAnnotator, which looks more mature in that sense).

**Comment by tischi** [comment]
Making some progress, but it is very brittle, there are some issues with the volatile pixel values and concurrency. One needs to move around a bit in BDV until one gets the correct rendering without any artifacts.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/2157566/163157472-70b9222a-13a4-4b3e-9a46-4ae681a1dadc.png">

**Comment by constantinpape** [comment]
> Making some progress, but it is very brittle, there are some issues with the volatile pixel values and concurrency. One needs to move around a bit in BDV until one gets the correct rendering without any artifacts.

At least the image looks very good already :). Maybe you can just push the latest code you manage to get before you leave (also on MoBIE-beta) so I can give it a try before your back from your Easter break?

**Comment by tischi** [comment]
I still have to work on it for the Covid project, because the current code does not work on 2-D data, because then everything is a boundary ;-)

**Comment by constantinpape** [comment]
Ok :D

**Comment by tischi** [comment]
Right click: `Configure Label Rendering` 🥳 

<img width="428" alt="image" src="https://user-images.githubusercontent.com/2157566/163242901-259df755-2729-491d-9441-f0eca27a7b8b.png">

Was quite some work, but I found now also a much better and computationally more efficient way to do this. Thanks to this new implementation the size of the boundaries is now adjustable in calibrated units (e.g. 0.5 micrometer) (used to be pixels only).

- [ ] Before uploading this I want to also have a look at the issue that the boundaries are not correct for transformed sources.

**Comment by constantinpape** [comment]
This is great!

> Thanks to this new implementation the size of the boundaries is now adjustable in calibrated units (e.g. 0.5 micrometer) (used to be pixels only)

How do we set it? It would be handy to be able to adjust it for the figure.

> * [ ]  Before uploading this I want to also have a look at the issue that the boundaries are not correct for transformed sources.

Do you mean the issue from https://github.com/mobie/clem-example-project/issues/18 with this?

**Comment by tischi** [comment]
> How do we set it? It would be handy to be able to adjust it for the figure.

The [Configure Label Rendering] context menu will present a UI element for the boundary width 

> Do you mean the issue from https://github.com/mobie/clem-example-project/issues/18 with this?

yes

**Comment by tischi** [comment]
Note to self: working on this in branch `realMask`.

**Comment by constantinpape** [comment]
Just to confirm: works on current MoBIE-beta for the covid-if data now. Though it interacts a bit weirdly with interpolation when zooming in/out or panning. So I think that part could still be improved.
But it's sufficient for making the figures in any case. Thanks!
