### ISSUE TITLE
Several issues with "saveView"

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#672]
The json serialized by `save view` in the context menu has two issues that make it incompatible with the MoBIE jsonschema:

## selectedSegmentIds

The label id is saved as float, e.g. `1.0` instead of int `1`. This fails because the schema expects an int:
```
Failed validating 'pattern' in schema[1]['properties']['segmentationDisplay']['properties']['selectedSegmentIds']['items']:
    {'pattern': '^[^; \\/]+;\\d+;\\d+$', 'type': 'string'}

On instance['segmentationDisplay']['selectedSegmentIds'][0]:
    'fibsem-segmentation;0;94250.0'
```

## glasbey lut

Here, the value limits are serialized: `valueLimits: [null, null]`.
This fails because the value limits are expected to be a number:
```
Failed validating 'type' in schema[1]['properties']['segmentationDisplay']['properties']['valueLimits']['items'][0]:
    {'type': 'number'}

On instance['segmentationDisplay']['valueLimits'][0]:
    None
```
Note that `valueLimits` should not be serialized at all for glasbey, because they don't make sense for this colormap.

**Comment by constantinpape** [comment]
And there is another issue: the viewer transform is not serialized correctly:
I have saved the following view:
![sponge-screenshot](https://user-images.githubusercontent.com/4263537/164535607-5b32fbe8-8a81-41dc-9fee-e4618c5f3ba9.png)
But the view is saved with the axis aligned view:
![Screenshot from 2022-04-21 21-10-41](https://user-images.githubusercontent.com/4263537/164535756-ce8e6be2-1e8c-41bc-88c6-0c48bb869e88.png)
It's the following view: https://github.com/mobie/sponge-fibsem-project/blob/main/data/choanocyte-chamber/dataset.json#L99

**Comment by K-Meech** [comment]
I'll look into these issues @constantinpape. I'll also try and add a test that checks a view against the current schema.

**Comment by K-Meech** [comment]
This should be fixed on the current develop branch
