### ISSUE TITLE
Rendeting label masks as boundaries does not work for segmentations

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#673]
It would be nice if the label masks of segmentations could also be rendered as boundaries. This currently does not work, see

https://user-images.githubusercontent.com/4263537/164537965-86d1ac95-9bf5-44af-82a4-b4211ad4feb3.mp4

**Comment by tischi** [comment]
It does work, but you have to select a smaller boundary here, e.g. `0.2`.

Should I maybe make the default `1.0` to make it more obvious that decimal places are allowed?

Off topic: How do you upload those movies to the issues?

**Comment by constantinpape** [comment]
Thanks, it works! And now that the decimal place is shown it's also clear that decimal values can be used.
