### ISSUE TITLE
Transformed Grid Source Transformer: Finding Source Dimensions is slow

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#674]
In `TransformedGridSourceTransformer` this seems slow, probably because it needs to touch every source on S3/FS once:

```
final double[] cellRealDimensions = TransformHelper.getMaximalSourceUnionRealDimensions( sourceNameToSourceAndConverter, sources );
```

Likely the `MergedGrid` has the same issue.

**Comment by constantinpape** [comment]
Have you parallelized this already? If not that's probably an easy solution to speed this up significantly.

**Comment by tischi** [comment]
I think this is fixed now, because I "pre-touch" all sources (leading to the information being cached) during multi-threaded initial opening.
