### ISSUE TITLE
Defaults for centerAtOrigin

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#679]
Double check the default of `centerAtOrigin` for all implementations of: `AbstractSourceTransformer`

Somehow I remember that, for instantiation from JSON, one needs to do more than just set to some value in the field...

@constantinpape what do we say is the default in the spec?

**Comment by constantinpape** [comment]
The default is `true`.

> Somehow I remember that, for instantiation from JSON, one needs to do more than just set to some value in the field...

Yes, I also remember that there was something that needed to be changed, not 100% sure what exactly...

**Comment by constantinpape** [comment]
btw, the default I refered to was for `crop`. There it should be `true`. But if for the `transformedGrid` it makes more sense to set it to `false` that would be fine with me, see https://github.com/mobie/covid-if-project/issues/2#issuecomment-1107546099.

**Comment by tischi** [comment]
we have to decide for those four:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/2157566/164967301-d11150b8-2188-4625-a305-3a96fcc148c8.png">

**Comment by tischi** [comment]
- `AffineSourceTransformer` does not have `centerAtOrigin`, which probably makes sense?
- `CropSourceTransformer`: true?!
- `MergedGridSourceTransformer`: true?!
- `TransformedGridSourceTransformer`: true and then false?!  

It is a bit complicated: For the first grid I think you always want `true` => default `true` seems good in general. But if you then do second grid of a grid, it depends: for `TransformedGrid` you then want `false`, otherwise you delete the effects of the first grid; however for a  `MergedGrid` of a `MergedGrid`, you may want `true` again, because the _output_ of the first `MergedGrid` are _new merged sources_...

**Comment by constantinpape** [comment]
> * `AffineSourceTransformer` does not have `centerAtOrigin`, which probably makes sense?
> 

Yes, doens't need it.

> * `CropSourceTransformer`: true?!
> 
> * `MergedGridSourceTransformer`: true?!
> 
> * `TransformedGridSourceTransformer`: true and then false?!

Ok, I would then leave it as `true` for all cases, and for the more `transformedGrid` it needs to be done correctly by whoever creates the project -- I think having different default values depending on nesting grids gets to complex and should be the user's responsibility.

**Comment by tischi** [comment]
I checked, and also the `MergedGridSourceTransformer` needs to have the `centerAtOrigin` set to false when operating on already transformed sources. Thus, it seems as if both grid transformers have the same behavior here (first run: `true`, second run: `false`)

**Comment by tischi** [comment]
> Ok, I would then leave it as `true` for all cases, and for the more `transformedGrid` it needs to be done correctly by whoever creates the project -- I think having different default values depending on nesting grids gets to complex and should be the user's responsibility.

Ok! Could you then change the `default` view in `covid-if` accordingly for testing this? Currently also the second round of grid building uses `centerAtOrigin=true`:

```
Merged 9 sources into E06_nuclei in 34ms (centerAtOrigin=true).
Merged 9 sources into E07_nuclei in 4ms (centerAtOrigin=true).
Merged 9 sources into E06_serumIgG in 3ms (centerAtOrigin=true).
Merged 9 sources into E07_serumIgG in 2ms (centerAtOrigin=true).
Merged 9 sources into E06_marker_tophat in 2ms (centerAtOrigin=true).
Merged 9 sources into E07_marker_tophat in 3ms (centerAtOrigin=true).
Merged 9 sources into E06_cell_segmentation in 2ms (centerAtOrigin=true).
Merged 9 sources into E07_cell_segmentation in 4ms (centerAtOrigin=true).
Merged 9 sources into E06_nucleus_segmentation in 4ms (centerAtOrigin=true).
Merged 9 sources into E07_nucleus_segmentation in 2ms (centerAtOrigin=true).
Merged 2 sources into plate_nuclei in 4ms (centerAtOrigin=true).
Merged 2 sources into plate_serumIgG in 6ms (centerAtOrigin=true).
Merged 2 sources into plate_marker_tophat in 3ms (centerAtOrigin=true).
Merged 2 sources into plate_cell_segmentation in 1ms (centerAtOrigin=true).
Merged 2 sources into plate_nucleus_segmentation in 3ms (centerAtOrigin=true).
```

**Comment by constantinpape** [comment]
`mergedGrid` should default to false, but you probably have this already, @tischi.
I think this is all done now, so I am closing the issue, feel free to reopen if anything is left to do here.
