### ISSUE TITLE
Rename annotation_id column?

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#681]
we could also just always call it `entity`...

-----

<img width="248" alt="image" src="https://user-images.githubusercontent.com/2157566/164916076-701c9745-ab9e-4ec5-acf6-3653a28a85d8.png">

This is now a bit confusing (`annotation_id` and `Annotate`), because they have nothing to do with each other, but I think this will be hard to change now...

_Originally posted by @tischi in https://github.com/mobie/mobie-viewer-fiji/issues/666#issuecomment-1107534815_

**Comment by constantinpape** [comment]
I agree that this is a bit confusing. I think on the python / spec side it would not be so much effort to change this and we only have a few projects that use the `sourceAnnotationDisplay` and associated tables, so updating these would also not be too much work.

**Comment by tischi** [comment]
It would also be easy to change on the java side.

Ideas:

- `region_id`
- `source_id` (this would match better the `sourceAnnotationDisplay`)

I realize one thing that confuses me with `source_id` as well as `sourceAnnotationDisplay` is that one can annotate multiple sources (=images) with one table row. 
I think that's also something that @martinschorb stumbled over when trying to use the spec. It would be nice to find a terminology that makes it more clear that one can annotated multiple images...

`sources_id` is ugly....maybe `region_id`.

**Comment by constantinpape** [comment]
I think `region_id` is good!

**Comment by constantinpape** [comment]
done
