### ISSUE TITLE
annotation mode: bug for non-numeric values

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#682]
It seems like the annotation mode does not support non-numeric values any more in the latest MoBIE-beta:

I have created a new column "manual_qc" for a sourceAnnotation table, with the two values "normal" and "outlier".
When I try to assign a row to one of these values, it throws the error "entered value must be numeric for column manual qc"

![image](https://user-images.githubusercontent.com/4263537/164973463-34b2b7d6-31f3-400a-8b50-ff949d84aa17.png)

**Comment by tischi** [comment]
I cannot reproduce this:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/2157566/164977308-aaf1d895-7f7f-4bff-8afc-b72ae4abf733.png">

**Comment by constantinpape** [comment]
I tried again and can't reproduce it either now. Not sure what happened there, gonna close it for now.
