### ISSUE TITLE
clear button does not remove annotations

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#692]
Hi,

when I clear all sources, the annotations stay.
Does it make sense to also clear any existing annotations? Or would an extra button to clear annotations make sense?
Is there a scenario where multiple annotations/tables are present in a MoBIE layout?

**Comment by constantinpape** [comment]
The annotations should also be removed. We don't want to introduce even more buttons, and I can't really think of a scenario where this would be useful.

**Comment by constantinpape** [comment]
Also fixed by the MoBIE-beta release.
