### ISSUE TITLE
Opacity displayed wrong

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#695]
Hi,

When I change the opacity of annotations to maximum, these turn white instead of keeping their colour.

**Comment by martinschorb** [comment]
This seems to be a general problem of opacity, also for images that it changes the display contrast instead of the actual opacity.

![Screenshot 2022-04-29 at 12 11 47](https://user-images.githubusercontent.com/35071867/165925873-1ae6b12d-249e-4b73-8310-272d94601b42.png)

**Comment by martinschorb** [comment]
also happens without an annotation present:
![Screenshot 2022-04-29 at 12 14 05](https://user-images.githubusercontent.com/35071867/165926233-8c0d1b10-4039-4be3-ba07-845a1d514c8c.png)

**Comment by tischi** [comment]
It is not really a bug, it has to do with our current definition of opacity (and having no good layering concept yet).

<img width="599" alt="image" src="https://user-images.githubusercontent.com/2157566/165952038-9d351409-e8d1-4111-8745-64582b079efe.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/2157566/165952103-23291bbb-c4fe-4bdb-ad90-6579325b2fd7.png">

It is just that if you add something very bright to something else very bright you get white.

Changing this is out-of-scope for now.

We could however try to come up with a better name instead of "opacity".

The code looks like this:

```
final int alpha = ARGBType.alpha( color.get() );
color.mul( alpha / 255.0 );
color.mul( opacity );
```

with

```
public void mul( final double c )
{
	final int value = get();
	set( rgba( red( value ) * c, green( value ) * c, blue( value ) * c, alpha( value ) * c ) );
}
```

So we are simply multiplying all RGB components with the `opacity`.

During rendering, every RGB that is `>255` will be clipped to `255`, thus it can become white.

I think "brightness" could be a better word, but we had `B` already assigned to the `ContrastLimits` ands `C` already assigened to `Color`, so I was running out of good letters....

Any suggestions (that do not involve developing a proper layering concept)? 

Ideally I would just change the names (and button labels).

**Comment by martinschorb** [comment]
so we are in RGBA space, then alpha should be adjusted, not the RGB values. 

Alpha of the current source (the one that is modified) needs to be multiplied with the opacity factor and all other alphas with `(1-opacity)`.

**Comment by martinschorb** [comment]
then the code above seems good. It is just that also the other elements (sources and annotations) need to be multiplied by `(1-c)`. That way the 255 will nor be exceeded and we won't run into the white-clipping situation. Is that feasible?

**Comment by tischi** [comment]
I created a branch and draft PR for this: https://github.com/mobie/mobie-viewer-fiji/pull/697

**Comment by tischi** [comment]
First good news, it looks like we can pull the `alpha` through to the Projector and apply it there (which is much nicer than the solution I had so far, where I applied it immediately):

```
		for ( int sourceIndex = 0; sourceIndex < accesses.length; sourceIndex++ )
		{
			final int argb = argbs[ sourceIndex ];
			final int a = ARGBType.alpha( argb );
			if ( a == 0 ) continue;
			if ( isOccluded( argbs, occludedBy.get( sourceIndex ) ) ) continue;

			final int r = ARGBType.red( argb );
			final int g = ARGBType.green( argb );
			final int b = ARGBType.blue( argb );

			final double alpha = a / 255.0;
			aAccu += a; // does this make sense??
			rAccu += r * alpha;
			gAccu += g * alpha;
			bAccu += b * alpha;
		}
```

Now we just would have to add some math to dim the other images accordingly, i.e. implement your `(1-c)` idea.

If you think about this, please keep in mind that whatever we implement must also work for fluorescence images, where the expectation is that the the intensity do simply add up.

**Comment by tischi** [comment]
Here are some formulas for inspiration: https://en.wikipedia.org/wiki/Alpha_compositing
As mentioned, I think the challenge will be to find something that generates the expected appearance for the fluorescence channels (without treating fluorescence differently, which would bring us back to defining more `blendingMode` metadata, which we had at some point and then removed again to reduce the complexity).

**Comment by martinschorb** [comment]
I think the key for us is `occluding`:

in general, we need to support two different blending modes.

- **additive** composition: default in BDV and well suited for flurescence sources
- **alpha** composition: for brightfield sources and annotations. Our current `occluding` is a subset of that.

### additive:
here alpha and also opacity can be entirely ignored (as in vanilla BDV). You just sum the RGB values until saturation.

### alpha:
This will add opacity to the `occluding` case. (Our present "occluding" basically means <img src="https://render.githubusercontent.com/render/math?math=\alpha= 1">)
So instead of replacing all underlying sources with the occluding source, you execute an alpha composition for each channel.

<img src="https://render.githubusercontent.com/render/math?math=C_n=\alpha_nI_n\,\!%2B\!\,(1-\alpha_n)C_{n-1}"> 

with `C` being the output blended value (`rAccu`,...) after adding each source and `I` the individual intensity (`r, g, b`).
Annotations should then be occluding as well.
The only annoying thing that we need to consider here is related to the "zeroValue" 
https://github.com/bigdataviewer/bigdataviewer-playground/issues/250

so here we need to introduce a catch for zero-value pixels to become additive instead. 
Otherwise Annotations (or any sources with a lot of zeros) would entirely overwrite everything.

**Comment by martinschorb** [comment]
in fact the zero-value issue is even easier, because at every pixel there should be a value for `a`. So in the *additive* case we just need to set that to zero: `if r+g+b ==0: a = 0`

**Comment by tischi** [comment]
Looking promising:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/2157566/166224359-d98ea07e-bc0b-4ff1-98be-07171ee42460.png">

<img width="708" alt="image" src="https://user-images.githubusercontent.com/2157566/166224384-df8290da-554b-4ba4-8cde-42e3a6ee8f49.png">

But there seem to be now two separate functions of the `alpha` of one source: If the source is occluding, we do `* (1-alpha)` of the previous sources, but if the source is not occluding we should do `* alpha` of the source itself? 
Is that correct?

**Comment by martinschorb** [comment]
I think for a *non-occluding = additive* source, opacity should just multiply the intensity values that will be added and not touch the underlying sources.

**Comment by martinschorb** [comment]
so exactly as you have it

> ```
>                         rAccu += r * alpha;
> 			gAccu += g * alpha;
> 			bAccu += b * alpha;

**Comment by tischi** [comment]
OK, this seems to work quite well:

```
			final double occludingAlpha = occludingAlpha( argbs, occludedBy.get( sourceIndex ) ) / 255.0;

			if ( ! isOccluding.get( sourceIndex ) )
			{
				rAccu += r * alpha * ( 1 - occludingAlpha );
				gAccu += g * alpha * ( 1 - occludingAlpha );
				bAccu += b * alpha * ( 1 - occludingAlpha );
			}
			else
			{
				rAccu += r * ( 1 - occludingAlpha );
				gAccu += g * ( 1 - occludingAlpha );
				bAccu += b * ( 1 - occludingAlpha );
			}
```

But, for the LM tomo, which is both occluding itself and also occludedBy the HM tomo, it behaves weird:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/2157566/166227473-64e9640d-f00b-4ffc-9fcd-56887dd7528d.png">


The LM does indeed become more transparent, but somehow also the HM becomes brighter....
Not sure yet why...

**Comment by martinschorb** [comment]
So the only thing left do check is zero-values...?

**Comment by tischi** [comment]
Yes, running in that right now in fact...
Would you have time again to come?

**Comment by martinschorb** [comment]
unterwegs...

**Comment by tischi** [comment]
@constantinpape 

```
BlendingMode blendingMode = display.getBlendingMode();
// https://github.com/mobie/mobie-viewer-fiji/issues/695
// we decided to make all label source occluding
blendingMode = BlendingMode.SumOccluding;
```

@martinschorb Were working on the blending and find that all annotations and segmentation should probably always have the `BlendingMode.SumOccluding`. 

Should we:

a) remove the ability to adjust this from the spec?
b) change the blending mode to `SumOccluding` in all our dataset.json?

By the way: it looks much better now, because the annotations maintain their color:


## Opacity 0.5

<img width="701" alt="image" src="https://user-images.githubusercontent.com/2157566/166241191-8c9180cc-95e5-4358-9208-b3f53053498f.png">

## Opacity 1.0

<img width="702" alt="image" src="https://user-images.githubusercontent.com/2157566/166241287-7eb4ed91-8c19-4567-ba55-2c26ed68bfed.png">

**Comment by constantinpape** [comment]
> a) remove the ability to adjust this from the spec?
> b) change the blending mode to `SumOccluding` in all our dataset.json?

Do you think there is any reason that this should ever be changed to `sum` for segmentations?
If not, then I would go with a) and remove it from the spec for `segmentationDisplay`.

For `sourceAnnotationDisplay` it's currently not in the spec.

**Comment by tischi** [comment]
I'd be for removing it from the spec.

**Comment by constantinpape** [comment]
> I'd be for removing it from the spec.

Done.

**Comment by constantinpape** [comment]
This should be fixed with the current MoBIE-beta. @martinschorb could you check that it actually works and then close this issue?

**Comment by martinschorb** [comment]
Confirm it works in beta.
