### ISSUE TITLE
What's here?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#698]
In the CLEM example it is very hard to navigate and one would really like to know which source is where.

@martinschorb and I discussed adding a "What's here?" item to the context menu, which would print the sources under the mouse pointer to the log window (since one may need this quite often a keyboard shortcut would be good as well).

One alternative could be to constantly listen to the mouse pointer position and display the source names somewhere in the BDV window.

What do you think? @constantinpape @K-Meech?

**Comment by constantinpape** [comment]
From a user perspective I would prefer not to create a new entry in the context menu and always show the name of the current source(s) under cursor somewhere in the bdv window.
But if that's harder too implement, or causes performance degradation, we can also go with the context menu entry.

**Comment by tischi** [comment]
> But if that's harder too implement

I will have a look. I was mainly worried about cluttering the BDV window. 
I guess it would be nice to be able to turn this on and off.
Maybe one more context menu item for "Settings", into which we could combine some things?

**Comment by K-Meech** [comment]
I'm not sure about displaying directly in the bdv window - if you have a lot of layers e.g. EM / LM / segmentations etc. it could be a lot of names to display. I kind of think the 'F' button + being able to toggle sources on and off is already enough? But I guess being able to display the sources at an exact position is useful too.

**Comment by martinschorb** [comment]
> the name of the current source(s) under cursor somewhere in the bdv window.

This can be dozens, so it might be indeed cluttering wherever we show it..

**Comment by tischi** [comment]
### Use case

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/2157566/166416183-6b073e2a-ef9a-46a9-b226-a3ab25b779c3.png">

I want to change the brightness of the green fluorescent image currently shown in BDV. How do I find out which one it is? Currently one has to do trial and error (switching on and off) on the left, which is annoying (not practical), if there are many.

**Comment by martinschorb** [comment]
> I want to change the brightness of the green fluorescent image currently shown in BDV.

What about changing the display in the sources list based on the viewer?
All sources that are currently not visible will be greyed-out (or smaller font,...) the ones that are shown stay normal and the ones that are underneath the current cursor position will turn bold.

**Comment by martinschorb** [comment]
Maybe also the saturation of the background colour could change.

**Comment by tischi** [comment]
I though of displaying an `*` next to the sources under the mouse cursor, but then we have this issue that when you move the mouse to change the color of one of those source, the star would disappear.

**Comment by martinschorb** [comment]
If you use what's currently visible in the viewer to adjust the list style, the mouse position wouldn't matter and you could simply zoom in to find out at one specific position.

**Comment by tischi** [comment]
I made a PR for us to work on this issue: https://github.com/mobie/mobie-viewer-fiji/pull/699

I like the idea:
- Listen to the sources the are visible in the current field of view
- Add stars for those sources to the MoBIE UI.

I am not sure how easy it will be to implement this.
Right click and "Log sources at mouse position" would certainly be much easier.

**Comment by tischi** [comment]
- [ ] SourceDisplay interface: Add getMask()?
- [ ] SourceDisplay interface: Maybe getRealInterval would be sufficient?
    - This would allow checking whether a SourceDisplay is currently visible in BDV in terms of intersecting with the current view (without checking all the individual sources, which may be expensive)
    - For this to work correctly, the SourceDisplay would need to listen whether the Transformation of one of the containing sources was changed and then accordingly update the mask.
- [ ] SliceView and AbstractSliceView could contain the getRealInterval() method (s.a.) to indicate the union location of all sources that are displayed in this SliceView. Then SourceDisplay.getSliceView().getRealInterval() would be used.

**Comment by tischi** [comment]
> Add stars for those sources to the MoBIE UI.

Or, in fact, only show the sources in the display settings list that are currently visible in BDV (I think that was what @martinschorb suggested above?).

**Comment by tischi** [comment]
I think with the "overlay names" functionality this is maybe covered for now.
Please reopen if you disagree.
