### ISSUE TITLE
annotations LUTs and views

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#707]
When annotating, the colours of the IDs can be chosen freely.
These are then also displayed in the viewer. 
At the moment these colour assignments are lost when changing to another LUT or re-loading the project.
Can they be made available as custom LUT that we store with the dataset?

**Comment by constantinpape** [comment]
> When annotating, the colours of the IDs can be chosen freely.
> These are then also displayed in the viewer.

I don't quite understand what you mean by this. Do you mean when using the annotation mode?
Can you please make a video / screenshot to illustrate the problem?
