### ISSUE TITLE
Save glasbey random seed

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#708]
To fully reproduce the view for segmentations / region annotations we would need to also save the random seed used by it.
What do you think @K-Meech, @tischi?
We could add it as field `glasbeyRandomSeed` to the corresponding displays.

See use case in #706.

**Comment by tischi** [comment]
> We could add it as field glasbeyRandomSeed to the corresponding displays.

Sounds useful to me.

**Comment by constantinpape** [comment]
> Sounds useful to me.

Cool! I will add it to the spec so you can integrate it into the viewer once you have time.
(This is not urgent, we found another solution for the paper figures, but I think it would still be nice to have.)

**Comment by tischi** [comment]
@K-Meech Do you want to do look into this? If you have other things to do, no problem, I can do it as well.

**Comment by constantinpape** [comment]
I added it to the jsonschema now: there's `glasbeyRandomSeed` for both segmentation and source annotation display.

**Comment by K-Meech** [comment]
@tischi I don't think I'll have time to do this this week. Could you look into it?

**Comment by tischi** [comment]
I can do it, pending https://github.com/mobie/mobie-viewer-fiji/pull/722

**Comment by tischi** [comment]
@constantinpape 

1. Should we also rename this to have the word "Label" in the name? `Change Random Coloring Seed [ Ctrl L ]`
2. Or should we even also move this into the `Configure Label Rendering`?!

I'd be for (2).

**Comment by tischi** [comment]
Another thing. In the code we have: `CategoryColoringModel` with code like this:

```
@Override
	public void convert( T input, ARGBType output )
	{
		if( ! inputToColorMap.keySet().contains( input ) )
		{
			final double random = createRandom( inputToColorMap.size() + 1 );
			inputToColorMap.put( input, new ARGBType( argbLut.getARGB( random ) ) );
		}

		output.set( inputToColorMap.get( input ).get() );
	}

	private double createRandom( double x )
	{
		double random = ( x * randomSeed ) * goldenRatio;
		random = random - ( long ) Math.floor( random );
		return random;
	}
```

In practice we right now always initialize this with the glasbeyLut, but we could also support other random LUTs.

Should we thus rather say: `randomColorSeed` instead of `glasbeyRandomSeed`?

**Comment by constantinpape** [comment]
Sounds good. I will rename it in the spec.

**Comment by tischi** [comment]
PR: https://github.com/mobie/mobie-viewer-fiji/pull/727

**Comment by constantinpape** [comment]
Done
