### ISSUE TITLE
Table column order

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#709]
Hi,

MoBIE orders the columns of a table alphabetically. Is it possible that it keeps the order from the `tsv` file?

**Comment by constantinpape** [comment]
I don't think so, but you can reorder the columns manually.

**Comment by tischi** [comment]
@martinschorb  Are you sure?
I checked, and at least I does not reorder for segments:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/2157566/168416309-67c44ec3-0fde-4406-899c-ac28b290a26b.png">
Maybe the python library that you use to _create_ the table does the ordering?

**Comment by martinschorb** [comment]
I manually created that table. 

https://github.com/mobie/clem-example-project/blob/main/data/hela/tables/fluorescence/default.tsv

And Beta re-orders the columns...
![Screenshot 2022-05-16 at 12 35 14](https://user-images.githubusercontent.com/35071867/168574928-f2785f34-3423-41db-bf92-dccc68272df0.png)

**Comment by tischi** [comment]
Interesting...how do you load that table into MoBIE?

**Comment by martinschorb** [comment]
that's the `Fig2a` view. All other figure views show the same behavior.

**Comment by tischi** [comment]
I found it:

```
		final List< String > columnNames = new ArrayList<>( columns.keySet() );
		Collections.sort( columnNames ); // <= why do we sort here?
		for ( String column : columnNames )
		{
			cells.put( column, columns.get( column ).get( rowIndex ) );
		}
```

@constantinpape @K-Meech  
I have a strong memory that we decided at some point to sort the column names of the source annotations alphabetically, but I do not remember why...
I could just remove the sorting, should I?

**Comment by martinschorb** [comment]
I would vote for displaying the table as in the `tsv` file. If a certain column order is desired, it would be defined there.

**Comment by K-Meech** [comment]
Using the order in the tsv file sounds good to me too @tischi . I'm not sure why we were sorting...

**Comment by constantinpape** [comment]
Fine with me as well
