### ISSUE TITLE
logo background color

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#711]
when checking the figures (screen grabs in Fig 1 and 3), I noticed that the MoBIE logo has a slightly different background color than the window.
![Screenshot 2022-05-10 at 12 25 33](https://user-images.githubusercontent.com/35071867/167608575-0675da70-d07f-4350-8ead-1a07a9632cf0.png)

Does Java allow transparency? Then we could just embed a background-less png...

**Comment by constantinpape** [comment]
> Does Java allow transparency? Then we could just embed a background-less png...

Alternatively we could also change the background color so that it matches fully.

**Comment by KateMoreva** [comment]
> Does Java allow transparency? Then we could just embed a background-less png...

Sure. I made a png version.

**Comment by constantinpape** [comment]
Fixed by #716
