### ISSUE TITLE
Simplify segments rendering UI

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#721]
Should we merge those into one in the GUI?
- Change Opacity Of Non-selected Segments
- Configure Coloring of Selected Segments
- Configure Label Rendering

---

> Yes, I think that would be good. I think "Configure Label Rendering" is a good name for the combined GUI.

**Comment by tischi** [comment]
Working on this here: https://github.com/mobie/mobie-viewer-fiji/pull/722

**Comment by tischi** [comment]
@constantinpape 
We also have:  “Configure Segments Volume Rendering”.

1. Should we also merge this into the "Configure Label Rendering"?
2. Segments or Labels?

**Comment by constantinpape** [comment]
> We also have: “Configure Segments Volume Rendering”.
> 
>     1. Should we also merge this into the "Configure Label Rendering"?

No, I wouldn't merge it; since this is responsible for a different window (i.e. for the 3d viewer instead of the bdv window).

But I agree that we should use the same name everywhere, my vote would be for "Label", i.e.
- "Configure Label Rendering"
- "Configure Label Volume Rendering"
