### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#723]
Currently only very few tests. 
Some are half working or commented.

**Comment by tischi** [comment]
- [ ] add test including a scatterplot

**Comment by martinschorb** [comment]
For the CLEM project they are all in the `mobie-paper` menu and are called
`Figure2x` with `x` in `[a,b,c,d,e,f]`

**Comment by K-Meech** [comment]
For the platybrowser, there's one called ```Figure 1a``` in the ```mobie-paper``` menu. It includes showing a scatter plot.
