### ISSUE TITLE
BDV window title

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#728]
Right now the BDV window title reads: `MoBIE - BigDataViewer`

<img width="490" alt="image" src="https://user-images.githubusercontent.com/2157566/168849445-b0fcead9-f8ba-43d3-a40b-6353ea8a1e62.png">

If one looks at the rest of the windows, we don't have MoBIE written anywhere in the title, apart from the main MoBIE UI.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/2157566/168849611-5c4fba87-b53d-4889-9dde-7f88bb7cf9c7.png">

Should we just leave it as plain `BigDataViewer`? 

One reason why the information `MoBIE` could make sense is that it indicates that there exists a right click context menu, which does not exist in the plain BDV.

**Comment by constantinpape** [comment]
I think having MoBIE in there is good to distinguish it from plain BDV. (With context menu as one difference and we may eventually have others).
