### ISSUE TITLE
problem loading crop

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#732]
Hi,

I try to display a cropped transform of a source.

This is view `test2` in `test` in https://github.com/mobie/clem-example-project, branch `crop1`.

When loading this view, it is added to the source list, but not displayed. I get:

```
Exception in thread "PainterThread" java.lang.NullPointerException
	at bdv.util.ResampledSource.getModelToOriginMipMapLevel(ResampledSource.java:206)
	at bdv.util.ResampledSource.buildSource(ResampledSource.java:277)
	at bdv.util.ResampledSource.getSource(ResampledSource.java:258)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:252)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:252)
	at bdv.viewer.render.VisibilityUtils.computeVisibleSourcesOnScreen(VisibilityUtils.java:97)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:428)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
```

and BDV freezes trying to load the images.

This happens only with crops. When not displaying the crop (no `imageDisplay` but having the crop transform in the dataset), it still works.

It is also independent on whether I employ `sourceNamesAfterTransform` in chains to label each transform uniquely or not.

**Comment by martinschorb** [comment]
the view is valid according to `mobie-python`.

**Comment by constantinpape** [comment]
I had a quick look and the view also seems fine to me. I think @tischi needs to take a look; but we should probably wait till the MoBIE beta is there and the view specs are fully updated here, since there is a bit of chaos now.
(@tischi: as soon as you have pushed to MoBIE-beta tomorrow I can update all the projects).

**Comment by martinschorb** [comment]
Still get:

```
Exception in thread "PainterThread" java.lang.NullPointerException
	at bdv.util.ResampledSource.getModelToOriginMipMapLevel(ResampledSource.java:206)
	at bdv.util.ResampledSource.buildSource(ResampledSource.java:277)
	at bdv.util.ResampledSource.getSource(ResampledSource.java:258)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:252)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:252)
	at bdv.viewer.render.VisibilityUtils.computeVisibleSourcesOnScreen(VisibilityUtils.java:97)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:428)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
```

In the log it seems tht it opens the source and then crashed when trying to display it.

```
Opening (1/1): https://raw.githubusercontent.com/mobie/clem-example-project//crop1/data/hela/images/bdv-n5-s3/em-detail-a1-A.xml
Opening image:
https://raw.githubusercontent.com/mobie/clem-example-project//crop1/data/hela/images/bdv-n5-s3/em-detail-a1-A.xml
Opened 1 image(s) in 524 ms, using 16 thread(s).
```

**Comment by constantinpape** [comment]
I checked again: the project is valid according to the python validator and also my quick manual check.
When I try to open the view in the latest MoBIE-beta it fails with the following error (slightly different from the one posted by Martin):
```
Exception in thread "PainterThread" java.lang.NullPointerException
	at bdv.util.ResampledSource.getModelToOriginMipMapLevel(ResampledSource.java:206)
	at bdv.util.ResampledSource.buildSource(ResampledSource.java:277)
	at bdv.util.ResampledSource.getSource(ResampledSource.java:258)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:252)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:252)
	at bdv.viewer.render.VisibilityUtils.computeVisibleSourcesOnScreen(VisibilityUtils.java:97)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:428)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
```
@tischi can you have a look at this?

**Comment by tischi** [comment]
@NicoKiaru Did you change something in the bdv-playground that could cause this error?

```
Exception in thread "PainterThread" java.lang.NullPointerException
	at bdv.util.ResampledSource.getModelToOriginMipMapLevel(ResampledSource.java:206)
	at bdv.util.ResampledSource.buildSource(ResampledSource.java:277)
```

Or do you have some tips how to debug this?

**Comment by tischi** [comment]
I see there is some log to help with this:

```
13:15:43.001 [main] DEBUG bdv.util.ResampledSource - Model mipmap level 0 correspond to origin mipmap level 0
13:15:43.006 [main] DEBUG bdv.util.ResampledSource - Model mipmap level 0 has a characteristic voxel size of NaN
13:15:43.009 [main] DEBUG bdv.util.ResampledSource - Origin level 0 has a characteristic voxel size of 0.010203798911897717
13:15:43.009 [main] DEBUG bdv.util.ResampledSource - Model mipmap level 0 correspond to origin mipmap level 0
13:15:43.010 [main] DEBUG bdv.util.ResampledSource - Model mipmap level 0 has a characteristic voxel size of NaN
13:15:43.010 [main] DEBUG bdv.util.ResampledSource - Origin level 0 has a characteristic voxel size of 0.010203798911897717
```

@NicoKiaru, does that help?

**Comment by tischi** [comment]
@martinschorb 
I think one issue may be that the crop is 2D:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/2157566/169295383-4e7b79ce-ef97-49bf-89e1-a7734956b5d5.png">
I guess it is on purpose that `min[2]==max[2]`?
I am not sure this will work in general.
Is there a way that you can specificy the crop in a way the `min[2]!=max[2]`?
I will dig a bit more...

**Comment by tischi** [comment]
OK, I did the same trick as with the Regions. T
o make it 3D, I enlarge the chosen interval by the voxel size:

```
				// determine number of voxels for resampling
				// the current method may over-sample quite a bit
				final double smallestVoxelSize = getSmallestVoxelSize( sourceAndConverter );
				// slightly enlarge the crop
				// important to deal with quasi 2D images or crops
				final double[] minMinusVoxelSize = new double[ 3 ];
				final double[] maxPlusVoxelSize = new double[ 3 ];
				for ( int d = 0; d < 3; d++ )
				{
					minMinusVoxelSize[ d ] = min[ d ] - smallestVoxelSize;
					maxPlusVoxelSize[ d ] = max[ d ] + smallestVoxelSize;
				}
				final FinalVoxelDimensions croppedSourceVoxelDimensions = new FinalVoxelDimensions( sourceAndConverter.getSpimSource().getVoxelDimensions().unit(), smallestVoxelSize, smallestVoxelSize, smallestVoxelSize );
				int[] numVoxels = getNumVoxels( smallestVoxelSize, maxPlusVoxelSize, minMinusVoxelSize );
				SourceAndConverter< ? > cropModel = new EmptySourceAndConverterCreator("Model", new FinalRealInterval( minMinusVoxelSize, maxPlusVoxelSize ), numVoxels[ 0 ], numVoxels[ 1 ], numVoxels[ 2 ], croppedSourceVoxelDimensions ).get();
```

Now it does not crash anymore, but I cannot see anything.

Should I upload this change to MoBIE-beta or do you rather want to create some tests for me that I can check from within IntelliJ?

**Comment by martinschorb** [comment]
> I think one issue may be that the crop is 2D:

it transforms a 2D source, so yes. 
I guess in the case that one size in any dimension is 0, one could simply add a pixel/corresponding length.

**Comment by tischi** [comment]
@martinschorb see my other posts  ⬆️

**Comment by martinschorb** [comment]
It works for me when specifying a thicker crop (1um).

**Comment by martinschorb** [comment]
I can see it...

**Comment by tischi** [comment]
OK, awesome!
I think I will still keep my code changes, right?

**Comment by martinschorb** [comment]
To clarify: I can see it when increasing `z` in the crop. I haven tested your code. If you put it in Beta, I will...

**Comment by tischi** [comment]
What is the voxelsize of this image in z?

**Comment by tischi** [comment]
Do you have enough functionality for now to work on the publication figure?

**Comment by martinschorb** [comment]
it seems not to be part of Beta yet. I will just create the cropviews with a z-margin.

**Comment by martinschorb** [comment]
OK, now there's the problem that the crop source is not shown where it should be. It is cropping the correct part of the image but it is showing somewhere off. (Looks like a translation to some wrong origin)

![Screenshot 2022-05-20 at 08 57 42](https://user-images.githubusercontent.com/35071867/169471565-147ebfc0-eb58-4c42-bbf7-2952ec1a2594.png)


This is not what I would expect from a crop. It should stay exactly where it was taken from.
This is view `Test_A1` from `crop1` branch of the CLEM dataset.

transforms https://github.com/mobie/clem-example-project/blob/f445f8a3ffcfa47af46f7be52730e43bada7db49/data/hela/dataset.json#L312-L431:
```
"sourceTransforms": [
        {
          "affine": {
            "name": "MapScaleMat",
            "parameters": [...],
            "sourceNamesAfterTransform": [
              "em-detail-a1-A_1"
            ],
            "sources": [
              "em-detail-a1-A"
            ]
          }
        },
        {
          "affine": {
            "name": "Translation",
            "parameters": [...],
            "sourceNamesAfterTransform": [
              "em-detail-a1-A_2"
            ],
            "sources": [
              "em-detail-a1-A_1"
            ]
          }
        },
        {
          "affine": {
            "name": "manualTransform",
            "parameters": [...],
            "sourceNamesAfterTransform": [
              "em-detail-a1-A_3"
            ],
            "sources": [
              "em-detail-a1-A_2"
            ]
          }
        },
        {
          "affine": {
            "name": "manual_shift_a1",
            "parameters": [...],
            "sourceNamesAfterTransform": [
              "em-detail-a1-A_4"
            ],
            "sources": [
              "em-detail-a1-A_3"
            ]
          }
        },
        {
          "crop": {
            "max": [
              98.0,
              -12.0,
              1.0
            ],
            "min": [
              76.0,
              -34.0,
              -1.0
            ],
            "sourceNamesAfterTransform": [
              "em-detail-a1-A_crop"
            ],
            "sources": [
              "em-detail-a1-A_4"
            ]
          }
        }
```

Has this always been like that? I think I never tried superimposing crops on top of their original sources.

**Comment by martinschorb** [comment]
Oh, and I also tried without `"sourceNamesAfterTransform"`s just chaining trafos. This clearly works, because the crop is from the correct part of the image. It is just shifted.

**Comment by tischi** [comment]
@martinschorb 

```
public class CropSourceTransformer extends AbstractSourceTransformer
{
	protected double[] min;
	protected double[] max;
	protected List< String > sources;
	protected List< String > sourceNamesAfterTransform;
	protected boolean centerAtOrigin = true;  // DEFAULTS TO TRUE
```

You need to set it to _false_.

**Comment by martinschorb** [comment]
It's  centerAtOrigin!!!
![Screenshot 2022-05-20 at 09 12 51](https://user-images.githubusercontent.com/35071867/169473657-c181299c-b80b-4b88-abe5-fe5beb04a5c0.png)

**Comment by martinschorb** [comment]
OK, we remembered that one at the same time ;-)

**Comment by tischi** [comment]
> this is not what I expect from a crop

Maybe `False` is the better default?
@constantinpape do you remember why we put this to `True`?

Reason: If you want to combine several crops into a grid, then the subsequent grid transform has `centerAtOrigin = true`, so it would not matter what you had in the crop itself.

**Comment by martinschorb** [comment]
Exactly, for grids it makes total sense. 
We just never showed a crop in its original location. The cool thing now is, by combining crops and annotation, you can annotate rectangles anywhere in your data ;-)

**Comment by tischi** [comment]
> The cool thing now is, by combining crops and annotation, you can annotate rectangles anywhere in your data ;-)

Yeah, but I think for this use case, we should rather extend the regionDisplay to enable  ROIs, isn't it? If you agree, please make an issue.

**Comment by constantinpape** [comment]
@tischi haven't followed the discussion here fully, but feel free to change  the default value for centerAtOrigin for crops back to false (jsonschema doesn't have a conept of default values anyways, so no need to update the spec for this)

**Comment by tischi** [comment]
> but feel free to change the default value for centerAtOrigin for crops back to false

done

**Comment by tischi** [comment]
> I just made them isotropic (roughly 10 nm). We can choose anything here, the images are 2D.

Not really, if we want to show them in a hetero-dimensional context the voxel size in z matters, because this will determine where along the z-axis the image is visible. 
If you make the image very thin it may practically not be visible at all, because you would need to exactly hit that plane within BDV, which may not be possible at that accuracy.

At least that is my current understanding of how BDV works...

Right now you fixed this by specifying a larger crop.
Once I updated MoBIE-beta again, you could try to instead specify a larger voxel size along the z-axis for those images.

**Comment by tischi** [comment]
@martinschorb can we close this issue?
