### ISSUE TITLE
Loading covid-if hangs

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#735]
Loading covid-if hangs for me:
MoBIE menu and viewer are started normally, but the images and tables are never shown. It does not throw any error.
Here is the end of the log output:
```
Opening image:
https://s3.embl.de/covid-if-project/20200406_164555_328/images/ome-zarr/nucleus_segmentation_WellE07_0007.ome.zarr
Opening image:
https://s3.embl.de/covid-if-project/20200406_164555_328/images/ome-zarr/nuclei_WellE06_0006.ome.zarr
Opened 90 image(s) in 6980 ms, using 16 thread(s).
 
Opening (1/18): https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/cell_segmentation_WellE07_0003/default.tsv
Opening (3/18): https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/cell_segmentation_WellE07_0006/default.tsv
Opening (5/18): https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/cell_segmentation_WellE07_0004/default.tsv
Opening (9/18): https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/cell_segmentation_WellE07_0008/default.tsv
Opening (17/18): https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/cell_segmentation_WellE06_0000/default.tsv
```

Note that this is with the latest MoBIE-beta and even after >10 minutes nothing happens when trying to load the project (took < 1 minute when it worked the last time).

**Comment by tischi** [comment]
Works for me:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2157566/169357419-250b8389-378d-4f3d-b6e3-bbec0abeddac.png">

@martinschorb could you please also try to open: https://github.com/mobie/covid-if-project

**Comment by constantinpape** [comment]
I tried again and now it works. Maybe some transient issue with my internet connection
