### ISSUE TITLE
Published moBIE figures

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#736]
@martinschorb 
@constantinpape 
Should we add example-clem and covid-if to the published projects? 
1. That could make it even easier to access for the reviewers
2. For Covid-IF there is even a publication

**Comment by martinschorb** [comment]
or we even create a new menu option "Open projects from MoBIE publication"

**Comment by constantinpape** [comment]
I would be fine with both options (Adding to published projects or creating new menu option.)

**Comment by martinschorb** [comment]
are all views from the IF and platy projects from one dataset?

If so, we could also create a new project just for the publication with the three figures as datasets.
This would also have the advantage that we can keep that repo frozen at the publication state while we could still modify the original projects.

**Comment by constantinpape** [comment]
My personal preference would be to just add clem and covid-if to published projects and not create anything extra for it.
(I think this extra project would be more confusing.)
What do you think, @tischi?

**Comment by martinschorb** [comment]
Let's imagine the actions required to open a figure as a user:

option **a** (leaving separate projects)
- check the figure which project to load
- load the relevant project
- load the figure panel view from the "mobie-figure" menu

option **b** (have an extra project)
- open the mobie publication project
- load the figure panel view from the "mobie-figure" menu

So it is basically one action less (given the name of the publication project is obvious).
How would a reader link the covid IF/CLEM published project name with the MoBIE paper without looking it up?

**Comment by tischi** [comment]
> How would a reader link the covid IF/CLEM published project name with the MoBIE paper without looking it up?

In the MoBIE paper figure legends we always give both, the project name and the figure name.
But I guess you are talking the other way around?

Could one extend option **b** to something like "MoBIE > Published MoBIE figures"?

Then it would only be **one click** and we could leave the "published MoBIE projects" untouched (of course adding the Covid-IF and the CLEM-Example. 

Thinking of me being a reviewer of the publication, a one-click solution might be worth it.
That would make it four steps:

- Install Fiji
- Add MoBIE update site
- Restart Fiji
- `MoBIE > Published MoBIE figures > MoBIE Nature Methods: Figure 2a`

Where the latter would internally call:
`new MoBIE("https://github.com/mobie/clem-example-project/", MoBIESettings.settings().view( "Figure2a" ));`

**Comment by constantinpape** [comment]
I like the published figure idea! @tischi can you implement it?

(For some context, I don't like putting everything into a single project because data in the same project should have something more in common than the arbitrary: "highlighted in our NM publication, but actually the paper is very different and comes from completely different sources". Ofc this is up to whoever creates projects, but we can at least set a good example ;).)

**Comment by martinschorb** [comment]
That extra route sounds like a very good solution to me.

**Comment by tischi** [comment]
I am implementing this, but now if a user selects two figures in a row there will be two MoBIEs which is very confusing.

1. Should we automatically close (all) MoBIE instance(s) when opening a MoBIE Figure?
2. https://github.com/mobie/mobie-viewer-fiji/issues/754
3. https://github.com/mobie/mobie-viewer-fiji/issues/755

**Comment by constantinpape** [comment]
> but now if a user selects two figures in a row there will be two MoBIEs which is very confusing.

I don't quite understand the issue. Shouldn't the new "Open Published MoBIE Figure" work exactly as "Open Published MoBIE project", just that it opens a specific view instead of the default view?

**Comment by constantinpape** [comment]
> Yes, in fact both have the same issue: multiple MoBIEs will clutter the Desktop.

Ok, then this clears up my confusion :).

**Comment by tischi** [comment]
OK, so:

Should we automatically close (all) MoBIE instance(s) when opening a MoBIE Figure _or Project_?

I think my vote is: yes.

**Comment by constantinpape** [comment]
> OK, so:
> 
> Should we automatically close (all) MoBIE instance(s) when opening a MoBIE Figure _or Project_?
> 
> I think my vote is: yes.

If possible I would vote for the following:
- `Open Published Project` -> Close all other MoBIE instances
- `Open Published Figure` -> Close all other MoBIE instances
- `Open Platybrowser` -> Close all other MoBIE instances
- other `Open` options:  don't close other MoBIE instances, there might be some use-cases for opening multiple

If that's too complicated I am also fine with closing all other MoBIE instances for everything in `Open`. (And if a use case for multiple instances really arises we can still change behaviour a bit then).

**Comment by constantinpape** [comment]
or, this could be the default for everything, but we add a check-box to the expert mode to *not close* other MoBIE instances

**Comment by tischi** [comment]
> And if a use case for multiple instances really arises we can still change behaviour a bit then

I would go with that and wait for complaints ;-)

**Comment by constantinpape** [comment]
> I would go with that and wait for complaints ;-)

Fine with me
