### ISSUE TITLE
Crop transform: centerAtOrigin default?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#737]
> this is not what I expect from a crop

Maybe `False` is the better default?
@constantinpape do you remember why we put this to `True`?

Reason: If you want to combine several crops into a grid, then the subsequent grid transform has `centerAtOrigin = true`, so it would not matter what you had in the crop itself.

_Originally posted by @tischi in https://github.com/mobie/mobie-viewer-fiji/issues/732#issuecomment-1132567076_

**Comment by constantinpape** [comment]
feel free to change the default value for centerAtOrigin for crops back to false (jsonschema doesn't have a conept of default values anyways, so no need to update the spec for this)

(repeating my post from #732
