### ISSUE TITLE
"showAsBoundaries" no longer works

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#738]
Hi,

with the updated specs, "showAsBoundaries" no longer works when initiated from a view (CLEM project).
When I activate it through the context menu, it comes back.

**Comment by constantinpape** [comment]
Can you please give exact steps to reproduce this? Which view should be loaded in the clem project?

**Comment by martinschorb** [comment]
Any Figure, that contains region boundaries from the `main` branch. They all show as filled rectangles for me.


![Screenshot 2022-05-20 at 09 30 59](https://user-images.githubusercontent.com/35071867/169476779-1a5d8dce-7a99-463c-9fd0-d23b1e9217e9.png)

When I then right click and apply the changes for "Configure Label Rendering", these are taken.

**Comment by constantinpape** [comment]
@tischi for example `mobie-paper -> Figure2a`. It should be loaded with boundaries due to https://github.com/mobie/clem-example-project/blob/main/data/hela/dataset.json#L685-L713

**Comment by tischi** [comment]
I fixed it and also wrote a test for this:

```
	@Test
	public void testFigure2a() throws IOException
	{
		// needed to init all Services
		final ImageJ imageJ = new ImageJ();
		imageJ.ui().showUI();

		// actual code
		final MoBIE moBIE = new MoBIE( "https://github.com/mobie/clem-example-project", MoBIESettings.settings().view( "Figure2a" ) );
		moBIE.sourceNameToSourceAndConverter().keySet().stream().forEach( s -> System.out.println( s ) );
		final SourceAndConverter< ? > sourceAndConverter = moBIE.sourceNameToSourceAndConverter().get( "fluorescence-annotations" );
		final LabelSource< ? > labelSource = SourceHelper.getLabelSource( sourceAndConverter );
		final boolean showAsBoundaries = labelSource.isShowAsBoundaries();
		assertTrue( showAsBoundaries );
	}
```

Good?
Let me know if you can think of similar such tests!
