### ISSUE TITLE
manual transform moves region annotations

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#747]
Hi,

when using BDV's manual transform inside MoBIE, all annotations are moved regardless of the "current" source.

_**current Beta**_
![Screenshot 2022-05-23 at 15 28 19](https://user-images.githubusercontent.com/35071867/169830300-435858dd-0369-4e2e-b836-30d0f5232365.png)

**Comment by martinschorb** [comment]
That only happens when "manual Transform"  is active. When stopping it (by either canceling it `Esc` or confirming it `T`) the source behaves as expected and also all annotations jump back.

**Comment by tischi** [comment]
I fixed it, but what would remain to be done is that the region annotation moves along with a transformed image.

**Comment by martinschorb** [comment]
> I fixed it, but what would remain to be done is that the region annotation moves along with a transformed image.

That's a tough one. It would require the original view being updated by the manual transformation or re-linking the annotation to the new view source.

**Comment by tischi** [comment]
I think it is possible, see the new issue: https://github.com/mobie/mobie-viewer-fiji/issues/750

Otherwise, can we close this? Manual transform should now leaves the regions in place.
