### ISSUE TITLE
Region Ids: Strings or Numbers?!

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#749]
@constantinpape @martinschorb 

Looking at my code, trying to make possible: https://github.com/mobie/mobie-viewer-fiji/issues/748

I found this:

```
	public static void mergeRegionTables( List< RegionTableRow > intervalTableRows, Map< String, List< String > > columns )
	{
		final HashMap< String, List< String > > referenceColumns = new HashMap<>();
		final ArrayList< String > gridIdColumn = TableColumns.getColumn( intervalTableRows, TableColumnNames.REGION_ID );
		referenceColumns.put( TableColumnNames.REGION_ID, gridIdColumn );

		// deal with the fact that the grid ids are sometimes
		// stored as 1 and sometimes as 1.0
		// after below operation they all will be 1.0, 2.0, ...
		MoBIEHelper.toDoubleStrings( gridIdColumn );
		MoBIEHelper.toDoubleStrings( columns.get( TableColumnNames.REGION_ID ) );
```

This strongly suggests that at some point we only allowed numeric values for region IDs.
I also saw that @martinschorb uses numbers as region IDs in the CLEM-Example project.

Probably we initially did that because we wanted the code to be compatible with the label_ids, which MUST be numbers.

Clearly the current code seems to work with non-numeric region_ids, e.g. from the Covid-IF project:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/2157566/169846708-41928a7c-4160-42ef-984d-5351a9af7ff0.png">

Question: Is it OK if I change the code above to simply do a String comparison to find the matching rows (and delete all the `toDoubleStrings` stuff)?

Thinking while writing: maybe I should leave it as is but only do the operation if the column in fact is numeric?

**Comment by constantinpape** [comment]
I don't quite understand this. But my immediate answer would be "leave it as it is, do float comparison if possible, otherwise string comparison".

**Comment by tischi** [comment]
> I don't quite understand this. But my immediate answer would be "leave it as it is, do float comparison if possible, otherwise string comparison".

That's what I did now.
