### ISSUE TITLE
Configure occluding blending mode

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#758]
There currently is: `Display>Set Blending Mode` in the context menu.
I would say this is not really working or at least hard to use.

I think it could be better to add more control to the display adjustment panel.

Idea: Remove this context menu and if one clicks the "O" button, the GUI that appears could, in addition to the opacity slider, also have a checkbox `[ ] occluding`.

What do you think @martinschorb?

**Comment by constantinpape** [comment]
Sounds like a good idea from my side.

**Comment by tischi** [comment]
- [X] I removed the BlendingModeChanger from the context menu (as it wasn't really working anyway.
- [ ] Add configuration options to the source UI, we could now use the `[S]` button for this.

**Comment by tischi** [comment]
In fact, I don't see a use-case for changing the blending mode in the UI right now.

Do you?

@constantinpape 
@martinschorb

**Comment by martinschorb** [comment]
Toggling occluding on/off is very useful if one wants to check how good the sources are registered with each other.
If people use MoBIE to register multi-modal data, that's a use case.

But we could also take it out now and include this topic into our upcoming discussion on registration.

**Comment by tischi** [comment]
> Toggling occluding on/off is very useful if one wants to check how good the sources are registered with each other.

Another good trick here is to color one source in Magenta and the other in Green, then the sum will look White if the registration is correct.

OK, let's leave this out for now and then have an in person meeting where we explore registration together.

**Comment by tischi** [comment]
OK, I will see to add it to the `[S]`ettings button then.

**Comment by constantinpape** [comment]
> OK, I will see to add it to the `[S]`ettings button then.

I agree, that's the right point to put it. And it also makes the UI look nicer since we have a `[S]` for image sources then.

**Comment by tischi** [comment]
Done, will upload later today.
