### ISSUE TITLE
Add 'go to' function for cells/segmented objects IDs

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#76]
Enhancement:
In my work I often need to find a cell with some id. Right now I am manually scrolling through the whole table to find it. Would be nice to have some search or 'go to object' that will allow to start typing the id, and it would move you to the corresponding line of the table

**Comment by constantinpape** [comment]
Thanks to @K-Meech we have the functionality "Select->Select equal to" now, which can be used for exactly this use case :).
