### ISSUE TITLE
Name under image in grid

### ISSUE THREAD

**Issue by KarelMocaer** [mobie/mobie-viewer-fiji#763]
Dear Mobie Team, 

I was wondering if it would be possible to implement an option for showing images' names under them in the grid view.

Best regards, 

Karel

**Comment by constantinpape** [comment]
I agree, this would be very useful. And is related to https://github.com/mobie/mobie-viewer-fiji/issues/698.

**Comment by tischi** [comment]
@KarelMocaer 
1. Is there a project/view that we could use to develop this?
2. Do you specifically want the names under the images (e.g. to make a nice screenshot) or would some other means of knowing what's what help? Please see https://github.com/mobie/mobie-viewer-fiji/issues/698 and comment there.

**Comment by tischi** [comment]
I guess the project is not public yet? I wrote you in the EMBL chat.

**Comment by tischi** [comment]
Good progress:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2157566/171617888-c523c2a0-f324-44e2-be77-c214fc8dfe7b.png">

Question: What to do when several sources have the same extend?

As one can see in the above screenshot this leads to the source name appearing at the same position.

**Comment by tischi** [comment]
@martinschorb @constantinpape 

Here is another example where things currently get crowed. Any suggestions?

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2157566/171618549-e36fc785-f695-43a0-bb21-72000a4a20e2.png">

**Comment by tischi** [comment]
Q: Where do we want the UI element to toggle the names on and off? 

What about next to the ` clear ` button?

<img width="549" alt="image" src="https://user-images.githubusercontent.com/2157566/171618894-b718f9e6-8f3b-4423-930b-f12f58b9163e.png">

**Comment by constantinpape** [comment]
> Here is another example where things currently get crowed. Any suggestions?

Not sure, I can't really think of a good solution, other than just showing everything as you do right now and users having to figure it out by toggling on / off visibility for the sources (which means the name should only be shown for sources that are visible!)

> What about next to the `clear` button?

Sounds good.

**Comment by tischi** [comment]
> which means the name should only be shown for sources that are visible!

That should be the case already...

------

Two ideas:
- scale the size of the font relative the space that the source occupies in the current field of view
- color the font with the same color as the source

**Comment by constantinpape** [comment]
> * scale the size of the font relative the space that the source occupies in the current field of view
> 
> * color the font with the same color as the source

I would go with option one, I think coloring can look pretty messy.

**Comment by tischi** [comment]
I think that could get somewhere:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2157566/171622874-81c5db2c-562a-4f75-b1a1-db39a480c3cb.png">

Right now I am painting the text at a position that it is visible even if the source is only partially visible. This is another source of over-plotting (s.a.).

Maybe just plot the name at the lower end of the source (no matter whether this position currently is visible or not)?

**Comment by constantinpape** [comment]
> Maybe just plot the name at the lower end of the source (no matter whether this position currently is visible or not)?

Yes! I think then it would look good.

**Comment by tischi** [comment]
Getting better.

Zoomed out:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2157566/171624709-5148812c-fb3f-4ea9-b48d-dd15640a5653.png">

Zoomed in:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2157566/171624785-aeb9a53b-fa5a-4cfa-a129-c604f761e38c.png">

**Comment by tischi** [comment]
Now really below the source:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2157566/171625182-65d2e279-3cdd-4b34-af89-11047ad7a2ce.png">

I think that's good enough for a first merge into MoBIE-beta?
I find it already incredibly useful :-)
Thanks @KarelMocaer for the suggestion!

**Comment by constantinpape** [comment]
Looks great! All for merging it, and I agree; this is super useful!

**Comment by KarelMocaer** [comment]
Looks amazing ! Thanks a lot :)

**Comment by martinschorb** [comment]
Kudos, that's really cool. 
- You could go for a font size maximum that cannot be exceeded even when the source is huge. 
- and it should be active for `imageDisplay`s only. Annotations are often at exactly the same position.

**Comment by martinschorb** [comment]
> Where do we want the UI element to toggle the names on

This could directly open a color chooser to set the label color.

**Comment by tischi** [comment]
Good like this @KarelMocaer ?

<img width="847" alt="image" src="https://user-images.githubusercontent.com/2157566/171813600-011468b6-e447-4443-b396-90819fa31dec.png">

**Comment by tischi** [comment]
@martinschorb 

I changed it now such that is does not show the annotation names:

<img width="976" alt="image" src="https://user-images.githubusercontent.com/2157566/171814712-2713c29c-835a-4a68-8b86-68460d5be7bc.png">

Do you want to remove the "cropShift" inset from this view ("default")?

**Comment by martinschorb** [comment]
looks good!
This seems to be a stale branch. The default view in the current main branch only contains the overview EM image.

I will clean up the branches in this project...

**Comment by KarelMocaer** [comment]
> Good like this @KarelMocaer ?
> 
> <img alt="image" width="847" src="https://user-images.githubusercontent.com/2157566/171813600-011468b6-e447-4443-b396-90819fa31dec.png">

It looks really good ! Thanks everyone this is super helpful !

**Comment by tischi** [comment]
initial functionality is implemented.
closing this.
please open a new issue for future suggestions.
