### ISSUE TITLE
licenses

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#766]
@constantinpape 

Is that on purpose that there are two license files?

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/2157566/171504571-a6fabbdd-435d-4943-bdc1-ca66cd47e9ba.png">

It is a bit odd that the only difference in the names are that one ends on .txt and the other not.

**Comment by constantinpape** [comment]
> Is that on purpose that there are two license files?

I don't know, both files were created by you ;)

**Comment by tischi** [comment]
we settled on the BSD-2 that is suggested by scijava
