### ISSUE TITLE
time point transform

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#771]
I would need a transform to move a image in time (e.g., from time point 0 to 7).

In my use case the original image only has one time point.

How should we do this? 

@constantinpape something like `transform -> timeMap` with parameters `List< Pair< Integer, Integer > > fromTo`?

@bogovicj do you have already something in mind for OME-Zarr?

@NicoKiaru In terms of `Source`: one could wrap a `Source` into a new `Source` with different timepoints, like `MappedTimeSource( Source source, List< Pair< Integer, Integer > > fromTo )` I think that would be easy to implement and I can do it, but somehow I have a feeling that I saw that somewhere already...do you know?

**Comment by bogovicj** [comment]
Hi @tischi 

What I have in mind for OME-Zarr would make that possible.   There would still be implementation to make it displayed correctly in viewers, but that idea would be expressible, hopefully with something as simple as this:

```json
{
"type" : "coordinates",
"coordinates" : [7]
}
```

(i.e. the 0th element of the coordinate list is the destination index = 7)

**Comment by tischi** [comment]
Thanks a lot @bogovicj ! 

@constantinpape 
Could we be early adopters and support exactly this notation in MoBIE dataset.json?

**Comment by constantinpape** [comment]
I like the approach by @bogovicj a lot in general, but I am not sure how good it fits to the current MoBIE transforms, since we don't really have a concept of input and output spaces yet. I think it would make more sense to adopt the new ngff transformation logic wholesale once it's released (which will be a bit of work...).
If you need the time point transform now, it probably makes sense to introduce it through a bit simpler transform for now.

**Comment by bogovicj** [comment]
@constantinpape 

> I think it would make more sense to adopt the new ngff transformation logic wholesale once it's released (which will be a bit of work...).

Agreed.  The hope from my end is to make a java library with a nice api that makes this stuff relatively easy from a developer point of view. Would love some help and input from you all.

**Comment by tischi** [comment]
@constantinpape 

OK, what about this for us?

```
"sourceTransforms": [
  {
   "time": {
      "name": "...",
      "parameters": [7]
  }
```

**Comment by constantinpape** [comment]
> "sourceTransforms": [
>   {
>    "time": {
>       "name": "...",
>       "parameters": [7]
>   }

I think `time` is a bit generic. How about `timeShift`? Also, is there a use-case for parameters being a list (i.e. do we want to enable duplicating a single time point across multiple other timepoints)? If not, we could just have a single integer there.

**Comment by constantinpape** [comment]
> Agreed. The hope from my end is to make a java library with a nice api that makes this stuff relatively easy from a developer point of view. Would love some help and input from you all.

Absolutely! My time during the summer term here is a bit limited, but I should have some bandwidth for this after the summer break (so end of August/September).

**Comment by tischi** [comment]
> do we want to enable duplicating a single time point across multiple other timepoints

yes, good point.

**Comment by tischi** [comment]
@bogovicj 
In your spec: can images have missing time points? As you know BDV/`Source` supports this and in fact I have a use case now where this is handy.

**Comment by tischi** [comment]
This is the current code to map the timepoint in the _new_ image to the _old_ image: https://github.com/mobie/mobie-viewer-fiji/blob/c64b83fb76c06c5449c08a099f6170890f6f096f/src/main/java/org/embl/mobie/viewer/source/TransformedTimepointSource.java#L119

**Comment by tischi** [comment]
I merged this into `develop` and will upload to MoBIE-beta later today such that our user can test it.

**Comment by tischi** [comment]
> we'll have the spec in json as:

It is important to note that the _first_ entries in the inner lists MUST be _unique_, because one can specify the timepoint only once. The _second_ entries MAY _reoccur_, because one can, e.g. specify that timepoint 4 _and_ 5 in the new image should both be replaced with the data at timepoint 3 in the old image: `[ [4, 3], [5, 3] ]`.

**Comment by constantinpape** [comment]
@tischi: I am implementing this for the spec now; and we'll also need `sources` in the parameters, as for all the other transformations.

**Comment by constantinpape** [comment]
and I will also add an optional `name` for consistency with the others.

**Comment by constantinpape** [comment]
@tischi I have added it to the spec, could you point me to where the example project is on the embl server, so that I can check that it matches it?
