### ISSUE TITLE
image data formats in project.json

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#772]
Why do we need the image data formats in the project.json?

Could it be that this is somehow obsolete now?

**Comment by tischi** [comment]
> As far as I know we have to have them in there so that you know which formats are available before opening the project.

But, now, every dataset could have different formats (with all the mixed formats that we support now).

**Comment by constantinpape** [comment]
> > As far as I know we have to have them in there so that you know which formats are available before opening the project.
> 
> But, now, every dataset could have different formats (with all the mixed formats that we support now).

Yeah, but what's the alternative? Just assuming we have all file formats is not a good option.

**Comment by tischi** [comment]
> Yeah, but what's the alternative? Just assuming we have all file formats is not a good option.

I have a feeling that within the Java code I don't need those fields in the project.json (in fact, considering them just makes things more confusing).

I only initially have to determine whether to open from _remote or local_ (which is currently done based on the project location, e.g. `.startsWith("http")`). And then when opening any source, the code can just look whether that specific source supports being opened remotely or locally, and pick the corresponding image format.

In case the source supports _several_ remote or local image data formats, it would just pick the first one (in fact, that's what's happening right now already).

Unless, the user (in the expert mode) specifies that they specifically want to use one format.

We can leave them in the project.json, but I could make a branch where I don't use them and see whether all the tests run.

**Comment by constantinpape** [comment]
> We can leave them in the project.json, but I could make a branch where I don't use them and see whether all the tests run.

That sounds good. (But in terms of priorities, I don't see that this is a pressing issue...)

**Comment by tischi** [comment]
> That sounds good. (But in terms of priorities, I don't see that this is a pressing issue...)

+1, ( +1 )

**Comment by tischi** [comment]
We removed image data types from project.json for mobie3.
