### ISSUE TITLE
Project creator "link" bdv images, OS problems

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#779]
Hi,

when you create/edit a project and add a BDV image using the "link" option. It generates a local XML with a relative path to the original data.
This relative path is Windows-specific (backslashes). Could you please change this to using forward slashes, so it is compatible with all OSes?

**Comment by tischi** [comment]
@K-Meech found that already: https://github.com/mobie/mobie-viewer-fiji/issues/659
Closing this one.
