### ISSUE TITLE
Some projects without time axis have a time scrollbar

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#784]
Both covid-if and clem-example now has a time scrollbar: (latest MoBIE beta)

https://user-images.githubusercontent.com/4263537/172236443-06cad357-e9a4-4f32-85ab-aeee1b53d199.mp4

But not all have it, e.g. Platy is correct and doesn't have it.

**Comment by tischi** [comment]
The issue is that the region annotations currently have an infinite number of timepoints.
I asked on gitter: https://gitter.im/bigdataviewer/bigdataviewer-core
