### ISSUE TITLE
Decrease loading time for MergedGrid Source

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#786]
Every interaction with S3 appears to take about 0.1 s.
Therefore initialization of the 4000 sources for the Covid-IF data takes ~400 s (probably a bit less due to the multi-threading).

To substantially improve this it appears that we would need to avoid accessing every image on S3 before showing it. I think for the `MergedGridSource` this may be possible, because we know that all sources MUST have the same metadata. 

Thus, one could explore whether one could implement a `LazySourceAndConverter`, which could be initiated with some known metadata and the path to the actual image data, which would internally use `SpimDataOpener` to load the data once really needed (i.e. when being shown in BDV).

**Comment by tischi** [comment]
@NicoKiaru Did you ever experiment with something like a `LazySourceAndConverter` (see above)?

**Comment by NicoKiaru** [comment]
Nope, I never tried this.

**Comment by tischi** [comment]
@constantinpape Do we have a view where we load the _whole_ plate using the `mergedGridTransform` but where we load _no tables_? If not, could you please add one?

**Comment by constantinpape** [comment]
@tischi `plate->merge-grid-no-tables`

**Comment by tischi** [comment]
Can you please remove the segmentations?

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/2157566/172843739-9a7a8bc9-bbe5-4103-834d-402294d52fea.png">

**Comment by tischi** [comment]
🥳  with https://github.com/mobie/mobie-viewer-fiji/pull/789 it initializes the whole thing in only 11 s and then lazy loads the images while one can already interact with everything in BDV  🥳 

so, now we "just" have to figure something out for the tables...
