### ISSUE TITLE
Open Ome Zarr via BDV is very inconvenient

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#790]
Our functionality for opening ome.zarr via bdv is quite inconvenient, e.g. compared to napari. For referecne, here is how to open an example file I am dealing with in napari (using the ome-zarr plugin):

https://drive.google.com/file/d/1dMs7tEFz3bwSQCyzJTiboJV1cM2-ratL/view?usp=sharing

and this is how it looks in our BDV opener

https://user-images.githubusercontent.com/4263537/172938356-bfc5f6fc-54aa-42e1-9080-42bb454b4160.mp4

As you can see I can't even get it to display any data ....
(I managed once when trying beforehand).

@tischi @KateMoreva the data is at `/g/kreshuk/pape/Work/data/ngff-examples` if one of you wants to take a look.

**Comment by constantinpape** [comment]
> Is this the latest OME-Zarr version?

Yes, it's 0.4.

> Weird.... opening this in napari, can you see the contrast settings?
> Does napari do auto-contrast?

Something def. does an autocontrast there, but I am not sure where it happens, it might be in the `ome-zarr-napari-plugin`; maybe @willmoore knows.

**Comment by KateMoreva** [comment]
I'll take a look on Friday

**Comment by will-moore** [comment]
If there is `omero` rendering metadata for the NGFF https://ngff.openmicroscopy.org/latest/#omero-md
then this is actually converted into `constrast_limits` metadata in `ome-zarr-py` (this was added before `napari-ome-zarr` was split as a separate repo):
https://github.com/ome/ome-zarr-py/blob/13bb14fcf0d4749a29585c01b37d5edc0bc9183b/ome_zarr/reader.py#L379
I don't know of any other "auto" setting unless `napari` is doing something?

**Comment by will-moore** [comment]
In vizarr, Trevor recently added the 'auto-contrast' using a low-resolution multiscale array to set the limits if they weren't provided: https://github.com/hms-dbmi/vizarr/pull/137

**Comment by tischi** [comment]
> I'll take a look on Friday

@KateMoreva I don't think you can do much in mobie-io, as I don't think we want to read the omero metadata at this stage...

I think we should add auto-contrast functionality to `mobie-viewer-fiji`. I think there is code in [labkit](https://github.com/juglab/labkit-ui) that we can copy. If you want to work on this @KateMoreva, go ahead, but I would be happy to do it otherwise.

**Comment by constantinpape** [comment]
> If there is `omero` rendering metadata for the NGFF https://ngff.openmicroscopy.org/latest/#omero-md
> then this is actually converted into `constrast_limits` metadata in `ome-zarr-py` (this was added before `napari-ome-zarr` was split as a separate repo):

In this case there isn't any omero metadata, so there must be something else happening in napari.

> @KateMoreva I don't think you can do much in mobie-io, as I don't think we want to read the omero metadata at this stage...
> 
> I think we should add auto-contrast functionality to `mobie-viewer-fiji`. I think there is code in [labkit](https://github.com/juglab/labkit-ui) that we can copy. If you want to work on this @KateMoreva, go ahead, but I would be happy to do it otherwise.

The auto-contrast sounds like a good solution!

**Comment by tischi** [comment]
@tibuch 

Since you may be familiar with the LabKit code for auto-contrast, if you want to give this a shot, be our guest 😉 

I guess we would need something around here:
https://github.com/mobie/mobie-viewer-fiji/blob/c6bc0518c0c460c117739ee539d2590482d2d96a/src/main/java/org/embl/mobie/OMEZarrViewer.java#L92

**Comment by constantinpape** [comment]
Ok, the issue here was that the data was invalid, see https://github.com/mobie/mobie-io/issues/107.
(Autocontrast might still be a good idea, but I will close this issue for now; I think the auto-contrast discussion has moved somewhere else in any case.)

**Comment by tischi** [comment]
citing Tobias from bdv-core gitter:

> I think it always only does it for the first source added
but that could be changed of course
You can dig into the code / debug to find out what happens exactly
InitializeViewerState.initBrightness(...) is the method that does the min/max estimation
Internally, it calls InitializeViewerState.estimateSourceRange(...)
You can also use this one, if you want to implement your own auto-contrast thing for additional sources, on demand, ... etc
