### ISSUE TITLE
Cell segment navigation is off for Covid-IF 

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#794]
project: covid-if
view: default
branch: main

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/2157566/173100085-5de1b8c2-09a6-46fa-88ff-6a02e96541f3.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2157566/173100117-0cf4b30f-a957-4537-82f7-e1808bd7ab55.png">

moves to the wrong place (totally outside the image).

I have a feeling that this could have to to with the calibration.
We did not have pixel sizes in OME-Zarr for a long time, but now we do and in fact the scale bar in BDV shows a scaling in micrometer.

@constantinpape do you know in which units the anchor points in the cell segments tables are?

**Comment by tischi** [comment]
Note to self: 

- [ ] First fix this in **main**
- [ ] Then check again in **develop** (because due to the new `LazySourceAndConverter` there may be additional sources of errors)
- [ ] Only then check in branch **issue400** (as there again could be more wrong)

**Comment by constantinpape** [comment]
Hi @tischi,
I know what the issue is: in the beginning we did not know the pixel size for the data (so it was set to 1); but then later I got the information about this from Vibor. But I haven't updated the tables accordingly. I will fix it and ping you once that's done.

**Comment by constantinpape** [comment]
@tischi I updated the values in the table and it works for me on MoBIE from the main update site now.
