### ISSUE TITLE
Change image color in 3D viewer

### ISSUE THREAD

**Issue by Buglakova** [mobie/mobie-viewer-fiji#803]
When I assign different color to the image, it changes immediately in the slice viewer, but only changes in the 3D viewer if I close it and open again.

**Comment by tischi** [comment]
I cannot reproduce this.
How exactly do you change the colors in the slice viewer?

**Comment by Buglakova** [comment]
For example, here big volume is yellow at first:
![Screenshot from 2022-06-23 16-54-14](https://user-images.githubusercontent.com/89460016/175336725-8376e9c0-f764-4e5c-994f-cc64d3da65d3.png)
Then I change color to red in the main menu, but in the 3D viewer it's still yellow:
![Screenshot from 2022-06-23 16-54-38](https://user-images.githubusercontent.com/89460016/175336881-c2008a4d-05a0-446a-9b4e-f2afc59a2786.png)
It only changes if I close 3D viewer window and open it again.
