### ISSUE TITLE
Rename and remove datasets and images

### ISSUE THREAD

**Issue by Buglakova** [mobie/mobie-viewer-fiji#804]
Both in the GUI editing dataset dialogue and in the examples for Python utils I couldn't find a way to remove or rename existing images. Is it possible somehow?

**Comment by constantinpape** [comment]
Good point. I can implement it in python. It's easy to do. I will ping you once it's there.

**Comment by constantinpape** [comment]
I have implemented this for the python library in
https://github.com/mobie/mobie-utils-python/pull/75 &
https://github.com/mobie/mobie-utils-python/pull/76

I will ping you here once there is a new release and this can be tested.

**Comment by constantinpape** [comment]
This is implemented now in mobie python:
- [remove_source](https://github.com/mobie/mobie-utils-python/blob/master/mobie/source_utils.py#L74)
- [rename_source](https://github.com/mobie/mobie-utils-python/blob/master/mobie/source_utils.py#L169)
