### ISSUE TITLE
Do we need a separate interface for Region and Segment

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#808]
```
public interface Segment
{
	String imageId();
	int labelId();
	int timePoint();
	double[] anchor();

	RealInterval boundingBox();
	void setBoundingBox( RealInterval boundingBox );

	float[] mesh();
	void setMesh( float[] mesh );
}
```

This could be _very similar_ to what we expect from a region.
The main difference seems that a `region` has a `String regionId()` and a `segment` has a `Integer labelId()` method. 

It feels quite annoying that I would need to implement "everything", e.g. a `TableModel` that represents them twice (as they are so similar)...

@constantinpape it would be helpful for me to brainstorm a bit how different a segment and a region really are...

**Comment by constantinpape** [comment]
> @constantinpape it would be helpful for me to brainstorm a bit how different a segment and a region really are...

Sounds good. I will write to you in mattermost.

**Comment by tischi** [comment]
@constantinpape does that look good to you?
Also note the static methods for creating IDs in the `Segment` interface.

```
public interface Location
{
	int timePoint();
	double[] anchor();
}

public interface Segment extends Location
{
	String imageId();
	int labelId();

	// create ID (also used for serialisation)
	static String toAnnotationId( String imageId, int timePoint, int labelId )
	{
		return ""+imageId+";"+timePoint+";"+labelId;
	}

	// create ID (also used for serialisation)
	static String toAnnotationId( Segment segment )
	{
		return toAnnotationId( segment.imageId(), segment.timePoint(), segment.labelId() );
	}

	RealInterval boundingBox();
	void setBoundingBox( RealInterval boundingBox );

	float[] mesh();
	void setMesh( float[] mesh );
}
```

**Comment by constantinpape** [comment]
@tischi yes, that looks good!
