### ISSUE TITLE
scatterplot JSON

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#815]
We have as fields in the JSON:

```
protected boolean showScatterPlot;
protected String[] scatterPlotAxes;
```

Would it be OK to assume that `scatterPlotAxes` MUST be given if `showScatterPlot=true`?

**Comment by constantinpape** [comment]
> Would it be OK to assume that `scatterPlotAxes` MUST be given if `showScatterPlot=true`?

Yes.

**Comment by constantinpape** [comment]
https://github.com/mobie/mobie.github.io/commit/d6f00b70ff00280bd3a00667608942a25090dcdb
