### ISSUE TITLE
colorByColumn default value?!

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#817]
Here: https://github.com/mobie/platybrowser-project/blob/d82ef21888f77e5774694b8b5cdbabdce46e4cba/data/1.0.1/dataset.json#L6670
...there is no `colorByColumn` name given, but a `lut`.
Do we specify a default for the `colorByColumn`, maybe `label_id`?

**Comment by tischi** [comment]
ok, it looks like we support also categorical coloring without any specific column.

**Comment by constantinpape** [comment]
Yes, by default we always use the `label_id` column (for segmentations) or `region_id` column (for regions)

**Comment by tischi** [comment]
I found out that in terms of code, I can sort of simply color by "row", thus I don't need to specify any specific column. I would leave the code like that?
