### ISSUE TITLE
Cannot adjust brightness limits in OME-zarr BigDataViewer viewer window

### ISSUE THREAD

**Issue by kgabor** [mobie/mobie-viewer-fiji#823]
If I open an OME-zarr image via mobie `(Plugins -> BigDataViewer -> OME-Zarr -> Open OME-Zarr from file system...)` the `BigDataViewer` window is displayed. However, display limits cannot be adjusted via` Settings -> Brightness & Color`. As such, most of my images are shown as completely black with the default value limits.

I also noticed that if I open platybrowser `(Plugins -> MoBIE -> Open -> Open PlatyBrowser)` , the shown BigDataViewer window is also unresponsive for the` Settings -> Brightness & Color` menu, but there is the "B" button in the platybrowser window to adjust the display limits which works. But this option seems to be unavailable if open ome-zarr is used.

Versions: 
mobie-viewer-fiji-2.1.10.jar
ImageJ 1.53q

**Comment by constantinpape** [comment]
Hi @kgabor,

I think the proper way to adjust the brightness is via the bigdataviewer menu. You can open it by pressing `p` and then you can adjust the brightness for the individual sources.

**Comment by kgabor** [comment]
Thanks, it works indeed this way!
