### ISSUE TITLE
Volume view, data types

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#826]
Hi, 

I have data of type `float32`. While display (and contrast adjustment) works fine, I cannot use the volume viewer.
```
Exception: Volume view of image of type 0.0 is currently not supported.
	at org.embl.mobie.viewer.volume.ImageVolumeViewer.getContrastLimits(ImageVolumeViewer.java:270)
...
```

Can the contrast range be mapped on-the-fly to some supported data type to enable the volume view?

**Comment by martinschorb** [comment]
same data as in #825

**Comment by tischi** [comment]
I will have a look!

**Comment by tischi** [comment]
test data: `emcf/Hamburg_XRay/20220522/mobie_demo`
