### ISSUE TITLE
Unique IDs for annotations

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#827]
@constantinpape 

For the fields: `selectedSpots` `selectedRegions` `selectedSegments` we need a unique Strings in the JSON.

Could you remind me how they are currently specified in the JSON?

**Comment by constantinpape** [comment]
Currently we have:
- `selectedSegmentIds`: `sourceName;timePoint;label_id`
- `selectedRegionIds`: `timePoint;regionId`
- `selectedSpotIds`: we haven't discussed this yet, I guess it should be `timePoint;spotId`.

**Comment by tischi** [comment]
Thanks!

1. I guess they are all with underscore, right? `region_id`, `spot_id`?
2. `region_id` is a String?
3. `spot_id` is an Integer?

**Comment by constantinpape** [comment]
Yes to all three.

**Comment by constantinpape** [comment]
@tischi: short correction: a spotDisplay can have multiple spot sources. So we also need the format `sourceName;timePoint;spot_id`

**Comment by tischi** [comment]
And `sourceName` refers to either an `image` or a `segmentation`, right?

**Comment by constantinpape** [comment]
Here it would refer to the spotSource.

**Comment by tischi** [comment]
or maybe not...???
maybe sourceName always refers to the table source name?
maybe this is also true for segmentations, because they also contain a table...

**Comment by constantinpape** [comment]
in the case of the segmentation it would always refer to the corresponding segmentation source. (use-case: grids: multiple segmentations have the same segmentationDisplay, we need to know which one the label id belongs to)
same is true here because `sources` in the `spotDisplay` is also a list. (I don't fully know the use-case yet tbh, but it happens by extension of the segmentationDisplay)

**Comment by tischi** [comment]
Hm, I am trying to write the Java code for this. Current attempt:

```
public interface Annotation extends Location
{
	// UUID for serialisation of selected annotations
	String id();

	// Creates the UUID (THIS IS WHAT I TRY TO UNDERSTAND)
	default String createId( String sourceName, int timePoint, int labelId )
	{
		return ""+sourceName+";"+timePoint+";"+labelId;
	}

	// Integer label for representing the annotation as a
	// region in one time point of a label image
	int label();

	// For retrieving features (measurements)
	// (typically: feature = column in an annotation table)
	Object getValue( String feature );

	// For adding manual annotations
	void setString( String columnName, String value );

	// for merging tables
	String[] idColumns();
}
```

I thought maybe I can just use the same code here for all annotation types?!

Because also the regions have a source name, namely the name of the tableSource, which I think we will add with the new spec?

**Comment by constantinpape** [comment]
> Because also the regions have a source name, namely the name of the tableSource, which I think we will add with the new spec?

But in the case of the regionDisplay we don't really need to add it, because we only have a single table source per region display. So the region_id there is unique.

**Comment by tischi** [comment]
Yes, true for the regions it is different...

**Comment by tischi** [comment]
OK, I will not use it for the UUID for regions, but do you think it is a valid abstraction to still say that each annotation (region, segment, spot) must have a source?

This is useful in my code, because then I can use the combination of `source`, `timepoint` and `label` to uniquely identify an Annotation object.

```
public interface Annotation extends Location
{
	String uuid();

	// Data source (can be a table and/or a label mask image)
	String source();

	// Integer label for representing the annotation as a
	// region in one time point of a label image
	int label();

	// For retrieving features (measurements)
	// (typically: feature = column in an annotation table)
	Object getValue( String feature );

	// For adding manual annotations
	void setString( String columnName, String value );

	// for merging tables
	String[] idColumns();
}
```

**Comment by constantinpape** [comment]
> OK, I will not use it for the UUID for regions, but do you think it is a valid abstraction to still say that each annotation (region, segment, spot) must have a source?

Yes, I think it's a useful abstraction. In the case of the `regionDisplay` it's just trivial for the `selectedRegionId`, since we only have a single table source in the view; so if you deserialize this you could just add the `tableSource` to it automatically (and strip it when it's serialized).

**Comment by tischi** [comment]
The issue however is that `region_id` is a String. That makes this different from the other two. 

Related to that: in the code, I need to create an intermediate representation of the regions as a label mask image, thus I need an Integer label. Currently I take the hashcode of the region_id for this. Do you think this is fine? Are there better ways? Hmmm, I just see that I could also use the `rowIndex` of the region in its table. I think this is more straight-forward. I don't know why I did not do this... I think will try that instead...what do you think?

**Comment by constantinpape** [comment]
> The issue however is that `region_id` is a String. That makes this different from the other two.

Good point.

> Currently I take the hashcode of the region_id for this. Do you think this is fine? Are there better ways? Hmmm, I just see that I could also use the `rowIndex` of the region in its table. I think this is more straight-forward. I don't know why I did not do this... I think will try that instead...what do you think?

I think that the row index makes more sense at all and is more transparent than taking a hash.

**Comment by tischi** [comment]
OK, so for the Region:

```
        	this.regionId = row.getObject( ColumnNames.REGION_ID ).toString();
		this.label = rowIndex;
		this.timePoint = row.columnNames().contains( ColumnNames.TIMEPOINT ) ? row.getInt( ColumnNames.TIMEPOINT ) : 0;
		this.sourceName = tableSupplier.get().name();
```
