### ISSUE TITLE
Support making bookmarks from UI

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#83]

**Comment by tischi** [comment]
@constantinpape 

Well, thanks to our recent efforts we know now how to submit files to github via the API 😃  
One option would thus be that we have a **bookmarks folder** and each bookmark would be one json file. That would make it quite simple to add and remove bookmarks. I would find that easier and cleaner than changing the one big bookmarks file that we currently have.

What do you think? 

It is a bit annoying though that a user would need to get a github API token and also push rights to the repo. It is quite involved to get this and thus the user would need to be kind of a github crack...speaking of which, the other repo is on gitlab, not github...maybe annoying to even support both github and gitlab API...then again gitlab API looks at first glance very similar to github: https://docs.gitlab.com/ee/api/repository_files.html

**Comment by constantinpape** [comment]
> Well, thanks to our recent efforts we know now how to submit files to github via the API smiley
> One option would thus be that we have a **bookmarks folder** and each bookmark would be one json file. That would make it quite simple to add and remove bookmarks. I would find that easier and cleaner than changing the one big bookmarks file that we currently have.

Yes, I agree that's a better solution then having the big bookmark file.
(We could still support multiple bookmarks per file though).

> It is a bit annoying though that a user would need to get a github API token and also push rights to the repo. It is quite involved to get this and thus the user would need to be kind of a github crack...speaking of which, the other repo is on gitlab, not github...maybe annoying to even support both github and gitlab API...then again gitlab API looks at first glance very similar to github: https://docs.gitlab.com/ee/api/repository_files.html

For starters, we can just support the bookmarks locally. I.e. you have a second folder in the fiji plugin sources (custom data in there is possible, right?) where the bookmarks generated from the UI are stored.
If users want to push those upstream, they need to clone the repo and make a PR with their new bookmarks (this means they also don't need push rights, which is not a scalable solution).

Of course in the long run also being able to push to github / gitlab directly would be great, but I don't think it's immediately necessary to be useful.

**Comment by tischi** [comment]
> Of course in the long run also being able to push to github / gitlab directly would be great

Actually, maybe it is least work to just implement this. I have most of the code in the PlateViewer already anyway.

**Comment by constantinpape** [comment]
> > 
> 
> Actually, maybe it is least work to just implement this. I have most of the code in the PlateViewer already anyway.

Ok, but from a user perspective there should always be a local option to store the bookmarks,
so that it's not necessary to have git API tokens.

**Comment by tischi** [comment]
ok, like an optional bookmarks folder?

**Comment by constantinpape** [comment]
> ok, like an optional bookmarks folder?

yes, I think either an optional bookmark folder, or something that is always made in the plugin files (I don't know how fiji handles files that should persist in between runs)

**Comment by tischi** [comment]
The natural place would be the ImageJ preferences file. That would be most convenient, because the user would not have to specify anything. Con: If they install a new Fiji or go to another computer they loose everything...

**Comment by constantinpape** [comment]
> The natural place would be the ImageJ preferences file. That would be most convenient, because the user would not have to specify anything. Con: If they install a new Fiji or go to another computer they loose everything...

I think that would be ok for now, if you add a warning to the log window about this and we put a short explanation somwhere how to either manually push them to upstream via PRs or via the UI and API tokens.

(I would generally make this a two stage process: make the bookmark that's stored locally and then add another option to push it if the API token is available)

**Comment by constantinpape** [comment]
Just one thing to keep in mind:
It might be nice to have some bot user for the bookmark creation in order to allow this for users without going through the github API token process.

Not sure if this is such a good idea, and def. not the first thing to do, but I just wanted to keep track of this idea.

**Comment by tischi** [comment]
@K-Meech 
To me, this (adding bookmarks from the UI), would be to most important enhancement of MoBIE.
If you have capacity, I think that would be the thing to work on 🙂

**Comment by K-Meech** [comment]
@tischi I'm game! I agree this would be super useful, and something many users are waiting for...

Am I right that bookmarks are currently loaded from the 'project location'?
I guess we will need to support multiple cases then:
- Local project location = write directly to bookmarks folder of project
- Remote project location = support adding to github with api tokens etc, or save locally and then add them manually to git

It would be nice to have an option similar to the 'load columns...' option for tables, where you can choose to load tables from an arbitrary location on your file system. This has been really useful for sharing things with group members unfamiliar with git.

**Comment by tischi** [comment]
> Am I right that bookmarks are currently loaded from the 'project location'?

Yes and also yes to all the other things you said.

I think we also have to think how to manage that people cannot screw up stuff too much if everyone has write access in some form. For the `PlateViewer` project we employed a database server, but I think a "github only" solution would be nice to keep things a bit more simple.

One option to get started, as you mentioned, could be to implement an option "Load additional bookmarks..." similar to the "Load columns...". And then for saving new bookmarks people could simply save to their own location of choice where they have write access, but potentially more people have read access. Like this we could separate write from read access. Or something like this...

**Comment by tischi** [comment]
...on the other hand, maybe it is easier to just for once figure out a clever way to get the api token stuff working such that not every user needs to create them (maybe via some "dummy account") and then just write everything to the main repo. I feel maybe in the end this is maybe the better and easier way, because everything is in one place.

**Comment by tischi** [comment]
In terms of Java code, have a look at:

```
de.embl.cba.plateviewer.github.* (in plateViewer repo: https://github.com/embl-cba/plateviewer)
de.embl.cba.tables.github.* (in imagej-utils repo)
```

**Comment by K-Meech** [comment]
Sounds good! I'll take a look. I guess my concern with having everything written to the main repo is that the bookmarks may become very cluttered i.e. many, many entries in the dropdown from lots of different projects making it hard for users to find their own bookmarks.

**Comment by tischi** [comment]
> I guess my concern with having everything written to the main repo is that the bookmarks may become very cluttered i.e. many, many entries in the dropdown from lots of different projects making it hard for users to find their own bookmarks.

My idea would be to make one bookmarks.json file per user, e.g. bookmarks-meechan.json, a.s.o.
Then we could think about giving the option in the UI not to see all of them, or have a nested tree UI.
Having one file per user also helps us to keep track of things.

**Comment by K-Meech** [comment]
So I'm modifying the bookmark code atm - it'd be good to have a way to only show certain bookmarks in the dropdown by default (e.g. for platy, default.csv and manuscript_bookmarks.csv), and then let the user choose any more they want to add later. Any ideas for a good place to store which bookmark .jsons should be loaded by default?

**Comment by tischi** [comment]
> Any ideas for a good place to store which bookmark .jsons should be loaded by default?

Looks like we have this logic already?

![image](https://user-images.githubusercontent.com/2157566/95472048-da6e6b00-0982-11eb-9bbc-d2522b3fb61a.png)

**Comment by K-Meech** [comment]
At the moment it still loads everything though (not just the default). I can change it to just load the default, but we'd have to move all our manuscript bookmarks into that file if we wanted them to appear straight away..

**Comment by tischi** [comment]
> I can change it to just load the default, but we'd have to move all our manuscript bookmarks into that file if we wanted them to appear straight away..

True, up to you 👍

**Comment by K-Meech** [comment]
@tischi I've been in a load of conferences over the last few weeks, so never got around to uploading my changes to mobieBeta. Should I do this now? I know there were some problems with the s3 storage - is this all fixed now?

**Comment by constantinpape** [comment]
> I know there were some problems with the s3 storage - is this all fixed now?

Yes, this should all be fixed now.

**Comment by tischi** [comment]
> Should I do this now?

Why now? 🚀

**Comment by K-Meech** [comment]
I just thought people could test it out a bit / see if we need to change anything. No pressure though - whenever is easiest! :)

**Comment by tischi** [comment]
Sorry! I wanted to write:

Why **not**?

Sure, go for it!!!!!!!!

**Comment by K-Meech** [comment]
@tischi @constantinpape @vzinche 
I've updated mobieBeta to the latest version. If you have time, it'd be great if you could try out the new bookmark logic. The main changes are summarised at the top of the pull request: https://github.com/mobie/mobie-viewer-fiji/pull/134.
For saving bookmarks to the project, you need a github access token - this will write directly to the github repo. So maybe try it on a fork for testing!

One main change is that only bookmarks in the default json are loaded at startup. So we may want to move e.g. our manuscript bookmarks for platy into the default

**Comment by constantinpape** [comment]
> I've updated mobieBeta to the latest version. If you have time, it'd be great if you could try out the new bookmark logic. The main changes are summarised at the top of the pull request: #134.
> For saving bookmarks to the project, you need a github access token - this will write directly to the github repo. So maybe try it on a fork for testing!

Ok, I will try to test it soon!

**Comment by K-Meech** [comment]
This works now
