### ISSUE TITLE
Issues with parsing segmentation tables

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#832]
Hi @tischi,
I run into some issues with opening the segmentation tables in MoBIE 3.
Specifically, opening the project at `/g/kreshuk/data/marioni/shila/mouse-atlas-2020/ngff/` (this is the full spatial transcriptomics project) fails with a long error message that indicates that the column `bb_min_z` from the table `/g/kreshuk/data/marioni/shila/mouse-atlas-2020/ngff/embryo3/tables/MMStack_Pos0_cells/default.tsv` cannot be parsed as double. However, I made sure that all entries have a decimal point, and reading it with python/pandas works without issue (and recognizes the correct dtype):
```python
import pandas as pd
table = pd.read_csv("embryo3/tables/MMStack_Pos0_cells/default.tsv", sep="\t")
print(table["bb_min_z"])
```
```
0       0.0
1       0.0
       ... 
425    12.0
426    12.0
Name: bb_min_z, Length: 427, dtype: float64
```

Here's the full error I get in MoBIE:
![image](https://user-images.githubusercontent.com/4263537/194280974-fcbcbed4-8315-4805-8876-10efb327cf42.png)

**Comment by tischi** [comment]
I am not sure what is going on. 

I decided to side-step this by using a method `row.getNumber( columnName )` which will return a double representation of whatever numeric type the column has. I feel that's OK?!

**Comment by constantinpape** [comment]
> I decided to side-step this by using a method `row.getNumber( columnName )` which will return a double representation of whatever numeric type the column has. I feel that's OK?!

Yes, I think that sounds good and it's safe for the columns where we know that the values are float (like `anchor`, `bb_min` and `bb_max`).

Can you make an updated mobie-beta release with these changes?

**Comment by constantinpape** [comment]
Works now, thanks!
