### ISSUE TITLE
Segmentation in grid does not work

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#833]
Segmentations in a grid don't work yet in mobie3: the segmentation is only loaded for the first segmenation source (related to this: the `image-id` column is not loaded).
And selecting any of the segments from the image or table results in undefined behavior, sometimes selecting a random cell / position, sometimes throwing a NullPointer Exception.

See an example for this bug from the zebrafish project below.
To reproduce: open `https://github.com/mobie/zebrafish-lm-datasets`: `mobie3`, select `bookmark->small-grid-view`.

![mobie-seg-zebrafish](https://user-images.githubusercontent.com/4263537/194326079-45d442e1-aafd-4621-8c0e-0dab96e5ca3d.png)

**Comment by tischi** [comment]
For me, both segmentation are loaded, but it seems like the table only has one of them.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2157566/194357169-9aff4043-103d-45e8-90ee-103665fe442c.png">

**Comment by constantinpape** [comment]
> For me, both segmentation are loaded, but it seems like the table only has one of them.

Yes, the same happens for me; sorry my description was not 100% precise.



> But there is some bigger underlying issue. Looking into it, hoping that this is not something major design-wise sweat

Ok, fingers crossed!

**Comment by tischi** [comment]
I think I may have a good solution...but the nested MergedGridSource is giving me a headache (like always)...I will think more tomorrow. 

`MergedGridSource`  is currently only used in the covid-if project, is it?

**Comment by constantinpape** [comment]
> `MergedGridSource` is currently only used in the covid-if project, is it?

Yeah, I think so.

**Comment by tischi** [comment]
I think that works now, please reopen if needed.
