### ISSUE TITLE
AccumulateOccludingProjectorARGBFactoryAdapter ?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#842]
@NicoKiaru do we still need this?

https://github.com/mobie/mobie-viewer-fiji/blob/main/src/main/java/org/embl/mobie/viewer/bdv/render/AccumulateOccludingProjectorARGBFactoryAdapter.java

**Comment by NicoKiaru** [comment]
Hum, I think so. It is there in order for bdv-playground to remember and re-use the mobie-specific version of BdvHandle you are using.
