### ISSUE TITLE
settings menu does not work for showBoundaries and spotRadius

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#845]
For me neither changing the `showAsBoundaries` (both spot and segmentation sources) nor the `spotRadius` (spt sources) buttons in the new settings menu work. See here on platybrowser: (as you can see random seed does work)

https://user-images.githubusercontent.com/4263537/194948509-bfdb285a-c2ff-430b-b855-85ee4a940da3.mp4

**Comment by tischi** [comment]
`5.0` micrometer may be too thick for the boundaries. The cells are only a couple of micrometer. Could you try a smaller value, e.g. `0.5`?

**Comment by tischi** [comment]
For the spot radius however I found a bug. I can upload the fix later.

**Comment by constantinpape** [comment]
Indeed, it works for smaller values for the segmentation.
However, for the spots I am pretty sure that the boundary rendering doesn't work, I tried for very small values of the boundary radius now and it still renders the whole spots.
