### ISSUE TITLE
Test Proejct Creator UI

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#847]
@K-Meech Thanks a lot for fixing the other issue.

May I ask two more things:

1. Could you try out whether the ProjectCreator UI still works in the `mobie3` branch?
2. Could you play around with the `PlatyBrowser` in the `mobie3` branch, testing different views , saving views, loading views, etc. and create issues for things that don't work yet?

Thanks!

**Comment by K-Meech** [comment]
Sure - will do!

**Comment by K-Meech** [comment]
Spotted a minor issue with the project creator that I made a quick fix for (https://github.com/mobie/mobie-viewer-fiji/pull/853). Apart from this, project creator ui seems to be working fine!

I spotted a few other problems that I made issues for.
