### ISSUE TITLE
BlendingMode static name field

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#850]
@constantinpape @K-Meech 
Do you know whether this is still needed?
https://github.com/mobie/mobie-viewer-fiji/blob/f4fdda9a5c20f78d24bf7e94adcb973d451ce9a6/src/main/java/org/embl/mobie/viewer/bdv/render/BlendingMode.java#L73

**Comment by constantinpape** [comment]
I am not sure. My guess would be that we needed this at some point to read the extra blending mode config from xml that @NicoKiaru had in bdv-playground. But I am not sure.

**Comment by K-Meech** [comment]
I'm not sure either. I don't remember what this line was for.

**Comment by tischi** [comment]
@NicoKiaru do you remember (see above)?

**Comment by NicoKiaru** [comment]
I do not know the mobie side of it. I know that a projectionMode field is set on the `Entity` `Displaysettings`:

https://github.com/BIOP/bigdataviewer-spimdata-extras/blob/5caaa1d8d73bd64f81da9f66e294e533211352a3/src/main/java/spimdata/util/Displaysettings.java#L55

This field contains some information on the blending mode.

I would avoid changing anything in the Displaysettings class, but it's all I can tell
