### ISSUE TITLE
Implement segmentation images without tables

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#862]
...not yet implemented in mobie3.

**Comment by tischi** [comment]
@constantinpape Do you feel it could be useful to on-the-fly populate a segments table? It would initially probably only have one column, namely `label_id`. Note that I probably anyway have to implement such a "lazy" table in the code, because I _think_ I need it for the coloring and selection model of the segments.... 

I mainly wonder right now whether (a) it would be useful to show it and whether (b) there are some  use-cases where on-the-fly building of segments tables could be useful?

**Comment by tischi** [comment]
Should work now. 
I am showing the table.
But the navigation does not work because the table rows do not know the location of the segments. Currently the all move to `0,0,0`.

**Comment by tischi** [comment]
And what about showing the table but then logging a comment that the browsing is not implemented because no positions are given if a user tries to click (instead of moving to `0,0,0`)? 

You could also in the display set `showTable` to false?!

**Comment by constantinpape** [comment]
> And what about showing the table but then logging a comment that the browsing is not implemented because no positions are given if a user tries to click (instead of moving to `0,0,0`)?

But is the table of much use then? It will just show the `label_id` column without being able to navigate or to properly annotate objects (since this would also need navigation).

**Comment by tischi** [comment]
One could manually annotate some segments....
Otherwise probably not much.

OK, I will think about how to entirely disable table views for such cases...
Involves a little bit of coding thus, I wanted to avoid it, but probably worth it...

**Comment by constantinpape** [comment]
> OK, I will think about how to entirely disable table views for such cases...
> Involves a little bit of coding thus, I wanted to avoid it, but probably worth it...

I think that would be better too.
