### ISSUE TITLE
Serialise current view

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#863]
@K-Meech 

I have a couple of questions about this code:

```
	public View createViewFromCurrentState( String uiSelectionGroup, boolean isExclusive, boolean includeViewerTransform )
	{
		List< Display > viewDisplays = new ArrayList<>();
		List< Transformation > viewSourceTransforms = new ArrayList<>();

		for ( Transformation imageTransformation : currentTransformers )
			if ( ! viewSourceTransforms.contains( imageTransformation ) )
				viewSourceTransforms.add( imageTransformation );

		for ( Display display : currentDisplays )
		{
			Display currentDisplay = null;

			if ( display instanceof ImageDisplay )
			{
				ImageDisplay imageDisplay = ( ImageDisplay ) display;
				currentDisplay = new ImageDisplay( imageDisplay );
				addManualTransforms( viewSourceTransforms, imageDisplay.nameToSourceAndConverter );
			}
			else if ( display instanceof SegmentationDisplay )
			{
				SegmentationDisplay segmentationDisplay = ( SegmentationDisplay ) display;
				currentDisplay = new SegmentationDisplay( segmentationDisplay );
				addManualTransforms( viewSourceTransforms, segmentationDisplay.nameToSourceAndConverter );
			}
			else if ( display instanceof RegionDisplay )
			{
				currentDisplay = new RegionDisplay( ( RegionDisplay ) display );
			}
			else if ( display instanceof SpotDisplay )
			{
				currentDisplay = new SpotDisplay( ( SpotDisplay) display );
			}
			else
			{
				throw new UnsupportedOperationException( "Serialisation of a " + display.getClass().getName() + " is not yet supported." );
			}

			if ( currentDisplay != null )
			{
				viewDisplays.add( currentDisplay );
			}
```

1. Shouldn't we do the `addManualTransforms( ... )` always? So we could move it out of the if clauses? 
2. Can `currentDisplay` ever be `null`?

**Comment by tischi** [comment]
In fact, the `RegionDisplay` may be a special case in terms of transformations,
because it derives its position indirectly by the regions that it annotates. 
Thus the `RegionDisplay` may actually never be transformed by itself. 

@constantinpape does that sound conceptually correct to you?

**Comment by tischi** [comment]
I rewrote the code: https://github.com/mobie/mobie-viewer-fiji/blob/afa8ad10a1d2bc426b855fb451ded52bff4a4599/src/main/java/org/embl/mobie/viewer/view/ViewManager.java#L205

@K-Meech please reopen if you think that I overlooked something.

**Comment by constantinpape** [comment]
> In fact, the `RegionDisplay` may be a special case in terms of transformations, because it derives its position indirectly by the regions that it annotates. Thus the `RegionDisplay` may actually never be transformed by itself.
> 
> @constantinpape does that sound conceptually correct to you?

That sounds right.

**Comment by K-Meech** [comment]
@tischi - looks fine to me, although it's been a while since I looked at this part. Probably good to check that a manual transform can be saved / loaded from a view in the new mobie3.
