### ISSUE TITLE
Loading segmentation table in grid view fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#865]
There is still an issue when trying to load segmentation tables in a merged grid. When loading from filesystem it throws a lot of NullPointerErrors, see screenshot below.

To reproduce:
Open the view `segmentations` in `/g/kreshuk/pape/Work/data/mobie/covid-if-2` and try to load the `cell-segmentation` table.

![image](https://user-images.githubusercontent.com/4263537/196461823-6e28cc98-5838-48b9-bf38-1b86ae5beb70.png)

**Comment by constantinpape** [comment]
(I can't reproduce it in the `htm-test` project, there the similar view works fine.)

**Comment by constantinpape** [comment]
@tisch: loading the segmentation works now, but I run into a similar bug when using color by column:

After loading the cell segmentation i do: "Color By Column" -> is_train -> glasbey.
This leads to the following issue.

![image](https://user-images.githubusercontent.com/4263537/196736595-39abf4d4-b75d-4b7e-9ae4-efdf52f07f8d.png)

**Comment by tischi** [comment]
Turns out I did not support Boolean type yet. 

Now I do, with fancy rendering in the JTable ;-)

<img width="649" alt="image" src="https://user-images.githubusercontent.com/2157566/196877514-0e5a20e9-0c2e-441b-8d2b-ea00df0c0a8f.png">

**Comment by constantinpape** [comment]
Nice, thanks!
