### ISSUE TITLE
kdTree building can take a long time

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#866]
For 100k spots around 6 seconds. 

When loading many spot images that yields a bad user experience.

Idea: One could first build a smaller tree such that at least some spots are visible immediately and then asynchronously build the big one.

**Comment by constantinpape** [comment]
I will continue the kdTree related discussion here: would you need a smaller table for this or could you just read the table and build the tree in parallel by loading chunks of the table directly from html? (https://github.com/tlabs-data/tablesaw-parquet/blob/master/docs/working_with_remote_files.md)

**Comment by tischi** [comment]
> would you need a smaller table

My current feeling is that loading the tables is less of an issue than building the tree. Thus I could load the whole table anyway.

> by loading chunks of the table directly from html

Did you see an option for how to do this?

**Comment by constantinpape** [comment]
> My current feeling is that loading the tables is less of an issue than building the tree. Thus I could load the whole table anyway.

Ok, makes sense.

> Did you see an option for how to do this?

I haven't looked at this in so much detail yet, just assumed it might be possible.

But I agree, let's focus on the tree first. My current thought: what if we precompute the tree? (Also brought up in the other issue).

**Comment by tischi** [comment]
Tree building is fast now. Issue was that we had the same number in one dimension, often.
We fixed this by adding noise.
Tobias is looking into a proper solution.
See here: https://imagesc.zulipchat.com/#narrow/stream/327240-ImgLib2/topic/kdTree.20issue
