### ISSUE TITLE
Enable a label mask image for a spatial-omics source

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#867]
Creating kdTrees for many elements can be slow.

In such cases having a pre-computed label mask image may be better?
We could discuss how that would be different from a regular segmentation image.

We could look at this for inspiration: https://github.com/PreibischLab/STIM

**Comment by constantinpape** [comment]
Can we precompute the kdTree? That may be simpler than switching to a new concept with label masks here.

**Comment by tischi** [comment]
But then we would need a way to serialize it?!

**Comment by tischi** [comment]
> That may be simpler than switching to a new concept with label masks here.

On the Java side not much new concept, that would work just like any segmentation image.

**Comment by constantinpape** [comment]
> > 
> 
> On the Java side not much new concept, that would work just like any segmentation image.

Ok, let's try to discuss in a quick zoom later.

**Comment by tischi** [comment]
We discussed that this is not a good idea.
