### ISSUE TITLE
Do not show any table if the there are no stored tables 

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#868]

**Comment by tischi** [comment]
@constantinpape 

This is a bit tricky for a grid view, because some images may have a table while others may not.

Currently, for 

```
new MoBIE("/g/kreshuk/pape/Work/data/mobie/covid-if-2", MoBIESettings.settings().view( "segmentations" ) )
```

It loads now but it shows and empty table for the nuclei segmentation.

- [ ] I would first like to fix the bug that it actually does populate the concatenated nuclei segmentation table properly and then we can still think about disabling the view of it.

**Comment by tischi** [comment]
> Do you mean that not all label images that belong to cell-segmentation have a table? -> That should not be the case, either all of them have a table or none, otherwise the view is wrong.f

Oh I see, the AnnotationDisplay has a field `tables`! Is that what you mean?
Unfortunately, I think this now only includes the `additionalTables` and not the default table.
If it would also include the default table we could use this field to easily check whether there are no tables at all...
(BTW: did we rename this? In my code it still is `called tables`).

**Comment by tischi** [comment]
> No, you don't even need to look into the display for this. You can check in the segmentationSource if you have tableData or not. This has to be consistent for all the sources in the display (otherwise the view is incorrect).

OK, I did not know this.

**Comment by constantinpape** [comment]
> > 
> 
> OK, I did not know this.

This is how we changed the table spec recently. The fact that this has to be consistent across the sources in a display is not fully mentioned in the spec yet, I will add it. But you can def. assume this, I also check for this in the python validator.
