### ISSUE TITLE
Loading table from file system *from Table UI* doesn't work

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#872]
There is no error message, but the new columns are not added:

https://user-images.githubusercontent.com/4263537/197418927-f7e194fd-6c8c-4f9f-a944-d95faba7f131.mp4

**Comment by tischi** [comment]
I changed the title, because if you specify `additionalTables` is does work, is it?

**Comment by constantinpape** [comment]
> I changed the title

:+1:

> because if you specify `additionalTables` is does work, is it?

Yes, that works.

**Comment by tischi** [comment]
Should work now...

**Comment by constantinpape** [comment]
No, it doesn't work yet @tischi. Could you please give this one another look?

**Comment by constantinpape** [comment]
If you want to have an easier to reproduce issue, @tischi: I can reproduce for loading extra cell tables in platybrowser:



https://user-images.githubusercontent.com/4263537/197600510-b295bcd0-8d95-4b38-9061-ba9564f60b15.mp4

**Comment by tischi** [comment]
Weird, I tried it and it worked with your initial example (maybe I did not upload the changes...)  
To be sure, could you please update Fiji and try again?

**Comment by constantinpape** [comment]
I just tried with the platybrowser example. It's not working. (I made sure to update to a new version)

**Comment by tischi** [comment]
Could you please update and try again?
It seems it was loading the data but not showing it.
I added a `jTable.tableChanged( )` and for me it works now.

**Comment by constantinpape** [comment]
Yes, works now.
