### ISSUE TITLE
AdditionalTables saved wrong in bookmarks

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#876]
The default table gets saved in views under 'additionalTables' with it's full file path. E.g.

Open platybrowser (mobie3 branch)
Add the cell segmentation
'Save Current View' to filesystem
The saved file contains:
```
"additionalTables": [
              "https://raw.githubusercontent.com/mobie/platybrowser-datasets/mobie3/data/1.0.1/tables/sbem-6dpf-1-whole-segmented-cells/default.tsv"
            ],
```

**Comment by tischi** [comment]
1. I changed the code such that the default table is now separate from the additional tables.

2. For the additional tables I only put the file name there using below code

```
public static String getFileName( String path )
	{
		if ( path.startsWith( "http" ) )
		{
			final String[] split = path.split( "/" );
			return split[ split.length - 1 ];
		}
		else
		{
			return new File( path ).getName();
		}
	}
```

Questions:

1. Are my changes correct?
2. That means we do currently do not support serialization of absolute paths here, such as tables loaded from the file system (in fact we would serialize them **wrongly**!). What to do about this? We would need some logic in the code that keeps track of whether table paths are "part of the project" or not. Overall it is a bit messy that we need to support both relative and absolute paths...any ideas how to solve that in a clean way?

**Comment by tischi** [comment]
Could you please update Fiji and try again?

**Comment by constantinpape** [comment]
> 1. I changed the code such that the default table is now separate from the additional tables and will not be serialised.

That's correct.

> 1. Are my changes correct?

Yes, the changes look correct.

> 2\. That means we do currently do not support serialization of absolute paths here, such as tables loaded from the file system (in fact we would serialize them **wrongly**!). What to do about this?

Yes, we do not support serializing with tables from the filesystem that are not part of the project. (And I think for now we also shouldn't attempt doing this since it will make things more complicated.)

>  What to do about this? We would need some logic in the code that keeps track of whether table paths are "part of the project" or not. Overall it is a bit messy that we need to support both relative and absolute paths...any ideas how to solve that in a clean way?

For now: the best solution I can come up with is to check whether the table exist in the `tableData` when it's being serialized.
Here's how the python pseudo-code for this would look like:
```python
# when serializing a view with additionalTables
# path is the path to one of the additional tables
name = getFileName(path)
relative_table_folder = this_source["tableData"]["tsv"]["relativePath"]
# assuming here the 'join' operation works both for filepaths and urls,
# since the dataset location can be either
project_table_path = join(dataset_location, relative_table_folder, name)
if path.startswith("https"):
    ...   # check if the address exists
else:
   if  not path.exists(path):
        raise Error("Table {name} is not part of the project")
```

**Comment by K-Meech** [comment]
I think we already had some logic for checking if tables were from inside the project or not. E.g. there was a  ```hasColumnsFromTablesOutsideProject``` variable inside the TableViewer - https://github.com/mobie/mobie-viewer-fiji/blob/a9fb5ef47f541a7c0e3fbd529efc68ac00b90787/src/main/java/org/embl/mobie/viewer/table/TableViewer.java#L446 . Not sure if this is still somewhere in the new mobie3 code?

**Comment by tischi** [comment]
I think this has been refactored and it working now.
