### ISSUE TITLE
Enable keeping selection active in "Select ..." Table UI

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#877]
Currently the "Select ..." functionality in the table menu (Equal to, Greater, Less), undoes the previous selection before applying the criterion to select rows.

I think it would be very helpful to enable keeping the previous selection active. An example use case: a spot table with many rows and several genes: I want to select all spots which are from (for example) from 3 of the genes. This is currently not supported via the UI and one would need to do this in a json view file. 

For the UI: I would propose to add a checkbox `[ ] Keep current selection` to the "Select ..." menus.

![image](https://user-images.githubusercontent.com/4263537/197622569-2900e7fd-deb4-4490-81fd-83899a92fa52.png)

**Comment by tischi** [comment]
In fact this should be very easy. I will do it later today.

**Comment by constantinpape** [comment]
> In fact this should be very easy. I will do it later today.

Thanks! I hoped this was easy, and I think it will be a great addition.

**Comment by tischi** [comment]
Should be fixed.

**Comment by constantinpape** [comment]
Yes, it works. Thanks!
