### ISSUE TITLE
randomColorSeed not saved/loaded from views

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#881]
The ```randomColorSeed``` saved in ```segmentationDisplay``` in views doesn't seem to be saved/loaded properly. e.g. in the platybrowser project:

Save a view showing the cell segmentation (will be saved with ```randomColorSeed``` 42)
Load the view

Every time you 'view'  it the colour scheme will be different i.e. doesn't seem to be using the set seed from the view

**Comment by tischi** [comment]
Found out why:

<img width="986" alt="image" src="https://user-images.githubusercontent.com/2157566/198325126-97dee3aa-5fdb-4e77-8bd8-79716dedb5d6.png">

It is using the hashcode of the annotation object now.
I have to think how to make it use the label instead....

**Comment by tischi** [comment]
I am using the hashcode of the annotation UUID now in case no column is specified for the coloring. This should work with version `3.0.1` (I will ping about the upload).
