### ISSUE TITLE
3D Viewer trouble (v3)

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#882]
Hi, 

I cannot get the segmentations to display in 3D Viewer for the following projects:

- https://github.com/mobie/covid-em-project
- https://github.com/mobie/plankton-fibsem-project
- https://github.com/mobie/sponge-fibsem-project
- https://github.com/mobie/zebrafish-lm-project

The viewer window stays empty even after waiting for a long time. 

Current Beta, MacOS

**Comment by tischi** [comment]
@martinschorb could you please update and try again?

**Comment by martinschorb** [comment]
https://github.com/mobie/covid-em-project view `s5_mock_segmentation` still does not show up.
Same for https://github.com/mobie/plankton-fibsem-project `cell-mask` in default dataset.
I have not tested any other segmentations.
It feels like the 3D Viewer takes a bit longer to load, but it still stays empty forever.
