### ISSUE TITLE
Segment volume rendering does not work for transformed sources

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#883]
@martinschorb 

I had a look at the code and I think the volume rendering issues may all due to sources that have been transformed.

To fully debug this, I would need two examples:

1. Segments with bounding box information in the table, where the source is transformed, e.g. into a grid view
2. Segments without bounding box information in the table, where the source is transformed, e.g. into a grid view

Do we have an example for each?

**Comment by martinschorb** [comment]
I have not created any of the affected segmentations.
 @constantinpape did the covid and sponge ones for sure...

**Comment by tischi** [comment]
Then probably they all have bounding boxes, anyway I can also work on this case first.

**Comment by tischi** [comment]
Seems I fixed it. In fact I am not sure this was working before, according to how the code looks, it should never have worked.

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/2157566/197826953-57b15c61-2516-49fb-bd08-1ba5a8d03ab6.png">
