### ISSUE TITLE
Loading columns for a subset of ids breaks continuous coloring  

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#887]
I suspect you changed something about the way missing values in columns are treated.

I load a csv for a subset of label_ids. Before missing values were filled in with some defaults (Nones? NaNs?), now there are just blank spaces. Categorical coloring (glasbey) still works for such columns, but continuous (BluwWhiteRed and viridis) throws an error that irreversibly freezes the BDV:

![Screenshot from 2022-11-01 11-25-38](https://user-images.githubusercontent.com/32451366/199214335-f2aaa966-dd36-4fdb-acd3-9e1356999101.png)

**Comment by constantinpape** [comment]
@vzinche can you please provide a minimal reproducible example for this bug?

**Comment by tischi** [comment]
I don't think we need an example, pretty sure this will be fixed with `3.0.5`.

**Comment by constantinpape** [comment]
Fixed in MoBIE-beta.
