### ISSUE TITLE
Discussion: Why is loading columns with duplicate names not allowed?

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#888]
Previously loading custom columns with names already existing in the table would just rewrite the existing columns, now it throws an error. I personally found the previous version much more useful, since I often need to regenerate the same table, and opening a new mobie every time is annoying. How about just throwing a warning like "Columns X, Y, Z have been rewritten"?

**Comment by constantinpape** [comment]
> How about just throwing a warning like "Columns X, Y, Z have been rewritten"?

I agree, that makes sense.

(I think we discussed this a few days ago @tischi and decided to throw an error, but I think @vzinche makes a good point here that we should instead over-write and throw an error.)

**Comment by tischi** [comment]
OK, I can implement this. Would it be possible to have a view in some project for me to test this?

**Comment by tischi** [comment]
Maybe @constantinpape could help?
Otherwise if you share a table with me and tell me how to exactly reproduce your issue that would work as well!

**Comment by vzinche** [comment]
I think this minimal example should be enough (had to zip it just to be able to drop it here). 
[test_dupl_col.zip](https://github.com/mobie/mobie-viewer-fiji/files/9930584/test_dupl_col.zip)

To reproduce:

- Open PlatyBrowser
- View sbem-segmentation -> cells
- Table -> Load columns -> Load from FileSystem
- Select the tsv that I uploaded here

**Comment by tischi** [comment]
I think I fixed it:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/2157566/200900323-b8fe85bc-f306-4339-b137-ba8b9cc75ac2.png">

This will be part of release `3.0.5`.
