### ISSUE TITLE
Focussing on sites yields out of focus

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#892]
`https://github.com/mobie/htm-test`, branch: `main`, view:`simple-grid`

Clicking `[F]` on the `sites` in a weird way makes the other images disappear for me.

For the `wells` and the other sources it is fine though.

@constantinpape can you reproduce this? Does this also happen in other projects?

**Comment by constantinpape** [comment]
This is fixed now too.
