### ISSUE TITLE
Loading of multiple channels in StitchedImage

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#901]
The multi-threading is currently implemented such that if

1. one opens the nuclei channel
2. zooms out to trigger loading of all nuclei
3. selects the serum channel
4. it will only start loading the serum channel once all nuclei are loaded

I think this is not ideal. 

I think I should look into whether I can insert the newly requested images somewhere higher in the loading queue. Maybe there is something to randomly reshuffle the queue?

**Comment by tischi** [comment]
Ships with `3.0.5`.

@constantinpape you will have to check this out! For my taste, it loads now the sites in a very intuitive order, e.g. when you zoom in it stops loading sites outside the current view and, e.g., when you add a new channel it starts loading this immediately.

**Comment by constantinpape** [comment]
Yes, I think the loading behavior is better now in the 3.0.5 beta release.
I will leave this open in case you want to still improve things, but this can also be closed from my end.
