### ISSUE TITLE
Screenshot sampling units

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#902]
At the moment, the screenshot 'sampling' line gives no units, and no indication of the final image size:
![screenshot_ui](https://user-images.githubusercontent.com/24316371/201530911-6a035155-d652-4a05-8d47-a197fa91fc75.png)

Would it be possible to add this? In the old version of this window, both of these were present which made it a bit easier to use: https://github.com/mobie/mobie-viewer-fiji/issues/555#issuecomment-987740149

**Comment by tischi** [comment]
OK, I will have a look. 
It was a problem adding it to the text, because then the UI would hang...

**Comment by tischi** [comment]
I managed to do it like this:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/2157566/201610928-b727cc16-27c0-46d2-8104-edc13fd8f79a.png">

Currently, there is only one choice for the units, namely the global project units. We could allow more choices at some point, but I think this is still better than not showing the units at all.

**Comment by tischi** [comment]
ships with `3.0.5`

**Comment by K-Meech** [comment]
Thanks @tischi ! Looks good to me.
I can update the screenshot of this menu in the docs once it's on the main MoBIE update site :)
