### ISSUE TITLE
Screenshot doesn't work with segmentation

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#904]
I am able to make screenshots from raw data, but once I load segmentation it doesn't work anymore. 
Steps to reproduce:
- Open PlatyBrowser
- sbem-segmentation -> cells -> view
- Take a screenshot

Somehow nothing happens afterwards

**Comment by tischi** [comment]
Thank you for spotting this. This is a little bit of a bigger issue since the way I internally represent segmentation images changes significantly. I will work on it.

**Comment by tischi** [comment]
Should be fixed with `3.0.6`.

**Comment by constantinpape** [comment]
Works now on MoBIE-beta.
