### ISSUE TITLE
Screenshot does not work for floating point images or Long label mask

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#905]
Currently the screenshot is rendered as unit16.

We need to make this more flexible for data types that cannot be represented as such.

For example:

- floating point images
- label masks with more than unit16 labels

Issue is that ImageJ is limited here to unit8, unit16 or float.

**Comment by tischi** [comment]
@martinschorb @constantinpape what about just always showing the raw pixel values in a screenhot as `float`? That would be the easiest and I am not sure this functionality is used a lot anyway, probably most people just want the RGB screenshot?!

**Comment by martinschorb** [comment]
As long as ImageJ can display it, I think that's fine. Then the user would do contrast adjustments and exporting from there.

**Comment by constantinpape** [comment]
Sounds good to me.
