### ISSUE TITLE
Saving selection colour / opacity to views

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#907]
Currently, the 'selected labels coloring', 'selection color' and 'opacity of non-selected labels' (from settings menu below) are not saved into views. This would be nice to add (but it's not an urgent fix)

![configureLabelRendering](https://user-images.githubusercontent.com/24316371/202173309-f2c61a54-f8e3-4ec1-b1b2-3a4d6e9fcfb2.png)

**Comment by constantinpape** [comment]
Good point @K-Meech. I guess we should add those to the spec so that they can be serialized within views (and should add to `segmentationDisplay`, `regionDisplay` and `spotDisplay`).

I am not quite sure what the meaning of `Selection color` and `Selection labels coloring` is though. Could you explain what these do, @tischi or @K-Meech?

**Comment by K-Meech** [comment]
```Selection labels colouring``` lets you choose between 'Keep current color' (i.e. use whatever the current colour scheme is for selected labels) and 'Use below selection color' (i.e. use the ```Selection color``` for all selected labels). This is really useful for making figures where you want to highlight specific cells in a bright colour!

**Comment by constantinpape** [comment]
> `Selection labels colouring` lets you choose between 'Keep current color' (i.e. use whatever the current colour scheme is for selected labels) and 'Use below selection color' (i.e. use the `Selection color` for all selected labels). This is really useful for making figures where you want to highlight specific cells in a bright colour!

Ok, I see. 

@tischi: can you make a suggestion for how we map the three things to the spec? I can then update the view jsonschema accordingly.

**Comment by tischi** [comment]
Good idea!

Currently in my code the variables and default values are:

```
ARGBType selectionColor = null;
Double opacityNotSelected = 0.15;
```
 
The `Selection labels colouring` is implicitly covered in that if `selectionColor == null`  the selected objects will keep their color.

For serializing the `selectionColor`, we could  reuse something that we did for the tables:
I think this was: `alpha-r-g-b` with `unit8` for each entry, so e.g., `255-255-0-0` for red. Correct @K-Meech?

Regarding the variable names, I am open to suggestions. Is there something that you'd find more intuitive?

**Comment by constantinpape** [comment]
@tischi: the names are fine.

I have added support for this in the spec here: https://github.com/mobie/mobie.github.io/commit/d4a23f3af22ff45dfc484379978891052ce3646e

You can go ahead and serialize it to the json with the views :).
