### ISSUE TITLE
Change opacity of non-selected segments

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#910]
When one selects a label (a cell in the volume), all the other labels are still shown, just with much smaller opacity. Before there was an option to change this opacity of non-selected segments to set it to 0. (I believe it was somewhere in "Configure volume rendering"?).
Is this option still available? I can't seem to find it

**Comment by constantinpape** [comment]
Yes, it's still available. It's in the settings menu (`S`) now:

![image](https://user-images.githubusercontent.com/4263537/202695278-9d346184-9303-4a49-a599-b964b0bf6cc9.png)

**Comment by vzinche** [comment]
Oh, great, many thanks!
