### ISSUE TITLE
Coloring argbColumn

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#912]
Did anything change about the value format for coloring by column? Because for me it doesn't work at all, doesn't even throw any error 
Here are the columns that I'm using:
https://github.com/kreshuklab/MorphoFeatures/blob/main/data_mobie/ganglia_comparison.tsv

**Comment by constantinpape** [comment]
I don't think that the value format has changed, probably this wasn't checked yet in the new MoBIE version and there is some bug.

**Comment by tischi** [comment]
@vzinche could please you let me know how to reproduce this error?

**Comment by vzinche** [comment]
- Open PlatyBrowser
- sbem-segmentation -> cells -> view
- Table -> Load columns -> Load the tsv [from the link](https://github.com/kreshuklab/MorphoFeatures/blob/main/data_mobie/ganglia_comparison.tsv)
-  Color by column -> select any of the 3 new columns -> select Coloring argbColumn

**Comment by tischi** [comment]
Hm, that already throws me an error when _loading_ the table:

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 3 >= 1
	at java.util.Vector.elementAt(Vector.java:479)
	at javax.swing.table.DefaultTableColumnModel.getColumn(DefaultTableColumnModel.java:294)
	at javax.swing.plaf.basic.BasicTableHeaderUI.paint(BasicTableHeaderUI.java:648)
```

For you, too?

**Comment by tischi** [comment]
`Color by Column` seems to work though:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/2157566/204570957-2e5315d8-ffdc-4e53-ac81-73dfbbe9917e.png">

**Comment by tischi** [comment]
Are you running MoBIE-beta?

**Comment by tischi** [comment]
> Glasbey coloring works, but the argbColumn does not.

Got it. Confirmed.

**Comment by tischi** [comment]
I think I fixed it. Does it look good? 

<img width="614" alt="image" src="https://user-images.githubusercontent.com/2157566/204582932-a3e4dea3-eaaf-4245-98ef-c871fad82333.png">

I think we can ignore the other error for now, it does not do any harm and does not always occur.

**Comment by vzinche** [comment]
Yes, the coloring looks correct, thanks!
