### ISSUE TITLE
Open ImagePlus in MoBIE

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#917]
@nicokiaru do we somewhere have a function that creates a `SourceAndConverter` from an `ImagePlus`?

**Comment by NicoKiaru** [comment]
There's this stuff: 

https://github.com/BIOP/bigdataviewer-image-loaders/blob/master/src/main/java/ch/epfl/biop/bdv/img/imageplus/ImagePlusToSpimData.java

Not a SourceAndConverter, but a SpimData.

**Comment by tischi** [comment]
This would work! Is it easy to add this as another dependency to MoBIE?

**Comment by NicoKiaru** [comment]
Yes it's in here: https://maven.scijava.org/#nexus-search;quick~bigdataviewer-image-loaders

The current Fiji compatible version is 0.3.7, but 0.4.0 should work as well.
