### ISSUE TITLE
Specification for color string

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#924]
@constantinpape @K-Meech 

I am confused, in different places in the Java code I find different conventions how to encode/decode a color string:

- `(r=255,g=255,b=255,a=255)`
- `r=255,g=255,b=255,a=255`
- `255-255-255-255`

Could you please check what we actually say in the spec? 

For images and for values in tables?

- [ ] #934

**Comment by constantinpape** [comment]
We have two different color specifications in the spec as well:
- `selectionColor`: `255-255-255-255` (see https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json#L117)
- `color`(for the image display): `r=255,g=255,b=255,a=255`. (see https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json#L132)

I agree that it would be good to unify this. My vote would be for `r=255,g=255,b=255,a=255` because it's more explicit.

**Comment by tischi** [comment]
The issue with `r=255,g=255,b=255,a=255` is that I'd be very afraid that it may break a CSV table..
We could specify that it MUST be enclosed in quotation marks, but I am not sure this will always work, depending on the CSV parser....
In fact, did you also find the spec for the table? We support a color column...


maybe: `r255-g255-b255-a255` ?

**Comment by tischi** [comment]
OK,  do you agree that commas are risky?

Could you find what we write in the spec for the colours in a table column?

Should I then change this in the places where we _write_ colors?

And I think for _reading_ colors I would support everything, i.e. try all conventions using a pattern matcher. Like this we would stay backwards compatible.

**Comment by constantinpape** [comment]
> `r255-g255-b255-a255`

Ok, so we decided we will use this as the default encoding for colors (so use it when we write data, and in any description in the spec). We will support the old encodings for backwards compatibility.

I will update the spec tomorrow to support the new encoding.

**Comment by constantinpape** [comment]
I updated this in the spec now.

**Comment by tischi** [comment]
I forgot to implement this in the Java code until today, but now it should work.

**Comment by tischi** [comment]
@constantinpape I am confused again

**Comment by constantinpape** [comment]
@tischi you are correct, we want to use `r255-g255-b255-a255` as the default color string.
(I have misread the spec there, and we actually still support the other color strings as well.)
