### ISSUE TITLE
Support opening from relative path?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#933]
Right now I thought only this works:

`./mobie -i "./src/test/resources/golgi-intensities.tif" -s "./src/test/resources
/golgi-cell-labels.tif"`

But interestingly this also works:

`./mobie -i "src/test/resources/golgi-intensities.tif" -s "src/test/resources/ggi-cell-labels.tif"`

I am surprised, but OK, I take it :-) 

@constantinpape does that also work on Linux?

**Comment by constantinpape** [comment]
I don't see the difference (besides some typos in the filenames). Both `"./my/path/image.tif"` and `"my/path/image.tif"` are relative paths to the same file. The `"./"` just makes this a bit more explicit.

**Comment by tischi** [comment]
Yeah, I guess that is the point, I was not sure that Java agrees on this view, but it is nice that it does :-)

So `src/test/resources/golgi-intensities.tif` also works for you?
