### ISSUE TITLE
platybrowser ui

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#939]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/2157566/212540137-df1c8ea2-231f-42ec-a293-814208a5c252.png">

should we rename "bookmark" to "cell-paper"?

**Comment by constantinpape** [comment]
Done in https://github.com/mobie/platybrowser-project/commit/ba994be618a91226ba113d714c92bf6c7bd89c04
