### ISSUE TITLE
Volume rendering_smoothing_problem_Mobie

### ISSUE THREAD

**Issue by KarelMocaer** [mobie/mobie-viewer-fiji#940]
Hi, 
I had problems for thin objects in the volume rendering option of Mobie that appeared fragmented.
- Configuring the resolution of volume rendering seems to not be working.
- Note for Tischi (as discussed last week) : check that the bookmarks are saving the resolution of the segmentation in the view.
Best,
Karel

**Comment by tischi** [comment]
Working on it in branch `issue940`
