### ISSUE TITLE
manual transform moves segmentation sources when they are not selected

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#941]
HI,

I want to register a fluorescence image with a segmentation in EM. When I enable manual transforms, the segmentation moves with the active source.

example data:
https://github.com/mobie/environmental-dinoflagellate-vCLEM

any FM channels and EM segmentation "Chloroplast"

**Comment by tischi** [comment]
Thank you for spotting this. Should be fixed in `3.0.11`.
Let me know if that is critical for you then I can upload the fix to mobie-beta.

**Comment by martinschorb** [comment]
we managed to register using the raw data, so not super-urgent...
