### ISSUE TITLE
Project parsing out of date

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#955]
@constantinpape @martinschorb 

That is the current code:

```
public class Project
{
	// Serialisation
	private String name;
	private List< String > datasets = new ArrayList<>();
	private String defaultDataset;
	private String specVersion;

	public Project()
	{
	}

	public Project( String name )
	{
		this.name = name;
	}

	public List< String > datasets()
	{
		return datasets;
	}

	public String getDefaultDataset()
	{
		return defaultDataset;
	}

	public String getSpecVersion()
	{
		return specVersion;
	}

	public void setDatasets( List< String > datasets ) { this.datasets = datasets; }

	public void setDefaultDataset( String defaultDataset ) { this.defaultDataset = defaultDataset; }

	public void setSpecVersion( String specVersion ) { this.specVersion = specVersion; }

	public String getName()
	{
		return name;
	}

	public void setName( String name )
	{
		this.name = name;
	}

}
```

But this looks different:

https://github.com/mobie/clem-example-project/blob/main/data/project.json

Are the `references` part of the spec?

If so, probably that is what we should show [here](https://github.com/mobie/mobie-viewer-fiji/issues/954) as the `Project publication`? 

And then I guess that should be plural, because there can be several?!

**Comment by constantinpape** [comment]
> Are the `references` part of the spec?

Yes, they are.


> If so, probably that is what we should show [here](https://github.com/mobie/mobie-viewer-fiji/issues/954) as the `Project publication`?
> 
> And then I guess that should be plural, because there can be several?!

Yes to both!

**Comment by constantinpape** [comment]
> But, e.g., here the `resources` are missing:

What do you mean by `resources`? Do you mean `references`?

> I guess they might be missing in others , too....

If you're referring to `references`: yes, this is an optional field, so they can be missing.

> I think we should _remove_ the `URL` field from `PublishedProjects.java` and rather add this information to the `resources` field in the `project.json`. What do you think?

How is the publication url in there used right now?

**Comment by tischi** [comment]
Sorry, yes, I meant `references`.
The publication URL is used here: https://github.com/mobie/mobie-viewer-fiji/issues/954
For `Project publication`.
We could replace `Project References` by `Project References`.

**Comment by constantinpape** [comment]
> The publication URL is used here: #954
> For `Project Publication`.
> We could replace `Project Publication` by `Project References`.

I see. And yes, I think it would be good to replace the `Project Publication` by `Project References` there.

**Comment by tischi** [comment]
OK, then someone needs to go through all the published repos and add the `references` field.

I can do this.

**Comment by tischi** [comment]
There also is a `description` field in the `Project`, which we don't use yet in MoBIE.
Should we display it somewhere?
