### ISSUE TITLE
New context menu: Log Current Source Transforms

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#957]
@constantinpape @martinschorb 

I would like to add a new context menu field:

`Log Current Source Transforms`

It simply prints the affine source transformations (data space to global space) for all visible sources.

I find this is useful for:

1. Checking how a manual or bigwarp transform changed a source transformation
2. For teaching purposes to have quick access to the source transforms without the need of saving a whole view

OK?

**Comment by constantinpape** [comment]
No ojections

**Comment by tischi** [comment]
Done in `3.0.13-SNAPSHOT`
