### ISSUE TITLE
UI rendering issues

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#960]
@maulakhan showed me that the UI rendering is bad when launching on Windows from IntelliJ.

1. Could you please post a screenshot here?
2. Is that also the case when you launch it from within Fiji?

@tibuch @K-Meech do you happen to have access to a Windows computer?

**Comment by maulakhan** [comment]
![image](https://user-images.githubusercontent.com/17739639/218994159-41ecfc06-61c3-4710-8c6d-56aec60ccc8f.png)

I guess it looks better on this monitor as compared to the one we looked at yesterday. However, I still have this problem that if I drag the MoBIE window to see the complete file names, it still would not display the full file names. It would to be good to have a bigger area for drop-down menu for all image names to be displayed completely or at least the tool tip description .

**Comment by tischi** [comment]
@maulakhan can we close this issue with the latest fixes in MoBIE-beta?
