### ISSUE TITLE
bdv-image-loaders error?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#963]
@NicoKiaru

Is that something that bdv-img-loaders would throw?

`
Error in file N:\exchange\ARIF\Dario\output\preprocess\20221026_ibidi_H838_series_1-25xy_cells_preprocess.tif: null
`

**Comment by NicoKiaru** [comment]
Hmm. Yes, possible. Can you share the file ?

**Comment by NicoKiaru** [comment]
https://github.com/BIOP/bigdataviewer-image-loaders/blob/93c22096aa267828c7a314ab430a0eb5a2da5800/src/main/java/ch/epfl/biop/bdv/img/bioformats/BioFormatsHelper.java#L70

It's a null pointer exception.

I should print the stack trace. But if you give me the file, maybe I can understand what's wrong, and fix both issues together

**Comment by tischi** [comment]
This will be hard to reproduce as it was not on my computer.
If you just add the stack trace that would probably fix it!
