### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#966]
@constantinpape @K-Meech 

Do you think we could remove everything within and below [this section](https://github.com/mobie/mobie-viewer-fiji#operation) of the README?

It seems to me that much of this is now in our tutorials?

**Comment by tischi** [comment]
I will then also update the publication.

**Comment by constantinpape** [comment]
I agree and went ahead with the changes: https://github.com/mobie/mobie-viewer-fiji/pull/968.
