### ISSUE TITLE
HCS support

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#967]
I am working on moving all functionality from https://github.com/embl-cba/plateviewer#plateviewer to MoBIE, because I think we have everything here and I think it will be less maintenance work if I deprecate https://github.com/embl-cba/plateviewer#plateviewer.

Where should I add the documentation for this?

I guess a new section here?

https://github.com/mobie/mobie.github.io/tree/master/tutorials

**Comment by constantinpape** [comment]
Yes, a new section in `tutorials` is good.

Note that we also have the usage example for covid-if that may cover some of this:
https://mobie.github.io/use-cases/htm.html

**Comment by tischi** [comment]
https://github.com/mobie/mobie.github.io/pull/101
