### ISSUE TITLE
Enter s3 credentials in plugin

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#97]
Adding the s3 credentials [the official way](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html) is a bit cumbersome and can be an issue for some users.

We should thus also support providing them in the fiji viewer directly. One thing we need to figure out is which keys need to be provided here:
1. the vanilla option would be to ask for both public and private key
2. another option would be to have a fixed public key (=fixed user-name) with read-only permissions for all MoBIE projects
3. we could also store the public key on github; from a security point of view, this should be ok

We should investigate a bit more how s3 encryption works before we decide on this. According to [this document](https://aws.amazon.com/blogs/developer/data-encryption-with-amazon-s3/) aws-s3 uses RSA encryption, so public and private key should not be independent.
However in the minio client we use at EMBL, the public key can just be the user name. I will ask EMBL-IT about this next week.

Note that this is only necessary for private datasets, that have encrypted s3 buckets.

cc @tischi @martinschorb

**Comment by martinschorb** [comment]
Hi,

I'd like to revive this. When you deal with several private buckets it really gets annoying. You have to swap the credentials file every time you want to access a new project (and make sure you keep the former one as a backup). I would see two options:

- Can you tell the plugin to not only use the `[default]` credentials but actually parse the file for credentials that match the project name? At least the user would only need that one credentials file and manage that (copy credentials of all private projects in there).

- Include some kind of credential management into the Plugin. Maybe from a config file that the user defines...

**Comment by tischi** [comment]
Somehow I thought the credentials for each user are always the same; in other words: one user just has one unique credential. Then I thought that just on the S3 provider side it is checked which "user" (with respective credentials) has access to which private buckets. Seems am I wrong?

**Comment by martinschorb** [comment]
Hi,

there are different scenarios:

- every user gets unique credentials. This would mean that we would need to manage the access rights on the aws server
- we generate access keys (pair) for a project and distribute them to the collaborators.

The second option is what we used so far. We have to check with IT, whether management of buckets and user permission is supposed to be done by us ourselves.

However when accessing different projects there are different keys do be dealt with in the credentials file. So far MoBIE (or the java aws lib) is using the`[default]` entry. AFAIK, there can only be one such entry. So what we have done so far is copying and swapping credentials files which is not very practical.

**Comment by tischi** [comment]
> every user gets unique credentials. This would mean that we would need to manage the access rights on the aws server

OK! I actually thought this ^ is what we have done already. I think we should indeed have a chat with IT, however Josep currently is on holidays afaik...

**Comment by constantinpape** [comment]
> OK! I actually thought this ^ is what we have done already.

We have been doing both; where the advantage of 

>     * we generate access keys (pair) for a project and distribute them to the collaborators.

is that we don't need to create extra credentials per user in order to give (read-only) credentials.

**Comment by martinschorb** [comment]
Yes, in fact I was distributing the credentials file as email attachment. Due to the fact that the destination folder is hidden and the file has no extension, it still caused some trouble with Windows and Mac.

Does the aws Java lib provide some way to use other keys than `[default]`? If so, it would be the easiest to just add project-specific keys to the credentials file.

**Comment by tischi** [comment]
1. seems like there can also be something else but **[default]**, e.g. **[project]** https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
2. but I did not find out yet how to read this one with Java...  if you find it let me know!

**Comment by tischi** [comment]
> If so, it would be the easiest to just add project-specific keys to the credentials file.

Yes, this could be nice, but then we may also have to amend our current xml specs:
https://github.com/mobie/platybrowser-datasets/blob/master/data/1.0.1/images/remote/prospr-6dpf-1-whole-ache.xml#L33

Maybe then there should be more choices:
- Anonymous
- Default
- ProjectXYZ

**Comment by tischi** [comment]
Hi @igorpisarev @axtimwalde, I am adding you here to this discuss, because maybe you know the answer :)

The aws credentials file allows for more profiles than the default one, e.g. [see here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html):
```
[default]
aws_access_key_id={YOUR_ACCESS_KEY_ID}
aws_secret_access_key={YOUR_SECRET_ACCESS_KEY}

[profile2]
aws_access_key_id={YOUR_ACCESS_KEY_ID}
aws_secret_access_key={YOUR_SECRET_ACCESS_KEY}
```

Now, I am not sure what the best way is to actually _use_ the `profile2` credentials.
From the [documentation](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) I seems that one would need to set a system variable like so:

```
export AWS_PROFILE="profile2"
```

Once this is set, the `DefaultAWSCredentialsProviderChain` class would look for this profile.

1. @martinschorb Can you try this out to see whether this works for you.
1. In case we want to routinely give users project specific credentials I think we would need to control from the Java side which credentials should be used for a given project and then, based on the [xml](https://github.com/mobie/platybrowser-datasets/blob/master/data/1.0.1/images/remote/prospr-6dpf-1-whole-ache.xml#L33) pick the correct ones. Does that mean we have to set the `AWS_PROFILE` system variable from Java? To me that feels odd but reading the documentation I could not find another way yet? Any ideas?

**Comment by martinschorb** [comment]
Hi,
I just tried:

**MacOS:**

- launching Fiji from a MacOS app and `launchctl setenv ...` does not work. 
- I could not manage to properly launch Fiji from a Terminal shell where I can specifically set environment variables.

**Linux**

- setting a terminal environment variable accordingly and the launching fiji from it gives me a `forbidden` exception when trying to launch the dataset with the key specified but `[default]` still works. So it seems it is not considering the environmental variable.

**Comment by tischi** [comment]
@martinschorb 
ok, that's then already better than having to change your credentials file!
I guess we should still explore whether we can achieve this also from within java such that the user does not have to do anything, should we?

**Comment by martinschorb** [comment]
Hi,
you would still need to add new keys to the credentials file. 
The question would be whether the mechanism of credential file plus environmental variable would be the way to go to implement it (that's a bit ugly because it is very OS-specific).

**Comment by tischi** [comment]
@constantinpape @KateMoreva 

Do we actually currently still use the `Authentication` tag for anything in the Java code?

https://github.com/mobie/platybrowser-project/blob/1eaabccf04eebdf58785550dbdd84f2e2791e78d/data/1.0.1/images/remote/sbem-6dpf-1-whole-raw.xml#L33

**Comment by constantinpape** [comment]
No, we don't use it in the java code anymore. It should also be removed from the xmls; somehow this didn't work out here.
I will remove it now.

**Comment by constantinpape** [comment]
@tischi I have removed the `Authentication` tag from the platybrowser project now and made a PR to remove the last places where I could find it it here: #577. Should we close this issue, since you have implemented entering the credentials in mobie-fiji now?

**Comment by tischi** [comment]
Thanks!
