### ISSUE TITLE
Modelling HCS data

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#972]
@joshmoore do you know whether it is true that the files that HCS microscopes produce _always_ only contain one 2D plane? And C,Z,T are distributed into multiple files? (cc @constantinpape)

**Comment by constantinpape** [comment]
> And C,Z,T are distributed into multiple files?

I know of at least one example where this is not the case: the data we had in the first covid screen. The tif files there contained all channels for a given position, with the following naming scheme:
`WellH06_PointH06_0007_ChannelDAPI,WF_GFP,TRITC,WF_Cy5,DIA_Seq0502.tiff`

**Comment by joshmoore** [comment]
I'd concur that "`always`" is not a safe assumption.
