### ISSUE TITLE
Add time-lapse support for StitchedImage (to render time-lapse HCS data).

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#973]
@constantinpape 

Unfortunately, the `StitchedImage` that we use to render a `MergedGrid` does not have any time-lapse support nor logic yet.
This is a bigger project and I am not sure when I will manage to implement this.

For now, the IncuCyte data can be loaded but it does only show the first time point.

**Comment by constantinpape** [comment]
Makes sense. Will be great to have the timepoint support, but I can imagine that this is a bigger project.
