### ISSUE TITLE
HCS Opener: BDV freezes when zooming out

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#985]
When zooming out it tries to load all images.

Since there typically is no resolution pyramid this is a lot of data, maybe more than fits into RAM.

@ThomasMicroscopy
@tibuch 

Could you please explore this:

1. Let me how many GB of data are in the HCS folder that you are opening
2. Let me how much memory you have here in Fiji: `Edit › Options › Memory & Threads...`
3. Check how much memory your computer has
4. If possible increase the memory in Fiji and try again, does it help to avoid the freezing?

**Comment by ThomasMicroscopy** [comment]
Ok, I tried some things.  The image data is around 4.6 Gb.   Edit... Memory.. show like 25'000 Meg. 
When it crashed, just before, it popped-up the Bioinfo Import dialog, even though that is now xml.xxx in file name. So, I think actually the Bioinfo pop-up is linked to the crashing. 
I then made a new folder, where I kicked out all the channel 2 images, so reducing the data by a factor of 2. This worked, kept running, no Bioinfo-import dialog.    Still showed me something like 29'000 Meg under Memory. The Mac itself has 64 GB. 

I restarted the whole Mac to clean out everything, and only running Fiji, nothing else. 
I loaded the full data set (~2000 file, 4.6 GB), it crashed again, with first popping-up the Bioinfo-import, and then later a file error (see attachment).   Memory in Fiji indicated only about 8.2 GB (up from about 6GB when starting Fiji). Odd...
<img width="1401" alt="Screenshot 2023-03-03 at 14 14 12" src="https://user-images.githubusercontent.com/126269188/222730886-be985bf0-bfe1-48e9-b3b6-d63713292d7a.png">

**Comment by ThomasMicroscopy** [comment]
uijjj, now I can't start Fiji anymore, tells me it's damaged.....

**Comment by tischi** [comment]
@ThomasMicroscopy 

Hmm, maybe an issue is that there are more (hidden) files in your folder that it tries to open.
Could you please check whether there are hidden files?
Basically anything that is not the actual TIFF images that we want to open is a potential problem!
For example, in your screenshot that file starts with a dot, which is suspicious!

Sorry about your Fiji!
Hopefully deleting it and installing a new one will fix it?

**Comment by ThomasMicroscopy** [comment]
yes, I didn't understand where that dot file is coming from either.

**Comment by tischi** [comment]
I would not know that Linux creates automatically such `.` files. This is strange!

@joshmoore do you know whether Bio-Formats would create such files starting with a dot (see above)?

**Comment by ThomasMicroscopy** [comment]
Ok, I tried it again, and it crashed.  It does say that it only opens 1055 files (which is the correct number without dot files)
<img width="544" alt="Screenshot 2023-03-03 at 16 32 11" src="https://user-images.githubusercontent.com/126269188/222761518-973bf6d8-dfee-4c25-bd66-57a392850049.png">

then suddenly the bioformats-import pops up again, 
<img width="1215" alt="Screenshot 2023-03-03 at 16 33 11" src="https://user-images.githubusercontent.com/126269188/222761621-7d301789-c294-4b46-8b34-dc1ed054ea07.png">

and the inevitable crash that follows.  I think you can consolidate all three bug threads into one.

Here the error is now exactly the new ._r08 .... file.
But interestingly, in many of the crashes, I didn't get an error with a specific file name.

<img width="1008" alt="Screenshot 2023-03-03 at 16 33 41" src="https://user-images.githubusercontent.com/126269188/222762102-276117e1-da57-459e-b0a8-55bd388d6933.png">

**Comment by tischi** [comment]
Can you share this data with me?
I am home now but on Monday I could download even a couple of GB.

**Comment by ThomasMicroscopy** [comment]
ok, I have delete the ._r.....   files now, and right now it doesn't crash, it doesn't pop up, it doesn't freeze.
Ok, so I guess the importer needs to be modified to not read any .xxx files.  These files quickly generated by Unix Operating systems and appear drives, on servers etc., so the user has very little control over the appearance of these files. I think any file importer must make sure to not try to import such files.  I will make bundle of files with a different field number.

**Comment by tischi** [comment]
Wait!
:-)
I am uploading right now a version where my code will ignore the `.` files...

**Comment by ThomasMicroscopy** [comment]
A Fix in 1 Minute...  ;-)

**Comment by tischi** [comment]
If you restart your Fiji now it should download a new version of `mobie-viewer-fiji`.
Let me know how it goes (with the `.` files).
Please also copy the whole text of the Log window here.
Thanks!

**Comment by ThomasMicroscopy** [comment]
I loaded now the larger image set, so far no crash.


# MoBIE
Opening: /Volumes/Wymoperetta/Thorsten/2023_02_13_MCF7measurement1/Images
Files: 2134
Image data format: tiff
Initialised HCS plate: Images
Images: 2110
Channels: 2
Wells: 96
Sites per well: 11
HCS Pattern: Operetta
Opening view: Images
Initializing data from 2110 source(s)...
Initialising (1/2110): Images-ch1-wr05c06-s03
Initialising (16/2110): Images-ch1-wr02c08-s03
Initialising (32/2110): Images-ch1-wr05c06-s09
Initialising (64/2110): Images-ch2-wr05c07-s05
Initialising (4/2110): Images-ch1-wr05c06-s06
Initialising (128/2110): Images-ch2-wr07c08-s07
Initialising (256/2110): Images-ch2-wr03c06-s11
Initialising (8/2110): Images-ch1-wr02c08-s11
Initialising (512/2110): Images-ch1-wr03c10-s08
Initialising (1024/2110): Images-ch2-wr04c09-s04
Initialising (2/2110): Images-ch1-wr05c06-s04
Initialising (2048/2110): Images-ch1-wr04c11-s11
Initialised 2110 data source(s) in 247 ms, using up to 5 thread(s).
Opened view: Images in 889 ms.

**Comment by tischi** [comment]
ok, cool! 

so looks like the `.` files were _one_ issue.; maybe there are more...

...maybe I could work more on the memory management. 
let me know how that goes.
it would also be nice if you could share a whole plate with me that I can look into further optimisations.

for now: I wish you a nice weekend 🌴 !

**Comment by tischi** [comment]
Manual is here: https://mobie.github.io/tutorials/explore_a_project.html

For example:

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/2157566/222770342-3786a0e3-57d1-4955-8262-deea7dd7bcf5.png">

**Comment by ThomasMicroscopy** [comment]
ah, ok, thank you. this panel works to adjust color and brightness contrast.
the brightness and color under "settings" in the bigdataviewer didn't seem to do anything.

**Comment by tibuch** [comment]
Hi @tischi,

Sorry for taking some time. The plates I want to look at are in the 150-100GB range. I have also checked with some users and they are very much interested in looking at the big picture. Their inspection usually starts on the fully zoomed-out and then selectively they pick wells to take a closer look. 

__Note:__ I did not try to find a computer with enough memory. But I would also not expect this to work just out of the box without any re-saving. The 100GB is also only for 2D planes and we will most likely have 3D stacks coming soon i.e. it gets even bigger.

**Comment by ThomasMicroscopy** [comment]
> ok, cool!
> 
> so looks like the `.` files were _one_ issue.; maybe there are more...
> 
> ...maybe I could work more on the memory management. let me know how that goes. it would also be nice if you could share a whole plate with me that I can look into further optimisations.
> 
> for now: I wish you a nice weekend 🌴 !

Hello again. Maybe to clarify, it's not always to Os which creates the '.' files. I just saw an old post of yours about .xxxx..bfmemo files, which I find also in some of my image folders.  The ._r01xxxx files are obviously created when opening the original image file in Fiji. 
But also the OsX has processes running in the background that create '.' files, which normal users are not supposed to see. Examples here: 
<img width="304" alt="Screenshot 2023-03-06 at 12 20 24" src="https://user-images.githubusercontent.com/126269188/223096897-d06f39ca-13f2-47ff-b3f9-c08c08039300.png">

**Comment by tischi** [comment]
Thanks!
