### ISSUE TITLE
Refresh the data

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#99]
In order to have some interactivity with outside tools, it would be useful to have a "Refresh the Data" button, that reloads the current view of the data and tables from source.

This would only be necessary in expert mode.

**Comment by tischi** [comment]
I think removing the respective source and adding it back should do the job? Or is that to cumbersome?

**Comment by constantinpape** [comment]
I agree, removing and adding it is fine for now; we can revisit this if a specific use case comes up.
