### ISSUE TITLE
Operetta image calibration is wrong!

### ISSUE THREAD

**Issue by ThomasMicroscopy** [mobie/mobie-viewer-fiji#990]
Looks to me that the scale bar is not right yet. This whole plate would be too big (30 cm... ) 
I guess more parameters need to be extracted from the metadata, resolution data is both in tiff header and xml file.

<img width="1603" alt="Screenshot 2023-03-03 at 17 38 37" src="https://user-images.githubusercontent.com/126269188/222777066-96db0934-8e81-4141-af5c-57f38886f10f.png">

From info in Fiji. pixel size of camera looks correct, resolution of camera is correct. Magnification of objective (10x)
is not shown here. so, the actual length is 0.877 mm, not 8.77 mm.  So one probably needs to extract it from the xml.

Title: r02c02f01p01-ch1sk1fk1fl1.tiff
Width:  8772.4956 µm (1360)
Height:  6605.1732 µm (1024)
Size:  2.7MB
Resolution:  0.1550 pixels per µm
Pixel size: 6.4504x6.4504 µm^2
ID: -5157
Bits per pixel: 16 (unsigned)
Display range: 0 - 6931

**Comment by tischi** [comment]
It seems that is is simply wrong in the TIFF images.

In the xml that I have it says, probably correctly:

`<ImageResolutionX Unit="m">9.9322451493686488E-07</ImageResolutionX>`

and in the TIFF files it is indeed, wrongly, as you say:

`6.4504 µm`

Do you have a contact person at the company to tell them they should fix this?

I think it would be important to let them know as this likely will cause **wrong scientific publications i**f users analysis the TIFF images!

**Comment by tischi** [comment]
@ThomasMicroscopy 
Having the wrong calibration in the TIFF images is a very serious bug! 
If people do image analysis on these TIFF images they get the wrong results.
We have to report this to them!
