### ISSUE TITLE
Operetta Samples example, some images look funny 

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#996]
@ThomasMicroscopy

Is this normal?

<img width="423" alt="image" src="https://user-images.githubusercontent.com/2157566/224070697-81b34e5a-34f0-4834-8ff6-da40858d4d54.png">

**Comment by ThomasMicroscopy** [comment]
No, this is a problem with the microscope - a very different issue, maybe a stuck filter wheel. But the camera of course has no idea, just takes pictures happily, and we can look at it now trying to figure out what is wrong.... The first use of the HCS importer ... ;-)
